### ISSUE TITLE
Mintegral Native can not be displayed with max

### ISSUE THREAD

**Issue by taugin** [AppLovin/AppLovin-MAX-SDK-Android#100]
I am using applovin max 11.0.0 and mintegral adapter 15.8.1.3, and I cannot successfully load and display mintegral native ads 。

Please help

**Comment by joeapplovin** [comment]
Hi @taugin - what do you see in [Mediation Debugger](https://dash.applovin.com/documentation/mediation/android/testing-networks/mediation-debugger) for Mintegral?

**Comment by taugin** [comment]
Hello, This is the mediation debugger interface:
![device-2022-01-21-110252](https://user-images.githubusercontent.com/5130314/150458501-d22e8abc-816b-40bd-ac47-9feb742039b4.png)

loading logs:

01-21 11:05:41.228  7470  7645 D AppLovinSdk: [MediationAdapterManager] Loaded MINTEGRAL_NATIVE_BIDDING
01-21 11:05:41.229  7470  7645 D AppLovinSdk: [MediationAdapterWrapper] MintegralMediationAdapter: running load_ad...
01-21 11:05:41.230  7470  7645 I AppLovinSdk: [MintegralMediationAdapter] Loading bidding native ad for unit id: 1672447 and placement id: 397726...
01-21 11:05:41.324  7470  7645 D AppLovinSdk: [MediationAdapterWrapper] Setting timeout 10000ms. for MediatedAd{thirdPartyAdPlacementId=1672447, adUnitId=60938a0ed23f2308, format=NATIVE, networkName='MINTEGRAL_NATIVE_BIDDING'}
01-21 11:05:41.324  7470  7645 D AppLovinSdk: [MediationAdapterWrapper] MintegralMediationAdapter: finished load_ad
01-21 11:05:42.951  7470  7664 I AppLovinSdk: [ConnectionManager] Successful GET returned 200 in 1.73 s over wifi to #-1376145443 "prod-ms.applovin.com/1.0/event/lerr"
01-21 11:05:48.189  7470  7670 I AppLovinSdk: [ConnectionManager] Sending GET request to id=#-185445827 "prod-ms.applovin.com/1.0/event/serr"...
01-21 11:05:48.550  7470  7670 I AppLovinSdk: [ConnectionManager] Successful GET returned 200 in 0.36 s over wifi to #-185445827 "prod-ms.applovin.com/1.0/event/serr"
01-21 11:05:51.326  7470  7668 E AppLovinSdk: [TaskTimeoutMediatedAd] MintegralMediationAdapter is timing out MediatedAd{thirdPartyAdPlacementId=1672447, adUnitId=60938a0ed23f2308, format=NATIVE, networkName='MINTEGRAL_NATIVE_BIDDING'}...
01-21 11:05:51.329  7470  7470 I AppLovinSdk: [MediationService] Destroying MediatedAd{thirdPartyAdPlacementId=1672447, adUnitId=60938a0ed23f2308, format=NATIVE, networkName='MINTEGRAL_NATIVE_BIDDING'}
01-21 11:05:51.329  7470  7470 D AppLovinSdk: [MediationAdapterWrapper] MintegralMediationAdapter: running destroy...
01-21 11:05:51.329  7470  7470 I AppLovinSdk: [MediationAdapterWrapper] Marking MintegralMediationAdapter as disabled due to: destroy
01-21 11:05:51.333  7470  7470 D AppLovinSdk: [MediationAdapterWrapper] MintegralMediationAdapter: finished destroy
01-21 11:05:51.333  7470  7470 D AppLovinSdk: [TaskProcessMediationWaterfall:60938a0ed23f2308:NATIVE] Ad failed to load in 10114 ms with error: MaxError{code=-5101, message='Adapter timed out'}
01-21 11:05:51.335  7470  7470 I AppLovinSdk: [TaskProcessMediationWaterfall:60938a0ed23f2308:NATIVE] Waterfall failed in 10145ms with error: MaxError{code=-5001, message='MAX returned eligible ads from mediated networks, but all ads failed to load. Inspect getWaterfall() for more info.'}

from the log, I can get the bid response from mintegral, but can not load ads assets from mintegral, please help me.

the bid reponse like this : db979e9c-30be-43ac-9f7f-56787e1fbf8f-1642734096_se-new-cdn-ap-northeast-2c

**Comment by joeapplovin** [comment]
Hi @taugin - it looks like the request to load the native ad assets from Mintegral is timing out.  Can you use Charles proxy to capture the network request that's failing?  We may need to let the Mintegral team know.

**Comment by taugin** [comment]
Hello，
I have grabbed the network request of mintegral through charles, and I can see that there are creatives through charles 。
![charles](https://user-images.githubusercontent.com/5130314/150721657-9231c8b3-c842-40a0-81ca-db0cf438cb42.png)

log as follow：
![log](https://user-images.githubusercontent.com/5130314/150721707-2318215f-678a-4ac1-813c-9d03408da82c.png)

the curl request like this：

curl -H ':method: GET' -H ':path: /load?app_id=150680&unit_id=1672447&placement_id=397726&req_type=2&sign=b1cdfc80391e4b67f56dfec50eda1c0b&ad_num=1&only_impression=1&ping_mode=1&tnum=1&d=%5B%5D&video_version=2.0&offset=0&ad_type=42&ad_source_id=1&token=0f5b37ad-1409-475c-b990-c92a34151b9a-1642997784_se-new-cdn-ap-northeast-2a&misk_spt=-1&open=0&channel=&band_width=0&platform=1&os_version=7.1.1&package_name=com.fast.cleaner.cpu.cool.powerful&app_version_name=1.0&app_version_code=1&orientation=1&model=1607-A01&brand=360&gaid=&gaid2=DnDbiAtrGnNwfU3MGZTTDnvFWkRAHnlwf7jeG7R2fUDeiASU&network_type=9&network_str=&language=zh-CN&timezone=GMT%2B08%3A00&useragent=Mozilla%2F5.0+%28Linux%3B+Android+7.1.1%3B+1607-A01+Build%2FNMF26F%3B+wv%29+AppleWebKit%2F537.36+%28KHTML%2C+like+Gecko%29+Version%2F4.0+Chrome%2F59.0.3071.82+Mobile+Safari%2F537.36&sdk_version=MAL_15.8.01&screen_size=1080x1920&h=25386&i=10838&f=RHRLqBzRKzUkRlis0m%2BgWZxbnZ8PFzz4VD6oPlgYO%2Fp6NQnHeRDwUFtpcMb8SHyg8s3Yu6ZbzUyk%0AVzG3GI961A%3D%3D%0A++++&web_env=%7B%22webgl%22%3A0%7D&http_req=2&a_stid=1_1%2C3_2&dvi=4Bz3Y%2BN0G0RFinD2R0M0H72rRUEAfANM6N%3D%3D&b=d9P_sj_wDR5k9H61e2TWIX-81zMy9U7fMRhRNGf8B9k17jo_6qgIbvRTmKXQqzTg&c=nWZr7K1Fczp59NMINhR5SlgK7yiaEkG1GYMTpLxXePqKGW2VAJMjvs6Ev0nvT1PQ&api_version=2.2&ts=1642997785203&st=9ba4545b3f5e5876e111b7236b62add4' -H ':authority: se-new-cdn-ap-northeast-2a-hb.rayjump.com' -H ':scheme: https' -H 'charset: UTF-8' -H 'charset: UTF-8' -H 'accept-encoding: gzip' -H 'user-agent: okhttp/3.12.13' 'https://se-new-cdn-ap-northeast-2a-hb.rayjump.com/load?app_id=150680&unit_id=1672447&placement_id=397726&req_type=2&sign=b1cdfc80391e4b67f56dfec50eda1c0b&ad_num=1&only_impression=1&ping_mode=1&tnum=1&d=%5B%5D&video_version=2.0&offset=0&ad_type=42&ad_source_id=1&token=0f5b37ad-1409-475c-b990-c92a34151b9a-1642997784_se-new-cdn-ap-northeast-2a&misk_spt=-1&open=0&channel=&band_width=0&platform=1&os_version=7.1.1&package_name=com.fast.cleaner.cpu.cool.powerful&app_version_name=1.0&app_version_code=1&orientation=1&model=1607-A01&brand=360&gaid=&gaid2=DnDbiAtrGnNwfU3MGZTTDnvFWkRAHnlwf7jeG7R2fUDeiASU&network_type=9&network_str=&language=zh-CN&timezone=GMT%2B08%3A00&useragent=Mozilla%2F5.0+%28Linux%3B+Android+7.1.1%3B+1607-A01+Build%2FNMF26F%3B+wv%29+AppleWebKit%2F537.36+%28KHTML%2C+like+Gecko%29+Version%2F4.0+Chrome%2F59.0.3071.82+Mobile+Safari%2F537.36&sdk_version=MAL_15.8.01&screen_size=1080x1920&h=25386&i=10838&f=RHRLqBzRKzUkRlis0m%2BgWZxbnZ8PFzz4VD6oPlgYO%2Fp6NQnHeRDwUFtpcMb8SHyg8s3Yu6ZbzUyk%0AVzG3GI961A%3D%3D%0A++++&web_env=%7B%22webgl%22%3A0%7D&http_req=2&a_stid=1_1%2C3_2&dvi=4Bz3Y%2BN0G0RFinD2R0M0H72rRUEAfANM6N%3D%3D&b=d9P_sj_wDR5k9H61e2TWIX-81zMy9U7fMRhRNGf8B9k17jo_6qgIbvRTmKXQqzTg&c=nWZr7K1Fczp59NMINhR5SlgK7yiaEkG1GYMTpLxXePqKGW2VAJMjvs6Ev0nvT1PQ&api_version=2.2&ts=1642997785203&st=9ba4545b3f5e5876e111b7236b62add4'

**Comment by taugin** [comment]
Hello，

I have found the reason.

the statement "mbBidNativeHandler.bidLoad( parameters.getBidResponse()); " should be called in the main thread.

**Comment by thomasmso** [comment]
@taugin - How did you come to that conclusion? If you look into the `bidLoad(...)` it looks like their SDK ends up checking against the main thread. Right now their SDK is not responding with either the `onAdLoaded(...)` or `onAdLoadError(...)` callback from looking at your logs.

**Comment by taugin** [comment]
Hello,

I downloaded your open source code MintegralMediationAdapter.java, and after modifying the code, the ads can be loaded successfully. The modified code is as follows:

         mbBidNativeHandler = new MBBidNativeHandler( properties, activity.getApplicationContext() );
         mbBidNativeHandler.setAdListener( nativeAdListener );
         Handler handler = new Handler(Looper.getMainLooper());
         handler.post(new Runnable() {
             @Override
             public void run() {
                 mbBidNativeHandler.bidLoad( parameters.getBidResponse() );
             }
         });
![mintegral](https://user-images.githubusercontent.com/5130314/150752080-a9de7c92-d28f-4378-a954-80c0cd1fd930.png)

**Comment by thomasmso** [comment]
Thanks for checking - we'll fix it server-side. I'll notify this thread when that's out (est. EoW).

**Comment by taugin** [comment]
Hello，
When is this problem expected to be fixed?

**Comment by thomasmso** [comment]
Sometime this week. We are actively looking into it (cc @Billy-Hu).

**Comment by Billy-Hu** [comment]
Hey @taugin ! I'm now looking at it. Will be fixed today.

**Comment by williamycyh** [comment]
> Thanks for checking - we'll fix it server-side. I'll notify this thread when that's out (est. EoW).

pls fix it.  This affects our income....

**Comment by thomasmso** [comment]
@williamycyh - Our backend team should be able to push this tomorrow, thanks.

**Comment by rosebm** [comment]
Hello! I'm experiencing the same timeout error with Mintegral, would be great to get the fix available:

onNativeAdLoaded networkResponse = [MaxResponseInfo{adLoadState=FAILED_TO_LOAD, mediatedNetwork=MaxMediatedNetworkInfo{name=Mintegral, adapterClassName=com.applovin.mediation.adapters.MintegralMediationAdapter, adapterVersion=15.8.1.3, sdkVersion=MAL_16.0.11}, credentials=Bundle[{app_id=155920, app_key=446283020350539c34ee67cdc56bfde1, placement_id=1732021}], error=MaxError{code=-5101, message='Adapter timed out'}, latencyMillis=10045], MaxResponseInfo{adLoadState=AD_LOADED, mediatedNetwork=MaxMediatedNetworkInfo{name=AppLovin, adapterClassName=com.applovin.mediation.adapters.AppLovinMediationAdapter, adapterVersion=11.1.0, sdkVersion=11.1.0}, credentials=Bundle[{placement_id=native_native}], latencyMillis=36]]

**Comment by chauduyphanvu** [comment]
Hey all, we've pushed the fix server-side. Could you try again and let us know if you continue seeing the issue? Thanks.

**Comment by rosebm** [comment]
Yes! @chauduyphanvu  I just tested on my side, and the ads are being correctly loaded from Mintegral. Thank you! 

NativeAdListener: onNativeAdLoaded networkResponse = [MaxResponseInfo{adLoadState=AD_LOADED, mediatedNetwork=MaxMediatedNetworkInfo{name=Mintegral, adapterClassName=com.applovin.mediation.adapters.MintegralMediationAdapter, adapterVersion=15.8.1.3, sdkVersion=MAL_16.0.11}, credentials=Bundle[{app_id=---------, app_key=----------, placement_id=--------}], latencyMillis=1111], MaxResponseInfo{adLoadState=AD_LOAD_NOT_ATTEMPTED, mediatedNetwork=MaxMediatedNetworkInfo{name=AppLovin, adapterClassName=com.applovin.mediation.adapters.AppLovinMediationAdapter, adapterVersion=11.1.0, sdkVersion=11.1.0}, credentials=Bundle[{placement_id=native_native}]]]
