### ISSUE TITLE
Indicates that no ads are currently eligible for your device. for native ads in android

### ISSUE THREAD

**Issue by Prabha10cs** [AppLovin/AppLovin-MAX-SDK-Android#101]
i am creating Native Ads (Manual) i am getting error code 204 only for facebook native

**Comment by chauduyphanvu** [comment]
@Prabha10cs, we currently don't support test mode for Facebook native/MRECs, so it not working in test mode is expected.

For live ads please check that the following requirements are met:
* ATE flag needs to be set
* COPPA (ageRestrictedUser) and LDU needs to be false
* App needs to be live in the App Store
* Will only bid in California if CCPA is set
* Does not fill for new apps that are not on the latest version of the Facebook SDK

You can also check the Facebook checklist for additional integration issues: https://developers.facebook.com/tools/property/checklist/

Vu Chau
AppLovin Team
