### ISSUE TITLE
Facebook - Medium rectangle format support

### ISSUE THREAD

**Issue by apshard** [AppLovin/AppLovin-MAX-SDK-Android#105]
We use Medium Rectangle placements in the Facebook Audience network.
![fan_mrec](https://user-images.githubusercontent.com/97424424/150651420-64b75a98-a3fd-4460-9385-2c4abf050f82.png)
But in Applovin for MREC units only Facebook Native network is available.
![applovin_mrec](https://user-images.githubusercontent.com/97424424/150651437-05216135-defe-4d1a-97c1-8acc71445994.png)
So it seems we have to create Native placements on Facebook and Applovin will render native ads from Facebook using the medium template in MREC units, am I correct?
As I can see from the adapter source code it can support both options but in the Applovin console, we can select only Facebook Native network for MREC unit but not Facebook network and only Facebook network for the banner unit but not Facebook native network?
On the other side, we have one Applovin banner unit (that was created a way ago) where both Facebook and Facebook Native networks are available.
![applovin_banner](https://user-images.githubusercontent.com/97424424/150651594-324973b4-8e9c-4cd5-bf96-4c734f1ff4a5.png)
Would you please clarify all this?

**Comment by NanaAmoah** [comment]
Addressed here: https://github.com/AppLovin/AppLovin-MAX-SDK-Android/issues/99#issuecomment-1018933094

**Comment by NanaAmoah** [comment]
Hi @apshard, we plan to add MAX MREC ads for Facebook in the future. I will share updates once they're available.

**Comment by apshard** [comment]
Hi @NanaAmoah, thank you. What about my second question? Why do we see two Facebook networks in our MAX Banner unit? Can we turn on both networks and how will it work in this case?
![applovin_banner](https://user-images.githubusercontent.com/97424424/151445132-5a9d55e5-d9a3-46f4-a78b-c271a25a7649.png)

**Comment by NanaAmoah** [comment]
With **Facebook Native** a regular native ad is requested from **Facebook** and MAX renders that as a banner ad, while with **Facebook** a regular banner ad is requested. If both are turned on, they'd be treated as two different bidding networks.

**Comment by apshard** [comment]
This is interesting. Thank you for your explanation. But why is this feature available only on one of our MAX banner units (the oldest one, other banner units have the only Facebook network, but not Native)?

**Comment by NanaAmoah** [comment]
This feature is currently deprecated so this is expected for MAX Banner units created recently.

**Comment by apshard** [comment]
> Hi @apshard, we plan to add MAX MREC ads for Facebook in the future. I will share updates once they're available.

@NanaAmoah any update on this? Medium rectangle format is fully supported for bidding on the Facebook side https://developers.facebook.com/docs/audience-network/guides/ad-formats/medium-rectangle/ but in Applovin we can only select Meta Native network (that requests native ad format from Facebook and then renders it as MREC).

**Comment by NanaAmoah** [comment]
Hi @apshard support for Facebook Bidding MRECs is now live. **Meta** should be an available option for MRECs now.
