### ISSUE TITLE
Not able to load test ad

### ISSUE THREAD

**Issue by Khang-NT** [AppLovin/AppLovin-MAX-SDK-Android#108]
I was able to load test ads few days ago, but now I receive this log message when I try to load native ad in debug mode, please check:
```
[{"code":1028,"msg":"No message"},{"code":1000,"msg":"Ad network does not match filter ad networks list"}]
```

**Comment by NanaAmoah** [comment]
Hi @Khang-NT. Are you trying to load native ads for a particular ad network ?

**Comment by Khang-NT** [comment]
I'm able to do now, it's because the SDK initialization requires an `Activity` instance, by initializing with the application context, I receive this message:
```
Failed to initialize 3rd-party SDKs. Please make sure to initialize the AppLovin SDK with an Activity context
```
