### ISSUE TITLE
Load Applovin max native will cause crash

### ISSUE THREAD

**Issue by taugin** [AppLovin/AppLovin-MAX-SDK-Android#109]
Hello,

When I load max native, I got a crash error as follow:

01-24 15:20:35.662 27299 27299 E AndroidRuntime: java.util.ConcurrentModificationException
01-24 15:20:35.662 27299 27299 E AndroidRuntime:        at java.util.LinkedHashMap$LinkedHashIterator.nextNode(LinkedHashMap.java:775)
01-24 15:20:35.662 27299 27299 E AndroidRuntime:        at java.util.LinkedHashMap$LinkedEntryIterator.next(LinkedHashMap.java:808)
01-24 15:20:35.662 27299 27299 E AndroidRuntime:        at java.util.LinkedHashMap$LinkedEntryIterator.next(LinkedHashMap.java:806)
01-24 15:20:35.662 27299 27299 E AndroidRuntime:        at org.json.JSONObject.writeTo(JSONObject.java:732)
01-24 15:20:35.662 27299 27299 E AndroidRuntime:        at org.json.JSONObject.toString(JSONObject.java:701)
01-24 15:20:35.662 27299 27299 E AndroidRuntime:        at com.applovin.impl.sdk.AppLovinAdBase.<init>(Unknown Source:35)
01-24 15:20:35.662 27299 27299 E AndroidRuntime:        at com.applovin.impl.sdk.nativeAd.AppLovinNativeAdImpl.<init>(Unknown Source:12)
01-24 15:20:35.662 27299 27299 E AndroidRuntime:        at com.applovin.impl.sdk.nativeAd.AppLovinNativeAdImpl.<init>(Unknown Source:0)
01-24 15:20:35.662 27299 27299 E AndroidRuntime:        at com.applovin.impl.sdk.nativeAd.AppLovinNativeAdImpl$Builder.build(Unknown Source:3)
01-24 15:20:35.662 27299 27299 E AndroidRuntime:        at com.applovin.impl.sdk.nativeAd.e.a(Unknown Source:95)
01-24 15:20:35.662 27299 27299 E AndroidRuntime:        at com.applovin.impl.sdk.nativeAd.e.adReceived(Unknown Source:9)
01-24 15:20:35.662 27299 27299 E AndroidRuntime:        at com.applovin.impl.sdk.e.c$2.run(Unknown Source:18)
01-24 15:20:35.662 27299 27299 E AndroidRuntime:        at android.os.Handler.handleCallback(Handler.java:900)
01-24 15:20:35.662 27299 27299 E AndroidRuntime:        at android.os.Handler.dispatchMessage(Handler.java:103)
01-24 15:20:35.662 27299 27299 E AndroidRuntime:        at android.os.Looper.loop(Looper.java:219)
01-24 15:20:35.662 27299 27299 E AndroidRuntime:        at android.app.ActivityThread.main(ActivityThread.java:8668)
01-24 15:20:35.662 27299 27299 E AndroidRuntime:        at java.lang.reflect.Method.invoke(Native Method)
01-24 15:20:35.662 27299 27299 E AndroidRuntime:        at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:513)
01-24 15:20:35.662 27299 27299 E AndroidRuntime:        at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1109)

**Comment by thomasmso** [comment]
Hey @taugin - Thanks for reporting the issue, we will release a new SDK this week with a fix.

**Comment by winnerawan** [comment]
Hi @thomasmso, sorry for bothering you, give me the release date so i can update my app asap

**Comment by thomasmso** [comment]
@winnerawan - It should be in a few days. We're working on a few other changes for the SDK as well.

**Comment by winnerawan** [comment]
@thomasmso why not release a minor update for this bug with maybe wrap with try catch? This crash is massive

**Comment by onestravel** [comment]
I also encountered this problem, waiting for an updated version

**Comment by ductientrinh** [comment]
Hi, some exception with applovin that my app crash.
1. Fatal Exception: java.lang.RuntimeException
Unable to start activity ComponentInfo{dan.prod.image/com.applovin.adview.AppLovinFullscreenActivity}: java.lang.NullPointerException: Attempt to invoke virtual method 'int java.lang.String.length()' on a null object reference

2. Fatal Exception: java.lang.NullPointerException
Attempt to invoke virtual method 'boolean com.applovin.impl.mediation.debugger.ui.b.b.a()' on a null object reference

3. Fatal Exception: java.lang.RuntimeException
Unable to start activity ComponentInfo{dan.prod.image/com.android.billingclient.api.ProxyBillingActivity}: java.lang.NullPointerException: Attempt to invoke virtual method 'android.content.IntentSender android.app.PendingIntent.getIntentSender()' on a null object reference\

4. Fatal Exception: java.lang.RuntimeException
Unable to start activity ComponentInfo{dan.prod.image/com.applovin.mediation.MaxDebuggerAdUnitDetailActivity}: java.lang.NullPointerException: Attempt to invoke virtual method 'java.lang.String com.applovin.impl.mediation.debugger.ui.a.b.a()' on a null object reference

5. Fatal Exception: java.lang.RuntimeException
Unable to destroy activity {dan.prod.image/com.applovin.mediation.MaxDebuggerMultiAdActivity}: java.lang.NullPointerException: Attempt to invoke virtual method 'com.applovin.impl.mediation.debugger.ui.testmode.b com.applovin.impl.sdk.m.J()' on a null object reference

**Comment by thomasmso** [comment]
@ductientrinh - Do you mind sending the stack traces of all those crashes to thomas.so@applovin.com and christopher.cong@applovin.com? Thanks!

(cc @christophercong)

**Comment by thomasmso** [comment]
Hi all - the crash is fixed in v11.1.0. Please let us know if you encounter further issues.

**Comment by apshard** [comment]
The original crash was fixed however we began to see crashes with the same java.util.ConcurrentModificationException but different stack trace.
```
Fatal Exception: java.util.ConcurrentModificationException
       at java.util.LinkedHashMap$LinkedHashIterator.nextNode(LinkedHashMap.java:757)
       at java.util.LinkedHashMap$LinkedKeyIterator.next(LinkedHashMap.java:780)
       at com.applovin.impl.sdk.utils.JsonUtils.shallowCopy(JsonUtils.java:15)
       at com.applovin.impl.sdk.nativeAd.e.a(e.java:2)
       at com.applovin.impl.sdk.nativeAd.e.adReceived(e.java:9)
       at com.applovin.impl.sdk.e.c$2.run(c.java:18)
       at android.os.Handler.handleCallback(Handler.java:938)
       at android.os.Handler.dispatchMessage(Handler.java:99)
       at android.os.Looper.loop(Looper.java:254)
       at android.app.ActivityThread.main(ActivityThread.java:8218)
       at java.lang.reflect.Method.invoke(Method.java)
       at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:632)
       at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1049)
```

**Comment by chauduyphanvu** [comment]
@apshard - ACK. We will be working on addressing the new one as well. 

Internal ticket for reference: https://app.asana.com/0/268044616416407/1201760054486673/f.

**Comment by williamycyh** [comment]
> The original crash was fixed however we began to see crashes with the same java.util.ConcurrentModificationException but different stack trace.
> 
> ```
> Fatal Exception: java.util.ConcurrentModificationException
>        at java.util.LinkedHashMap$LinkedHashIterator.nextNode(LinkedHashMap.java:757)
>        at java.util.LinkedHashMap$LinkedKeyIterator.next(LinkedHashMap.java:780)
>        at com.applovin.impl.sdk.utils.JsonUtils.shallowCopy(JsonUtils.java:15)
>        at com.applovin.impl.sdk.nativeAd.e.a(e.java:2)
>        at com.applovin.impl.sdk.nativeAd.e.adReceived(e.java:9)
>        at com.applovin.impl.sdk.e.c$2.run(c.java:18)
>        at android.os.Handler.handleCallback(Handler.java:938)
>        at android.os.Handler.dispatchMessage(Handler.java:99)
>        at android.os.Looper.loop(Looper.java:254)
>        at android.app.ActivityThread.main(ActivityThread.java:8218)
>        at java.lang.reflect.Method.invoke(Method.java)
>        at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:632)
>        at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1049)
> ```
still crash at v11.1.0, pls fix it

**Comment by thomasmso** [comment]
@williamycyh - Could you check out v11.1.2? It should be resolved there.
