### ISSUE TITLE
The Ad option View is too big

### ISSUE THREAD

**Issue by taugin** [AppLovin/AppLovin-MAX-SDK-Android#110]
Hello,

In MaxNativeAdView.java : 

View var4 = var1.getOptionsView();
  if (this.h != null && var4 != null) {
      **var4.setLayoutParams(new LayoutParams(-1, -1));**
      this.h.addView(var4);
  } else if (this.h != null) {
      this.h.setVisibility(8);
}

this code will cause a big ad option view like this:

![image](https://user-images.githubusercontent.com/5130314/150757325-b2bbd165-d68e-4baa-9b1b-a46d10083ca8.png)

should be modified to 
**var4.setLayoutParams(new LayoutParams(-2, -2));**

please check it.

**Comment by NanaAmoah** [comment]
Hi @taugin, which native ad method are you integrating? Can you also share which network this is for? You can find the network name by using our `onAdLoaded()` callback. Please find more information on how to do this [here](https://dash.applovin.com/documentation/mediation/android/testing-networks/creative-debugger).

**Comment by taugin** [comment]
Hello,

the network is mintegral

**Comment by NanaAmoah** [comment]
Hello. Thanks for sharing the network name. Here are our docs for our [template](https://dash.applovin.com/documentation/mediation/android/getting-started/native-templates) and [manual](https://dash.applovin.com/documentation/mediation/android/getting-started/native-manual) APIs.  Could you share the method you're using as well?

**Comment by maxakash** [comment]
Hey @NanaAmoah , I am using manual api to load native ads. Currently the ads are only served from AppLovin. I am not able to see Ad option view( which is required for FAN native ads) in the ads loaded. 
Any option to make it visible?

![WhatsApp Image 2022-01-26 at 1 49 22 PM](https://user-images.githubusercontent.com/17406944/151127505-9ad38e38-2252-4adc-ba1e-2a68c9ab8835.jpeg)
