### ISSUE TITLE
Pangle issue on MAX 11.0

### ISSUE THREAD

**Issue by UnateD** [AppLovin/AppLovin-MAX-SDK-Android#111]
Good afternoon. The application integrates MAX mediation and, among other providers, Pangle is used. Until recently, version max 10.3.5 was used and Pangle worked correctly. Last week the app was migrated to MAX version 11.0, Pangle version (`com.applovin.mediation:bytedance-adapter:4.1.1.5.2 `)
version of the Pangle adapter ( `com.pangle.global:ads-sdk:4.1.1.5` ) and now the number of requests to Pangle on this version has dropped from 20% to 1%. We tried to roll back the versions to the previous ones and everything became normal again. This behavior is reproduced on an interstitial format ad.
I note in advance that we conducted a similar experiment on our other applications - wherever we upgraded the version of Pangle and MAX to the above voiced, the situation repeated itself - requests to Pangle in the MAX console fall down.

**We tested similar behavior in mopub with the latest version of Pangle and requests kept their number there.**

What could be the reason for the fall in the Pangle provider in MAX mediation?

**Comment by NanaAmoah** [comment]
Hi @UnateD, please fill this [form](https://try.applovin.com/mopub-max-integration) so we can investigate this further.

**Comment by UnateD** [comment]
Good afternoon, we do not need to migrate - we have already transferred ads from MoPub to max. However, we are seeing the problem described above. What could be the reason?

**Comment by NanaAmoah** [comment]
Hello. In order to investigate what the reason could be, we would need the information collected in the form.

**Comment by UnateD** [comment]
in this form, I was asked for my name and address of the application in google play. I entered the data, but apart from "thank you" nothing happened on the page

**Comment by NanaAmoah** [comment]
Thanks for submitting the form. Someone from our business development team will reach out with updates.
