### ISSUE TITLE
Google AdMob adapter does not support Star Rating, Price, and Store fields for native ads

### ISSUE THREAD

**Issue by svenoaks** [AppLovin/AppLovin-MAX-SDK-Android#112]
Fields for AdMob native ads: https://support.google.com/admob/answer/6240809

It would be really great if MAX supported these fields as it is preventing me from switching to MAX as my mediation platform following acquisition of MoPub. These fields feature prominently in my ads and I feel it might decrease CPM somewhat to not include them.

With AdMob SDK directly, we can simply put the rating into a `RatingBar` view and it would be great if MAX supported that too along with the other fields.

**Comment by NanaAmoah** [comment]
Hi @svenoaks, thank you for bringing this to our attention. We'll consider it and bring it up to our product team and share updates when possible.
