### ISSUE TITLE
Applovin throw exception on some devices

### ISSUE THREAD

**Issue by ductientrinh** [AppLovin/AppLovin-MAX-SDK-Android#115]
Hi, I use Android SDK and have some exception with applovin

1. Fatal Exception: java.lang.RuntimeException
Unable to start activity ComponentInfo{dan.prod.image/com.applovin.adview.AppLovinFullscreenActivity}: java.lang.NullPointerException: Attempt to invoke virtual method 'int java.lang.String.length()' on a null object reference

2. Fatal Exception: java.lang.NullPointerException
Attempt to invoke virtual method 'boolean com.applovin.impl.mediation.debugger.ui.b.b.a()' on a null object reference

3. Fatal Exception: java.lang.RuntimeException
Unable to start activity ComponentInfo{dan.prod.image/com.android.billingclient.api.ProxyBillingActivity}: java.lang.NullPointerException: Attempt to invoke virtual method 'android.content.IntentSender android.app.PendingIntent.getIntentSender()' on a null object reference\

4. Fatal Exception: java.lang.RuntimeException
Unable to start activity ComponentInfo{dan.prod.image/com.applovin.mediation.MaxDebuggerAdUnitDetailActivity}: java.lang.NullPointerException: Attempt to invoke virtual method 'java.lang.String com.applovin.impl.mediation.debugger.ui.a.b.a()' on a null object reference

5. Fatal Exception: java.lang.RuntimeException
Unable to destroy activity {dan.prod.image/com.applovin.mediation.MaxDebuggerMultiAdActivity}: java.lang.NullPointerException: Attempt to invoke virtual method 'com.applovin.impl.mediation.debugger.ui.testmode.b com.applovin.impl.sdk.m.J()' on a null object reference

**Comment by ductientrinh** [comment]
@thomasmso,

Fatal Exception: java.lang.NullPointerException
Attempt to invoke interface method 'java.util.Iterator java.util.List.iterator()' on a null object reference
com.applovin.impl.mediation.e.a (e.java:14)
com.applovin.impl.mediation.e.a (e.java:1)
com.applovin.impl.mediation.MediationServiceImpl.collectSignal (MediationServiceImpl.java:44)
com.applovin.impl.mediation.b.b$2.run (b.java:26)
android.os.Handler.handleCallback (Handler.java:900)
android.os.Handler.dispatchMessage (Handler.java:103)
android.os.Looper.loop (Looper.java:219)
android.app.ActivityThread.main (ActivityThread.java:8299)
java.lang.reflect.Method.invoke (Method.java)
com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run (RuntimeInit.java:513)
com.android.internal.os.ZygoteInit.main (ZygoteInit.java:1052)

**Comment by ductientrinh** [comment]
@thomasmso,

Caused by java.lang.NullPointerException
Attempt to invoke virtual method 'int java.lang.String.length()' on a null object reference
com.applovin.impl.sdk.m.a (m.java:428)
com.applovin.sdk.AppLovinSdk.a (AppLovinSdk.java:143)
com.applovin.sdk.AppLovinSdk.getInstance (AppLovinSdk.java)
com.applovin.adview.AppLovinFullscreenActivity.onCreate (AppLovinFullscreenActivity.java:92)
android.app.Activity.performCreate (Activity.java:7144)
android.app.Activity.performCreate (Activity.java:7135)
android.app.Instrumentation.callActivityOnCreate (Instrumentation.java:1271)
android.app.ActivityThread.performLaunchActivity (ActivityThread.java:2931)
android.app.ActivityThread.handleLaunchActivity (ActivityThread.java:3086)
android.app.servertransaction.LaunchActivityItem.execute (LaunchActivityItem.java:78)
android.app.servertransaction.TransactionExecutor.executeCallbacks (TransactionExecutor.java:108)
android.app.servertransaction.TransactionExecutor.execute (TransactionExecutor.java:68)
android.app.ActivityThread$H.handleMessage (ActivityThread.java:1816)
android.os.Handler.dispatchMessage (Handler.java:106)
android.os.Looper.loop (Looper.java:193)
android.app.ActivityThread.main (ActivityThread.java:6718)
java.lang.reflect.Method.invoke (Method.java)
com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run (RuntimeInit.java:493)
com.android.internal.os.ZygoteInit.main (ZygoteInit.java:858)

**Comment by ductientrinh** [comment]
Fatal Exception: java.lang.NullPointerException
Attempt to invoke virtual method 'boolean com.applovin.impl.mediation.debugger.ui.b.b.a()' on a null object reference
com.applovin.impl.mediation.debugger.ui.b.a.onStart (a.java:12)
android.app.Instrumentation.callActivityOnStart (Instrumentation.java:1447)
android.app.Activity.performStart (Activity.java:8108)
android.app.ActivityThread.handleStartActivity (ActivityThread.java:3901)
android.app.servertransaction.TransactionExecutor.performLifecycleSequence (TransactionExecutor.java:235)
android.app.servertransaction.TransactionExecutor.cycleToPath (TransactionExecutor.java:215)
android.app.servertransaction.TransactionExecutor.executeLifecycleState (TransactionExecutor.java:187)
android.app.servertransaction.TransactionExecutor.execute (TransactionExecutor.java:105)
android.app.ActivityThread$H.handleMessage (ActivityThread.java:2464)
android.os.Handler.dispatchMessage (Handler.java:110)
android.os.Looper.loop (Looper.java:219)
android.app.ActivityThread.main (ActivityThread.java:8299)
java.lang.reflect.Method.invoke (Method.java)
com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run (RuntimeInit.java:513)
com.android.internal.os.ZygoteInit.main (ZygoteInit.java:1052)

**Comment by ductientrinh** [comment]
Caused by java.lang.NullPointerException
Attempt to invoke virtual method 'android.content.IntentSender android.app.PendingIntent.getIntentSender()' on a null object reference
com.android.billingclient.api.ProxyBillingActivity.onCreate (ProxyBillingActivity.java:78)
android.app.Activity.performCreate (Activity.java:8085)
android.app.Activity.performCreate (Activity.java:8073)
android.app.Instrumentation.callActivityOnCreate (Instrumentation.java:1320)
android.app.ActivityThread.performLaunchActivity (ActivityThread.java:3850)
android.app.ActivityThread.handleLaunchActivity (ActivityThread.java:4056)
android.app.servertransaction.LaunchActivityItem.execute (LaunchActivityItem.java:91)
android.app.servertransaction.TransactionExecutor.executeCallbacks (TransactionExecutor.java:149)
android.app.servertransaction.TransactionExecutor.execute (TransactionExecutor.java:103)
android.app.ActivityThread$H.handleMessage (ActivityThread.java:2464)
android.os.Handler.dispatchMessage (Handler.java:110)
android.os.Looper.loop (Looper.java:219)
android.app.ActivityThread.main (ActivityThread.java:8299)
java.lang.reflect.Method.invoke (Method.java)
com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run (RuntimeInit.java:513)
com.android.internal.os.ZygoteInit.main (ZygoteInit.java:1052)

**Comment by ductientrinh** [comment]
Caused by java.lang.NullPointerException
Attempt to invoke virtual method 'java.lang.String com.applovin.impl.mediation.debugger.ui.a.b.a()' on a null object reference
com.applovin.impl.mediation.debugger.ui.a.a.onCreate (a.java:10)
android.app.Activity.performCreate (Activity.java:8085)
android.app.Activity.performCreate (Activity.java:8073)
android.app.Instrumentation.callActivityOnCreate (Instrumentation.java:1320)
android.app.ActivityThread.performLaunchActivity (ActivityThread.java:3850)
android.app.ActivityThread.handleLaunchActivity (ActivityThread.java:4056)
android.app.servertransaction.LaunchActivityItem.execute (LaunchActivityItem.java:91)
android.app.servertransaction.TransactionExecutor.executeCallbacks (TransactionExecutor.java:149)
android.app.servertransaction.TransactionExecutor.execute (TransactionExecutor.java:103)
android.app.ActivityThread$H.handleMessage (ActivityThread.java:2464)
android.os.Handler.dispatchMessage (Handler.java:110)
android.os.Looper.loop (Looper.java:219)
android.app.ActivityThread.main (ActivityThread.java:8299)
java.lang.reflect.Method.invoke (Method.java)
com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run (RuntimeInit.java:513)
com.android.internal.os.ZygoteInit.main (ZygoteInit.java:1052)

**Comment by ductientrinh** [comment]
Caused by java.lang.NullPointerException
Attempt to invoke virtual method 'com.applovin.impl.mediation.debugger.ui.testmode.b com.applovin.impl.sdk.m.J()' on a null object reference
com.applovin.impl.mediation.debugger.ui.testmode.a.onDestroy (a.java:5)
android.app.Activity.performDestroy (Activity.java:8349)
android.app.Instrumentation.callActivityOnDestroy (Instrumentation.java:1355)
android.app.ActivityThread.performDestroyActivity (ActivityThread.java:5645)
android.app.ActivityThread.handleDestroyActivity (ActivityThread.java:5690)
android.app.servertransaction.DestroyActivityItem.execute (DestroyActivityItem.java:44)
android.app.servertransaction.TransactionExecutor.executeLifecycleState (TransactionExecutor.java:190)
android.app.servertransaction.TransactionExecutor.execute (TransactionExecutor.java:105)
android.app.ActivityThread$H.handleMessage (ActivityThread.java:2464)
android.os.Handler.dispatchMessage (Handler.java:110)
android.os.Looper.loop (Looper.java:219)
android.app.ActivityThread.main (ActivityThread.java:8299)
java.lang.reflect.Method.invoke (Method.java)
com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run (RuntimeInit.java:513)
com.android.internal.os.ZygoteInit.main (ZygoteInit.java:1052)

**Comment by maxakash** [comment]
@ductientrinh They are aware of the crashes and going to release an update by the starting of next week.

**Comment by Lorenzo45** [comment]
Hi @ductientrinh - Would you be able to send the Android Studio project where you're seeing these crashes. We'd like to see how you're integrating our SDK.

**Comment by Lorenzo45** [comment]
It looks like you may not have set your SDK key correctly. Have you set your SDK key in the Android Manifest as described here? https://dash.applovin.com/documentation/mediation/android/getting-started/integration#add-the-sdk-key

If you could also share the logs from your session that would be helpful in diagnosing the issue.

**Comment by ductientrinh** [comment]
Hi, I already added the sdk key to Android Manifest and I don't "Enable Ad
Review".
The exceptions occur on Huawei and Pixel 3 XL devices

Regards,
Duc Trinh

**Comment by Lorenzo45** [comment]
Noted, thanks. Could you send device logs from a session where you see the crash? Alternatively an APK or the Android Studio project itself would be even better. Without these we won't be able to diagnose the issue.

**Comment by ductientrinh** [comment]
Hi, This is the project test that I made. It the same code with my project.
You can input your test sdk key and ad unit ids to reproduce the issues.
Please get the project that I shared on google drive.

https://drive.google.com/file/d/1LX7D_mBhtA-lEtWMT1pCQbzaPcZsGKmC/view?usp=sharing

Regards,
Duc Trinh

**Comment by applovinAsh** [comment]
Hi Duc, 

I tested the application you provided, and I could not reproduce the crash you saw. While testing the application, the only ad format that loaded initially was MREC, and I had no problems getting an ad to load and display. 

After messing with the code, I was able to test all ad formats (inters, banners, MRECs, and native) and was able to load and display all of them successfully. I was also able to load the mediation debugger and test ads.  

Can you explain what happens in the application before this crash to help us understand better?

**Comment by williamycyh** [comment]
> Hi Duc,
> 
> I tested the application you provided, and I could not reproduce the crash you saw. While testing the application, the only ad format that loaded initially was MREC, and I had no problems getting an ad to load and display.
> 
> After messing with the code, I was able to test all ad formats (inters, banners, MRECs, and native) and was able to load and display all of them successfully. I was also able to load the mediation debugger and test ads.
> 
> Can you explain what happens in the application before this crash to help us understand better?

I also crash when call AppLovinSdk.getInstance(MainActivity.this).showMediationDebugger().
My another app is ok, it is a little weird.

02-14 19:10:32.479 16635 16635 E AndroidRuntime: java.lang.NullPointerException: Attempt to invoke virtual method 'void android.widget.ListView.setAdapter(android.widget.ListAdapter)' on a null object reference
02-14 19:10:32.479 16635 16635 E AndroidRuntime:        at com.applovin.impl.mediation.debugger.ui.b.a.onStart(Unknown Source:7)
02-14 19:10:32.479 16635 16635 E AndroidRuntime:        at android.app.Instrumentation.callActivityOnStart(Instrumentation.java:1433)
02-14 19:10:32.479 16635 16635 E AndroidRuntime:        at android.app.Activity.performStart(Activity.java:7986)
02-14 19:10:32.479 16635 16635 E AndroidRuntime:        at android.app.ActivityThread.handleStartActivity(ActivityThread.java:3677)
02-14 19:10:32.479 16635 16635 E AndroidRuntime:        at android.app.servertransaction.TransactionExecutor.performLifecycleSequence(TransactionExecutor.java:221)
02-14 19:10:32.479 16635 16635 E AndroidRuntime:        at android.app.servertransaction.TransactionExecutor.cycleToPath(TransactionExecutor.java:201)
02-14 19:10:32.479 16635 16635 E AndroidRuntime:        at android.app.servertransaction.TransactionExecutor.executeLifecycleState(TransactionExecutor.java:173)
02-14 19:10:32.479 16635 16635 E AndroidRuntime:        at android.app.servertransaction.TransactionExecutor.execute(TransactionExecutor.java:97)
02-14 19:10:32.479 16635 16635 E AndroidRuntime:        at android.app.ActivityThread$H.handleMessage(ActivityThread.java:2267)
02-14 19:10:32.479 16635 16635 E AndroidRuntime:        at android.os.Handler.dispatchMessage(Handler.java:107)
02-14 19:10:32.479 16635 16635 E AndroidRuntime:        at android.os.Looper.loop(Looper.java:237)
02-14 19:10:32.479 16635 16635 E AndroidRuntime:        at android.app.ActivityThread.main(ActivityThread.java:8167)
02-14 19:10:32.479 16635 16635 E AndroidRuntime:        at java.lang.reflect.Method.invoke(Native Method)
02-14 19:10:32.479 16635 16635 E AndroidRuntime:        at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:496)
02-14 19:10:32.479 16635 16635 E AndroidRuntime:        at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1100)

**Comment by santoshbagadi** [comment]
@williamycyh , We have recently fixed this crash (`NullPointerException: Attempt to invoke virtual method 'void android.widget.ListView.setAdapter(android.widget.ListAdapter)`) in our latest release v11.1.2. Please let us know if you still experience this issue after upgrading to that version.

**Comment by williamycyh** [comment]
> @williamycyh , We have recently fixed this crash (`NullPointerException: Attempt to invoke virtual method 'void android.widget.ListView.setAdapter(android.widget.ListAdapter)`) in our latest release v11.1.2. Please let us know if you still experience this issue after upgrading to that version.

i am using v11.1.2, still crash when call AppLovinSdk.getInstance(MainActivity.this).showMediationDebugger()

**Comment by christophercong** [comment]
Hi @williamycyh, would you mind providing the full device logs or a project with v11.1.2?
