### ISSUE TITLE
No proper AdMob adaptive-ads support

### ISSUE THREAD

**Issue by caynax** [AppLovin/AppLovin-MAX-SDK-Android#116]
I never get server parameter "adaptive_banner" to display AdMob adaptive ads:

`if ( adFormat == MaxAdFormat.BANNER || adFormat == MaxAdFormat.LEADER )
        {
            // Check if adaptive banner sizes should be used
            if ( serverParameters.getBoolean( "adaptive_banner", false ) )
            {
                Display display = activity.getWindowManager().getDefaultDisplay();
                DisplayMetrics outMetrics = new DisplayMetrics();
                display.getMetrics( outMetrics );
                int screenWidthDp = AppLovinSdkUtils.pxToDp( activity, outMetrics.widthPixels );

                return AdSize.getCurrentOrientationAnchoredAdaptiveBannerAdSize( activity, screenWidthDp );
            }
            else
            {
                return adFormat == MaxAdFormat.BANNER ? AdSize.BANNER : AdSize.LEADERBOARD;
            }
        }`

If I force to always display adaptive banner ads then they are cut and there is no close X button visible.
They don't scale and always stay in fixed 50dp height size.
![Screenshot_20220124_195511](https://user-images.githubusercontent.com/87134484/151162271-6f6887cd-4bff-4689-a9c8-f9f2ee371b36.jpg)

In example above I have replaced:
`return adFormat == MaxAdFormat.BANNER ? AdSize.BANNER : AdSize.LEADERBOARD;`
with
`return adFormat == MaxAdFormat.BANNER ? new AdSize(FULL_WIDTH, 50) : new AdSize(FULL_WIDTH, 90);`
to at least get full width ads and not 320 width.

I'm losing on ads quality because of this. Please fix it.

**Comment by caynax** [comment]
Resolved it.
Instead of using it as documentation says and strictly limits us to 50dp or 90dp:

>         // Stretch to the width of the screen for banners to be fully functional
>        int width = ViewGroup.LayoutParams.MATCH_PARENT;
>    
>        // Banner height on phones and tablets is 50 and 90, respectively
>        int heightPx = getResources().getDimensionPixelSize( R.dimen.banner_height );
>    
>        adView.setLayoutParams( new FrameLayout.LayoutParams( width, heightPx ) );



I have used that:
>		int width = ViewGroup.LayoutParams.MATCH_PARENT;
>		boolean isTablet = getContext().getResources().getBoolean(R.bool.cx_isTablet);
>		if(isTablet)
>		{
>			int heightPx = getContext().getResources().getDimensionPixelSize(R.dimen.cx_tabletBannerHeight);
>			mAdView.setLayoutParams(new FrameLayout.LayoutParams(width, heightPx));
>		}
>		else
>		{
>			Display display = getContext().getWindowManager().getDefaultDisplay();
>			DisplayMetrics outMetrics = new DisplayMetrics();
>			display.getMetrics(outMetrics);
>
>			float widthPixels = outMetrics.widthPixels;
>			float density = outMetrics.density;
>
>			int adWidth = (int) (widthPixels / density);
>
>			AdSize calculatedAdSize =  AdSize.getCurrentOrientationAnchoredAdaptiveBannerAdSize(getContext(), adWidth);
>			
>			mAdView.setLayoutParams(new FrameLayout.LayoutParams(width, >calculatedAdSize.getHeightInPixels(getContext())));
>		}

Unfortunately setting it like this:
>		mAdView.setLayoutParams(new FrameLayout.LayoutParams(ViewGroup.LayoutParams.MATCH_PARENT, ViewGroup.LayoutParams.WRAP_CONTENT));


doesn't work as ad container gets full height.

**Comment by caynax** [comment]
Unfortunately I have to reopen it.
Even though I set the same size (height) for AppLovin banner and Google banner somehow AdMob banner always get cut and AppLovin banner leave some space blank so AdMob ad is cut.
![Screenshot_20220126-180222](https://user-images.githubusercontent.com/87134484/151211248-46fdbb1e-fa61-4ba7-8a29-3ba78e73e243.png)

**Comment by NanaAmoah** [comment]
Hi @caynax, are you setting  adaptive banner to `true` before loading the ad?  Like this:
`adView.setExtraParameter( "adaptive_banner", "true" );`

**Comment by caynax** [comment]
Hi. Thanks for answer,
No I was not setting it. Where was that mentioned in documentation?

Testing but is seems like that resolves these cut ads and blank space issue.

**Comment by NanaAmoah** [comment]
Great! You can find this in our documentation [here](https://dash.applovin.com/documentation/mediation/android/getting-started/banners) under **Adaptive Banners** after `adView.setLayoutParams( new FrameLayout.LayoutParams( width, heightPx ) );` is set in the code snippet.
