### ISSUE TITLE
Pangle mediation bug (Could not find com.pangle.global:ads-sdk:4.1.19)

### ISSUE THREAD

**Issue by mastervnc** [AppLovin/AppLovin-MAX-SDK-Android#119]
Please check, if i add Pangle adapter → Could not find com.pangle.global:ads-sdk:4.1.19

**Comment by NanaAmoah** [comment]
Hello @mastervnc, how are you integrating our adapters? You can find the three ways our adapters can be integrated [here](https://dash.applovin.com/documentation/mediation/android/mediation-adapters?network=TIKTOK_NETWORK). 

If you are integrating using Gradle, do you mind sharing the snippet of code showing how you integrate the Pangle adapter in your app-level `build.gradle` file?

**Comment by mastervnc** [comment]
I using implementation 'com.applovin.mediation:google-adapter:+' without problems, but if i add implementation 'com.applovin.mediation:bytedance-adapter:+' will get this error. I check you just updated to version 4.1.1.9.1 a few hours ago, maybe this is the cause?
