### ISSUE TITLE
Advertiser name is empty for FAN in manual native ad

### ISSUE THREAD

**Issue by maxakash** [AppLovin/AppLovin-MAX-SDK-Android#125]
I am using FAN as ad network for manual native ad. 
When using test ads, advertiser name is visible and for live ads filled with AppLoving Exchange.

Advertiser name is a mandatory requirement for FAN. 
Please look into it.

P.S : I am using  AppLovin Sdk v11.1.0 and FAN adapter v6.8.0.5.

**Comment by tiandrew** [comment]
Hey @maxakash, I've pushed a new version of our FAN adapter v6.8.0.6 that adds the advertiser name.

**Comment by maxakash** [comment]
Hey @tiandrew Thanks. Also look into the size of privacy icon and it's background color for AppLovin native ads

**Comment by tiandrew** [comment]
Hey @maxakash, could you elaborate more on that? Is there something wrong with the size of the privacy icon and its background color for AppLovin native ads? Feel free to open another issue if there is an issue.

**Comment by maxakash** [comment]
Hey @tiandrew Yes, the size of privacy icon is bigger than it should be. Also its background is not transparent but greyish.

**Comment by tiandrew** [comment]
Do you have a screenshot of the icon? Ours is 20x20 dp, and the background is supposed to be set to grey - that's our standard privacy icon.
