### ISSUE TITLE
NPE when initialising Native ads

### ISSUE THREAD

**Issue by NedkoBrymchev** [AppLovin/AppLovin-MAX-SDK-Android#126]
Hello, we added Native ads to our application using the Manual template. 
However there is a strange crash that we can`t reproduce on our own, but Firebase and the store report a huge amount of crashes that affects our users. We are using version 11.0.0 of the SDK, with lots of adapters. For the native ads we are only using AppLovin & AppLovin Exchange as network bidders.

Currently for the past 7 days the affected users are more than 8000 and the triggered events are more than 50 000, Here is the stack trace: 

> Fatal Exception: java.lang.NullPointerException: Attempt to invoke virtual method 'char[] java.lang.String.toCharArray()' on a null object reference
>        at com.applovin.impl.sdk.AppLovinAdBase.<init>(AppLovinAdBase.java:39)
>        at com.applovin.impl.sdk.nativeAd.AppLovinNativeAdImpl.<init>(AppLovinNativeAdImpl.java:12)
>        at com.applovin.impl.sdk.nativeAd.AppLovinNativeAdImpl.<init>(AppLovinNativeAdImpl.java)
>        at com.applovin.impl.sdk.nativeAd.AppLovinNativeAdImpl$Builder.build(AppLovinNativeAdImpl.java:3)
>        at com.applovin.impl.sdk.nativeAd.e.a(e.java:95)
>        at com.applovin.impl.sdk.nativeAd.e.adReceived(e.java:9)
>        at com.applovin.impl.sdk.e.c$2.run(c.java:18)
>        at android.os.Handler.handleCallback(Handler.java:907)
>        at android.os.Handler.dispatchMessage(Handler.java:105)
>        at android.os.Looper.loop(Looper.java:216)
>        at android.app.ActivityThread.main(ActivityThread.java:7625)
>        at java.lang.reflect.Method.invoke(Method.java)
>        at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:524)
>        at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:987)

**Comment by thomasmso** [comment]
Hi, thank you for reporting this issue. To better analyze the issue, could you email your AppLovin account email and the Crashlytics time chart for this crash to me at thomas.so@applovin.com? It would be helpful to know when this crash started occurring (unless it occurred immediately after integration/release). Thanks!

**Comment by NedkoBrymchev** [comment]
The issue is resolved in the latest to current date version. 
After updating to version 11.1.0, the crash was resolved. 

Thank you, @thomasmso. 
Moving this issue to "Closed".
