### ISSUE TITLE
Pangle / AdColony bidding issues in MAX 11.0

### ISSUE THREAD

**Issue by UnateD** [AppLovin/AppLovin-MAX-SDK-Android#129]
Good afternoon. The previous question was closed without an answer and no one contacted us. Duplicate my question again as nothing has changed

The application integrates MAX mediation and, among other providers, Pangle is used. Until recently, version max 10.3.5 was used and Pangle worked correctly. Last week the app was migrated to MAX version 11.0, Pangle version (com.applovin.mediation:bytedance-adapter:4.1.1.5.2 )
version of the Pangle adapter ( com.pangle.global:ads-sdk:4.1.1.5 ) and now the number of requests to Pangle on this version has dropped from 20% to 1%. We tried to roll back the versions to the previous ones and everything became normal again. This behavior is reproduced on an interstitial format ad.
I note in advance that we conducted a similar experiment on our other applications - wherever we upgraded the version of Pangle and MAX to the above voiced, the situation repeated itself - requests to Pangle in the MAX console fall down.

We tested similar behavior in mopub with the latest version of Pangle and requests kept their number there.

What could be the reason for the fall in the Pangle provider in MAX mediation?

**Comment by UnateD** [comment]
@chauduyphanvu Hello! Thanks for the answer. We checked the behavior on the project, where we only updated MAX to the latest version, and even without changing the version of the adapters, the proportions of requests change - most requests go to Applovin and other networks do not receive requests in bidding. However, if we roll back to version 10.3, everything becomes normal. Could you explain why there is such a difference in the distribution of requests in bidding between versions 10.3 and 11?

**Comment by chauduyphanvu** [comment]
@UnateD, there was a recent server-side change (just yesterday) to correct that. Could you try to update to v11.x again and let us know if you continue seeing the issue?

Thanks!

**Comment by caricent** [comment]
Hi @chauduyphanvu Our app had the same problem as @UnateD.

The MAX version we accessed is 11.2.0, and the pangle version is 4.2.5.2.

Under the bidding of MAX, the request volume of Pangle's rewarded ads and interstitial ads is 20% of the other networks.

We hope to get an answer, thank you
