### ISSUE TITLE
Native ads in test mode (template) always show full screen, very difficult to test.

### ISSUE THREAD

**Issue by mastervnc** [AppLovin/AppLovin-MAX-SDK-Android#131]
I have tried setting it to small or medium in the dashboard but it's still the same, the ads always fill the screen, covering the main screen of the app, so it's hard to check, please fix it soon this problem.

**Comment by chauduyphanvu** [comment]
@mastervnc - could you show us a screenshot and some code snippets pertaining to your native ad integration? Thanks!

Vu Chau
AppLovin Team

**Comment by chandankrs2022** [comment]
Hi I am also facing same issue. I have tried setting it to small or medium in the dashboard but it's still the same, the ads always fill the screen, covering the main screen of the app, so it's hard to check and in dark mode hard to read text also
<img width="534" alt="Screenshot 2022-02-22 at 1 43 09 PM" src="https://user-images.githubusercontent.com/100191844/155090265-25ecb24a-2069-4ec6-bac4-2fdf106ba91b.png">
, Could you please guide to us how to fix.

**Comment by chauduyphanvu** [comment]
Thanks. Could you show us your code that requests and renders the native ad? 

Here's our [sample app layout](https://github.com/AppLovin/AppLovin-MAX-SDK-Android/blob/master/AppLovin%20MAX%20Demo%20App%20-%20Java/app/src/main/res/layout/native_custom_ad_view.xml) layout for reference.

**Comment by santoshbagadi** [comment]
Actually, looks like this is for template ads. 

@mastervnc , @chandankrs2022  Our `MaxNativeAdView` uses the container view provided for the template ads. So, please set your desired height to the container view or set it to the `MaxNativeAdView` provided when adding it to a container view.

**Comment by chandankrs2022** [comment]
> Thanks. Could you show us your code that requests and renders the native ad?
> 
> Here's our [sample app layout](https://github.com/AppLovin/AppLovin-MAX-SDK-Android/blob/master/AppLovin%20MAX%20Demo%20App%20-%20Java/app/src/main/res/layout/native_custom_ad_view.xml) layout for reference.


    <FrameLayout
        android:layout_marginTop="@dimen/_10sdp"
        android:id="@+id/dashboardNativeAdLayout"
        android:layout_width="match_parent"
        android:layout_height="wrap_content" />


    private fun showNativeAdDashboard()
    {
        val nativeAdContainer = rootView.dashboardNativeAdLayout
        nativeAdLoaderDashboard = MaxNativeAdLoader( getString(R.string.applovin_native_small_id),requireActivity() )
        nativeAdLoaderDashboard.setNativeAdListener(object : MaxNativeAdListener() {

            override fun onNativeAdLoaded(nativeAdView: MaxNativeAdView, ad: MaxAd)
            {
                if ( nativeAdDashboard != null ) {
                    nativeAdLoaderDashboard.destroy( nativeAdDashboard )
                }
                nativeAdDashboard = ad
                nativeAdContainer.removeAllViews()
                nativeAdContainer.addView( nativeAdView )
            }

            override fun onNativeAdLoadFailed(adUnitId: String, error: MaxError)
            {}

            override fun onNativeAdClicked(ad: MaxAd)
            {}
        })
        nativeAdLoaderDashboard.loadAd()
    }

Note:-> Please consider its small native ads.If I am setting height ads formate is coming properly.

**Comment by santoshbagadi** [comment]
Hi @chandankrs2022 , please consider setting a desired height to the container `dashboardNativeAdLayout` to fix the issue. 

```
<FrameLayout
    android:layout_marginTop="@dimen/_10sdp"
    android:id="@+id/dashboardNativeAdLayout"
    android:layout_width="match_parent"
    android:layout_height="250dp" />
```
