### ISSUE TITLE
Bidding for AppLovin Native (Manual) to FAN Native Banner  

### ISSUE THREAD

**Issue by clevsh** [AppLovin/AppLovin-MAX-SDK-Android#135]
HI.

I am trying integrating AppLovin Native (Manual) and I succeed.
But it can not bid to FAN's native banner.

"Media Content View" is not mandatory for FAN's native banner.
But "setMediaContentViewId( R.id.media_view_container )" seems to be mandatory for loading AppLovin's Native ad.

"com.facebook.ads.MediaView" is used for "Icon" in FAN's native banner.

Therefore, "setIconImageViewId( R.id.icon_image_view )" should be changed to
 "setIconContentViewId( R.id.icon_view_container )" and
 "R.id.icon_view_container" should be "FrameLayout" for loading FAN's native banner.

Please add the option for loading FAN's native banner.

AdMob already has the feature.
https://developers.google.com/admob/android/mediation/facebook

var extras = FacebookExtras()
       .setNativeBanner(true)
       .build()

**Comment by NanaAmoah** [comment]
Hello @clevsh, we're actively working on adding support for Facebook's native banners. I will share updates once they are available.

**Comment by NanaAmoah** [comment]
Hello @clevsh, support for Meta (Facebook) native banners is now live.
