### ISSUE TITLE
Native Ad Custom Event adapter for Admob

### ISSUE THREAD

**Issue by robertdo** [AppLovin/AppLovin-MAX-SDK-Android#137]
No official adapter exists, so I am currently trying to write my own following the Admob documentation:
https://developers.google.com/admob/android/custom-events/native

However, I am getting stuck at mapping the AppLovin native ad data to Admob's required spec. For example, I cannot find the native ad data (ie. title, image urls, body text, etc.) in the returned MaxNativeAdView or MaxAd. Also I cannot find the methods for recording impressions or handling clicks.

**Comment by thomasmso** [comment]
`Max*` APIs are used for our mediation solution. We do not support AppLovin native ads outside of MAX yet, but we will in Q2.
