### ISSUE TITLE
Help!!!!!    [AdWebView] about:blank: 0: Not allowed to load local resource:

### ISSUE THREAD

**Issue by skyzd** [AppLovin/AppLovin-MAX-SDK-Android#139]
AppLovin Interstitial Ad
Black screen may appear when the advertisement is displayed or after the video is played. 
View logs, The webView cannot load JS or images.

Key to log：
:23.045 2967-2967/ D/AppLovinSdk: [AdWebView] about:blank: 0: Not allowed to load local resource: file:///data/user/0//files/al/ofc4cdc5_989fd91d778c910eae4cd7c21a4b191a9b82c01f_v21_phone.jpg
:23.045 2967-2967/ D/AppLovinSdk: [AdWebView] about:blank: 0: Not allowed to load local resource: file:///data/user/0//files/al/1381250003_28x28.png

A complete log：
:22.782 2967-2967/ D/AppLovinSdk: [AppLovinAdView] Rendering advertisement ad for #6146428...
:22.783 2967-2967/ D/AppLovinSdk: [AdWebView] AppLovinAd rendered
:22.784 2967-2967/ I/AppLovinSdk: [AppLovinMediationAdapter] Interstitial ad shown
:22.784 2967-2967/ I/AppLovinSdk: [MediationAdapterWrapper] AppLovinMediationAdapter: interstitial ad displayed with extra info: null
:22.784 2967-2967/ D/AppLovinSdk: [AppLovinSdk] Creating ad debug thread with name: AL-11.1.0-INTER-6146428
:22.829 2967-3730/ I/AppLovinSdk: [ConnectionManager] Successful GET returned 200 in 0.115 s over wifi to #-746395644 "prod-ms.applovin.com/1.0/event/cimp"
:22.913 2967-2967/ I/AppLovinSdk: [AdWebView] Loaded resource: data:text/html;charset=utf-8;base64,
:22.918 2967-2967/ D/AppLovinSdk: [AppLovinFullscreenActivity] Web content rendered
:22.918 2967-2967/ D/AppLovinSdk: [AdWebView] Forwarding "javascript:al_onAdViewRendered();" to ad template
:22.924 2967-2967/ D/AppLovinSdk: [AdWebView] : 1: Winter Is Coming!
:22.924 2967-2967/ D/AppLovinSdk: [AdWebView] about:blank: 1: Uncaught ReferenceError: al_onAdViewRendered is not defined
:22.925 2967-2967/ D/AppLovinSdk: [MediationService] Scheduling impression for ad via callback...
:22.925 2967-2967/ D/AppLovinSdk: [CommunicatorService] Sending "max_ad_events" message: Bundle[{network_placement=inter_regular, third_party_ad_placement_id=inter_regular, creative_id=6146428, network_name=APPLOVIN_NETWORK, id=14d09f4dbcf9acca6493d82100b85d60c8bb8bf7, type=DID_DISPLAY, ad_format=INTER, max_ad_unit_id=cefadb7cf7225ce6}]
:22.926 2967-3568/ I/AppLovinSdk: [ConnectionManager] Sending GET request to id=#1843018685 "prod-ms.applovin.com/1.0/event/cimp"...
:22.926 2967-2967/ D/AppLovinSdk: [AppLovinSdk] Creating ad debug thread with name: MAX-11.1.0-INTER-APPLOVIN-6146428
:22.927 2967-2967/ D/AppLovinSdk: [FullScreenAdTracker] Setting fullscreen ad displayed: 1644233542927
:22.929 2967-2967/ D/AppLovinSdk: [AdWebView] : 1: [object Object]
:22.930 2967-2967/ I/AppLovinSdk: [AdWebView] Loaded resource: data:text/html;charset=utf-8;base64,
:22.962 2967-2967/ D/AppLovinSdk: [AppLovinFullscreenActivity] MediaPlayer prepared: android.media.MediaPlayer@397e266
:22.963 2967-2967/ I/AppLovinSdk: [AdWebView] Loaded resource: file:///data/user/0//files/al/ofc4cdc5_989fd91d778c910eae4cd7c21a4b191a9b82c01f_v21_phone.jpg
:22.963 2967-2967/ I/AppLovinSdk: [AdWebView] Loaded resource: file:///data/user/0//files/al/1381250003_28x28.png
:22.991 2967-3568/ I/AppLovinSdk: [ConnectionManager] Successful GET returned 200 in 0.065 s over wifi to #1843018685 "prod-ms.applovin.com/1.0/event/cimp"
:23.003 2967-2967/ D/AppLovinSdk: [MaxNativeAdLoader] MaxNativeAdLoader(adUnitId=2fd865a5c2dfa2dc, sdk=AppLovinSdk{sdkKey='gRKTQxnkCCOx30n8aSSe7UhLOdy5gATLpkRBepcuMMDTkZ3PLr-94oG8wDXzSiMPSsqAKRTr8JUb1o3TJUR2dk', isEnabled=true, isFirstSession=true})
:23.003 2967-2967/ D/AppLovinSdk: [MaxNativeAdLoader] Created new MaxNativeAdLoader (MaxNativeAdLoader{adUnitId='2fd865a5c2dfa2dc', nativeAdListener=null, revenueListener=null})
:23.003 2967-2967/ D/AppLovinSdk: [MaxNativeAdLoader] setNativeAdListener(listener=com.vt.lib.adcenter.applovin.ApplovinNativeAdLoader$1@fd3b116)
:23.003 2967-2967/ D/AppLovinSdk: [MaxNativeAdLoader] Setting native ad listener: com.vt.lib.adcenter.applovin.ApplovinNativeAdLoader$1@fd3b116
:23.003 2967-2967/ D/AppLovinSdk: [MaxNativeAdLoader] loadAd(adView=null)
:23.003 2967-2967/ D/AppLovinSdk: [MaxNativeAdLoader] Loading native ad for '2fd865a5c2dfa2dc' and notifying com.applovin.impl.mediation.ads.MaxNativeAdLoaderImpl$a@a1b4a97...
:23.004 2967-3560/ D/AppLovinSdk: [TaskCollectSignals] Running signal collection for MINTEGRAL_BIDDING on the main thread
:23.004 2967-3564/ D/AppLovinSdk: [TaskCollectSignals] Running signal collection for APPLOVIN_NETWORK on the background thread
:23.004 2967-3560/ D/AppLovinSdk: [TaskCollectSignals] Running signal collection for TIKTOK_BIDDING on the background thread
:23.004 2967-3564/ D/AppLovinSdk: [MediationAdapterManager] Loaded APPLOVIN_NETWORK
:23.004 2967-3563/ D/AppLovinSdk: [TaskCollectSignals] Running signal collection for MYTARGET_BIDDING on the background thread
:23.004 2967-3560/ D/AppLovinSdk: [MediationAdapterManager] Not attempting to load TIKTOK_BIDDING due to prior errors
:23.004 2967-3563/ D/AppLovinSdk: [MediationAdapterManager] Not attempting to load MYTARGET_BIDDING due to prior errors
:23.004 2967-3560/ D/AppLovinSdk: [TaskCollectSignals] Running signal collection for APPLOVIN_EXCHANGE on the background thread
:23.004 2967-3563/ D/AppLovinSdk: [TaskCollectSignals] Running signal collection for VERVE_BIDDING on the background thread
:23.004 2967-3560/ D/AppLovinSdk: [MediationAdapterManager] Loaded APPLOVIN_EXCHANGE
:23.004 2967-3564/ D/AppLovinSdk: [MediationAdapterManager] Loaded APPLOVIN_NETWORK
:23.004 2967-3564/ I/AppLovinSdk: [MediationAdapterInitializationManager] Initializing adapter MediationAdapterSpec{adapterClass='com.applovin.mediation.adapters.AppLovinMediationAdapter', adapterName='APPLOVIN_NETWORK', isTesting=true}
:23.004 2967-3564/ D/AppLovinSdk: [MediationService] Collecting signal for adapter: APPLOVIN_NETWORK
:23.004 2967-3564/ D/AppLovinSdk: [MediationAdapterWrapper] AppLovinMediationAdapter: running collect_signal...
:23.004 2967-3564/ I/AppLovinSdk: [AppLovinMediationAdapter] Collecting signal...
:23.004 2967-3560/ D/AppLovinSdk: [MediationAdapterManager] Loaded APPLOVIN_NETWORK
:23.004 2967-3560/ I/AppLovinSdk: [MediationAdapterInitializationManager] Initializing adapter MediationAdapterSpec{adapterClass='com.applovin.mediation.adapters.AppLovinMediationAdapter', adapterName='APPLOVIN_NETWORK', isTesting=true}
:23.005 2967-3560/ D/AppLovinSdk: [MediationService] Collecting signal for adapter: APPLOVIN_EXCHANGE
:23.005 2967-3560/ D/AppLovinSdk: [MediationAdapterWrapper] AppLovinMediationAdapter: running collect_signal...
:23.005 2967-3560/ I/AppLovinSdk: [AppLovinMediationAdapter] Collecting signal...
:23.005 2967-3563/ D/AppLovinSdk: [MediationAdapterManager] Not attempting to load VERVE_BIDDING due to prior errors
:23.005 2967-3563/ D/AppLovinSdk: [TaskCollectSignals] Running signal collection for SAYGAMES_BIDDING on the background thread
:23.005 2967-3563/ D/AppLovinSdk: [MediationAdapterManager] Not attempting to load SAYGAMES_BIDDING due to prior errors
:23.005 2967-3563/ D/AppLovinSdk: [TaskCollectSignals] Running signal collection for OGURY_PRESAGE_BIDDING on the background thread
:23.005 2967-3563/ D/AppLovinSdk: [MediationAdapterManager] Not attempting to load OGURY_PRESAGE_BIDDING due to prior errors
:23.005 2967-3563/ D/AppLovinSdk: [TaskCollectSignals] Running signal collection for TAPJOY_NETWORK on the background thread
:23.005 2967-3563/ D/AppLovinSdk: [MediationAdapterManager] Not attempting to load TAPJOY_NETWORK due to prior errors
:23.005 2967-3563/ D/AppLovinSdk: [TaskCollectSignals] Running signal collection for FACEBOOK_NETWORK on the background thread
:23.005 2967-3563/ D/AppLovinSdk: [MediationAdapterManager] Loaded FACEBOOK_NETWORK
:23.006 2967-3563/ D/AppLovinSdk: [MediationAdapterManager] Loaded FACEBOOK_NETWORK
:23.006 2967-3563/ I/AppLovinSdk: [MediationAdapterInitializationManager] Initializing adapter MediationAdapterSpec{adapterClass='com.applovin.mediation.adapters.FacebookMediationAdapter', adapterName='FACEBOOK_NETWORK', isTesting=true}
:23.006 2967-3563/ D/AppLovinSdk: [MediationService] Collecting signal for adapter: FACEBOOK_NETWORK
:23.006 2967-3563/ D/AppLovinSdk: [MediationAdapterWrapper] FacebookMediationAdapter: running collect_signal...
:23.006 2967-3563/ I/AppLovinSdk: [FacebookMediationAdapter] Collecting signal...
:23.006 2967-3563/ D/AppLovinSdk: [MediationAdapterWrapper] FacebookMediationAdapter: running destroy...
:23.006 2967-3563/ I/AppLovinSdk: [MediationAdapterWrapper] Marking FacebookMediationAdapter as disabled due to: destroy
:23.006 2967-3563/ D/AppLovinSdk: [MediationAdapterWrapper] FacebookMediationAdapter: finished destroy
:23.006 2967-3563/ D/AppLovinSdk: [MediationAdapterWrapper] FacebookMediationAdapter: finished collect_signal
:23.006 2967-3563/ D/AppLovinSdk: [TaskCollectSignals] Running signal collection for ADCOLONY_NETWORK on the background thread
:23.006 2967-3563/ D/AppLovinSdk: [MediationAdapterManager] Not attempting to load ADCOLONY_NETWORK due to prior errors
:23.009 2967-3560/ D/AppLovinSdk: [MediationAdapterWrapper] AppLovinMediationAdapter: running destroy...
:23.009 2967-3560/ I/AppLovinSdk: [MediationAdapterWrapper] Marking AppLovinMediationAdapter as disabled due to: destroy
:23.009 2967-3560/ D/AppLovinSdk: [MediationAdapterWrapper] AppLovinMediationAdapter: finished destroy
:23.009 2967-3560/ D/AppLovinSdk: [MediationAdapterWrapper] AppLovinMediationAdapter: finished collect_signal
:23.009 2967-3564/ D/AppLovinSdk: [MediationAdapterWrapper] AppLovinMediationAdapter: running destroy...
:23.009 2967-3564/ I/AppLovinSdk: [MediationAdapterWrapper] Marking AppLovinMediationAdapter as disabled due to: destroy
:23.009 2967-3564/ D/AppLovinSdk: [MediationAdapterWrapper] AppLovinMediationAdapter: finished destroy
:23.009 2967-3564/ D/AppLovinSdk: [MediationAdapterWrapper] AppLovinMediationAdapter: finished collect_signal
:23.045 2967-2967/ D/AppLovinSdk: [AdWebView] about:blank: 0: Not allowed to load local resource: file:///data/user/0//files/al/ofc4cdc5_989fd91d778c910eae4cd7c21a4b191a9b82c01f_v21_phone.jpg
:23.045 2967-2967/ D/AppLovinSdk: [AdWebView] about:blank: 0: Not allowed to load local resource: file:///data/user/0//files/al/1381250003_28x28.png
:23.053 2967-2967/ I/AppLovinSdk: [AdWebView] Loaded resource: data:text/html;charset=utf-8;base64,
:23.053 2967-2967/ D/AppLovinSdk: [AdWebView] : 1: Winter Is Coming!
:23.058 2967-2967/ D/AppLovinSdk: [AdWebView] : 1: [object Object]

**Comment by chauduyphanvu** [comment]
@skyzd, thanks for letting us know. Are you able to share additional details like the ad unit ID, screenshots, steps to reproduce the issue, etc.?

Vu Chau
AppLovin Team

**Comment by skyzd** [comment]
@chauduyphanvu ,thank you for help me。
**My project, All ad unit ID is same。**
Interstitial ad loaded，call <onAdLoaded>
then 《if (interstitialAd.isReady()) {
            interstitialAd.showAd();》
Display test ads。
Two kinds of phenomena。
1、Enter the interstitial AD directly black screen
**According to the log, it can be seen that js load failed**
log：
```
AppLovinSdk: [AdWebView] Loaded resource: file:///data/user/0/xxx.xxx.xxx/files/al/zepto-1.1.3.min.js
AppLovinSdk: [AdWebView] Loaded resource: file:///data/user/0/xxx.xxx.xxx/files/al/ofc4cdc5_989fd91d778c910eae4cd7c21a4b191a9b82c01f_v21_phone.jpg
AppLog: WebViewJsUtil injectJsCallback tocom.applovin.impl.adview.d{2636878 VFED..CL. ........ 0,0-1440,2898}
AppLovinSdk: [ConnectionManager] Successful GET returned 200 in 0.521 s over wifi to #-1758602760 "prod-ms.applovin.com/1.0/event/mimp"
AppLovinSdk: [AdWebView] about:blank: 0: Not allowed to load local resource: file:///data/user/0/xxx.xxx.xxx/files/al/zepto-1.1.3.min.js
AppLovinSdk: [AdWebView] about:blank: 1: Not allowed to load local resource: file:///data/user/0/xxx.xxx.xxx/files/al/ofc4cdc5_989fd91d778c910eae4cd7c21a4b191a9b82c01f_v21_phone.jpg
AppLovinSdk: [AdWebView] about:blank: 1: Not allowed to load local resource: file:///data/user/0/xxx.xxx.xxx/files/al/ofc4cdc5_989fd91d778c910eae4cd7c21a4b191a9b82c01f_v21_phone.jpg
AppLovinSdk: [AdWebView] about:blank: 59: Uncaught ReferenceError: $ is not defined
AppLovinSdk: [AdWebView] about:blank: 0: Not allowed to load local resource: file:///data/user/0/xxx.xxx.xxx/files/al/ofc4cdc5_989fd91d778c910eae4cd7c21a4b191a9b82c01f_v21_phone.jpg
AppLovinSdk: [AdWebView] about:blank: 0: Not allowed to load local resource: file:///data/user/0/xxx.xxx.xxx/files/al/1381250003_28x28.png
```

2、Black screen will be displayed after the countdown of the video advertisement
log：
```
:23.009 2967-3564/ D/AppLovinSdk: [MediationAdapterWrapper] AppLovinMediationAdapter: finished destroy
:23.009 2967-3564/ D/AppLovinSdk: [MediationAdapterWrapper] AppLovinMediationAdapter: finished collect_signal
:23.045 2967-2967/ D/AppLovinSdk: [AdWebView] about:blank: 0: Not allowed to load local resource: file:///data/user/0//files/al/ofc4cdc5_989fd91d778c910eae4cd7c21a4b191a9b82c01f_v21_phone.jpg
:23.045 2967-2967/ D/AppLovinSdk: [AdWebView] about:blank: 0: Not allowed to load local resource: file:///data/user/0//files/al/1381250003_28x28.png
:23.053 2967-2967/ I/AppLovinSdk: [AdWebView] Loaded resource: data:text/html;charset=utf-8;base64,
:23.053 2967-2967/ D/AppLovinSdk: [AdWebView] : 1: Winter Is Coming!
:23.058 2967-2967/ D/AppLovinSdk: [AdWebView] : 1: [object Object]
```

**After a few seconds, a close button appears in the upper right corner of the screen**
![13501644286136_ pic](https://user-images.githubusercontent.com/3231503/152904612-7c756c64-4f06-43e1-8977-cebba2b1d5b8.jpg)
![13511644286137_ pic](https://user-images.githubusercontent.com/3231503/152904623-16197894-7a25-415c-8db6-1a9f57f9130f.jpg)

**Comment by chauduyphanvu** [comment]
@skyzd, thanks for the details. However, did you mean to say that you reproduced the issue(s) even with our sample app and ad unit IDs too? If so, I'm not able to replicate it in our test setups.

On the other hand, if you see this black screen issue only a few times, then it might be specific to the ad served at that time (as opposed to telling something is wrong in the SDK or your ad integration). I see `about:blank: 59: Uncaught ReferenceError: $ is not defined` in your logs, which means the ad is probably using jQuery and the jQuery script might not have been imported (still, that reason is specific to your logs only).

**Comment by thomasmso** [comment]
@skyzd - Do you have ByteDance's BytePlus SDK integrated? Could you try removing that to see if it resolves the issue? Furthermore, could you check removing ByteDance adapter/SDK?

**Comment by skyzd** [comment]
@thomasmso thanks，That's exactly what you said。remove bytedance，it is OK.
@thomasmso @chauduyphanvu 
If I have to use ByteDance, how do I solve this problem?

**Comment by chauduyphanvu** [comment]
@skyzd - could you confirm what exactly you removed? Was it BytePlus or ByteDance?

**Comment by skyzd** [comment]
implementation 'com.bytedance.applog:RangersAppLog-All-global:5.5.6'

@chauduyphanvu  It is this gradle setting.

**Comment by skyzd** [comment]
@chauduyphanvu @thomasmso 
How can I solve this problem?

**Comment by thomasmso** [comment]
We will reach out to their team. Will keep you posted.

**Comment by thomasmso** [comment]
@skyzd - Are you still experiencing this issue?
