### ISSUE TITLE
Reward callback calling delay

### ISSUE THREAD

**Issue by valsap** [AppLovin/AppLovin-MAX-SDK-Android#14]
Hello! 
We have ~20 sec. delay between user ended rewarded video and our server get callback. Is it possible avoid this delay?

**Comment by thomasmso** [comment]
Hi @valsap - Are you able to reproduce this consistently? Do you mind sharing logs with us for when you are able to reproduce this? To enable our SDK's logs, see [here](https://monetization-support.applovin.com/hc/en-us/articles/236114328-How-can-I-expose-verbose-logging-for-the-SDK-).
