### ISSUE TITLE
Native bid has no impression

### ISSUE THREAD

**Issue by williamycyh** [AppLovin/AppLovin-MAX-SDK-Android#140]
![image](https://user-images.githubusercontent.com/8869509/152951725-d3ba2b0e-bb2e-4de6-a92a-9536b95b8f9d.png)

I migrated from mopub, and I integrated a native ad on one of my apps with template.
But after going online, my native bid does not have any impression, only AppLovin Exchange has impression.
The three-party bid (mintergal) also had no impression.  Interstitial ads are fine.
The sdk is the latest (11.1.0).

**Comment by taugin** [comment]
please reference the issus #100 ,this problem has not beed solved yet now, you can modify the mintegral adapter for temporary solution。

**Comment by taugin** [comment]
> > please reference the issus #100 ,this problem has not beed solved yet now, you can modify the mintegral adapter for temporary solution。
> 
> Can the Facebook native bid be displayed normally? Another app of mine is integrating to Facebook's native

I didn't use fb to monetize
