### ISSUE TITLE
Is it possible to change the update interval of MREC?

### ISSUE THREAD

**Issue by 1008k** [AppLovin/AppLovin-MAX-SDK-Android#146]
Hi there.
I noticed that in the MAX ad unit settings screen, when the ad size is MREC, I cannot find the Refresh Interval setting item.
When I checked the actual operation of the application, MREC ads are refreshed in the same way as banners.
MREC is often operated in a similar way to BANNER, and I think it would be more appropriate if publishers could control the refresh interval.

Thank you for your consideration.

**Comment by thomasmso** [comment]
Hi there. We're actively working on updating our UI to support this functionality. I will notify this thread once the feature is live. Thank you.

**Comment by thomasmso** [comment]
@1008k - The functionality is live in our UI now.

![image](https://user-images.githubusercontent.com/5104410/154908793-8b591b3e-b6cb-49ac-a7cd-a48d75bcecd9.png)
