### ISSUE TITLE
MaxNativeAdView doesn't respect current Theme in new version 11.1.2

### ISSUE THREAD

**Issue by apshard** [AppLovin/AppLovin-MAX-SDK-Android#155]
In the new version 11.1.2 MaxNativeAdView doesn't respect the current App/Activity theme it always inflates the ad template based on the default theme. Our app has a light theme but all elements (texts, button) inside MaxNativeAdView are in a dark theme now.

**Comment by apshard** [comment]
Found a workaround for this issue.

This way it works correctly
```
new MaxNativeAdView(
                            new MaxNativeAdViewBinder.Builder(LayoutInflater.from(ActivityRoot.this).inflate(R.layout.native_ad, null))
                                    .setTitleTextViewId(R.id.native_ad_headline)
                                    .setBodyTextViewId(R.id.native_ad_body)
                                    .setAdvertiserTextViewId(R.id.native_ad_advertiser)
                                    .setMediaContentViewGroupId(R.id.native_ad_media)
                                    .setOptionsContentViewGroupId(R.id.native_ad_options)
                                    .setCallToActionButtonId(R.id.native_ad_cta)
                                    .build(),
ActivityRoot.this);
```
instead of following (this code used to be working fine prior to 11.1.1)
```
new MaxNativeAdView(
                            new MaxNativeAdViewBinder.Builder(R.layout.native_ad)
                                    .setTitleTextViewId(R.id.native_ad_headline)
                                    .setBodyTextViewId(R.id.native_ad_body)
                                    .setAdvertiserTextViewId(R.id.native_ad_advertiser)
                                    .setMediaContentViewGroupId(R.id.native_ad_media)
                                    .setOptionsContentViewGroupId(R.id.native_ad_options)
                                    .setCallToActionButtonId(R.id.native_ad_cta)
                                    .build(),
ActivityRoot.this);
```

**Comment by santoshbagadi** [comment]
Hi @apshard , thank you for bringing this to our attention and the workaround. I think we know what the cause of the issue is and we'll have a fix for it in the next release.

**Comment by hoanghiephui** [comment]
> Found a workaround for this issue.
> 
> This way it works correctly
> 
> ```
> new MaxNativeAdView(
>                             new MaxNativeAdViewBinder.Builder(LayoutInflater.from(ActivityRoot.this).inflate(R.layout.native_ad, null))
>                                     .setTitleTextViewId(R.id.native_ad_headline)
>                                     .setBodyTextViewId(R.id.native_ad_body)
>                                     .setAdvertiserTextViewId(R.id.native_ad_advertiser)
>                                     .setMediaContentViewGroupId(R.id.native_ad_media)
>                                     .setOptionsContentViewGroupId(R.id.native_ad_options)
>                                     .setCallToActionButtonId(R.id.native_ad_cta)
>                                     .build(),
> ActivityRoot.this);
> ```
> 
> instead of following (this code used to be working fine prior to 11.1.1)
> 
> ```
> new MaxNativeAdView(
>                             new MaxNativeAdViewBinder.Builder(R.layout.native_ad)
>                                     .setTitleTextViewId(R.id.native_ad_headline)
>                                     .setBodyTextViewId(R.id.native_ad_body)
>                                     .setAdvertiserTextViewId(R.id.native_ad_advertiser)
>                                     .setMediaContentViewGroupId(R.id.native_ad_media)
>                                     .setOptionsContentViewGroupId(R.id.native_ad_options)
>                                     .setCallToActionButtonId(R.id.native_ad_cta)
>                                     .build(),
> ActivityRoot.this);
> ```

Same issues.

**Comment by dirkam** [comment]
> Hi @apshard , thank you for bringing this to our attention and the workaround. I think we know what the cause of the issue is and we'll have a fix for it in the next release.

Can you please tell us when can we expect this? Thank you.

**Comment by santoshbagadi** [comment]
Hi @dirkam , we originally made the change to use `applicationContext` to fix potential memory leaks when the ad view is being saved to be shown outside Activity context. So, we are still discussing internally on the change.

Do you think you can use the workaround mentioned above, where you can pass the inflated view to us like below: 
```
new MaxNativeAdView(
                            new MaxNativeAdViewBinder.Builder(LayoutInflater.from(ActivityRoot.this).inflate(R.layout.native_ad, null))
                                    .setTitleTextViewId(R.id.native_ad_headline)
                                    .setBodyTextViewId(R.id.native_ad_body)
                                    .setAdvertiserTextViewId(R.id.native_ad_advertiser)
                                    .setMediaContentViewGroupId(R.id.native_ad_media)
                                    .setOptionsContentViewGroupId(R.id.native_ad_options)
                                    .setCallToActionButtonId(R.id.native_ad_cta)
                                    .build(),
ActivityRoot.this);
```

**Comment by santoshbagadi** [comment]
We would be doing the same things as `LayoutInflater.from(context).inflate(R.layout.native_ad, null)` in our internal implementation as well. So, I'm actually curious why that might not be working for you.

We don't have any specific timeline for our next release, but we'll update to use the context provided to inflate the layout.

**Comment by dirkam** [comment]
I'm sorry, I must have made a mistake. Tried it again and it works. For me, it's fine with this workaround.

**Comment by dirkam** [comment]
@santoshbagadi 
Actually, this still poses some limitations. The best would be to separate the Ad fetching from the View creation. Would that be possible? Perhaps with the current version even that I'm not aware of?
That way we could just inflate the view whenever we need it and fetch the Ad separately. This is how MoPub worked, and most of the networks also (FAN, for instance, before going bidding only).

**Comment by santoshbagadi** [comment]
Hi @dirkam , we currently don't have support for loading and rendering the ads separately but we are working on adding support for it now.

**Comment by silane-tech** [comment]
> Hi @dirkam , we originally made the change to use `applicationContext` to fix potential memory leaks when the ad view is being saved to be shown outside Activity context. So, we are still discussing internally on the change.
> 
> Do you think you can use the workaround mentioned above, where you can pass the inflated view to us like below:
> 
> ```
> new MaxNativeAdView(
>                             new MaxNativeAdViewBinder.Builder(LayoutInflater.from(ActivityRoot.this).inflate(R.layout.native_ad, null))
>                                     .setTitleTextViewId(R.id.native_ad_headline)
>                                     .setBodyTextViewId(R.id.native_ad_body)
>                                     .setAdvertiserTextViewId(R.id.native_ad_advertiser)
>                                     .setMediaContentViewGroupId(R.id.native_ad_media)
>                                     .setOptionsContentViewGroupId(R.id.native_ad_options)
>                                     .setCallToActionButtonId(R.id.native_ad_cta)
>                                     .build(),
> ActivityRoot.this);
> ```

This workaround does not work properly. Native ad media framelayout takes whole screen even after defining custom size.

**Comment by santoshbagadi** [comment]
Hi @silane-tech , could you please share the `.xml` layout file used to inflate the native ad view?

**Comment by silane-tech** [comment]
[mx_native4.zip](https://github.com/AppLovin/AppLovin-MAX-SDK-Android/files/8130326/mx_native4.zip)
@santoshbagadi

**Comment by tiandrew** [comment]
Hi @silane-tech, if you pass `null` as the root viewGroup, then the layout you declared will inflate to the parent views' size regardless of what you have set in the XML.

I recommend passing in the container view you'll add the native ad view to, as well as `false` for `attachToRoot` in order to properly size your native ad. So instead of:
```
new MaxNativeAdViewBinder.Builder(LayoutInflater.from(ActivityRoot.this).inflate(R.layout.native_ad, null))`
```
please try this:
```
new MaxNativeAdViewBinder.Builder(LayoutInflater.from(ActivityRoot.this).inflate(R.layout.native_ad, nativeAdContainerView, false))`
```

Optionally you can also ensure your parent view that you'll add the native ad to is properly sized and no larger than the ad itself.

**Comment by santoshbagadi** [comment]
Our Android SDK [v11.3.0](https://github.com/AppLovin/AppLovin-MAX-SDK-Android/releases/tag/release_11_3_0) should fix this issue without the workaround.
