### ISSUE TITLE
How to test Consent GDPR?

### ISSUE THREAD

**Issue by hoanghiephui** [AppLovin/AppLovin-MAX-SDK-Android#156]
Hi @thomasmso 
How can GDPR display be tested? When I'm not a european user.

**Comment by thomasmso** [comment]
Hi @hoanghiephui - Please check out the docs [here](https://dash.applovin.com/documentation/mediation/android/getting-started/privacy#built-in-consent-flow) for displaying the flow. You can use our API to check the user consent status via `AppLovinSdkSettings`. Thanks!
