### ISSUE TITLE
Testing Ad showing with live ad unit id

### ISSUE THREAD

**Issue by radhasharma123** [AppLovin/AppLovin-MAX-SDK-Android#157]
Hi ,
I am using Applovin max sdk.
But with live ads i am not able to show live ads still showing test ad.
Please help to provide any answer why this is going on.

**Comment by joeapplovin** [comment]
Hi @radhasharma123 - can you please check if your device ID is still listed as a [test device](https://monetization-support.applovin.com/hc/en-us/articles/115000509267-How-can-I-get-test-ads-)?

**Comment by radhasharma123** [comment]
Yes i have checked the same but in all device we are getting test ads.No device is configure or active for testing but still status is test mode true, why?
