### ISSUE TITLE
Gradle Task :app:safedkInstrumentation: MergedFlavor.getApplicationId()' is obsolete

### ISSUE THREAD

**Issue by soenkegissel** [AppLovin/AppLovin-MAX-SDK-Android#159]
When building a project with com.applovin.quality:AppLovinQualityServiceGradlePlugin:4.0.2 I get the following error:
> Task :app:safedkInstrumentationMyApp
AGPBI: {"kind":"warning","text":"API 'MergedFlavor.getApplicationId()' is obsolete and has been replaced with 'Variant.getApplicationId()'.\nIt will be removed in version 7.0 of the Android Gradle plugin.\nGradle Properties must be used to change Variant information.\nFor more information, see https://d.android.com/r/tools/use-properties.\nTo determine what is calling MergedFlavor.getApplicationId(), use -Pandroid.debug.obsoleteApi=true on the command line to display more information.","sources":[{}]}

**Comment by pegtop** [comment]
Hi! I stop at this step too, and i cannot compile successfully with Ubuntu, but my colleague can compile successfully with Windows. it's so strange, pelase help!

**Comment by chauduyphanvu** [comment]
@pegtop, which version are you using? And could you share any log? Thanks.

**Comment by pegtop** [comment]
> @pegtop, which version are you using? And could you share any log? Thanks.
gradle-6.5
com.android.tools.build:gradle:4.1.3
AppLovinQualityServiceGradlePlugin-3.9.11

![2022-02-21 17-02-57屏幕截图](https://user-images.githubusercontent.com/10073015/154937301-38ac6431-a076-44e0-9538-9681df92fba5.png)

I will be bolcked at this step everytime when i build my project(i have also tried AppLovinQualityServiceGradlePlugin-4.3.2, but failed too). No further log is printed(sometimes i will get a OOM error)

**Comment by orilentz** [comment]
@pegtop Since you're using Gradle 6.5 and this is a warning for Gradle 7, I assume there's some lint rule that fails the compilation on warnings? Anyway, we have a fix for it coming up in our next hotfix version, scheduled for last week. Will keep you posted on when it's out.

**Comment by chauduyphanvu** [comment]
Internal ticket for reference: https://app.asana.com/0/337926977135969/1201872910553552/f.

**Comment by orilentz** [comment]
Warning should be resolved with latest version - **4.3.7**

**Comment by soenkegissel** [comment]
I can confirm. Warning is gone.
