### ISSUE TITLE
Lazy inflation of MaxNativeAdView

### ISSUE THREAD

**Issue by appetizermonster** [AppLovin/AppLovin-MAX-SDK-Android#161]
Is there a way to inflate MaxNativeAdView lazily?
Something like loading native ads with the application context and inflating ad view with an activity context for preloading native ads before opening the activity, for better impression chances.

It's possible with AdMob SDK and MoPub SDK. but AppLovin SDK requires MaxNativeAdView as a parameter for loading ads even before showing it.

It will be awesome if the SDK supports lazy inflation.
Thanks!

**Comment by chauduyphanvu** [comment]
@appetizermonster, we support `Context` in the `MaxNativeAdView` constructor now (v[11.1.0](https://github.com/AppLovin/AppLovin-MAX-SDK-Android/releases/tag/release_11_1_0)). Have you tried with that? 

Let us know if you need something else.

Vu Chau
AppLovin Team

**Comment by appetizermonster** [comment]
Thanks for the quick reply.

I know that I can use the application context in MaxNativeAdView for preloading native ads. It's good but it's not sufficiently good in my opinion.

When I look at the SDK code, It looks like the SDK needs a MaxNativeAdView for loading ads and it fills the view properties right after the ad has been loaded. I believe it's not good in terms of memory usage and reusability of views as well.
(I guess that MediaView inflation needs a WebView instance internally in many cases, so extra memory would be wasted even before showing it for preloading native ads.)

and AdMob, MoPub SDKs can reuse one view for multiple native ads, for something like RecyclerView use-cases or preloading multiple native ads.

So removing a requirement for MaxNativeAdView as a parameter for loading native ads will be very appreciated.

Code example:
```kotlin
val nativeAdLoader = MaxNativeAdLoader("adunitid", context)
nativeAdLoader.loadAd()
```
```kotlin
val ad: MaxAd // comes from nativeAdLoader
val adView = MaxNativeAdView(viewBinder, context)
adView.render(ad)
```
(Actually, there is a similar code in the SDK already but the behavior is not documented and looks like something different than I expect.)

Thanks!

**Comment by chauduyphanvu** [comment]
@appetizermonster, thanks for the feedback. I've relayed it to the rest of the team and we'll see what we can do here. Stay tuned!

**Comment by dirkam** [comment]
+1
This is very much needed.

**Comment by xiaopei** [comment]
+1
This is very much needed.

**Comment by santoshbagadi** [comment]
@appetizermonster , @dirkam , @xiaopei  we have just released version [11.2.0](https://github.com/AppLovin/AppLovin-MAX-SDK-Android/releases/tag/release_11_2_0) of our SDK that allows for loading and rendering the native ad separately. We'll update the docs soon, but here is how it can be achieved: 

Android: 
Load the native ad by calling `MaxNativeAdLoader.loadAd()`. Then use the `MaxAd` provided in `onNativeAdLoaded` to render the ad view by calling `MaxNativeAdLoader.renderAd( MaxNativeAdView, MaxAd )`.

iOS
Load the native ad by calling `-[MANativeAdLoader loadAd]`. Then use the `MAAd` provided in `didLoadNativeAd:forAd:` to render the ad view by calling `-[MANativeAdLoader renderNativeAdView:withAd:]`.

**Comment by maxakash** [comment]
> 

Hey @santoshbagadi , there is no method ```MaxNativeAdLoader.renderAd()``` in v 11.2.1 but ```MaxNativeAdLoader.render()``` is there.
Also for my use case, I am pre loading native ad by calling ```MaxNativeAdLoader.loadAd()``` in an object with application context. And I want to show the native ad in an activity. 
According to your comment, I have got the ```MaxAd``` from  ```onNativeAdLoaded``` but where do I get the ```MaxNativeAdView``` . Also to use ```MaxNativeAdLoader.renderAd( MaxNativeAdView, MaxAd )```, I have to reinitialize it.
Please provide clear documentation.

Thanks

**Comment by pratik-pattanaik** [comment]
+1

It seems that we're expected to create the `MaxNativeAdView` before the ad is loaded, but I'm getting odd results when rendering that ad inside an `AlertDialog`. The ad doesn't bind correctly (images aren't displayed and theme isn't applied). Besides, the `onNativeAdLoaded` callback has its own instance of `MaxNativeAdView` which seems to be redundant and wasteful.

**Comment by santoshbagadi** [comment]
@maxakash , my bad on the incorrect API posted earlier. `MaxNativeAdLoader.render()` is the right API. 
> Also to use MaxNativeAdLoader.renderAd( MaxNativeAdView, MaxAd ), I have to reinitialize it.
Please provide clear documentation.

You can save the instance of `MaxNativeAdLoader` used to load the ad, or you can create a new one as needed to render that native ad view. 
> where do I get the `MaxNativeAdView`

Just to clarify, are you using native template or native manual ads? Right now, Lazy inflation of `MaxNativeAdView` is only supported for [`Manual` native ads](https://dash.applovin.com/documentation/mediation/android/getting-started/native-manual#bind-ui-components). 

We have updated our docs showing how you can [Load and Render Ads separately](https://dash.applovin.com/documentation/mediation/android/getting-started/native-manual#load-the-native-ad) and we are actively working on updating our demo apps as well.


@pratik-pattanaik , the `MaxNativeAdView` returned in `onNativeAdLoaded` will be `null` when using our lazy inflation API. 

> The ad doesn't bind correctly (images aren't displayed and theme isn't applied).

I think the issue might be related to us using application context to inflate the view. Could you please try the workaround mentioned [here](https://github.com/AppLovin/AppLovin-MAX-SDK-Android/issues/155#issuecomment-1045134243) and see if that fixes the issue.

**Comment by maxakash** [comment]
> @maxakash , my bad on the incorrect API posted earlier. `MaxNativeAdLoader.render()` is the right API.
> 
> > Also to use MaxNativeAdLoader.renderAd( MaxNativeAdView, MaxAd ), I have to reinitialize it.
> > Please provide clear documentation.
> 
> You can save the instance of `MaxNativeAdLoader` used to load the ad, or you can create a new one as needed to render that native ad view.
> 
> > where do I get the `MaxNativeAdView`
> 
> Just to clarify, are you using native template or native manual ads? Right now, Lazy inflation of `MaxNativeAdView` is only supported for [`Manual` native ads](https://dash.applovin.com/documentation/mediation/android/getting-started/native-manual#bind-ui-components).
> 
> We have updated our docs showing how you can [Load and Render Ads separately](https://dash.applovin.com/documentation/mediation/android/getting-started/native-manual#load-the-native-ad) and we are actively working on updating our demo apps as well.
> 
> @pratik-pattanaik , the `MaxNativeAdView` returned in `onNativeAdLoaded` will be `null` when using our lazy inflation API.
> 
> > It seems that we're expected to create the MaxNativeAdView before the ad is loaded
> 
> Please take a look at our [Load and Render Ads separately](https://dash.applovin.com/documentation/mediation/android/getting-started/native-manual#load-the-native-ad) section of our doc to see how you can create and render the `MaxNativeAdView` after the ad has been loaded.
> 
> > The ad doesn't bind correctly (images aren't displayed and theme isn't applied).
> 
> I think the issue might be related to us using application context to inflate the view. Could you please try the workaround mentioned [here](https://github.com/AppLovin/AppLovin-MAX-SDK-Android/issues/155#issuecomment-1045134243) and see if that fixes the issue. Instead of providing us the layout resource ID, you can provide us with the inflated view using
> 
> ```
> new MaxNativeAdViewBinder.Builder(LayoutInflater.from(ActivityRoot.this).inflate(R.layout.native_ad, nativeAdContainerView, false))
> ```

Yes, I am using manual native ad.
From where do I get MaxNativeAdView if I am loading and rendering native ad seperately?

**Comment by santoshbagadi** [comment]
You need to create the `MaxNativeAdView` as described in this section of our docs: https://dash.applovin.com/documentation/mediation/android/getting-started/native-manual#bind-ui-components. 

```
    private MaxNativeAdView createNativeAdView()
    {
        MaxNativeAdViewBinder binder = new MaxNativeAdViewBinder.Builder( R.layout.native_custom_ad_view )
                .setTitleTextViewId( R.id.title_text_view )
                .setBodyTextViewId( R.id.body_text_view )
                .setAdvertiserTextViewId( R.id.advertiser_textView )
                .setIconImageViewId( R.id.icon_image_view )
                .setMediaContentViewGroupId( R.id.media_view_container )
                .setOptionsContentViewGroupId( R.id.options_view )
                .setCallToActionButtonId( R.id.cta_button )
                .build();

        return new MaxNativeAdView( binder, this );
    }
```

**Comment by maxakash** [comment]
> You need to create the `MaxNativeAdView` as described in this section of our docs: https://dash.applovin.com/documentation/mediation/android/getting-started/native-manual#bind-ui-components.
> 
> ```
>     private MaxNativeAdView createNativeAdView()
>     {
>         MaxNativeAdViewBinder binder = new MaxNativeAdViewBinder.Builder( R.layout.native_custom_ad_view )
>                 .setTitleTextViewId( R.id.title_text_view )
>                 .setBodyTextViewId( R.id.body_text_view )
>                 .setAdvertiserTextViewId( R.id.advertiser_textView )
>                 .setIconImageViewId( R.id.icon_image_view )
>                 .setMediaContentViewGroupId( R.id.media_view_container )
>                 .setOptionsContentViewGroupId( R.id.options_view )
>                 .setCallToActionButtonId( R.id.cta_button )
>                 .build();
> 
>         return new MaxNativeAdView( binder, this );
>     }
> ```

Thanks for your help @santoshbagadi .
But MaxNativeAdLoader.renderAd( MaxNativeAdView, MaxAd ) returns a boolean. How am I supposed to ad the rendered native ad to a view?

**Comment by santoshbagadi** [comment]
The `MaxNativeAdView` passed into the `MaxNativeAdLoader.render( MaxNativeAdView, MaxAd )` gets rendered and you can add that view to your view hierarchy. The method returns a `boolean` that indicated whether or not the render was successful.

**Comment by pratik-pattanaik** [comment]
> Please take a look at our [Load and Render Ads separately](https://dash.applovin.com/documentation/mediation/android/getting-started/native-manual#load-the-native-ad) section of our doc to see how you can create and render the `MaxNativeAdView` after the ad has been loaded.

Hi ! I was indeed following the instructions in that page and am able to render manual native ads, but the ad icon and media content don't get displayed. I checked the `MaxAd` object that's returned in the `onNativeAdLoaded` callback and there is media content, but no icon in it. The image somehow doesn't get displayed, despite the view id being specified in the binder. It looks as below. 
![applovin test ad cropped](https://user-images.githubusercontent.com/8583043/157292714-e964d1a2-17a5-4f8d-b761-bf7e65b031e7.png)

**Comment by santoshbagadi** [comment]
@pratik-pattanaik , we are currently having issues with test mode for native manual ads and are actively working on getting them fixed. Could you please try disabling test mode to see if you still see the issue?

**Comment by pratik-pattanaik** [comment]
Paused test mode but still getting test ads. Is it going to take a while for the settings to be updated ?

**Comment by pratik-pattanaik** [comment]
Managed to solve the issues. Testing with live ads worked. Thanks !

**Comment by xiaopei** [comment]
> 

I saw this when my debug model is disabled
