### ISSUE TITLE
App removed from Google Play Store due to AppLovin's Ads

### ISSUE THREAD

**Issue by mrudultora** [AppLovin/AppLovin-MAX-SDK-Android#165]
I am using AppLovin MAX with Facebook Audience Network Bidding from past few months. But recently one of my app was removed from Google Play Store, stating the reason as **Ads that interfere with normal app use that are not closeable after 5 seconds.**
This was due to the ads showed by MAX. The close button does not appears even after 5 seconds. Here's a screenshot of the reason of removal:
![image](https://user-images.githubusercontent.com/65870389/154011259-cb7bbede-8342-439f-8608-3eb1f0863eb3.png)

**Comment by chauduyphanvu** [comment]
@mrudultora, could you email partner_support@applovin.com about that? Someone will help you there. Thanks.

Vu Chau
ApPLovin Team
