### ISSUE TITLE
Custom Adapter cannot get App ID

### ISSUE THREAD

**Issue by abslzhx** [AppLovin/AppLovin-MAX-SDK-Android#167]
AppLovin SDK version: 11.1.2

I implemented a custom adapter and made a custom network configuration in the max dashboard, but I can't get the configuration of the APP ID on the client, is there something wrong with the way I'm getting it?

This is how I get the app id:
```java
@Override
public void initialize(MaxAdapterInitializationParameters parameters, Activity activity, OnCompletionListener onCompletionListener) {
    String appId = parameters.getServerParameters().getString("app_id"); // always return null
}
```

Print out the MaxAdapterInitializationParameters content:

```
I/MobiGrowingAdapter: serverParameters=Bundle[{amount=0, is_muted=false, currency=}]
```

This is the custom network configuration in ad units:
<img width="1025" alt="image" src="https://user-images.githubusercontent.com/16358424/154059951-cbf83e75-caad-4b98-91c3-96e3c9ee83aa.png">

**Comment by joeapplovin** [comment]
Hi @abslzhx - how long was the interval between you creating the custom network configuration in the UI and running your adapter?  It's possible you tested before the `app_id` data has propagated.

**Comment by abslzhx** [comment]
@joeapplovin I tested several times within a few hours of configuration, and I tried several times now and still can't get the `app_id`, but I can get the `Placement ID` from `MaxAdapterResponseParameters`

**Comment by joeapplovin** [comment]
Can you please let me know your ad unit ID so I can check the setup?
Thanks!

**Comment by abslzhx** [comment]
@joeapplovin 992e56ecbece07a4

**Comment by Ultima2876** [comment]
I also see the same issue on iOS. It seems that you can get the app_id from parameters when loading an ad, but at the init stage the parameters are not populated yet.

**Comment by joeapplovin** [comment]
Thanks @abslzhx - confirming that `app_id` is currently only returned for the `MaxAdapterResponseParameters` but not in the `MaxAdapterInitializationParameters`.  We'll fix this soon.

**Comment by joeapplovin** [comment]
Hi all - this is fixed.
