### ISSUE TITLE
Native ads play wrong video with a high chance

### ISSUE THREAD

**Issue by appetizermonster** [AppLovin/AppLovin-MAX-SDK-Android#169]
AppLovin SDK version: 11.1.2
Android OS: 11

As I tried to integrate Native Ads, I found that the `MaxNativeAdView` plays the wrong video with a high chance.
I guess that the issue might be caused by the same video filename for different live ads. (I see many different ads have the same video filename; `toutiao.mp4`)

### Example
The video is for **Banksalad** (https://www.banksalad.com/)
but the ad is for **ifland** (https://ifland.io/)
![native_ad_wrong_video](https://user-images.githubusercontent.com/6244462/154204407-741121ce-5353-486d-a641-0571dbe8dbd9.jpg)

I am increasingly doubting whether this SDK can really be used in production. 
Or I don't know if this is only happening to me. 😭

Anyway, I really thank you for the quick support.

**Comment by thomasmso** [comment]
We're aware of this, and the DSP responsible for the ad you're seeing is working on fixing their video URLs.

**Comment by thomasmso** [comment]
We will update you when their fix is live (no SDK update will be required).

**Comment by thomasmso** [comment]
This has been fixed for a while. Closing out issue.
