### ISSUE TITLE
E/AppLovinAdapter: Failed to load interstitial ad from AppLovin: 109: AppLovin requires an Activity context to load ads.

### ISSUE THREAD

**Issue by IrohaHanasaku** [AppLovin/AppLovin-MAX-SDK-Android#17]
im use Mediation

How to initialize interstitial with mediation admob ?

**Comment by thomasmso** [comment]
Hi, can you ensure that you are passing in an Activity context when you are initializing AdMob and creating the AdMob interstitial ad? Like

```
MobileAds.initialize( activity, ... );
```

and

```
InterstitialAd admobInter = new InterstitialAd( activity )
```

**Comment by IrohaHanasaku** [comment]
I use the API Backedn for my ad unit

**Comment by thomasmso** [comment]
Could you explain the issue in more detail? The SDKs have to live on the client side (on a device), not from backend (which might be the reason why you do not have an Activity context).

**Comment by IrohaHanasaku** [comment]
fixed , before im using activity.getAplicationContext()

i change it to (Activity)

**Comment by IrohaHanasaku** [comment]
Also i have 1 more question, 

for Banner not Support for adsize SMART_BANNER ?

**Comment by thomasmso** [comment]
Awesome. We should have support for SMART_BANNERs as our SDK is able to adjust the size to the provided viewport.

**Comment by IrohaHanasaku** [comment]
when I tried SMART_BANNER, it didn't appear,


banners only appear with adsize BANNER only

**Comment by thomasmso** [comment]
Can you show me what version of the AppLovin adapters you are using?

It looks like a sizable [change](https://github.com/googleads/googleads-mobile-android-mediation/commit/4e5e0b0a7a5fe999ad2c3e20962ee9900486cde5) was made to our adapters recently, we'll likely have to investigate the issue.

**Comment by IrohaHanasaku** [comment]
i use version    

implementation 'com.google.ads.mediation:applovin:9.12.8.0'

**Comment by re-LIFE** [comment]
When this issue wiil be solved 

ETA ?

**Comment by thomasmso** [comment]
@re-LIFE which is the issue you’re experiencing?

**Comment by fableyjg** [comment]
This means that you need use an activity type of parameter

**Comment by wwwgaoxi** [comment]
> Could you explain the issue in more detail? The SDKs have to live on the client side (on a device), not from backend (which might be the reason why you do not have an Activity context).

How to replace Activity context with Application context? 
I need this way new InterstitialAd( application.context)

**Comment by thomasmso** [comment]
@wwwgaoxi - Do you still need help with anything?
