### ISSUE TITLE
The Virus & threat protection found Trojan from Applovin sdk

### ISSUE THREAD

**Issue by congdanh1608** [AppLovin/AppLovin-MAX-SDK-Android#171]
![image](https://user-images.githubusercontent.com/14673327/154315412-0f43a0b0-c0f1-4897-a739-24dd2b5f68ea.png)
Hi, I am using Windows 11. 
The Virus & threat protection found Trojan from Applovin SDK.
When I build the APK, It also blocks my APK because of Trojan.
When I download APK from my android phone, Google Chrome also warning to me that it may harmful.

Please help me check because the clients/users are worrying about that and they think wrong about us.

Thank you.

**Comment by thomasmso** [comment]
Hi - you can ignore this. The file it is detecting is from our OMID SDK, which is an advertising industry standard for measuring ad viewability.

**Comment by thomasmso** [comment]
https://iabtechlab.com/standards/open-measurement-sdk/

**Comment by clevsh** [comment]
I am also worrying about it.
Even if it is because of OMID SDK, which is an advertising industry standard for measuring ad viewablility, normal users don't know about it.
Do you have any other workarounds?

**Comment by thomasmso** [comment]
Sorry, I might need more context. Chrome / Gmail will always consider APKs harmful. If users download your app from the Play Store it should be fine.

**Comment by congdanh1608** [comment]
> Sorry, I might need more context. Chrome / Gmail will always consider APKs harmful. If users download your app from the Play Store it should be fine.

Hi @thomasmso 
The windows defender and many other android antivirus apps also detect that is malware/trojan. 
For ex the above image, the windows defender detects that is a trojan.
There are 20% already remove my app. That is urger issue for us.
Do you have any way to remove that in the build?

**Comment by thomasmso** [comment]
Let me check with the OMID team.

**Comment by thomasmso** [comment]
@congdanh1608 / @clevsh - Could you try again with our latest SDK v11.1.3? It bundles against a new version of the OMID SDK.

**Comment by congdanh1608** [comment]
Thanks for your information. I will check it.
