### ISSUE TITLE
No Native ad impressions for Pangle

### ISSUE THREAD

**Issue by maxakash** [AppLovin/AppLovin-MAX-SDK-Android#173]
I have integrated Pangle as ad network. I am using it for native and interstitial ads. 
I am getting impressions for interstitial ad but not for native ads.
Please look into this.

<img width="1364" alt="Screenshot 2022-02-17 at 9 52 26 AM" src="https://user-images.githubusercontent.com/17406944/154404819-4c156e8f-6cc5-4e5c-8a8f-301ac0843933.png">

**Comment by thomasmso** [comment]
This should be fixed now, no SDK/adapter update needed.

**Comment by binodav** [comment]
@maxakash May I know how you display report for each bidding networks as captured in your screenshot ?
