### ISSUE TITLE
Failed to get adaptive banner size

### ISSUE THREAD

**Issue by xiaopei** [AppLovin/AppLovin-MAX-SDK-Android#181]
/AppLovinSdk: [MediationUtils] Failed to get adaptive banner size. Will fallback to using format specific ad view ad size.
    java.lang.NoSuchMethodException: com.google.android.gms.ads.AdSize.getCurrentOrientationAnchoredAdaptiveBannerAdSize [class android.content.Context, int]
        at java.lang.Class.getMethod(Class.java:2072)
        at java.lang.Class.getMethod(Class.java:1693)
        at com.applovin.impl.mediation.c.c.a(Unknown Source:66)
        at com.applovin.mediation.MaxAdFormat.getAdaptiveSize(Unknown Source:14)
        at com.applovin.mediation.MaxAdFormat.getAdaptiveSize(Unknown Source:1)
        
crash when using adaptive banner,my code is
       

>         maxAdFormat = MaxAdFormat.BANNER;
>         adView = new MaxAdView(mUnitId,maxAdFormat, activity);
>         // Stretch to the width of the screen for banners to be fully functional
>         int width = ViewGroup.LayoutParams.MATCH_PARENT;
>         // Get the adaptive banner height.
>         int heightDp = maxAdFormat.getAdaptiveSize((Activity) context).getHeight();
>         int heightPx = AppLovinSdkUtils.dpToPx(context, heightDp);
>         adView.setLayoutParams(new FrameLayout.LayoutParams(width,heightPx));
>         adView.setExtraParameter( "adaptive_banner", "true" );
>         adView.loadAd();

**Comment by chauduyphanvu** [comment]
@xiaopei, if you are using adaptive banner, you will need to also integrate AdMob (as it is a Google ad format and the `AdSize.getCurrentOrientationAnchoredAdaptiveBannerAdSize()` is from the AdMob SDK). What the stack trace is saying is that it cannot find that method, which leads me to believe the AdMob SDK is not integrated in your project.

Please check out the instructions on https://dash.applovin.com/documentation/mediation/android/mediation-adapters to integrate AdMob. Let us know if you have any questions.

Vu Chau
AppLovin Team

**Comment by xiaopei** [comment]
The AdMob SDK is not integrated in my project,  and  we will not use the admob network。Is this necessary for us to use admob network？

**Comment by chauduyphanvu** [comment]
It's because of this line in your code:

```
adView.setExtraParameter( "adaptive_banner", "true" );
```

It is saying you want to use [Google adaptive banner](https://dash.applovin.com/documentation/mediation/android/getting-started/banners#adaptive-banners) and instructs us to call `AdSize.getCurrentOrientationAnchoredAdaptiveBannerAdSize()` to calculate an appropriate size. Because you don't have AdMob integrated you are seeing that exception.

If you don't intend to use adaptive banner, then you should remove the above line of code.

**Comment by thomasmso** [comment]
We'll also remove the log message in the next SDK release.
