### ISSUE TITLE
Wrong API specification of onAdDisplayed() in MaxAdListener 

### ISSUE THREAD

**Issue by silvermanseoul** [AppLovin/AppLovin-MAX-SDK-Android#183]
Both `onAdDisplayed()` and `onAdHidden()` are described as _'The SDK invokes this callback when it finishes displaying the ad.'_.
I think the description of `onAdDisplayed()` should be fixed like _'The SDK invokes this callback when it successfully displays the loaded ad'_.

**Comment by thomasmso** [comment]
Thanks for calling this out @silvermanseoul - will be fixed in an SDK release this weekend. Thanks!

**Comment by thomasmso** [comment]
@silvermanseoul - We just pushed out Android SDK v11.1.3 which fixes this. Thanks for reporting it!
