### ISSUE TITLE
Showing ads in Reyclerview list slow down the whole app

### ISSUE THREAD

**Issue by ihassanali259** [AppLovin/AppLovin-MAX-SDK-Android#188]
I was trying to implement the ads in the list but it makes the app so slow even with one ad in the list. It will be better to support caching the native ads for recyclerview or supporting pre-loading the ad and then inflating them when the view is visible in recyclerview.

**Comment by santoshbagadi** [comment]
Hi @ihassanali259 , we are working on providing an API to load and render native ads separately. We'll update here once we released an SDK with the new APIs.

**Comment by santoshbagadi** [comment]
@ihassanali259  we have just released version [11.2.0](https://github.com/AppLovin/AppLovin-MAX-SDK-Android/releases/tag/release_11_2_0) of our SDK that allows for loading and rendering the native ad separately. We'll update the docs soon, but here is how it can be achieved:

Android:
Load the native ad by calling MaxNativeAdLoader.loadAd(). Then use the MaxAd provided in onNativeAdLoaded to render the ad view by calling MaxNativeAdLoader.renderAd( MaxNativeAdView, MaxAd ).

iOS
Load the native ad by calling -[MANativeAdLoader loadAd]. Then use the MAAd provided in didLoadNativeAd:forAd: to render the ad view by calling -[MANativeAdLoader renderNativeAdView:withAd:].

**Comment by ihassanali259** [comment]
Thanks for the update.

**Comment by ritamsarmah** [comment]
As an update, we have officially released Ad Placer in our latest Android SDK (11.4.0), allowing you to easily insert native ads into your existing content streams using `RecyclerView`. Check out our documentation for more information and integration instructions: https://dash.applovin.com/documentation/mediation/android/getting-started/native-ad-placer
