### ISSUE TITLE
Native ad impression down

### ISSUE THREAD

**Issue by hoanghiephui** [AppLovin/AppLovin-MAX-SDK-Android#191]
Hi @thomasmso 
Please check why, Our Native Ads have no impressions these days. It is inexplicably reduced.

**Comment by thomasmso** [comment]
@hoanghiephui - Our product team disabled AppLovin Exhange for native ads, we will re-enable traffic ou on our latest SDKs Android 11.1.3 & iOS 11.1.2 tomorrow.

**Comment by hoanghiephui** [comment]
> @hoanghiephui - Our product team disabled AppLovin Exhange for native ads, we will re-enable traffic ou on our latest SDKs Android 11.1.3 & iOS 11.1.2 tomorrow.

Thanks @thomasmso

**Comment by hoanghiephui** [comment]
Hi @thomasmso 
I upgraded the sdk to 11.1.3. But the ad is still not showing.
Could you tell me why?

Thanks

**Comment by thomasmso** [comment]
Our backend team is actively working on re-enabling native ad demand on the latest SDKs, it should be done tm.

**Comment by hoanghiephui** [comment]
> Our backend team is actively working on re-enabling native ad demand on the latest SDKs, it should be done tm.

I really hope the problem is resolved soon. This has had a huge impact on my revenue.

**Comment by chauduyphanvu** [comment]
@hoanghiephui, could you check again now to see if the stats look good? Traffic should have been re-enabled by now. Thanks.

Vu Chau
AppLovin Team

**Comment by hoanghiephui** [comment]
> @hoanghiephui, could you check again now to see if the stats look good? Traffic should have been re-enabled by now. Thanks.
> 
> Vu Chau AppLovin Team

Thanks @chauduyphanvu 
I'll tracking more.

**Comment by Khang-NT** [comment]
>  Traffic should have been re-enabled by now
@chauduyphanvu yes I saw it's enabled for a few hours, but then did you guys just turn it off again?

**Comment by chauduyphanvu** [comment]
@Khang-NT, there's a min AppLovin SDK version you need to be on in order to get AppLovin native ads: iOS: 11.1.2
Android: 11.1.3. Are you using those versions?

**Comment by Khang-NT** [comment]
> @Khang-NT, there's a min AppLovin SDK version you need to be on in order to get AppLovin native ads: iOS: 11.1.2 Android: 11.1.3. Are you using those versions?

Yes, I confirm that the Native ad is back in version 11.1.3, but very poor fill rate (only ~4%) compare to prior the incident (~30%).

**Comment by chauduyphanvu** [comment]
@Khang-NT, are you able to share some app names or ad units so we can check? Feel free to email me at vu.chau@applovin.com if preferred.

**Comment by Khang-NT** [comment]
@chauduyphanvu , never mind, I just misunderstood the tracking report. The fill rate of Native ads is fine. 
Thanks for your support.
