### ISSUE TITLE
Too much height MaxNativeAd

### ISSUE THREAD

**Issue by Zozulinsky** [AppLovin/AppLovin-MAX-SDK-Android#192]
Hello! On Google Pixel 3A, Android 12, MaxNativeAd has height equals >3000dp. Ad from AdMob. Why?
<img width="1159" alt="Снимок экрана 2022-02-22 в 16 47 14" src="https://user-images.githubusercontent.com/13776823/155145667-a8a67d61-24c2-400b-9fdd-3a7238b5cd42.png">

**Comment by santoshbagadi** [comment]
Hi @Zozulinsky , could you please provide more information on you integration. Are you using native template or manual native ads? Could you also provide the AppLovin SDK version you are on?

For native template ads, you need to set the height you need on the `MaxNativeAdView`.

**Comment by Zozulinsky** [comment]
I use manual native ads, applovin-sdk:11.0.0

**Comment by santoshbagadi** [comment]
@Zozulinsky , do you mind sharing the full layout `.xml` file of your custom native ad layout so that we can try to reproduce the issue locally.

**Comment by santoshbagadi** [comment]
Could you please try constraining the height of the media and the full layout instead of using wrap content. The Google media view tries to take up the available space in the given container view. So, setting a fixed height for the views should fix the issue.

**Comment by Zozulinsky** [comment]
If constraining the height i don't see title, body, description and button.
![photo_2022-02-24_11-06-42](https://user-images.githubusercontent.com/13776823/155483679-d76fe9ad-2bc4-4118-b476-21ff11d2fd04.jpg)

**Comment by Zozulinsky** [comment]
I also try to use Native medium template. Just small picture was download
![photo_2022-02-24_13-53-38](https://user-images.githubusercontent.com/13776823/155510946-fadf4303-bed0-42c2-bf80-62a54340bf51.jpg)

**Comment by Zozulinsky** [comment]
@santoshbagadi Thanks! Issue resolved
