### ISSUE TITLE
Android Custom NetWork load NativeAd Error

### ISSUE THREAD

**Issue by liangning121** [AppLovin/AppLovin-MAX-SDK-Android#195]
errorCode:-5001--errorMsg:Both template and native ad view are null. Please select a template in the dashboard or provide a `MaxNativeAdView` when loading the ad to render the native ad.

this is my code for adapter

`public void loadNativeAd(MaxAdapterResponseParameters parameters, final Activity activity,
                             final MaxNativeAdAdapterListener listener) {
        final String posID = parameters.getThirdPartyAdPlacementId();
        NativeAd mNativeAd = new NativeAd(posID);
        mNativeAd.setListener(new NativeAd.NativeListener() {
            Override
            public void onAdLoaded(final NativeAd nativeAd) {
                AppLovinSdkUtils.runOnUiThread(new Runnable() {
                    Override
                    public void run() {
                        Future<Drawable> iconDrawableFuture = null;
                        Future<Drawable> imageDrawableFuture = null;

                        if (!TextUtils.isEmpty(nativeAd.getIconUrl())) {
                            iconDrawableFuture = createDrawableFuture(nativeAd.getIconUrl(), activity.getResources());
                        }
                        if (!TextUtils.isEmpty(nativeAd.getCoverImageUrl())) {
                            imageDrawableFuture = createDrawableFuture(nativeAd.getCoverImageUrl(), activity.getResources());
                        }
                        Drawable iconDrawable = null;
                        Drawable imageDrawable = null;
                        try {
                            if (iconDrawableFuture != null) {
                                iconDrawable = iconDrawableFuture.get(5, TimeUnit.SECONDS);
                            }
                            if (imageDrawableFuture != null) {
                                imageDrawable = imageDrawableFuture.get(5, TimeUnit.SECONDS);
                            }
                        } catch (Throwable e) {
                            e.printStackTrace();
                        }
                        MaxNativeAd.MaxNativeAdImage icon = iconDrawable != null ? new MaxNativeAd.MaxNativeAdImage(iconDrawable) : null;

                        ImageView meaidView = null;
                        if (imageDrawable != null) {
                            meaidView = new ImageView(activity);
                            meaidView.setImageDrawable(imageDrawable);
                        }
                        if (meaidView == null) {
                            listener.onNativeAdLoadFailed(MaxAdapterError.MISSING_REQUIRED_NATIVE_AD_ASSETS);
                            return;
                        }
                        MaxNativeAd.Builder builder = new MaxNativeAd.Builder()
                                .setAdFormat(MaxAdFormat.NATIVE)
                                .setBody(nativeAd.getAdBody())
                                .setIcon(icon)
                                .setCallToAction(nativeAd.getButtonTxt())
                                .setTitle(nativeAd.getTitle())
                                .setMediaView(meaidView);
                        MaxNativeAd maxNativeAd = new MaxExAdxNativeAd(builder);
                        listener.onNativeAdLoaded(maxNativeAd, null);
                    }
                });

            }

            Override
            public void onFailed(int i) {
                MaxAdapterError adapterError = toMaxError(i);
                listener.onNativeAdLoadFailed(adapterError);
            }
        });
        mNativeAd.setImpressionListener(new NativeAd.NativeImpressionListener() {
            Override
            public void onAdImpression() {
                listener.onNativeAdDisplayed(null);
            }

            Override
            public void onAdClick() {
                listener.onNativeAdClicked();
            }
        });
        mNativeAd.load();
    }`
`   private class MaxExAdxNativeAd extends MaxNativeAd {

        public MaxExAdxNativeAd(final Builder builder) {
            super(builder);
        }

        @Override
        public void prepareViewForInteraction(final MaxNativeAdView maxNativeAdView) {

        }
    }`

**Comment by santoshbagadi** [comment]
Hi @liangning121 , I think you are trying to load native template ads instead of native manual ads. You need to use `MaxNativeAdLoader.loadAd ( MaxNativeAdView )` to get this working.

**Comment by liangning121** [comment]
`public void loadNativeTemplate(View view) {
        String POSID = et_native_template.getText().toString();
        if (TextUtils.isEmpty(POSID)) {
            Toast.makeText(this, "posid is null", Toast.LENGTH_LONG).show();
            return;
        }
        FrameLayout fl_native = findViewById(R.id.fl_native);
        nativeAdLoader = new MaxNativeAdLoader(POSID, this);
        nativeAdLoader.setNativeAdListener(new MaxNativeAdListener() {
            @Override
            public void onNativeAdLoaded(MaxNativeAdView maxNativeAdView, MaxAd ad) {
                if (maxAd != null) {
                    nativeAdLoader.destroy(maxAd);
                }
                maxAd = ad;
                fl_native.removeAllViews();
                fl_native.addView(maxNativeAdView);
                Log.e(TAG, "Native Template Loaded");
                showToast("Native Template Loaded");
            }

            @Override
            public void onNativeAdLoadFailed(String s, MaxError maxError) {
                Log.e(TAG, "Native Template onNativeAdLoadFailed errorCode:" + maxError.getCode() + "--errorMsg:" + maxError.getMessage());
                showToast("Native Template onNativeAdLoadFailed errorCode:" + maxError.getCode() + "--errorMsg:" + maxError.getMessage());
            }

            @Override
            public void onNativeAdClicked(MaxAd maxAd) {
                Log.e(TAG, "Native Template Clicked");
                showToast("Native Template Clicked");
            }
        });
        nativeAdLoader.loadAd();
    }`

**Comment by liangning121** [comment]
I can't use MaxNativeAdLoader.loadAd()?If it is a custom adapter,must use  MaxNativeAdLoader.loadAd(MaxNativeAdView)?

**Comment by liangning121** [comment]
I select a template (Medium) in the dashboard,but it still gives me an error.

Both template and native ad view are null. Please select a template in the dashboard or provide a MaxNativeAdView when loading the ad to render the native ad.

**Comment by liangning121** [comment]
My Native Ad Units is  1e16bc56ca8244a0 ,network is ExAdx
