### ISSUE TITLE
App ANR

### ISSUE THREAD

**Issue by RunningTheSnail** [AppLovin/AppLovin-MAX-SDK-Android#196]
android.os.MessageQueue.enqueueMessage (MessageQueue.java:583)
android.os.Handler.enqueueMessage (Handler.java:778)
android.os.Handler.sendMessageAtTime (Handler.java:727)
android.os.Handler.sendMessageDelayed (Handler.java:697)
android.os.Handler.postDelayed (Handler.java:499)
com.applovin.impl.sdk.y.b (y.java)
com.applovin.impl.sdk.y.d (y.java)
com.applovin.impl.sdk.y$1.run (y.java)
android.os.Handler.handleCallback (Handler.java:938)
android.os.Handler.dispatchMessage (Handler.java:99)
android.os.Looper.loop (Looper.java:246)
android.app.ActivityThread.main (ActivityThread.java:8512)
java.lang.reflect.Method.invoke (Method.java)

**Comment by thomasmso** [comment]
Hi - what SDK version are you on?

**Comment by RunningTheSnail** [comment]
> Hi - what SDK version are you on?

v11.1.3

**Comment by thomasmso** [comment]
Hi, we'll investigate and notify the thread when an SDK fix has been released.

**Comment by santoshbagadi** [comment]
Hi @RunningTheSnail , could you please send the full thread dump of the ANR so that we can better investigate the issue.

**Comment by RunningTheSnail** [comment]
> Hi @RunningTheSnail , could you please send the full thread dump of the ANR so that we can better investigate the issue.

I saw these messages on Firebase

**Comment by xiaopei** [comment]
+1 i saw these from google play

**Comment by santoshbagadi** [comment]
Hi @xiaopei , could you please share a thread dump from the play console so that we can better understand the issue.

**Comment by thomasmso** [comment]
Should be fixed in Android v11.2.2.
