### ISSUE TITLE
ANR in AppLovin MAX SDK  on version 11.1.0

### ISSUE THREAD

**Issue by shi-juan** [AppLovin/AppLovin-MAX-SDK-Android#197]
<img width="1685" alt="image" src="https://user-images.githubusercontent.com/4100715/155483625-0ac4027d-a316-4571-b2d5-6bdc09d2b8cd.png">

**Comment by jssgames** [comment]
What are the steps to simulate this ANR?

In our game we have the same ANR and we can't simulate it to create some adjustment or predict it.

Could you share your experience with this ANR?

What tool are you using to get this information?

Thanks in advanced!
