### ISSUE TITLE
AppLovin should provide information/CSV for Google Play Data Safety Form declaration

### ISSUE THREAD

**Issue by dirkam** [AppLovin/AppLovin-MAX-SDK-Android#198]
Hi,

AppLovin SDK collects and potentially shares lots of data that is/might be considered sensitive.
Google Play requires apps to submit the Data Safety Form that includes data handling of third-party SDKs as well.
**The deadline for this is April, 2022.**

It would be immensely helpful for your customers if you provided the relevant information. Or even better, if you could provide this in the supported CSV format.
It's almost impossible for the developers to fully understand what data AppLovin collects, stores and shares.

Here are some links for more information:
[Provide information for Google Play's Data safety section](https://support.google.com/googleplay/android-developer/answer/10787469?hl=en) - Google Play Help Article about the Data Safety Form
[Google Maps SDK guidelines](https://developers.google.com/maps/documentation/android-sdk/play-data-disclosure) - An example of how an SDK can provide this information
[SDK-Privacy-Report](https://github.com/Privado-Inc/SDK-Privacy-Report) - initiative to collect this in CSV format for commonly used third-party SDKs

Thank you

**Comment by vaibhavantil1** [comment]
Any news here?

**Comment by vaibhavantil1** [comment]
https://github.com/Privado-Inc/SDK-Privacy-Report/issues/41

**Comment by rewardedtenfold** [comment]
yeah, I hope Applovin and MAX provide us this information more clearly, since it's hard to tell which ones collected for ad targeting, etc. We need more accurate information.
