### ISSUE TITLE
Video ads pause my video

### ISSUE THREAD

**Issue by JasonDisel** [AppLovin/AppLovin-MAX-SDK-Android#199]
After the video ad is displayed during the video playback, my own video will be paused, and the focus will be seized. Trying to set "mediaView?.isFocusable = false" or "mediaView?.isFocusableInTouchMode = false" will not work.

**Comment by santoshbagadi** [comment]
Hi @JasonDisel , could you provide more details on the issue. Are these with Native video ads? Is this coming from a specific network?
