### ISSUE TITLE
some hesitation of setInitializationAdUnitIds

### ISSUE THREAD

**Issue by xiaopei** [AppLovin/AppLovin-MAX-SDK-Android#201]
AppLovinSdkSettings settings = new AppLovinSdkSettings( context );
List<String> adUnitIds = new ArrayList<>();
adUnitIds.add( "YOUR_AD_UNIT_ID_1" );
adUnitIds.add( "YOUR_AD_UNIT_ID_2" );
settings.setInitializationAdUnitIds( adUnitIds );

AppLovinSdk sdk = AppLovinSdk.getInstance( settings, context );
sdk.setMediationProvider( "max" );
sdk.initializeSdk( new AppLovinSdk.SdkInitializationListener() {
    @Override
    public void onSdkInitialized(final AppLovinSdkConfiguration config) {
        ⋮                
    }
} );

How does this feature affect？
Will the initialization time be shortened?
Will other adUnitIds take longer to load?

**Comment by joeapplovin** [comment]
Hi @xiaopei - It looks like you're referring to the [selective init](https://dash.applovin.com/documentation/mediation/android/getting-started/advanced-settings#selective-init) feature of our SDK.  Based on the waterfall that you associated with the ad unit, MAX initializes only valid networks. You might use this feature to segment users by privacy flags (e.g. COPPA vs. non-COPPA) or to initialize select networks to help reduce ANR potential on low-end devices or users.
