### ISSUE TITLE
Admob impressions are very less as compared to facebook audience network and applovin using mediation

### ISSUE THREAD

**Issue by BurkPow** [AppLovin/AppLovin-MAX-SDK-Android#202]
I am using applovin mediation and using facebook audience network and admob to show impressions. The problem i am getting is that i am getting decent requests and impressions from facebook audience and applovin but getting very low ad requests and impressions from admob showing on applovin dashboard. All though my admob account is not effected by ad limitation. All i can assume is the value which applovin asks for admob placements ids i.e CPM value. I have set it to 1$ and set same to the admob account in global CPM tab. I am using interstitial only for admob. I tried changing this value to less than 1$ but getting same result. What i learned so far that this is the minimum value for ad serving means if i set this to 1$ then admob will serve ads greater than 1$ CPM but i get the static value always in the eCPM tab in applovin for admob and i.e 1$ , means that only ads with 1$ CPM are showing and not the above ones. I have connected my applovin account with admob in the networks tab. What could be the reason behind it?

**Comment by maxakash** [comment]
I am facing the same issue.
Did you solve it @BurkPow ?

**Comment by nihp** [comment]
I have a clarification, could you please clarify?

I am supported the Applovin interstitial ads. I can able to see the ads as well. But If I add the mediation networks admob and facebook, shall I need to add the additional implementations to load or show the ads or how you guys integrated in the code? 

Any docs will be helpful.

Thanks.
@maxakash @BurkPow

**Comment by santoshbagadi** [comment]
@nihp please take a look at our [**Preparing Mediated Networks**](https://dash.applovin.com/documentation/mediation/android/mediation-adapters) guide on how to add mediated networks to your project.

You may also need to look into the following guides to enabled these networks on our dashboard:
AdMob: https://dash.applovin.com/documentation/mediation/android/mediation-setup/admob
Meta/Facebook: https://dash.applovin.com/documentation/mediation/android/mediation-setup/facebook

**Comment by nihp** [comment]
@santoshbagadi I have enabled the networks successfully. I need to know while showing the ads shall i need to use my existing admob and facebook ad request and showAd methods?

**Comment by nihp** [comment]
Implementation wise shall I need to or how to showAd with the mediation networks?
