### ISSUE TITLE
Attempt to invoke interface method 'android.view.View com.bytedance.sdk.openadsdk.TTNativeAd.getAdLogoView()' on a null object reference

### ISSUE THREAD

**Issue by Juski** [AppLovin/AppLovin-MAX-SDK-Android#205]
Fatal Exception: java.lang.NullPointerException
Attempt to invoke interface method 'android.view.View com.bytedance.sdk.openadsdk.TTNativeAd.getAdLogoView()' on a null object reference
com.applovin.mediation.adapters.ByteDanceMediationAdapter$NativeAdViewListener$1$1.run (ByteDanceMediationAdapter.java:941)
android.os.Handler.handleCallback (Handler.java:790)
android.os.Handler.dispatchMessage (Handler.java:99)
android.os.Looper.loop (Looper.java:192)
android.app.ActivityThread.main (ActivityThread.java:6711)
java.lang.reflect.Method.invoke (Method.java)
com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run (RuntimeInit.java:549)
com.android.internal.os.ZygoteInit.main (ZygoteInit.java:826)

----------------------------
implementation 'com.applovin.mediation:bytedance-adapter:4.2.5.2.3'

**Comment by thomasmso** [comment]
Looks like bug with Pangle banner native ads. Will push fix. (cc @Billy-Hu)

**Comment by thomasmso** [comment]
@Juski - Fix is live in latest adapter: https://github.com/AppLovin/AppLovin-MAX-SDK-Android/commit/5ec89cf6be0050f405af40e10fc3d3ad38ff871e, thanks for reporting it.

**Comment by Juski** [comment]
Thanks, the bug has been fixed in the latest version.
