### ISSUE TITLE
 Banner display wrong correctly Galaxy A52

### ISSUE THREAD

**Issue by Zozulinsky** [AppLovin/AppLovin-MAX-SDK-Android#206]
Hello! I have trouble with Applovin Exchange and AdMob Banner but only with Samsung A52 
<img width="1506" alt="Снимок экрана 2022-02-28 в 10 57 47" src="https://user-images.githubusercontent.com/13776823/155946783-f1a804c0-6c3f-42b3-8997-4234d92f2c44.png">
<img width="1506" alt="Снимок экрана 2022-02-28 в 11 04 32" src="https://user-images.githubusercontent.com/13776823/155946826-2bab31b5-d6bd-49ce-9d59-dacf5a93e934.png">
Code to add a banner to container

```
adView = MaxAdView(blockId, activity)
adView?.setListener(createListener(activity))
val heightPx = AppLovinSdkUtils.dpToPx(activity, 50)
adView?.layoutParams = FrameLayout.LayoutParams(ViewGroup.LayoutParams.MATCH_PARENT, heightPx)
adView?.setBackgroundColor(Color.BLACK)
bannerHolder.addView(adView)
adView?.loadAd()

**Comment by Zozulinsky** [comment]
Banner container xml

```
<FrameLayout xmlns:android="http://schemas.android.com/apk/res/android"
    xmlns:tools="http://schemas.android.com/tools"
    android:id="@+id/banner_placeholder"
    android:layout_width="match_parent"
    android:layout_height="@dimen/banner_height"
    android:background="?themeBackground"
    android:visibility="gone"
    android:layout_gravity="center"
    tools:background="@color/moderation_red"
    tools:showIn="@layout/fragment_profile_data"
    tools:visibility="visible" />

**Comment by Zozulinsky** [comment]
@santoshbagadi  can you help me?

**Comment by santoshbagadi** [comment]
Hi @Zozulinsky , sorry for the delayed response. Could you please share logs when the issue is occurring with our [SDK verbose logging enabled](https://monetization-support.applovin.com/hc/en-us/articles/236114328-How-do-I-enable-verbose-logging-in-AppLovin-s-SDK-).

**Comment by Zozulinsky** [comment]
@santoshbagadi i will try to catch bug again
