### ISSUE TITLE
Does Smaato support bidding on more than just banners?

### ISSUE THREAD

**Issue by 1008k** [AppLovin/AppLovin-MAX-SDK-Android#207]
Hi, I'm trying to integrate Smaato as a bidder.
I have done a series of work and noticed that Smaato is not listed under "Bidder Networks" in MAX dashboard for any ad space except BANNER and MREC.

Can I use Smaato in bidding for interstitials and rewards?
As far as I can see from the MAX documentation, Smaato is Bidding enabled and supports all ad formats.

Best regards.

**Comment by NanaAmoah** [comment]
Hi @1008k, we're actively working on supporting Smaato Bidding for interstitial and rewarded ads. I'll update you as soon as it's live.

**Comment by NanaAmoah** [comment]
Hi @1008k, support for Smaato Bidding interstitials and rewarded videos is now live for android adapter versions 21.6.6.1 and above.
You should see it listed under Bidder Networks now.

**Comment by dirkam** [comment]
@NanaAmoah do you plan to support bidding for native ads as well?
