### ISSUE TITLE
Native Ad - Missing Icon + main image

### ISSUE THREAD

**Issue by Khang-NT** [AppLovin/AppLovin-MAX-SDK-Android#208]
SDK version: 11.1.3-11.2.0
The issue happens on my app and can be reproduced on the demo app as well. Please check.
![274598415_1139114330198380_6479538505874126576_n](https://user-images.githubusercontent.com/13332950/156195227-82749e2a-b4f8-4233-9019-b4a4cfdc9cb8.jpg)
![274612891_331135818804730_7196673842820380244_n](https://user-images.githubusercontent.com/13332950/156195235-97afa3ae-674a-4bbf-b498-749b11e3bef8.jpg)

**Comment by santoshbagadi** [comment]
Hi @Khang-NT , it seems like you might be using a template native ad unit ID for loading a manual native ads. Could you please update your ad unit in our dashboard and select `Manual` for `Template` and see if that fixes the issue.

**Comment by Khang-NT** [comment]
> Hi @Khang-NT , it seems like you might be using a template native ad unit ID for loading a manual native ads. Could you please update your ad unit in our dashboard and select `Manual` for `Template` and see if that fixes the issue.

Hi @santoshbagadi, I created a new Manual ad unit, but still have the same issue. Are you able to reproduce it?

**Comment by Khang-NT** [comment]
Hi @santoshbagadi,  it's working now, thanks for pointing it out.

**Comment by androidsdev** [comment]
@santoshbagadi yes, test mode enabled, ok, I'll just release it, thanks

**Comment by kruguerjo** [comment]
> Hi @Khang-NT , it seems like you might be using a template native ad unit ID for loading a manual native ad. Could you please update your ad unit in our dashboard and select `Manual` for `Template` and see if that fixes the issue.

Hi @santoshbagadi i'm having the same issue, i'm using facebook bidding with Applovin Max, the native ad main image is not showing up (see image attached), i'm using medium template native ad, this is the ad unit : 894415bd856e22fe
![photo_2022-03-26_20-19-54](https://user-images.githubusercontent.com/102380669/160254138-3d2e914b-c5da-4b87-b1ae-dd785c8a860c.jpg)
