### ISSUE TITLE
On Adhidden my target intent working with little bit delay

### ISSUE THREAD

**Issue by asadzoobiapps** [AppLovin/AppLovin-MAX-SDK-Android#210]
My applovin interstitial ad is showing but issue is on Adhidden i am making a callback from where i cant go to my target activity instantly.It taking some time.

**Comment by NanaAmoah** [comment]
Hi @asadzoobiapps, each network will have their own timing related to the `onAdHidden(...)` callback. 

If you have a video and code snippet of the experience we can look into it for you.
