### ISSUE TITLE
Native ads not working with Test mode when AdMob is selected

### ISSUE THREAD

**Issue by appetizermonster** [AppLovin/AppLovin-MAX-SDK-Android#211]
When I set the test network to AdMob in Test Mode settings in the AppLovin dashboard,
It looks like AppLovin SDK uses the AdMob's test ad unit "**ca-app-pub-3940256099942544/1044960115**" for native ads.
(video native ad)
However, AdMob always returns "No fill" on the ad unit for no reason.
So I can't test AdMob native ads with Test mode. 😞 

Does this problem only occur to me?

**Comment by santoshbagadi** [comment]
Hi @appetizermonster , could you please send us logs with [verbose logs enabled](https://monetization-support.applovin.com/hc/en-us/articles/236114328-How-do-I-enable-verbose-logging-in-AppLovin-s-SDK-) for our SDK so we can investigate further. 

I'm not able to reproduce the issue locally.

**Comment by appetizermonster** [comment]
@santoshbagadi 
Here's the full log:
https://gist.github.com/appetizermonster/1745358e796d477289f6174e2329a0ed

Currently, AppLovin SDK uses the AdMob's **Native Advanced Video** test ad unit `ca-app-pub-3940256099942544/1044960115` and it's not working on my device. (South Korea, Korean language)

I personally confirmed that AdMob's other **Native Advanced** test ad unit `ca-app-pub-3940256099942544/2247696110` is working.

AdMob's test ad unit list: https://developers.google.com/admob/android/test-ads

**Comment by santoshbagadi** [comment]
Thank you @appetizermonster , we are looking into switching the ad unit, we'll update here when we made the change.

**Comment by hani09876** [comment]
> Thank you @appetizermonster , we are looking into switching the ad unit, we'll update here when we made the change. 


Please make sure that applovin max has a support for using on godot game engine.
