### ISSUE TITLE
Adcolony and smaato mediation integration with cleartextTrafficPermitted true

### ISSUE THREAD

**Issue by radhasharma123** [AppLovin/AppLovin-MAX-SDK-Android#213]
Hi team,
I am integrating applovin max sdk with all mediation but i have problem with Adcolony and smaato mediation integration because for those mediation we have use below code mandatory 
cleartextTrafficPermitted="true" in network config file.
but when we will use this with live apk on playstore then i will get issue with this beacuse this is not allowed by new versions and code.
According to [Network security configuration](https://developer.android.com/training/articles/security-config#CleartextTrafficPermitted)-

Please suggest how we can use that mediation.

Thanks in advance.
Radha sharma

**Comment by radhasharma123** [comment]
Which link you have shared above that is not my sdk implementation.
Please look this page:
https://dash.applovin.com/documentation/mediation/android/mediation-adapters?network=ADCOLONY_NETWORK

We are using Applovin MAX Sdk and it's mediation is Adcolony that generate problem for cleartext permissions.

**Comment by chauduyphanvu** [comment]
@radhasharma123, I understand you are using MAX SDK and mediation. What I meant was that AdColony no longer requires the Android cleartext permission according to their documentation that I quoted, so you are safe to remove it from your AndroidManifest.

We will update our own documentation to reflect the same.
