### ISSUE TITLE
About Huawei Custom Adapter 

### ISSUE THREAD

**Issue by BerkeCoban** [AppLovin/AppLovin-MAX-SDK-Android#214]
Why there is no Huawei Banner Ad adapter ? is there a reason for it? or do you plan to add in the future?

**Comment by thomasmso** [comment]
@BerkeCoban - Do you have publishers waiting for this? If so, who? If you provide the docs, we can implement. (cc @alvarshahanji)

**Comment by BerkeCoban** [comment]
Hello again,
thank you for your quick feedback, We are very pleased about this Huawei custom adapter, and it is an important solution for us. 

**official Huawei banner implementation link:** 
https://developer.huawei.com/consumer/en/doc/development/HMSCore-Guides/publisher-service-banner-0000001050066915

**Our previous custom adapter solutions:**
 https://github.com/Explore-In-HMS/?q=mediation&type=all&language=&sort=

**example banner ad implementation :** 
https://github.com/Explore-In-HMS/huawei.ads.smartadsserver_mediation/blob/main/smart_mediation/src/main/java/com/hmscl/huawei/smart_mediation/SASHuaweiBannerAdapter.kt

I hope these links can help you to implement banner ads.  If you need any help with this implementation , As Huawei ads team,  we can gladly  help. 

Thank you.

**Comment by thomasmso** [comment]
Thank you. We'll have an update within a week.

**Comment by BerkeCoban** [comment]
Hello again, 

Hope you are doing well.  I have a small code block for the Huawei Custom Adapter. I will be glad if you add this code before the release of the new version with banner ads.

This code block sends TCF  string to Huawei ads. You can check the gist below.

Gist Link:  https://gist.github.com/BerkeCoban/447d08de0fa31afb253c64500a276471#file-example-kt

 You can set the tcf string if any exists, using   "adParamBuilder.setConsent(tcfString)"   and make the ad request with that adParamBuilder. 

Thank you :)

**Comment by BerkeCoban** [comment]
Hello guys, 

I made some tests with the new version.

For the MREC ad type, there is no problem, but for the banner ad type, it seems there is a problem. 

I debugged inside the adapter, and when the custom adapter class running the code somehow Applovin onadfailed triggers and the adapter code stops running. 

If you can check this issue, It would be great.

Used demo app :
 https://github.com/AppLovin/AppLovin-MAX-SDK-Android/tree/master/AppLovin%20MAX%20Demo%20App%20-%20Kotlin

**Comment by thomasmso** [comment]
Could you enable our SDK's [verbose logs](https://dash.applovin.com/documentation/mediation/android/getting-started/advanced-settings#enable-verbose-logging) and send those over?

**Comment by thomasmso** [comment]
I'm observing logs such as:

```
2022-03-21 16:44:40.251 15129-16941/com.applovin.enterprise.apps.demoapp E/AppLovinSdk: [MediationAdapterWrapper] Failed start loading MediatedAd{thirdPartyAdPlacementId=testw6vs28auh3, adUnitId=4fdf733436d1e025, format=BANNER, networkName='HuaweiMediationAdapter'} : java.lang.NullPointerException: Attempt to read from field 'android.os.MessageQueue android.os.Looper.mQueue' on a null object reference
```

Does your SDK require all calls to be made from the UI thread?

**Comment by BerkeCoban** [comment]
Hello again,

![image](https://user-images.githubusercontent.com/53767481/159486913-2b0edb17-4b32-400f-a457-57760bcdedcc.png)


After that marked line, the adapter stops running. It does not reach if block.


For your question, the answer is no.  I believe this issue is not about the Huawei Ads SDK, because I got the MREC ad without any problem. This ad type also uses Huawei Banner ad only the size is 300x250 instead of 320x50. 
 ( it uses the same method  **loadAdViewAd()**)

If you can check it with the Huawei test ad unit id, it would be great.

**Comment by alvarshahanji** [comment]
I can take a look today

**Comment by alvarshahanji** [comment]
@BerkeCoban the new adapter(13.4.49.301.3) with the fix is live!
