### ISSUE TITLE
MaxNativeAdView makes app really slow with the native ad preload API

### ISSUE THREAD

**Issue by appetizermonster** [AppLovin/AppLovin-MAX-SDK-Android#215]
An infinite loop is made when some conditions are met in my RecyclerView use case.
In my RecyclerView use case, I expect that a native ad object can be reused until destroy and a MaxNativeAdView can be reused as well.
But the current AppLovin native ad API won't work as my expectation. (this use case works on MoPub and AdMob.)

Reproducing steps:
1. Preload a native ad. (with the new preload API)
2. Render the native ad with a new MaxNativeAdView.
3. Remove the MaxNativeAdView from the view tree.
4. Render the native ad with a new MaxNativeAdView again. (reuse the ad)
5. Repeating 3~4 steps cause the infinite loop and it makes app very slow.

Calling `recycle()` on the view at step 3 may eliminate the slowdown but it destroys the ad as well.

It looks like some code related to **VisibilityTracker** makes an infinite loop on handler.
the obfuscated SDK code:
```java
this.f = new Runnable() {
  if (z.this.b(var1, var2)) {
      z.this.b.b("VisibilityTracker", "View met visibility requirements. Logging visibility impression..");
      z.this.a();
      z.a var3 = (z.a)var4.get();
      if (var3 != null) {
          var3.onLogVisibilityImpression();
      }
  } else {
      z.this.b(); // Calling postDelayed in the following block
  }
};
```
```java
private void b() {
    this.e.postDelayed(this.f, (Long)this.a.a(com.applovin.impl.sdk.c.b.bS)); // Calling this.f again in the above after some delay
}
```

**Comment by chauduyphanvu** [comment]
@appetizermonster, this issue has been addressed in the latest SDK release v11.2.2: https://github.com/AppLovin/AppLovin-MAX-SDK-Android/releases/tag/release_11_2_2.

Check it out and let us know if the issue persists. Thanks!
