### ISSUE TITLE
Why do you need Activity context at Native format?

### ISSUE THREAD

**Issue by adxcorp** [AppLovin/AppLovin-MAX-SDK-Android#216]
Hi Team,

Our team need to integrate AppLovin MAX Native ad using ForegroundService. But AppLovin Native Ad doesn't suport that.

Actually, we want to integrate using Application Context. When we call native ad using application context, we got this exception.
java.lang.ClassCastException: com.ktcs.whowho.WhoWhoAPP cannot be cast to android.app.Activity

Best,

**Comment by santoshbagadi** [comment]
Hi @adxcorp , could you please share the full stack trace of the crash or logs with [verbose logs enabled](https://monetization-support.applovin.com/hc/en-us/articles/236114328-How-do-I-enable-verbose-logging-in-AppLovin-s-SDK-) for our SDK when the crash is happening.

**Comment by adxcorp** [comment]
@santoshbagadi 

I just checked our code, we casting application context to activity. It occur issue.

But, we need NativeAdLoader constructor using Context. Can you support it?

**Comment by santoshbagadi** [comment]
@adxcorp , we already support creating a `NativeAdLoader` with application context. You can update to our latest SDK to use the new API.

**Comment by adxcorp** [comment]
@santoshbagadi thanks. I'll check it 👍
