### ISSUE TITLE
Error applovin mediation debugger

### ISSUE THREAD

**Issue by byJS93** [AppLovin/AppLovin-MAX-SDK-Android#217]
I am using the mediation debugger to find out which advertisers are well integrated and I get that they are well integrated but I have a problem when I try to see the test ads to test them.
In adcolony in sdk I get "unavailable" and in the "Retrieving SDK Version" app, I attach a photo.
When I enter each of the advertisers, it always stays in "Waiting to initialize..." and if I try to load an ad in the "Test Mode" part I get error -5001.
========== NETWORKS ==========
     ---------- ADCOLONY_NETWORK ----------
     Status - COMPLETE
     SDK - UNAVAILABLE
     Adapter - 4.6.5.1
     ---------- APPLOVIN_NETWORK ----------
     Status - COMPLETE
     SDK-11.2.1
     Adapter - 11.2.1
     ---------- FACEBOOK_NETWORK ----------
     Status - COMPLETE
     SDK-6.8.0
     Adapter - 6.8.0.12
     ---------- VUNGLE_NETWORK ----------
     Status - COMPLETE
     SDK-6.10.4
     Adapter - 6.10.4.0

Error Retrieving SDK Version: https://prnt.sc/u9T4Z7rPsIKD
Error Waiting to initialize..:https://prnt.sc/ztmb3x82d7xA

**Comment by joeapplovin** [comment]
Hi @byJS93 - just wanted to confirm if you have
```
dependencies {
    implementation 'com.applovin:applovin-sdk:+'
    implementation 'com.applovin.mediation:adcolony-adapter:+'
}
```
in your `build.gradle`?

**Comment by byJS93** [comment]
If I have this set:

implementation 'com.applovin:applovin-sdk:11.2.1'
     implementation 'com.applovin.mediation:adcolony-adapter:4.6.5.1'
     implementation 'com.applovin.mediation:vungle-adapter:6.10.4.0'
     implementation 'com.applovin.mediation:facebook-adapter:6.8.0.12'
     implementation 'androidx.recyclerview:recyclerview:1.2.1'
     implementation 'androidx.appcompat:appcompat:1.4.1'

**Comment by byJS93** [comment]
I have been doing tests and when I install the app from the apk on a normal phone they load all the sdk except ADCOLONY which stays in "Retrieving SDK Version..."

The previous tests were done in the android studio emulator and there are if they all failed me.

**Comment by smvarela** [comment]
Same error here. I use these dependencies in build.gradle
```
dependencies {
  implementation 'com.applovin:applovin-sdk:11.3.0'
  implementation 'com.applovin.mediation:adcolony-adapter:+'
}
```
