### ISSUE TITLE
Native ad Icon & Media is missing in live versions

### ISSUE THREAD

**Issue by ihassanali259** [AppLovin/AppLovin-MAX-SDK-Android#223]
I have tried all the latest and old versions of the Aplovin SDK but the native ad icon and media are not showing. The impression rate is going down to 0% for the native ads
![fourg_scrrenshot](https://user-images.githubusercontent.com/43772154/156873779-e5a94865-c8eb-4b44-9ca2-a833f5826592.jpeg)
.

**Comment by santoshbagadi** [comment]
@ihassanali259 , do you by any chance have `Small` or `Medium` template selected on AppLovin dashboard for this ad unit. If so, switching to `Manual` should fix the issue.

**Comment by androidsdev** [comment]
@santoshbagadi, I can confirm that it is unstable, sometimes icons and media are shown, but mostly blank.
version 11.2.0, already update the ad unit id to manual

**Comment by ihassanali259** [comment]
Selecting manual from the unit id fixed my issue. Hope it won't happen again. ( Plus it takes almost one hour to take effect when you change to manual)
