### ISSUE TITLE
How do I disable Applovin AD?

### ISSUE THREAD

**Issue by RunningTheSnail** [AppLovin/AppLovin-MAX-SDK-Android#225]
The use of interstitial ad in non-game apps greatly affects the user experience, because his playing time is too long. It seriously affects the retention of users. Now we are forced to migrate from mopub to max and feel a lot of discomfort. I believe that many developers have been troubled by this, can you solve it?

**Comment by thomasmso** [comment]
Hi, please email partner_support@applovin.com, they will be able to assist you there re: product issues.
