### ISSUE TITLE
Keyboard automatically disappearing when banner ad loads/refreshes 

### ISSUE THREAD

**Issue by Apsaliya** [AppLovin/AppLovin-MAX-SDK-Android#227]
Mine is a utility app when writing is primary use case so users have keyboards open most of the time. Number of users have started complaining that when they are writing , keyboard automatically disappears and never comes back even of they tap again in input area. Pretty disrupting user behaviour.

When I investigated, I was not able to reproduce when test mode is enabled but when I disabled test mode i was able to reproduce the scenario (when actual ad is shown/refreshed). If I disable the ads, this behaviour doesn't happen. I'm not sure if it has anything to do with MAX Sdk. Do you think MAX SDK can be causing this in any way? I could not conclude it is MAX but from whatever I observed, it does look like something to do with SDK.

**Comment by chauduyphanvu** [comment]
@Apsaliya, we have publishers who can load and show banner ads while the keyboard is present with no issues. Given that, I'd say what you're seeing is implementation-specific. 

Have you tried moving the banner ad view to a different location (e.g. at the top of the screen) to see if the issue persists? Or maybe try to have the banner sit above/below (but not on top of) the keyboard (like in a vertical `LinearLayout`). 

If you have a reproducible project we can help take a look. 

Vu Chau
AppLovin Team

**Comment by Apsaliya** [comment]
@chauduyphanvu Thanks a lot. My immediate observation is that said behaviour doesn't happen if I remove Mintegral Adapter (I also observed MbBannerView from Mintegral SDK constantly taking keyboard focus). All other adapters work fine (I have Meta, Inmobi and Mytarget apart from Mintegral). I am going to try to re create this in standalone project to isolate the problem and will get back to you with my findings.
