### ISSUE TITLE
Please fix Mediation Native Ad font color

### ISSUE THREAD

**Issue by mastervnc** [AppLovin/AppLovin-MAX-SDK-Android#228]
Hello, when using Nativate Ad with Mediation, I have a very annoying problem that is the default font color to light (white) instead of dark (black). Therefore, the content cannot be seen. I am using small temple. Please fix soon, thanks!
![1646721006229](https://user-images.githubusercontent.com/67771965/157182986-ea46e3dc-f364-486e-9a32-11cccf3ffa65.jpg)

**Comment by tiandrew** [comment]
Hey @mastervnc, could you send a screenshot of the `Layout Inspector` in Android Studio while a native ad is showing and click on the textView containing the title? And then could you filter the right side's attributes by "color" to find what the `textColor` is set to? Here's an example of what it might look like:

![Screen Shot 2022-03-09 at 3 13 05 PM](https://user-images.githubusercontent.com/15932774/157555062-6f72521d-a19e-4561-86d1-2a9016d52583.png)

**Comment by mastervnc** [comment]
Test mode is fine, but the live ad is as above, I checked again, this situation is on a few devices, not all.

**Comment by tiandrew** [comment]
Is every live ad on those devices affected or is it only some ads? If so could you let me know which devices are affected?

**Comment by mastervnc** [comment]
If any device has that problem, 100% of all live ads are affected, I am testing live ad with Xiaomi Redmi Note 10 5G (Mediatek Dimensity), but I test another device that is much older but uses Snapdragon chip then don't have that problem.

This is the image I just checked, still having the font bug.
![1646874563676](https://user-images.githubusercontent.com/67771965/157567185-a1172887-c90b-480a-b179-62bc2cf43da4.jpg)

**Comment by tiandrew** [comment]
@mastervnc thanks for the info. Could you try checking the layout inspector using the example I showed above and sending a screenshot similar to mine? I'd like to see if the actual text color itself is changed or if something else is up, since I don't have a device that has this issue myself.

**Comment by tiandrew** [comment]
Also what Android API level is each device that's experiencing this problem on?

**Comment by mastervnc** [comment]
I'm really sorry, but this is a live ad, if I debug too many live ads like that, I'm afraid Applovin will ban my account :(

**Comment by tiandrew** [comment]
@mastervnc could you just send the verbose logs for your session then? No need for the layout inspector in that case
