### ISSUE TITLE
Massive Android WebView crashes because of Applovin ads

### ISSUE THREAD

**Issue by codesForLiving** [AppLovin/AppLovin-MAX-SDK-Android#23]
Some Applovin banner ads make the Android WebView crash (and hence make my app crash), with errors like:

```
in base.apk!libmonochrome.so (offset 0x2c4000)

backtrace:
 
  #00  pc 0000000002b373d0  /data/app/com.google.android.webview-4hNndG-Zz2yTk0o8sxkIEw==/base.apk!libmonochrome.so (offset 0x2c4000)
```

My app has hundreds of crashes everyday because the WebView crashes while showing ads.

This is a low level crash of the webview, so it's not visible in Crashlytics, only in Google Developer Console.

When I removed Applovin from my mediation, the number crashes collapsed to almost zero.

I am using Applovin through AdMob Mediation

**Admob Adapter for Applovin version:** com.google.ads.mediation:applovin:9.13.1.0 (also occurred with earlier versions)
**Admob version:** com.google.firebase:firebase-ads:19.2.0
**Android Studio Version:** 4.0.1
**Gradle Version:** 4.0.1
**Device model and OS Version:** Android 10 only

Pixel 3 (blueline) | 5 | 12.5%
-- | -- | --
Pixel 4 XL (coral) | 3 | 7.5%
P20 Pro (HWCLT) | 2 | 5.0%
OnePlus6T (OnePlus6T) | 2 | 5.0%
Galaxy Note9 (crownqlteue) | 2 | 5.0%
Pixel 3a (sargo) | 2 | 5.0%
Galaxy S10 (beyond1) | 2 | 5.0%
Galaxy S10 (beyond1q) | 2 | 5.0%
Galaxy S9 (starqltesq) | 2 | 5.0%
Pixel 4 (flame) | 2 | 5.0%
Galaxy Note10 (d1q) | 1 | 2.5%
Pixel XL (marlin) | 1 | 2.5%
Galaxy S9+ (star2qltesq) | 1 | 2.5%
Nokia 7.2 (DDV_sprout) | 1 | 2.5%
Galaxy S10e (beyond0q) | 1 | 2.5%
OnePlus6T (OnePlus6TSingle) | 1 | 2.5%
OnePlus5T (OnePlus5T) | 1 | 2.5%
Galaxy S9+ (star2qltecs) | 1 | 2.5%
Galaxy S20 5G (x1q) | 1 | 2.5%
OnePlus 7 Pro (OnePlus7ProTMO) | 1 | 2.5%
Others | 6 | 15.0%

Expected behavior:

Don't make the WebView crash, by not trying to load I-suppose-buggy-ads.

MoPub ads caused similar crashes, but they have fixed it. Here is link to MoPub issue https://github.com/mopub/mopub-android-sdk/issues/312

**Comment by Lorenzo45** [comment]
Hey, sorry for the delayed response. We've investigated issues in the past and these crashes come from WebViews outside of our SDK that don't handle onRenderProcessGone().

That being said, it seems like the ads that are causing these WebViews to crash are coming from our ad network and we don't yet have a way to track these down but we're working on tools to be able to.

**Comment by codesForLiving** [comment]
@Lorenzo45 Hey, any update on this? I tried using Applovin again, since MoPub is sun-setting, but the crashes are still there.

**Comment by Lorenzo45** [comment]
We've done multiple investigations into these crashes and they seem to be caused by devices being under a lot of stress in terms of memory and CPU usage. Would you be able to share which app you're seeing the crash in and more information about your mediation setup? If you could send a list of the SDKs you're mediating and the versions that would be helpful.
