### ISSUE TITLE
Fatal Exception: java.lang.IncompatibleClassChangeError

### ISSUE THREAD

**Issue by Zevsus** [AppLovin/AppLovin-MAX-SDK-Android#230]
Fatal Exception: java.lang.IncompatibleClassChangeError: Class 'org.apache.http.message.BasicHeader' does not implement interface 'org.apache.http.NameValuePair' in call to 'java.lang.String org.apache.http.NameValuePair.getName()' (declaration of 'com.yandex.mobile.ads.impl.fa' appears in /data/app/com.book.app-KjDkeIDkRNQR0gJgosMy0g==/base.apk!classes2.dex)
       at com.yandex.mobile.ads.impl.fa.a(SourceFile:195)
       at com.yandex.mobile.ads.impl.fa.a(SourceFile:14)
       at com.yandex.mobile.ads.impl.z30.run(SourceFile:24)
Hello! I get this error when running the app on real devices (Galaxy A01 Core and HUAWEI MediaPad M5 Pro).

**Comment by chauduyphanvu** [comment]
@Zevsus - thanks, we have relayed this crash to Yandex. Stay tuned for an update!

Vu Chau
AppLovin Team

**Comment by Zevsus** [comment]
> @Zevsus - спасибо, мы передали этот сбой в Яндекс. Следите за обновлениями!
> 
> Ву Чау AppLovin Team

Thank you! Will wait!

**Comment by chauduyphanvu** [comment]
@Zevsus, could you provide us with the following info? Thanks.

* OS version
* Yandex Ads SDK version
* Applovin SDK version
* Device type

**Comment by Zevsus** [comment]
OS version (9 and 10)
Yandex Ads SDK version (4.5.0.3)
Applovin SDK version (11.2.2)
Device type phone and tablet

**Comment by Zevsus** [comment]
The reason turned out to be in the library com.google.apis:google-api-services-drive:v3-rev20220227-1.32.1 in the old version 20211107-1.32.1 everything works!

**Comment by Zevsus** [comment]
Unfortunately, after turning on Yandex in the MAX management console, the application crashes.

**Comment by chauduyphanvu** [comment]
Thanks. Is it the same crash?

**Comment by Zevsus** [comment]
Yes
