### ISSUE TITLE
Migrating Facebook Native Banner Ad from Mopub to AppLovin

### ISSUE THREAD

**Issue by lucasrafagnin** [AppLovin/AppLovin-MAX-SDK-Android#234]
Hi guys, 

During the Sdk migration I noticed some different points, and I would like to know if there is a way to get around them:

- Lack of [listener callback](https://developers.mopub.com/publishers/android/native-manual/#step-1-request-the-native-ad) (_Topic 7_) for onClick and onImpression ad events, they are important events and existed both on Facebook and on Mopub (called MoPubNativeEventListener), and I didn't find it on your SDK.

- One way to detect if the ad loaded is still valid, on Facebook this function is called [`isAdInvalidated`](https://developers.facebook.com/docs/audience-network/reference/android/com/facebook/ads/nativeadbase.html/?version=v4.99.1).

- [Desired Assets](https://developers.mopub.com/publishers/android/native-manual/#step-1-request-the-native-ad)(_Topic 5_), in Mopub I can pass these optional parameters and I haven't found an equivalent in AppLovin.

Thanks

**Comment by chauduyphanvu** [comment]
@lucasrafagnin,

* We have a click callback in the `MaxNativeAdListener` interface. For impression you can assume it is tracked as soon as you've added the ad view to your view hierarchy in `onNativeAdLoaded()` (you can check your log for messages like `View met visibility requirements. Logging visibility impression` and `Tracking Visibility`). 
* We do check for `isAdInvalidated()` in the adapter (so no action required on your part): https://github.com/AppLovin/AppLovin-MAX-SDK-Android/blob/ea965190cb4a3a683eee9088f0a276f6e8ba9669/Facebook/src/main/java/com/applovin/mediation/adapters/FacebookMediationAdapter.java#L1074-L1080
* Desired assets can eventually be implemented but it was never a useful feature at MoPub (speaking as a former employee). You could specify the assets you want, but that can limit your fill (as opposed to requesting with everything and selectively discarding the ads you don't want later).

Vu Chau
AppLovin Team

**Comment by lucasrafagnin** [comment]
Hi @chauduyphanvu.

Could you add the impression event in MaxNativeAdListener class? I noticed that this information exists in MaxNativeAdAdapterListener, and it would be relevant to our project as we used this event callback previously in the Mopub SDK.

Thanks.
