### ISSUE TITLE
inmobi native integrate

### ISSUE THREAD

**Issue by williamycyh** [AppLovin/AppLovin-MAX-SDK-Android#236]
I want to integrate inmobi native, how should I do it?
Do you have any plans to add inmobi native?

**Comment by NanaAmoah** [comment]
HI @williamycyh, yes, we're actively working on adding support for InMobi native ads. I'll share an update here once it's live.

**Comment by NanaAmoah** [comment]
Hi, ETA for this is about 2.5 weeks. I'll share an update once it's available.

**Comment by taugin** [comment]
> Hi, ETA for this is about 2.5 weeks. I'll share an update once it's available.

The adapter already supports inmobi's native advertisements, but inmobi's native advertisements cannot be configured in the ad slot configuration interface. When will it be supported?

**Comment by dirkam** [comment]
+1

Can we get an update on this?

@applovin-mobile-engineering

**Comment by NanaAmoah** [comment]
Hi all, the support for InMobi native is currently undergoing testing. I'll share updates once they're available.

**Comment by dirkam** [comment]
Thanks @NanaAmoah. Will it support bidding? Can you please narrow it done if we can expect it in days or weeks? Thanks

**Comment by dirkam** [comment]
@NanaAmoah one more quick question: does your implementation show ad choices/privacy icon for the inmobi native ad?

**Comment by NanaAmoah** [comment]
Hi @dirkam, I don't have an ETA for InMobi native ads support at this time but we will share updates once they are available. Support for native ads bidding is in our pipeline and we will also share updates when available. 

Our implementation doesn't support the InMobi privacy/ad choices icon because InMobi does not support it at this time.

**Comment by williamycyh** [comment]
@NanaAmoah 
Can you update this case, thanks

**Comment by NanaAmoah** [comment]
Hi @williamycyh, ETA for support to go live is sometime at the end of this month. Thanks.
