### ISSUE TITLE
Attempt to read from field 'boolean com.applovin.impl.sdk.o$a.a' on a null object reference

### ISSUE THREAD

**Issue by xsjmichael** [AppLovin/AppLovin-MAX-SDK-Android#238]
Exception log from Firebase analytics are as below , all exceptions happened 100% background state.

SDK Version:
com.applovin:applovin-sdk:11.2.1
com.applovin.mediation:google-adapter:20.5.0.5
com.applovin.mediation:smaato-adapter:21.6.7.1

Fatal Exception: java.lang.NullPointerException
Attempt to read from field 'boolean com.applovin.impl.sdk.o$a.a' on a null object reference
com.applovin.impl.sdk.o.k (o.java:22)
com.applovin.impl.sdk.e.i.b (i.java:394)
com.applovin.impl.sdk.e.i.run (i.java:46)
java.util.concurrent.ThreadPoolExecutor.runWorker (ThreadPoolExecutor.java:1167)
java.util.concurrent.ThreadPoolExecutor$Worker.run (ThreadPoolExecutor.java:641)
java.lang.Thread.run (Thread.java:919)

**Comment by chauduyphanvu** [comment]
@xsjmichael, thanks for the report. We're aware of this crash and will be working on a fix soon. Stay tuned!
