### ISSUE TITLE
Could not GET 'https://maven.ornoma.org/ornoma-android-lib/com/applovin/quality/AppLovinQualityServiceGradlePlugin/maven-metadata.xml'.

### ISSUE THREAD

**Issue by waqas-334** [AppLovin/AppLovin-MAX-SDK-Android#239]
Hi, I integrated the Applovin to my Android app on a Windows computer. But recently I shifted to Macbook with M1 chip and the following error started appearing. 

`Could not GET 'https://maven.ornoma.org/ornoma-android-lib/com/applovin/quality/AppLovinQualityServiceGradlePlugin/maven-metadata.xml'.`

And even you visit that URL in the browser, you will not land anywhere but an error page. [Do check if out here](https://maven.ornoma.org/ornoma-android-lib/com/applovin/quality/AppLovinQualityServiceGradlePlugin/maven-metadata.xml)

Please help me out on this.

Thank you

**Comment by chauduyphanvu** [comment]
@waqas-334 - could you share your Gradle so we can try to reproduce it? You can also try to compile our sample app as a way to test your dev environment: https://github.com/AppLovin/AppLovin-MAX-SDK-Android/tree/master/AppLovin%20MAX%20Demo%20App%20-%20Java.

Vu Chau
AppLovin Team
