### ISSUE TITLE
Custom Adapters: No control received in SDKVersion and adapterVersion

### ISSUE THREAD

**Issue by pm-preety-narvekar** [AppLovin/AppLovin-MAX-SDK-Android#242]
Hello Team,

I have created custom adapters for a network for banner, interstitial and rewarded ad formats. I am able to get control in my adapter for all the ad formats and load the ads. But for `public String getSdkVersion()` and `public String getAdapterVersion()`, the control never comes to these methods.

Any idea about the reason? I am using SDK v11.2.1

**Comment by chauduyphanvu** [comment]
@pm-preety-narvekar, do you see anything suspicious in console logs? If there's an issue trying to invoke those APIs we will try-catch and log the error.

**Comment by pm-preety-narvekar** [comment]
Hi @chauduyphanvu ,

No, we can't see any error logged in the console. Directly, initialize method is getting called.

**Comment by hani09876** [comment]
> Hi @chauduyphanvu ,
> 
> No, we can't see any error logged in the console. Directly, initialize method is getting called.


Please make sure that applovin max has a support for using on godot game engine.
