### ISSUE TITLE
Custom Adapter: Unable to pass custom rewards through custom adapter APIs

### ISSUE THREAD

**Issue by pm-preety-narvekar** [AppLovin/AppLovin-MAX-SDK-Android#243]
Hello Team,

I have created custom adapter for a network for rewarded ad formats and it is working fine. I am able to render an ad coming from a custom network through my custom adapter. 

However, while calling `onUserRewarded` API of `MaxRewardedAdapterListener` I want to pass the reward received by my custom network to MAX's system. So I tried to convert the custom reward into `MaxReward`, but there is no API for it. I checked other adapters in this repository including custom adapters, but all are passing MAX's rewards itself, like:
```
MaxReward reward = getReward(); // Public API of MediationAdapterBaseClass
rewardedListener.onUserRewarded(reward);
```
On the other hand, in iOS MAX SDK, I can pass the custom reward using the API:
```
@property (nonatomic, weak) id<MARewardedAdapterDelegate> rewardedDelegate;

MAReward *maReward = [MAReward rewardWithAmount:reward.amount.integerValue label:reward.currencyType];
[self.rewardedDelegate didRewardUserWithReward:maReward];
```
And this custom reward is also being passed to the end user.

Could you help me to achieve the same in Android? Also, is it expected to pass MAX's rewards through custom adapter (like other adapters)? If yes, where to configure those, as I couldn't see any option while adding the network.

Thanks in advance for yor help!!

**Comment by chauduyphanvu** [comment]
@pm-preety-narvekar, thanks for the feedback. We will look into this and circle back with any updates.

Vu Chau
AppLovin Team

**Comment by pm-preety-narvekar** [comment]
Hi @chauduyphanvu,

I found the API to convert the custom rewards into MAX's rewards and pass them to MAX's system. The same are also getting passed to the user.

I also checked the other adapters, but most of them are using `final MaxReward reward = getReward();` and passing the same reward to MAX SDK. Are we also supposed to do the same? If yes, where to configure rewards for custom ad networks on MAX's portal?

**Comment by pm-preety-narvekar** [comment]
hi @chauduyphanvu 

Can you help with this please?

**Comment by thomasmso** [comment]
In your rewarded ad's Ad Unit page:
![image](https://user-images.githubusercontent.com/5104410/164168436-60919a43-6892-4927-a2d0-91226d863199.png)

**Comment by pm-preety-narvekar** [comment]
Thanks @thomasmso for your quick response. This will help us.
