### ISSUE TITLE
Error while jetifying smaato adapter 

### ISSUE THREAD

**Issue by isntaname** [AppLovin/AppLovin-MAX-SDK-Android#244]
Hello,

I'm trying to add Smaato to my app using the integration manager, but these errors occured (attached below).
Also I've tried to blacklist those .aar's but another bunch of errors occured. 
        
Any help appreciated. 
Thanks!

`
   > Failed to transform artifact 'com.smaato.android.sdk.module-core-light-21.7.3.aar (:com.smaato.android.sdk.module-core-light-21.7.3:)' to match attributes {artifactType=android-manifest}
      > Execution failed for JetifyTransform: /Users/isnotaname/Documents/UnityProjects/darkness/Temp/gradleOut/unityLibrary/libs/com.smaato.android.sdk.module-core-light-21.7.3.aar.
         > Failed to transform '/Users/isnotaname/Documents/UnityProjects/darkness/Temp/gradleOut/unityLibrary/libs/com.smaato.android.sdk.module-core-light-21.7.3.aar' using Jetifier. Reason: null. (Run with --stacktrace for more details.)
   > Failed to transform artifact 'com.smaato.android.sdk.module-richmedia-21.7.3.aar (:com.smaato.android.sdk.module-richmedia-21.7.3:)' to match attributes {artifactType=android-manifest}
      > Execution failed for JetifyTransform: /Users/isnotaname/Documents/UnityProjects/darkness/Temp/gradleOut/unityLibrary/libs/com.smaato.android.sdk.module-richmedia-21.7.3.aar.
         > Failed to transform '/Users/isnotaname/Documents/UnityProjects/darkness/Temp/gradleOut/unityLibrary/libs/com.smaato.android.sdk.module-richmedia-21.7.3.aar' using Jetifier. Reason: null. (Run with --stacktrace for more details.)
   > Failed to transform artifact 'com.smaato.android.sdk.module-video-21.7.3.aar (:com.smaato.android.sdk.module-video-21.7.3:)' to match attributes {artifactType=android-manifest}
      > Execution failed for JetifyTransform: /Users/isnotaname/Documents/UnityProjects/darkness/Temp/gradleOut/unityLibrary/libs/com.smaato.android.sdk.module-video-21.7.3.aar.
         > Failed to transform '/Users/isnotaname/Documents/UnityProjects/darkness/Temp/gradleOut/unityLibrary/libs/com.smaato.android.sdk.module-video-21.7.3.aar' using Jetifier. Reason: null. (Run with --stacktrace for more details.)
   > Failed to transform artifact 'com.smaato.android.sdk.smaato-sdk-21.7.3.aar (:com.smaato.android.sdk.smaato-sdk-21.7.3:)' to match attributes {artifactType=android-manifest}
      > Execution failed for JetifyTransform: /Users/isnotaname/Documents/UnityProjects/darkness/Temp/gradleOut/unityLibrary/libs/com.smaato.android.sdk.smaato-sdk-21.7.3.aar.
         > Failed to transform '/Users/isnotaname/Documents/UnityProjects/darkness/Temp/gradleOut/unityLibrary/libs/com.smaato.android.sdk.smaato-sdk-21.7.3.aar' using Jetifier. Reason: null. (Run with --stacktrace for more details.)
   > Failed to transform artifact 'com.smaato.android.sdk.smaato-sdk-banner-21.7.3.aar (:com.smaato.android.sdk.smaato-sdk-banner-21.7.3:)' to match attributes {artifactType=android-manifest}
      > Execution failed for JetifyTransform: /Users/isnotaname/Documents/UnityProjects/darkness/Temp/gradleOut/unityLibrary/libs/com.smaato.android.sdk.smaato-sdk-banner-21.7.3.aar.
         > Failed to transform '/Users/isnotaname/Documents/UnityProjects/darkness/Temp/gradleOut/unityLibrary/libs/com.smaato.android.sdk.smaato-sdk-banner-21.7.3.aar' using Jetifier. Reason: null. (Run with --stacktrace for more details.)
   > Failed to transform artifact 'com.smaato.android.sdk.smaato-sdk-in-app-bidding-21.7.3.aar (:com.smaato.android.sdk.smaato-sdk-in-app-bidding-21.7.3:)' to match attributes {artifactType=android-manifest}
      > Execution failed for JetifyTransform: /Users/isnotaname/Documents/UnityProjects/darkness/Temp/gradleOut/unityLibrary/libs/com.smaato.android.sdk.smaato-sdk-in-app-bidding-21.7.3.aar.
         > Failed to transform '/Users/isnotaname/Documents/UnityProjects/darkness/Temp/gradleOut/unityLibrary/libs/com.smaato.android.sdk.smaato-sdk-in-app-bidding-21.7.3.aar' using Jetifier. Reason: null. (Run with --stacktrace for more details.)
   > Failed to transform artifact 'com.smaato.android.sdk.smaato-sdk-interstitial-21.7.3.aar (:com.smaato.android.sdk.smaato-sdk-interstitial-21.7.3:)' to match attributes {artifactType=android-manifest}
      > Execution failed for JetifyTransform: /Users/isnotaname/Documents/UnityProjects/darkness/Temp/gradleOut/unityLibrary/libs/com.smaato.android.sdk.smaato-sdk-interstitial-21.7.3.aar.
         > Failed to transform '/Users/isnotaname/Documents/UnityProjects/darkness/Temp/gradleOut/unityLibrary/libs/com.smaato.android.sdk.smaato-sdk-interstitial-21.7.3.aar' using Jetifier. Reason: null. (Run with --stacktrace for more details.)
   > Failed to transform artifact 'com.smaato.android.sdk.smaato-sdk-native-21.7.3.aar (:com.smaato.android.sdk.smaato-sdk-native-21.7.3:)' to match attributes {artifactType=android-manifest}
      > Execution failed for JetifyTransform: /Users/isnotaname/Documents/UnityProjects/darkness/Temp/gradleOut/unityLibrary/libs/com.smaato.android.sdk.smaato-sdk-native-21.7.3.aar.
         > Failed to transform '/Users/isnotaname/Documents/UnityProjects/darkness/Temp/gradleOut/unityLibrary/libs/com.smaato.android.sdk.smaato-sdk-native-21.7.3.aar' using Jetifier. Reason: null. (Run with --stacktrace for more details.)
   > Failed to transform artifact 'com.smaato.android.sdk.smaato-sdk-rewarded-ads-21.7.3.aar (:com.smaato.android.sdk.smaato-sdk-rewarded-ads-21.7.3:)' to match attributes {artifactType=android-manifest}
      > Execution failed for JetifyTransform: /Users/isnotaname/Documents/UnityProjects/darkness/Temp/gradleOut/unityLibrary/libs/com.smaato.android.sdk.smaato-sdk-rewarded-ads-21.7.3.aar.
         > Failed to transform '/Users/isnotaname/Documents/UnityProjects/darkness/Temp/gradleOut/unityLibrary/libs/com.smaato.android.sdk.smaato-sdk-rewarded-ads-21.7.3.aar' using Jetifier. Reason: null. (Run with --stacktrace for more details.)`

**Comment by chauduyphanvu** [comment]
@isntaname, we've released a new adapter version (v[21.7.3.2](https://github.com/AppLovin/AppLovin-MAX-SDK-Android/commit/0da47d7cbda391d15f34034273803aa8f8ebfc70) | [Unity package](https://artifacts.applovin.com/unity/com/applovin/mediation/smaato-adapter/AppLovin-Smaato-Adapters-Android-21.7.3.2-iOS-21.7.1.3.unitypackage)) that references Smaato's older SDK that should work. Feel free to get it in the meantime if you need to use Smaato.

We'll continue working with Smaato on this issue.

**Comment by isntaname** [comment]
@chauduyphanvu, it works! Thanks!

**Comment by chauduyphanvu** [comment]
@isntaname, by the way we have released a newer adapter for Smaato 21.8.0 (latest SDK) and this new combination should work well with Unity. Feel free to upgrade and let us know if you run into any issues. Thanks.
