### ISSUE TITLE
Native ad Options view (aka privacy icon, aka AdChoices) should be two-toned with transparent background

### ISSUE THREAD

**Issue by talklittle** [AppLovin/AppLovin-MAX-SDK-Android#245]
Previously reported at #124

SDK version 11.3.0

The sharp corners look bad:

![Screenshot_20220314-175512](https://user-images.githubusercontent.com/87961/158285926-d35d2776-4b69-4a73-93b7-d0a2fc8df42c.jpg)

MoPub had a nice looking two-toned circular icon with transparency.

Also, test ads do not currently provide an Options view; they should.

**Comment by thomasmso** [comment]
@talklittle - We just released Android and iOS SDKs v11.3.1 with an updated privacy icon.
![image](https://user-images.githubusercontent.com/5104410/159113818-f7480355-b457-47f9-80ed-2118c20eba43.png)

**Comment by talklittle** [comment]
SDK 11.3.1 privacy icon looks great. Thank you for the quick fix!

I will follow issue #209 regarding missing privacy icon and ad images, when using Native Manual test mode.

**Comment by clevsh** [comment]
Please revert the icon from version 11.3.0.
In our app, the former non-transparent version is cleaner and better.
Please make an option to choose the type of icon.

**Comment by talklittle** [comment]
@clevsh Since it's a native ad, can't you just add an opaque view behind it?

**Comment by clevsh** [comment]
[ Privacy Icon - AppLovin SDK - 11.3.0 ]

![AppLovin_11_3_0](https://user-images.githubusercontent.com/48075086/159818191-ea8ade6f-441a-4755-8a27-26784d2f258d.png)

[ Privacy Icon - AppLovin SDK - 11.3.1 ]

![AppLovin_11_3_1](https://user-images.githubusercontent.com/48075086/159818202-62c8304f-7486-4f91-a2d0-3dc0be01b5e6.png)
