### ISSUE TITLE
Compose UI support

### ISSUE THREAD

**Issue by firefinchdev** [AppLovin/AppLovin-MAX-SDK-Android#249]
Hi,
It would be great if Applovin MAX SDK provides composables for banner, interstitials and native ads.

Since Compose UI is on its way to become defacto way to create Android UIs, creating composables would increase Applovin MAX SDK's overall reach to its users.

Creating composables is not an expensive task in terms of dev work, and a standard Composable by Applovin themselves will be really useful for its users (developers). 

Also, doing so will will eliminate all the error prone implementations currently implemented by developer themselves.

Thanks.

**Comment by chauduyphanvu** [comment]
@firefinchdev, thanks for the note. I've relayed your request to the rest of the team, and will update this thread once we have the support. Thanks.

Vu Chau
AppLovin Team

**Comment by firefinchdev** [comment]
Okay thanks
