### ISSUE TITLE
Clarification regarding the applovin apps

### ISSUE THREAD

**Issue by nihp** [AppLovin/AppLovin-MAX-SDK-Android#251]
I have some clarifications regarding the applovin.

1. AppLovin has a key
2. Does this has the native interstitial ids separately or for each apps there is a key alone?

**Comment by NanaAmoah** [comment]
Hi @nihp, there is one [Applovin SDK key](https://dash.applovin.com/documentation/mediation/ios/getting-started/integration#add-the-sdk-key) per Applovin account and can be used in all the apps added in your AppLovin dashboard. 

This is different from [ad units](https://dash.applovin.com/documentation/mediation/max/integrate#create-ad-units), which you would create for each ad format you'd want to use. Each ad unit corresponds to a specific package name so you will only be able to load ads in apps if your package name matches the ad unit id in your app.

Please let me know if this clarifies your question.

**Comment by Luklek** [comment]
> Hi @nihp, there is one [Applovin SDK key](https://dash.applovin.com/documentation/mediation/ios/getting-started/integration#add-the-sdk-key) per Applovin account and should be used in all the apps added in your AppLovin dashboard.
> 
> This is different from [ad units](https://dash.applovin.com/documentation/mediation/max/integrate#create-ad-units), which you would create for each ad format you'd want to use. Each ad unit corresponds to a specific package name so you will only be able to load ads in apps if your package name matches the ad unit id in your app.
> 
> Please let me know if this clarifies your question.

In MoPub we could use the same Ad Unit in multiple packagenames. Is this not possible anymore in AppLovinMAX?

**Comment by NanaAmoah** [comment]
Hi @Luklek, no, we don't support using multiple package names for one ad unit.

**Comment by Luklek** [comment]
I see... less and less reason to switch to Applovin... a perfect example on how to acquire and destroy something good...

**Comment by nihp** [comment]
@NanaAmoah Thanks for your inputs.

Does the Native Ads will work for the android and iOS from AppLovin?

**Comment by NanaAmoah** [comment]
Yes @nihp, AppLovin supports native ads on iOS and Android.

**Comment by nihp** [comment]
@NanaAmoah Thanks for your input.

I am getting the SDK initialized value as below. But I have added my test devica and enabled the test mode. Still getting the test mode as the disabled state. Any thoughts on this?

The Ad Review is a mandatory or optional one to integrate for applovin.


[MediationDebuggerListAdapter] 
    ========== MEDIATION DEBUGGER ==========
    ========== APP INFO ==========
    Dev Build - true
    Test Mode - disabled
    Target SDK - 31
    ========== MAX ==========
    SDK Version - 11.3.0
    Plugin Version - None
    Ad Review Version - Disabled
    ========== PRIVACY ==========
    Age Restricted User - No value set
    Has User Consent - No value set
    "Do Not Sell" - No value set
    ========== NETWORKS ==========
    ---------- APPLOVIN_NETWORK ----------
    Status  - COMPLETE
    SDK     - 11.3.0
    Adapter - 11.3.0
    ---------- FACEBOOK_NETWORK ----------
    Status  - INCOMPLETE INTEGRATION
    SDK     - UNAVAILABLE
    Adapter - UNAVAILABLE
    ---------- GOOGLE_AD_MANAGER_NETWORK ----------
    Status  - INCOMPLETE INTEGRATION
    SDK     - UNAVAILABLE
    Adapter - UNAVAILABLE
    ---------- ADMOB_NETWORK ----------
    Status  - INCOMPLETE INTEGRATION
    SDK     - UNAVAILABLE
    Adapter - UNAVAILABLE
    ========== AD UNITS ==========
    ---------- Android Int ----------
    Identifier - Value
    Format     - Interstitial
AppLovinSdk: [MediationDebuggerListAdapter] 
    
    ---------- Android Native ----------
    Identifier - value
    Format     - Native
    ========== END ==========

**Comment by nihp** [comment]
@NanaAmoah Could you please let  me does this is a mandatory one , **you can access impression-level user revenue data on the client side**

Also, for native ads I am using the adapter file for showing the ads. Can I able to write this reurning of the ads in a onBindView holder method with the native manual ads.

I can ale to receive the ads in my logs, but it failed to display it in the view.

**Comment by NanaAmoah** [comment]
Hi @nihp, retrieving impression-level user revenue data is not mandatory. 

To clarify your second question, are you asking about native support for binding native ads in a feed ? Is this related to your issue [here](https://github.com/AppLovin/AppLovin-MAX-SDK-Android/issues/263#issue-1179624536) ? 

Also, the logs shared in your message above show that there was a successful connection to AL servers- prod-ms.applovin.com/1.0/event/load endpoint not necessarily that an ad was successfully loaded. Feel free to share [full verbose logs](https://dash.applovin.com/documentation/mediation/android/getting-started/advanced-settings#enable-verbose-logging) here and we can investigate your issue further.

**Comment by nihp** [comment]
I am trying to set the rendered value or ad in a viewholder.

 nativeAdLoader.loadAd(new MaxNativeAdView(binder, context)); // it will load the ads and I have a separate method to view the ads or set it in the viewholder. But unable to get this. It shows null value for me.

MaxNativeAdView nativeAdView;

 ```
public void onBindViewHolder(int position, NativeAdViewHolder viewHolder) {
                nativeAdLoader.loadAd();
                nativeAdView.getTitleTextView().setText("RRRRRR");
                nativeAdView.getAdvertiserTextView().setText("OOOOOOO");
});

**Comment by NanaAmoah** [comment]
Closing as duplicate: https://github.com/AppLovin/AppLovin-MAX-SDK-Android/issues/263#issuecomment-1079089705

**Comment by nihp** [comment]
@NanaAmoah Could you please confirm the Applovin has the Manual native ads support with the adapters same as the Mopub

 ```
ViewBinder viewBinder = new ViewBinder.Builder(R.layout.native_ad_mopub)
                    .mainImageId(R.id.ad_cover)
                    .iconImageId(R.id.brand_logo)
                    .titleId(R.id.ad_title)
                    .textId(R.id.ad_description)
                    .privacyInformationIconImageId(R.id.native_privacy_information_icon_image)
                    .addExtra(context.getResources().getString(R.string.sponsored), R.id.description)

staticNativeAdRenderer = new MoPubStaticNativeAdRenderer(viewBinder);

moPubNative = new MoPubNative((Activity) context, key, new MoPubNative.MoPubNativeNetworkListener() {
```

**Comment by nihp** [comment]
@NanaAmoah I am using the native maunal mopbub integration with my adapter file to show the native ads. https://developers.mopub.com/publishers/android/native-manual/.

Is there is any equivalent support for this in Applovin with in the recyclerview

**Comment by nihp** [comment]
@NanaAmoah Appreciate your inputs on this.

**Comment by nihp** [comment]
@NanaAmoah How the Admob and Meta will be integrated for the Applovin mediation networks.

**Comment by thomasmso** [comment]
@nihp - Due to the high volume of your requests, it might be better for you to email partner_support@applovin.com for further assistance. Please include your GitHub username in the topic for us to find you.
