### ISSUE TITLE
can i call init and load in sub thread?

### ISSUE THREAD

**Issue by xiaopei** [AppLovin/AppLovin-MAX-SDK-Android#253]

**Comment by xiaopei** [comment]
must AppLovinSdk.initializeSdk() be called on main thread?
must xxxAd.loadAd() be call on main thread?

**Comment by santoshbagadi** [comment]
Hi @xiaopei , apart from creating banners, you can run both `AppLovinSdk.initializeSdk()` and `loadAd` on a background thread.

Are you seeing any issues when doing so?

**Comment by xiaopei** [comment]
No yet,I just make sure
