### ISSUE TITLE
Applovin Bidding response for Banner and Native ad

### ISSUE THREAD

**Issue by BilalZurmati** [AppLovin/AppLovin-MAX-SDK-Android#255]
# Applovin Bidding response for Banner and Native ad
Hi
I have recently integrated Applovin in my apps and using it as a mediator with open biding for META Audience Network.
I found the issue in two Ad formats namely Banner and Native in perspective of Applovin Bidding response that is zero while Applovin exchange response is ok with these two Ad formats.
It is also observed that the interstitial ad format showing the proper response from both networks.
Please help me to understand that this issue is facing by everyone, if yes then when it could get fix by your team.

![applovin](https://user-images.githubusercontent.com/64932501/158958333-c3cdf4ed-2938-474c-92d9-7987633df31e.png)

**Comment by BilalZurmati** [comment]
@NanaAmoah Thank you soo much for the response, as I am new with the Applovin and actually I don't know much about Applovin and Applovin exchange, I mean is there any documentation or reference that will help me understand this completely.

**Comment by NanaAmoah** [comment]
You can find out more about AppLovin exchange [here](https://www.applovin.com/alx/) and ad exchanges in our glossary [here](https://www.applovin.com/glossary/ad-exchange/) and on our blog [here](https://www.applovin.com/blog/what-is-an-ad-exchange/?_ga=2.139950899.1432796429.1647625423-1485113175.1631038649&_gac=1.86150762.1646264480.CjwKCAiAyPyQBhB6EiwAFUuakpAm-D0t2fAvWPNAhYNEzGmt2dlS0eyr8Cd0u33PXR8Yy4tBcPioBBoCOcQQAvD_BwE).  Thanks!
