### ISSUE TITLE
Ad INTER easy to press wrong

### ISSUE THREAD

**Issue by hoanghiephui** [AppLovin/AppLovin-MAX-SDK-Android#256]
Hi team,
Please re-evaluate the INTER ad close button. It is very easy for users to mistakenly click on the advertising content.

Thanks

**Comment by 1008k** [comment]
Hello. I agree with you.
Applovin's full screen ads clearly have too high a CTR compared to other networks.
There is a high possibility that users are accidentally clicking multiple times, which is stressful for the user and makes no sense for the advertiser.

In addition, it would be great if ould provide a setting that would allow us to choose the time before skipping and the type of creative.

**Comment by edgunn** [comment]
I also agree this is a problem. Additionally, when a postitial is displayed, the top right counter indicator/ad close button disappears completely for a few seconds, seemingly in an attempt to fool users into clicking on the ad.
This reflects poorly on the app and the MAX platform

**Comment by thomasmso** [comment]
GitHub issues should be reserved for technical issues. Issues relating to ad UX can be addressed in partner_support@applovin.com. Thanks.
