### ISSUE TITLE
Memory leak with Google AdMob native ads if Activity destroyed during load

### ISSUE THREAD

**Issue by talklittle** [AppLovin/AppLovin-MAX-SDK-Android#257]
Affects GoogleMediationAdapter 20.6.0.3

Example of how it should look:

https://github.com/googleads/googleads-mobile-android-examples/blob/154ea499b5092f9f4eb2642ecb63c791917ef197/java/admob/NativeAdvancedExample/app/src/main/java/com/google/example/gms/nativeadvancedexample/MainActivity.java#L204-L214

GoogleMediationAdapter needs additional checks like:

```
if ( activity.isDestroyed() || activity.isFinishing() || activity.isChangingConfigurations() )
{
    listener.onNativeAdLoadFailed( MaxAdapterError.INVALID_LOAD_STATE );
    nativeAd.destroy();
    return;
}

```

**Comment by joeapplovin** [comment]
Thanks @talklittle !  We'll fix this soon.

**Comment by joeapplovin** [comment]
Fixed by https://github.com/AppLovin/AppLovin-MAX-SDK-Android/commit/318ac9ff182dd79eb4882f4731a064bada8b782c
