### ISSUE TITLE
Start App crash

### ISSUE THREAD

**Issue by RunningTheSnail** [AppLovin/AppLovin-MAX-SDK-Android#258]
applovin sdk version : v11.3.0

Caused by java.lang.NullPointerException
Attempt to invoke virtual method 'java.lang.String java.io.File.getPath()' on a null object reference
safedk_App_onCreate_6b26f7a522d7cf7c19dfc75ed3dfb5e7 (App.java:28)

**Comment by joeapplovin** [comment]
Hi @RunningTheSnail - do you have the full stacktrace of this crash?

**Comment by RunningTheSnail** [comment]
![image](https://user-images.githubusercontent.com/13128088/159272787-caf65c07-5b75-419f-a199-470707d14d9d.png)

**Comment by thomasmso** [comment]
There's nothing here that indicates the crash is related to the AppLovin MAX SDK. Ad Review simply wraps around the `Application`'s onCreate() call but the actual crash is within your implementation.
