### ISSUE TITLE
onNativeAdLoaded Method returns MaxNativeAdView always null while live ads Load

### ISSUE THREAD

**Issue by VineshChauhan24** [AppLovin/AppLovin-MAX-SDK-Android#259]
@Override
            public void onNativeAdLoaded(final MaxNativeAdView nativeAdView, final MaxAd ad)
            {
                // Clean up any pre-existing native ad to prevent memory leaks.
                Log.d("AppLovin_SDKCHECK","FROMMAIN_NATIVE_Success");
                if ( nativeAdLoader != null )
                {
                    nativeAdLoader.destroy( nativeAdApplovin );
                }
                tvNavAds.setVisibility(View.GONE);
                // Save ad for cleanup.
                nativeAdApplovin = ad;

                // Add ad view to view.
                nativeAdContainer.removeAllViews();
                nativeAdContainer.addView( nativeAdView );//crashed Here
            }

While I trie with Testing Device is Working fine, But When App Got Live on Playstore we got Crash Report like Below

E/AppLovinSdk: [ListenerCallbackInvoker] Unable to notify ad event listener about native ad being loaded
    java.lang.IllegalArgumentException: Cannot add a null child view to a ViewGroup
        at android.view.ViewGroup.addView(ViewGroup.java:4966)
        at android.view.ViewGroup.addView(ViewGroup.java:4948)
        at com.cleanspkrwater.speakerdustremover.activities.MainActivity$2.onNativeAdLoaded(MainActivity.java:225)
        at com.applovin.impl.sdk.utils.j$20.run(Unknown Source:6)
        at android.os.Handler.handleCallback(Handler.java:873)
        at android.os.Handler.dispatchMessage(Handler.java:99)
        at android.os.Looper.loop(Looper.java:226)
        at android.app.ActivityThread.main(ActivityThread.java:7178)
        at java.lang.reflect.Method.invoke(Native Method)
        at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:503)
        at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:942)

I have used below line to implement

    implementation 'com.applovin:applovin-sdk:+'
    implementation 'com.applovin.mediation:facebook-adapter:6.8.0.12'

**Comment by chauduyphanvu** [comment]
@VineshChauhan24, with which ad network(s) are you seeing the above issue? Also, do you have an ad unit ID that we can borrow to reproduce the issue? Thanks.

**Comment by santoshbagadi** [comment]
@VineshChauhan24  could you also provide if you are using a template or custom native ads. Could you also share your integration code around loading the native ad.

**Comment by VineshChauhan24** [comment]
@santoshbagadi I am Using Template Native Ads

**Comment by VineshChauhan24** [comment]
@santoshbagadi i use below code

**Comment by VineshChauhan24** [comment]
@chauduyphanvu  i have used Facebook(meta) Mediation with AppLovin and here is my Unit ID - ba213e1892b4cb7c

**Comment by nihp** [comment]
In my app I only have the Applovin alone. Does this works for me to show the ads from the applovin network?

**Comment by chauduyphanvu** [comment]
@VineshChauhan24 - it looks like **ba213e1892b4cb7c** is a "manual" ad unit ID, while you said you were using template. Could you check again and make sure the ad unit ID and the code match the use case (both must be template **or** both must be manual)?

**Comment by chauduyphanvu** [comment]
> In my app I only have the Applovin alone. Does this works for me to show the ads from the applovin network?

Yes. If you plan to show ads from other ad networks, you can use mediation: https://dash.applovin.com/documentation/mediation/android/mediation-adapters.

**Comment by VineshChauhan24** [comment]
@chauduyphanvu  Okay Let me check from My Side once

**Comment by VineshChauhan24** [comment]
@chauduyphanvu  i have set Manual native but gettign below Error in loag ads loads but media container is Black(blank)

Unable to open content: file:///data/user/0/<apppakcge>/files/al/00ec11e8-da68-4277-92ec-93f05b65596b5fc0cc169f705.jpg
    java.io.FileNotFoundException: /data/user/0/<apppakcge>/files/al/00ec11e8-da68-4277-92ec-93f05b65596b5fc0cc169f705.jpg: open failed: ENOENT (No such file or directory)

**Comment by nihp** [comment]
I am also getting the above error in device.

**Comment by chauduyphanvu** [comment]
Yes we are working on fixing that issue. Will update this thread once it's resolved.

**Comment by VineshChauhan24** [comment]
@chauduyphanvu  now Native ads stop loading completely
