### ISSUE TITLE
can we use a id of textview when call setCallToActionButtonId？

### ISSUE THREAD

**Issue by xiaopei** [AppLovin/AppLovin-MAX-SDK-Android#262]
when I use manual native ad ,and set a id of textview in setCallToActionButtonId,
it throwes a Exception java.lang.ClassCastException: android.widget.TextView cannot be cast to android.widget.Button.
but，there are some problems about ui and focus when we use a button。case TextView is parent of Button，can we change the class of CallToAction?

**Comment by chauduyphanvu** [comment]
@xiaopei - thanks for the feedback. We'll see what can be done here. Stay tuned!
