### ISSUE TITLE
How to show the native ads in a recyclerview view with position 3 , 6, 9, etc..

### ISSUE THREAD

**Issue by nihp** [AppLovin/AppLovin-MAX-SDK-Android#263]
I have a list of feeds like facebook, I need to show the ads in in-between the feeds. I have a adapter file and the views are not adding in the list as expected from the applovin native ads.

**Comment by santoshbagadi** [comment]
Hi @nihp , could you please share more details, like screenshots, [verbose logs](https://dash.applovin.com/documentation/mediation/android/getting-started/advanced-settings#enable-verbose-logging), and more details of what exactly the issue is. Are you using native template or custom ads? It would also be helpful if you could share a sample project or integration code that is leading to the issue.

**Comment by nihp** [comment]
I am using the Native Manual Ads. I am creating the view in my adapter file. Here I can't  able to add the View.

My code is as below
```

private MaxNativeAdLoader nativeAdLoader;
    private MaxAd loadedNativeAd;
private AppLovinNativeAd applovinNative;

 MaxNativeAdViewBinder binder = new MaxNativeAdViewBinder.Builder( R.layout.native_ad_applovin )
                    .setTitleTextViewId( R.id.sponsor )
                    .setBodyTextViewId( R.id.body_text_view )
                    .setAdvertiserTextViewId( R.id.advertiser_textView )
                    .setIconImageViewId( R.id.icon_image_view )
                    .setMediaContentViewGroupId( R.id.media_view_container )
                    .setCallToActionButtonId( R.id.ad_action )
                    .build();
            nativeAdLoader.loadAd(new  MaxNativeAdView(binder, context));
            View adView = createContentAdCarrier(context, bundle,new  MaxNativeAdView(binder, context));
            new  MaxNativeAdView(binder, context).addView(adView);
            new  MaxNativeAdView(binder, context).removeAllViews();
            adView.forceLayout();
            nativeAdLoader.setNativeAdListener( new MaxNativeAdListener() {
                @Override
                public void onNativeAdLoaded(final MaxNativeAdView nativeAdView, final MaxAd nativeAd)
                {
                    // Clean up any pre-existing native ad to prevent memory leaks.
                    System.out.println("nativeAd22 == " +nativeAd);
                    System.out.println("nativeAdView == " +nativeAdView);
                    System.out.println("getBodyTextView ==" + (CharSequence)  nativeAdView.getBodyTextView().toString());
                    System.out.println("getAdvertiserTextView ==" + (CharSequence) nativeAdView.getAdvertiserTextView().toString());
                    System.out.println("getIconImageView ==" + (CharSequence) nativeAdView.getIconImageView().toString());

                    if ( loadedNativeAd != null ) {
                        nativeAdLoader.destroy( loadedNativeAd );
                    }

                    // Save ad for cleanup.
                    loadedNativeAd = nativeAd;
                    NativeAd ad = new NativeAd(context); // THIS IS ONE OF MY CLASS 
                    ad.setRealAdProvider(new NativeAd.RealAdViewProvider() {   ///HERE BY WHICH MAXLISTENER I WILL GET THE VIEWHOLDER. 
                        @Override
                        public void onBindViewHolder(int position, NativeAdViewHolder viewHolder) {
                            viewHolder.sponsor.setText((CharSequence) nativeAdView.getTitleTextView());
                            viewHolder.title.setText((CharSequence) nativeAdView.getBodyTextView());
                            viewHolder.card.setCardBackgroundColor(Integer.parseInt("#000000"));
                            viewHolder.container.addView(nativeAdView);
                            nativeAdView.setMinimumHeight(300);
                            nativeAdView.setMinimumWidth(300);
                        }

                        @Override
                        public int getItemViewType() {
                            return APPLOVIN;
                        }

                        @Override
                        String getProviderName() {
                            return "APPLOVIN_NETWORK";
                        }

                        @Override
                        public Object getRealNativeAd() {
                            return applovinNative;
                        }
                    });
                    //nativeAdContainerView.findViewById(R.id.media_view_container);
                    //nativeAdContainerView.removeAllViews();
                    //nativeAdContainerView.addView( nativeAdView );

                }



                @Override
                public void onNativeAdLoadFailed(String adUnitId, final MaxError error)
                {
                 
                    System.out.println("error.getmessage ==" + error.getMessage());
              
                    // Native ad load failed.
                    // AppLovin recommends retrying with exponentially higher delays up to a maximum delay.
                }

                @Override
                public void onNativeAdClicked(final MaxAd nativeAd) { }
            } );

```

**Comment by santoshbagadi** [comment]
Hi @nihp , it looks like you are trying to get the assets from an already rendered native ad and then re-adding them to your own view. You can just add the fully rendered `nativeAdView` that is provided in `onNativeAdLoaded` to your recycler view. You can have a placeholder in your `viewHolder` and just add the `nativeAdView` to it.

**Comment by santoshbagadi** [comment]
Hi @nihp , the `MaxNativeAdView` would already be rendered, so, you can just add it into your view hierarchy without updating the asset views.

**Comment by nihp** [comment]
Are you mentioning the MaxNativeAdView will have all the values. So I don't want to set the viewholder again.

But the view needs to replace by the maxadview correct? Otherwise how the list will be shown as expected in UI?

**Comment by nihp** [comment]
@santoshbagadi I think the issue is related with the thread https://github.com/AppLovin/AppLovin-MAX-SDK-Android/issues/151

**Comment by terry-thz** [comment]
hi @santoshbagadi, You can have a placeholder in your viewHolder and just add the nativeAdView to it. In this way, the recycleview will be stuck during the sliding process. How to optimize and process?

**Comment by nihp** [comment]
@terry-thz Does the placeholder in the viewholder shows the ads view for you?

**Comment by terry-thz** [comment]
> @terry-thz Does the placeholder in the viewholder shows the ads view for you?

Yes.The code adds MaxNativeAdView in onBindViewHolder,for example:
           MaxNativeAdView localAdView = mRecycleViewLoader.getLocalAdView(position);
            if (localAdView != null) {
                ViewGroup parent = (ViewGroup) localAdView.getParent();
                if (parent != null) {
                    parent.removeView(localAdView);
                }
                parseAdView(localAdView);
                adContainer.addView(localAdView);
                return;
            }

**Comment by nihp** [comment]
Could you please let me how the adContainer variable is declared?

**Comment by nihp** [comment]
@terry-thz Did you able to render the ads in the recyclerview from max applovin?

**Comment by thomasmso** [comment]
Android Ad Placer API is live, please check out the docs here: https://dash.applovin.com/documentation/mediation/android/getting-started/native-ad-placer, and demo implementation here: https://github.com/AppLovin/AppLovin-MAX-SDK-Android/pull/338
