### ISSUE TITLE
The Native Ad-Type is getting issue with error log: onNativeAdLoadFailed  from 25-Mar-2022

### ISSUE THREAD

**Issue by wanwan1910** [AppLovin/AppLovin-MAX-SDK-Android#268]
Hello guys,
Could you please check the **Native Ad-Type** today 25-March-2022?
I believe something went wrong.  The Native and Native Banner no impression today. I've checked with another guy, who is using MAX Applovin, he confirmed he get the same issue.

**Error log:**
2022-03-25 12:20:29.548 27902-27902/? D/vla: onNativeAdLoadFailed: MaxError{code=-5001, message='Both template and native ad view are null. Please select a template in the dashboard or provide a MaxNativeAdView when loading the ad to render the native ad.'}

![image](https://user-images.githubusercontent.com/9217414/160060869-c9dd715c-6bf8-4dac-8910-9a1b14949b66.png)

**Comment by wanwan1910** [comment]
I am using MAX Applovin to bidding with Meta network.
Here is the Meta's performance chart of last 24 hours:
![image](https://user-images.githubusercontent.com/9217414/160061235-7d5d9083-644a-4d97-bfed-83f98253f384.png)


Native and Native Banner type are getting down to 0 impression.  It happens from 00h00 25-March-2022  GMT

**Comment by twp520** [comment]
hi，i'm also have this problem，do you know how to fix ？

**Comment by santoshbagadi** [comment]
Hi @wanwan1910 , @twp520 , we are investigating the issue right now. Could you please provide the MAX ad units that are currently affected.

**Comment by apshard** [comment]
I can confirm this issue. We see the same
![fb_issue](https://user-images.githubusercontent.com/97424424/160163677-e8878473-17d3-4120-9fc0-054b621d7936.png)
.

**Comment by wanwan1910** [comment]
> Hi @wanwan1910 , @twp520 , we are investigating the issue right now. Could you please provide the MAX ad units that are currently affected.

Native Ad Unit Type - Medium template

**Comment by santoshbagadi** [comment]
@wanwan1910 , the issue should now be fixed. Please let us know if you are still seeing the issue.

**Comment by twp520** [comment]
@santoshbagadi  thanks，now ，native ad impression good。
