### ISSUE TITLE
banner callback

### ISSUE THREAD

**Issue by LiuZhiDaa** [AppLovin/AppLovin-MAX-SDK-Android#27]
Why does the banner type call onAdDisplayed immediately after loading successfully?

**Comment by thomasmso** [comment]
`onAdDisplayed()` is called when some mediated SDK considers that their banner ad has shown - this can either correspond to you actually displaying the ad, or simply loading the ad. Please let me know if you have any other questions.

**Comment by LiuZhiDaa** [comment]
I turned on the test mode, but the error code 204 is still returned when I request an advertisement, only the banner is a successful request

**Comment by thomasmso** [comment]
This seems to be a known issue with our test mode that we hope to resolve by the end of this week.
