### ISSUE TITLE
Impression rate is very low for all networks in MAX

### ISSUE THREAD

**Issue by silane-tech** [AppLovin/AppLovin-MAX-SDK-Android#270]
Impression rate for all networks is very low after moving to Applovin MAX. I was expecting it'd get better in one month or so but now it nearly 3 months that I have moved to MAX but still the impression rate have not improved a bit. 
Below is the screenshot of last 15-16 hours data.
![image](https://user-images.githubusercontent.com/100225475/160096782-49477623-e791-48b7-8dcd-e7f3750a3c42.png)

**Comment by maxakash** [comment]
Hey @silane-tech Did your impressions from Facebook reduce in the last few hours?
Mine have reduced significantly.

**Comment by silane-tech** [comment]
No one bothers to respond, Wow!
Thank you for this great support.

**Comment by thomasmso** [comment]
Please email partner_support@applovin.com. Our GitHub issues are related to technical issues. Thanks.
