### ISSUE TITLE
Impressions from Facebook network has stopped

### ISSUE THREAD

**Issue by maxakash** [AppLovin/AppLovin-MAX-SDK-Android#271]
From last few hours, my app is getting almost no impressions from Facebook network.
Please look into this ASAP.

@thomasmso

**Comment by santoshbagadi** [comment]
Hi @maxakash , we are investigating the issue right now. Could you please provide the MAX ad unit ID with the issue? Do you also know a specific time when the issue started happening? Also to confirm, is this native template ad or native manual?

**Comment by maxakash** [comment]
Hi @santoshbagadi It started around 13:00 Facebook reporting time. MAX ad unit ids are 23f741f42327c3ba and abe75d7739a5fd4f

**Comment by santoshbagadi** [comment]
@maxakash , the issue should now be fixed. Please let us know if you still see the issue happening.

**Comment by maxakash** [comment]
@santoshbagadi The issue seems to be fixed now.  But what about the revenue that is lost?
This is very unethical.
