### ISSUE TITLE
Impression rate is very low for all networks in MAX

### ISSUE THREAD

**Issue by HarshaliSachani** [AppLovin/AppLovin-MAX-SDK-Android#272]
Impression rate for all networks is very low in Applovin MAX. I have integrated following ads networks.
Please look into this ASAP.
![AdsNetwork](https://user-images.githubusercontent.com/84327237/160172280-461cc402-a3aa-4a5b-8889-22af53ea8f52.png)

**Comment by thomasmso** [comment]
Our GitHub issues should be reserved for technical issues only - please email partner_support@applovin.com for this request instead. Thanks.
