### ISSUE TITLE
Applovin Max Native Ad impressions Stopped

### ISSUE THREAD

**Issue by kruguerjo** [AppLovin/AppLovin-MAX-SDK-Android#273]
Hello guys,

 Yesterday around 21:00 utc+1, Impressions from Applovin Max has stopped, this is the ad unit 894415bd856e22fe - Medium template. Thanks in advance for the support!

**Comment by Rohan487** [comment]
@kruguerjo yes I have same issue I already reported to applovin team waiting for reply

It is surely from applovin side I think

**Comment by kruguerjo** [comment]
> @kruguerjo yes I have same issue I already reported to Applovin team waiting for reply
> 
> It is surely from Applovin side I think

I really don't know the reason why?, it wasn't working well at first and then it worked for only few hours but the icon and main image is not showing up, and after that it stopped working!

**Comment by santoshbagadi** [comment]
@kruguerjo the issue should now be fixed. Please let us know if you are still seeing the issue.
