### ISSUE TITLE
Impression for native Ads are stopped and not working 

### ISSUE THREAD

**Issue by Rohan487** [AppLovin/AppLovin-MAX-SDK-Android#274]
Hello from past 24 hour Applovin native Ads with Facebook bidding is not working even not single impress is registered in facebook statistics

It is causing us a big revenue loss I request team to solve this issue.

**Comment by kruguerjo** [comment]
> Hello from past 24 hour Applovin native Ads with Facebook bidding is not working even not single impress is registered in facebook statistics
> 
> It is causing us a big revenue loss I request team to solve this issue.

did you see any native ad statistic in Applovin max dashboard

**Comment by Rohan487** [comment]
My Ad unit I'd which is affected is 

e25ad77951431efb

Please fix asap

**Comment by santoshbagadi** [comment]
Hi @Rohan487 , we are actively investigating this issue. We'll post an update here when the issue is fixed.

**Comment by santoshbagadi** [comment]
@Rohan487 the issue should now be fixed. Please let us know if you are still see the issue.

**Comment by thomasmso** [comment]
This should've been fixed a while ago. Please feel free to re-open if that is not the case.
