### ISSUE TITLE
How to check  GDPR consent is obtained or Not?

### ISSUE THREAD

**Issue by TariqMahmud** [AppLovin/AppLovin-MAX-SDK-Android#277]
How to check if user is not agree and he just dismissed the dialog without any consent?

AppLovinUserService userService = AppLovinSdk.getInstance( this ).getUserService();
userService.showConsentDialog( activity, new AppLovinUserService.OnConsentDialogDismissListener() {
    @Override
    public void onDismiss()
    {
        …
    }
} );

**Comment by santoshbagadi** [comment]
Hi @TariqMahmud , you can use `AppLovinPrivacySettings.hasUserConsent(Context)` to get the consent value. 

```
public void onDismiss()
{
    if ( AppLovinPrivacySettings#hasUserConsent() )
    {
        ...
    }
    else
    {
        ...
    }
}
```

We also have `AppLovinPrivacySettings.isUserConsentSet(Context)` to check whether or not the consent value is set at all.

**Comment by clee2005** [comment]
@TariqMahmud Thanks for this.   I cannot find any sample or additional documentation for AppLovinUserService.   At this point I cannot even figure out what the import namespace is for this.

**Comment by clee2005** [comment]
@TariqMahmud Thanks for this.   What other functions are available for consent?  What about something like IsConsentRequired()   I can't find any other documentation.   What about for iOS as well?   Thanks!

**Comment by santoshbagadi** [comment]
@clee2005 , you can find more information in the following docs: 

[Android Privacy docs](https://dash.applovin.com/documentation/mediation/android/getting-started/privacy#privacy)
[iOS Privacy Docs](https://dash.applovin.com/documentation/mediation/ios/getting-started/privacy#privacy)
[iOS Consent Flow Docs](https://dash.applovin.com/documentation/mediation/ios/getting-started/consent-flow)

**Comment by clee2005** [comment]
@santoshbagadi Thanks for the reply (I had tagged the wrong person in my previous message)!    I had seen those documents, but I was looking for more documentation as you had mentioned functions like isUserConsentSet() and hasUserConsent() which I was unable to find anywhere except for here.

**Comment by santoshbagadi** [comment]
Here are the Obj-C snippets you requested: `[ALPrivacySettings isUserConsentSet]` and `[ALPrivacySettings hasUserConsent]`
