### ISSUE TITLE
MaxRewardedAd show Error 

### ISSUE THREAD

**Issue by xiaopei** [AppLovin/AppLovin-MAX-SDK-Android#279]
The rewardedAd did not show when i  continually request and show the same unitId.

#onAdDisplayed： errorCode -23 , Attempting to show ad when another fullscreen ad is already showing

**Comment by joeapplovin** [comment]
Hi @xiaopei - are you making the subsequent request after onAdHidden has been fired similar to the [rewarded documentation](https://dash.applovin.com/documentation/mediation/android/getting-started/rewarded-ads)?

**Comment by thomasmso** [comment]
Please refer to the documentation above on how to properly manage a rewarded ad's lifecycle.
