### ISSUE TITLE
app crash while loading applovin native ad

### ISSUE THREAD

**Issue by FTW-Khushal** [AppLovin/AppLovin-MAX-SDK-Android#281]
![device-2022-03-28-155952](https://user-images.githubusercontent.com/59960215/160380256-a67b7104-15b4-43ad-94b8-2e7d8533e0c7.png)

I have implemented applovin native ad (manual) with Facebook mediation.
Applovin test ads are working fine in debug apk but in live app it was crashing app
i also attached an screenshot of an error 

I tried to debug the problem myself and it's look like all the ads which come from applovin works well but because I have facebook mediation when applovin try to load facebook ads it was crashing the whole app

 I found my app was crashing in below method of applovin sdk
`public void onNativeAdLoaded(final MaxNativeAdView nativeAdView, final MaxAd ad)`
because `nativeAdView `is null

I'm using `implementation 'com.google.ads.mediation:applovin:11.2.2.0'`
and yes also tried the latest version and this ` implementation("com.applovin:applovin-sdk:+@aar")` too

**Comment by santoshbagadi** [comment]
Hi @FTW-Khushal , what version of Facebook mediation adapter are you using. Could you please try updating to the latest FB adapter and see if you still see the issue.
