### ISSUE TITLE
native ads

### ISSUE THREAD

**Issue by abhi9177** [AppLovin/AppLovin-MAX-SDK-Android#283]
after implementing native ads,im getting 'onNativeAdLoaded' overrides nothing error
 override fun onNativeAdLoaded(nativeAdView: MaxNativeAdView, ad: MaxAd)
if i downgrage applovin sdk to 11.0.0 error is solved
if i use lateset sdk 11.3.1 again i get this error how to fix

**Comment by santoshbagadi** [comment]
Hi @abhi9177 , we have made the `nativeAdView` returned in `onNativeAdLoaded` `nullable` starting SDK version 11.2.0. So, you need to mark `nativeAdView` as optional for it to work. 

We'll update our docs to reflect the same.

**Comment by abhi9177** [comment]
Ok thanks
