### ISSUE TITLE
Auto eCPM not working for Admob

### ISSUE THREAD

**Issue by maxakash** [AppLovin/AppLovin-MAX-SDK-Android#285]
I have entered $2 as eCPM for my Admob native ad unit id.  It has been a month and still I can see in reports that eCPM of Admob is still $2. That means auto eCPM is not working.

Also is Admob going to be added as bidding network in the future?

Please look into it.

@thomasmso

**Comment by thomasmso** [comment]
Please ensure that you have AdMob connected under MAX -> Mange -> Network.

For eCPM values to show up, we need enough impressions otherwise it will continue to default to whatever was manually entered.

We do not have any updates or comments re: AdMob bidding.

**Comment by maxakash** [comment]
> Please ensure that you have AdMob connected under MAX -> Mange -> Network.
> 
> For eCPM values to show up, we need enough impressions otherwise it will continue to default to whatever was manually entered.
> 
> We do not have any updates or comments re: AdMob bidding.

Hey Thomas
I have already connected Admob in networks. I get around 50000 ad requests daily from Admob. I think this number should be enough for auto cpm to kick in.

**Comment by richashukla23** [comment]
@maxakash Do you mind sharing the email associated with your account so that I can take a look in detail?

**Comment by maxakash** [comment]
> @maxakash Do you mind sharing the email associated with your account so that I can take a look in detail?

Yes its akashchaudharymax@gmail.com
