### ISSUE TITLE
Not loading Interstitial ads Live as well as Testing

### ISSUE THREAD

**Issue by chandankrs2022** [AppLovin/AppLovin-MAX-SDK-Android#286]
[MaxInterstitialAd] loadAd()
[MaxInterstitialAd] getActivity()
[MaxInterstitialAd] Loading ad for '3df3c501c90bb6af'...
[MaxInterstitialAd] Transitioning from IDLE to LOADING...
[MaxInterstitialAd] isReady() false for ad unit id 3df3c501c90bb6af

[MaxInterstitialAd] Handle ad loaded for regular ad: MediatedAd{thirdPartyAdPlacementId=inter_regular, adUnitId=3df3c501c90bb6af, format=INTER, networkName='AppLovin'}
[MaxInterstitialAd] Scheduling ad expiration 14399 seconds from now for 3df3c501c90bb6af...
[MaxInterstitialAd] Transitioning from LOADING to READY...

Note:-> Previously it was loading but now its not loading Interstitial ads . Could you please help me to come out this issue.

**Comment by nihp** [comment]
I think you have missing the ad.showAd(); in your method. Check that as well. 

I also faced the same. After adding the above it works fine

**Comment by chandankrs2022** [comment]
I am calling showAds()

interstitialAd = MaxInterstitialAd(getString(R.string.applovin_interstitial_id), requireActivity())
interstitialAd.setListener(this)
interstitialAd.loadAd()

if (interstitialAd.isReady) {
         interstitialAd.showAd()
  }
