### ISSUE TITLE
ManualNativeLateBindingAd Not loading images

### ISSUE THREAD

**Issue by SharkZXB** [AppLovin/AppLovin-MAX-SDK-Android#288]
When I was in use Demo loading ManualNativeLateBindingAd, text display, image did not show

**Comment by SharkZXB** [comment]
[blob:https://g76z6ro5rv.feishu.cn/c033031f-558b-4c85-873e-b0953a6d702b](url)

**Comment by SharkZXB** [comment]
[https://internal-api-drive-stream.feishu.cn/space/api/box/stream/download/all/boxcnpjLzr6DR6LBPPVsajdf99d/?mount_node_token=doccnKTAfwTwcgyPVFhXUeTKbBc&mount_point=doc_image](url)

**Comment by thomasmso** [comment]
Whilst native ads from AppLovin Exchange will have an image, MAX does not provide guarantees on mediated networks providing image assets.
