### ISSUE TITLE
Template Native ad banner image not loading

### ISSUE THREAD

**Issue by dhruvbhati10** [AppLovin/AppLovin-MAX-SDK-Android#291]
I setup everything in my Template Native ad as per the documentation, but the main image in medium native template ad was not loading. After looking at the demo app codes, I set my frame layout height from wrap_content to 300dp and then the image started showing. I recommend to put this on the documentation page or something so that they can also be informed about this.

**Comment by santoshbagadi** [comment]
Hi @dhruvbhati10 , thank you for reporting the issue. We'll look into documenting this. I'll update here when we updated the docs.
