### ISSUE TITLE
Memory leak risk in AmazonAdMarketplaceMediationAdapter

### ISSUE THREAD

**Issue by xsjmichael** [AppLovin/AppLovin-MAX-SDK-Android#293]
Hi, in my case, there's a MaxAdView in my Activity, after integrating amazon adapter, the code for MaxAdView is just as below, but when i open and close this Activity for multiple times, i found that the finished activity are not destroyed and they are referenced by AmazonAdMarketplaceMediationAdapter. Please let me know what's the problem and what should i do to avoid it. Thank you~

        var maxAdView: MaxAdView? = null
        val amazonAdSlotId = ******
        val adFormat: MaxAdFormat = MaxAdFormat.BANNER

        // Raw size will be 320x50 for BANNERs on phones, and 728x90 for LEADERs on tablets
        val rawSize = adFormat.size
        val size = DTBAdSize(rawSize.width, rawSize.height, amazonAdSlotId)

        val adLoader = DTBAdRequest()
        adLoader.setSizes(size)
        adLoader.loadAd(object : DTBAdCallback {
            override fun onSuccess(dtbAdResponse: DTBAdResponse) {
                // 'adView' is your instance of MaxAdView
                maxAdView?.setLocalExtraParameter("amazon_ad_response", dtbAdResponse)
                maxAdView?.loadAd()
            }

            override fun onFailure(adError: AdError) {
                // 'adView' is your instance of MaxAdView
                maxAdView?.setLocalExtraParameter("amazon_ad_error", adError)
                maxAdView?.loadAd()
            }
        })

![20220402-162109](https://user-images.githubusercontent.com/8433364/161374247-355cd0bf-090c-4fa5-a0fd-ceeeebbb7a35.png)

**Comment by thomasmso** [comment]
Thanks for reporting this - a fix for [this](https://github.com/AppLovin/Android-SDK-Mediation-Adapters/blob/master/AmazonAdMarketplace/src/main/java/com/applovin/mediation/adapters/AmazonAdMarketplaceMediationAdapter.java#L55-L56) is in our pipeline this week. We'll notify you when it is released.

**Comment by thomasmso** [comment]
This has been fixed in v9.4.2.2 of the adapter.

**Comment by xsjmichael** [comment]
it works, thanks a lot
