### ISSUE TITLE
MAX Interstitial tries to load for about 60 seconds before calling onAdLoadFailed

### ISSUE THREAD

**Issue by Luklek** [AppLovin/AppLovin-MAX-SDK-Android#294]
Is it normal that sometimes MAX Interstitial Ad tries to load for so long before failing?

The log below is repeated for few times at intervals of about 6-20 seconds for a total of about 60 seconds. Then it finally calls onAdLoadFailed.

Is there any setting to reduce the time?

2022-04-02 16:56:02.286 24510-24877/com.xxxxxxxxxxxxxxxxxxxxxxxxx W/AppLovinSdk: [TaskProcessMediationWaterfall:5e391d84b7282beb:INTER] No ads were returned from the server
2022-04-02 16:56:02.288 24510-24877/com.xxxxxxxxxxxxxxxxxxxxxxxxx E/AppLovinSdk: [AppLovinSdk] 
    **************************************************
    NO FILL received:
    ..ID: "xxxxxxxxxxxxxxxxxxxxxxxxx"
    ..FORMAT: "INTER"
    ..SDK KEY: "xxxxxxxxxxxxxxxxxxxxxxxxx"
    ..PACKAGE NAME: "com.xxxxxxxxxxxxxxxxxxxxxxxxx"
    ..Reason: [{"code":2051,"msg":"Please set test mode for guaranteed fill"},{"code":1028,"msg":"No message"},{"code":1000,"msg":"Ad network does not match filter ad networks list"}]
    **************************************************
2022-04-02 16:56:02.289 24510-24877/com.xxxxxxxxxxxxxxxxxxxxxxxxx I/AppLovinSdk: [TaskProcessMediationWaterfall:5e391d84b7282beb:INTER] Waterfall failed in 3ms with error: MaxError{code=204, message='MAX returned no eligible ads from any mediated networks for this app/device.'}

**Comment by thomasmso** [comment]
Hi - this is normal, our SDK has retry logic built in.

**Comment by Luklek** [comment]
Is there any way to disable this retry logic or reduce it to something like 15 seconds?

**Comment by thomasmso** [comment]
Could you email partner_support@applovin.com and cc me (thomas.so@applovin.com)?

**Comment by Luklek** [comment]
> Could you email [partner_support@applovin.com](mailto:partner_support@applovin.com) and cc me ([thomas.so@applovin.com](mailto:thomas.so@applovin.com))?

I sent email on 14 April but didn't get any reply.

**Comment by Luklek** [comment]
@thomasmso any chances to get a reply on this?

**Comment by thomasmso** [comment]
I see it, will reply
