### ISSUE TITLE
Please release an adapter so AdMob users can shows ads from MAX

### ISSUE THREAD

**Issue by svenoaks** [AppLovin/AppLovin-MAX-SDK-Android#295]
[Adapter exists for AppDiscovery](https://developers.google.com/admob/android/mediation/applovin) but not for MAX.

**Comment by thomasmso** [comment]
Hi - we do not support mediating our mediation platform through another mediator. If you'd like to use MAX, feel free to get started here: https://dash.applovin.com/documentation/mediation. Thanks!
