### ISSUE TITLE
Smaato ads are not loading

### ISSUE THREAD

**Issue by silane-tech** [AppLovin/AppLovin-MAX-SDK-Android#298]
I have tested in mediation debugger as well as live ads. No ads from Smaato are loading. 
`E/AppLovinSdk: [TaskTimeoutMediatedAd] SmaatoMediationAdapter is timing out MediatedAd`

Added dependencies:
```
    implementation 'com.smaato.android.sdk:smaato-sdk:21.8.0'
    implementation 'com.smaato.android.sdk:smaato-sdk-banner:21.8.0'
    implementation 'com.smaato.android.sdk:smaato-sdk-interstitial:21.8.0'
    implementation 'com.smaato.android.sdk:smaato-sdk-native:21.8.0'

    implementation 'com.applovin.mediation:smaato-adapter:21.8.0.1'
```

Max version: 11.3.2

**Comment by tr-appz** [comment]
@silane-tech  As a publisher on Applobin MAX, just like you, we have also implemented FB Bidding in our App & Only Applovin Ads are shown, FB ads are never shown in LIVE Ads. 

I hope that Applovin will fix these type of issues very soon. Because I am dam sure that applovin can not always bid more than FB and win the auction bidding every single time.

**Comment by NanaAmoah** [comment]
Hi @silane-tech, could you email nana.amoah@applovin.com with a sample app or APK and full verbose logs ?

**Comment by silane-tech** [comment]
@NanaAmoah 
Unable to send email to this address, your mail server blocked my email.
I am attaching full log and sample app here.
[smaato-max.log](https://github.com/AppLovin/AppLovin-MAX-SDK-Android/files/8453493/smaato-max.log)
[Smaato-MAX.zip](https://github.com/AppLovin/AppLovin-MAX-SDK-Android/files/8453494/Smaato-MAX.zip)

**Comment by NanaAmoah** [comment]
Thanks for sharing these. I will take a look and share updates.

**Comment by silane-tech** [comment]
Hi, @NanaAmoah 
One update from my side.
I checked it after connecting to a VPN server and the ads were working fine. This issue is with Indian ISPs I think. When I use any Indian internet service provider then ad does not load.
I am also using Smaato JS tag with MAX direct advertising feature and it is working fine. The issue is only with the SDK mediation with MAX.
Kindly check it as soon as possible.
