### ISSUE TITLE
Please remove the code appName( serverParameters.getString( "app_name", "Default App Name" ) )

### ISSUE THREAD

**Issue by taugin** [AppLovin/AppLovin-MAX-SDK-Android#300]
TTAdConfig adConfig = builder.appId( appId )
                    .appName( serverParameters.getString( "app_name", "Default App Name" ) )
                    .debug( parameters.isTesting() )
                    .supportMultiProcess( false )
                    .build();

Please remove the code appName( serverParameters.getString( "app_name", "Default App Name" ) ), this code will replace default app name some ui. and this code is deprecated by pangle.

thanks

**Comment by taugin** [comment]
attatch info:

when i load and show pangle splash ad, the "Default App Name" will show in the bottom
![20220408-173504](https://user-images.githubusercontent.com/5130314/162409414-47c90362-ca1b-416e-b234-30314e0674df.png)

**Comment by thomasmso** [comment]
Fixed here: https://github.com/AppLovin/AppLovin-MAX-SDK-Android/commit/78eaedc60ab4277b18ddbecd2d39ffe3282f0658
