### ISSUE TITLE
Memory leaks over time

### ISSUE THREAD

**Issue by laurencedawson** [AppLovin/AppLovin-MAX-SDK-Android#301]
I'm seeing some pretty bad memory leaks when using the SDK v11.3.3.

Looking in the source for "MaxAdView" I noticed that the view is setup using application context instead of activity context. **Is there a reason for this?**

Also can we get some clarification on how to properly dispose of an adview. Right now we're calling:

```
adView.stopAutoRefresh();
adView.setVisibility(View.GONE);
adView.destroy();
```

**Can you please confirm if this is correct.**

Thanks

**Comment by laurencedawson** [comment]
Any word on this? 

Performance is totally destroyed when using AppLovin to the point of being unusable.

**Comment by thomasmso** [comment]
@laurencedawson - What are the specific memory leaks you are referring to? Why would using application context result in more leaks?

**Comment by laurencedawson** [comment]
We're using the Amazon APS adapter and our users are complaining that over prolonged usage the app grinds to a halt.

The only change we've made is switch from MoPub to Applovin.

Our concern is that even after calling destroy when an Activity is ended we're not tidying up after the ads sufficiently.

**Comment by thomasmso** [comment]
Amazon APS adapter had some memory leaks that is fixed in the latest [v9.4.3.1](https://github.com/AppLovin/AppLovin-MAX-SDK-Android/commit/6ae4e89dbf29414771683316ceab05c7eeeb8bdc). Can you please update to that?

**Comment by laurencedawson** [comment]
Error persists. No issues when using Admob + APS adapter.

**Comment by thomasmso** [comment]
ok - we'll continue to investigate
