### ISSUE TITLE
onRewardedVideoAdPlayFailed errorCode -23 , Attempting to show ad when another fullscreen ad is already showing

### ISSUE THREAD

**Issue by xiaopei** [AppLovin/AppLovin-MAX-SDK-Android#303]
I saw below error when playing the second reward ad after loaded two ads on the same unitId.What is wrong with it? How to avoid it？
#onRewardedVideoAdPlayFailed errorCode -23 , Attempting to show ad when another fullscreen ad is already showing

my max version is 11.3.0

**Comment by joeapplovin** [comment]
Hi @xiaopei  - as the error message suggests, we don't support showing a second ad while the first one is already on the screen.  Can you please ensure the first ad is dismissed before attempting to show the second one?
