### ISSUE TITLE
 Meta Audience Network - Impressions and Impression Rate are not displayed in the background

### ISSUE THREAD

**Issue by OhPeterPan** [AppLovin/AppLovin-MAX-SDK-Android#304]
There are 500,000 pulls in the background, but the number of impressions and the impression rate are not displayed at all? What is the reason for this? Does the meta ad network need any other configuration?

applovin version：11.3.1

**Comment by wuaoke** [comment]
![飞书20220411-142118](https://user-images.githubusercontent.com/18245901/162676761-1ff3403f-df7c-49ba-b8e9-ef662c049b01.jpg)
