### ISSUE TITLE
Ad-related images and videos cannot be displayed

### ISSUE THREAD

**Issue by wuaoke** [AppLovin/AppLovin-MAX-SDK-Android#305]
I am using Native Ads (Manual) ads, but all the pictures and videos of the ads cannot be displayed, please help me find the reason, thank you

**Comment by williamycyh** [comment]
same problem, pls help

**Comment by wuaoke** [comment]
> same problem, pls help
![173851649669290_ pic](https://user-images.githubusercontent.com/18245901/162709571-84b698fc-d1c7-470c-bd27-af2b36e6fff7.jpg)

**Comment by wuaoke** [comment]
> same problem, pls help

@williamycyh

**Comment by wuaoke** [comment]
> same problem, pls help

@williamycyh Let the background operators view the configuration corresponding to the advertisement id
