### ISSUE TITLE
ad request time is too long

### ISSUE THREAD

**Issue by Jeremyzwc** [AppLovin/AppLovin-MAX-SDK-Android#307]
Excuse me，how i can set the ad request time in 10 seconds?

**Comment by xiaopei** [comment]
We have same problems，Especially the first advertising request。The following is our ad request duration distribution。
The first one only supports applovin network
The second one supports applovin and google ad manager 
![WechatIMG226](https://user-images.githubusercontent.com/8287288/163548977-074d43c2-98bc-4509-a7fc-e3568f9f4808.jpeg)
![WechatIMG228](https://user-images.githubusercontent.com/8287288/163548993-3339874a-247d-43b0-a7cf-02bb06dcac9b.jpeg)
