### ISSUE TITLE
 Class referenced in the manifest, com.applovin.adview.AppLovinInterstitialActivity, was not found in the project or the libraries

### ISSUE THREAD

**Issue by Mr-Ramzan** [AppLovin/AppLovin-MAX-SDK-Android#308]
**Class referenced in the manifest, "com.applovin.adview.AppLovinInterstitialActivity", was not found in the project or the libraries**

`     <activity
            android:name="com.applovin.adview.AppLovinInterstitialActivity"
            android:configChanges="orientation|screenSize|smallestScreenSize|screenLayout|uiMode"
            android:hardwareAccelerated="true"
            android:screenOrientation="behind"/>`

Upon following integration guide 
of Iron Source Ads Mediations AppLovin adapters this error come in the manifest when adding interstitial activity.
Upon lookin into dex files in external libraries section this class is actually not there  

SDK version and mediation adapter version is as below...

        ` implementation 'com.ironsource.adapters:applovinadapter:4.3.30'//updated

    implementation 'com.applovin:applovin-sdk:11.2.2'//updated` 

Please refer to a possible solution or fix this issue.

**Comment by thomasmso** [comment]
`com.applovin.adview.AppLovinInterstitialActivity` is an Activity we removed from our SDK years ago. Can you point me to the ironSource docs with this code snippet? Thanks.

**Comment by Mr-Ramzan** [comment]
```


<activity
    android:name="com.applovin.adview.AppLovinInterstitialActivity"
    android:configChanges="orientation|screenSize|smallestScreenSize|screenLayout|uiMode"
    android:hardwareAccelerated="true"
    android:screenOrientation="behind"/>

<activity
    android:name="com.applovin.adview.AppLovinFullscreenActivity"
    android:configChanges="keyboard|keyboardHidden|locale|orientation|screenLayout|screenSize|smallestScreenSize|uiMode"
    android:exported="false"
    android:hardwareAccelerated="true"
    android:launchMode="singleTop"
    android:screenOrientation="behind"/>


```


this is Tittle to this snippet is Manifest activities.

Link to the guide resources is 
[AppLovin via IronSource](https://developers.is.com/ironsource-mobile/android/applovin-mediation-guide/#step-4)

**Comment by thomasmso** [comment]
Thanks. We'll reach out to them to update their docs.
