### ISSUE TITLE
Too many Ads and Low eCPM

### ISSUE THREAD

**Issue by jmimohsin** [AppLovin/AppLovin-MAX-SDK-Android#310]
After getting problem with Native & Rewarded Ads, now the problem is eCPM. Every user is reporting about too many frustrating Ads and we developers are seeing very low eCPM(Always below $0.3) from AppLovin. FB has eCPM higher than $2 always then why are you guys showing your lowest eCPM ads?

Bidding means higher eCPM Ad will show to the user then you have to show FB Ad mostly time because your eCPM is always below $0.3

Please improve quality of Ads, Native Ad image/video/ad caption issues, Rewarded video eCPM/fill rate and the last eCPM for all Ads type.

**Comment by sijifairy** [comment]
Same with me. Applovin wins 30% native bidding request,  but provide a much lower eCPM than FB. I could only put a Bidding Floor to filter out Applovin impressions.

**Comment by jmimohsin** [comment]
@sijifairy Can you please guide me as well for avoiding lower eCPM Ads From AppLovin? Because I am earning approximate half now due to lower eCPM.

**Comment by jmimohsin** [comment]
I can see "Bid Floor" option with "Country Group Name", "CPM Floor" and "Country Targeting".  I need to set CPM Floor to $0.5 to avoid AppLovin Ads. Am I right @sijifairy?

**Comment by sijifairy** [comment]
> I can see "Bid Floor" option with "Country Group Name", "CPM Floor" and "Country Targeting". I need to set CPM Floor to $0.5 to avoid AppLovin Ads. Am I right @sijifairy?

Yes, $2.5 for Tier1 countries for example, but be aware this could result in lower Fill Rate for both FB & AppLovin. You could request another ad unit to avoid revenue lose.

Past few days, I could see a eCPM raise for AppLovin ads, maybe they're fixing this issue.

**Comment by jmimohsin** [comment]
I did in a simple way to take care with Fill rate. I set $0.1 for Banner and $0.2 for other Ad types for all countries. Now seeing good eCPM result from AppLovin too :)

**Comment by lucasrafagnin** [comment]
@jmimohsin hi, what CPM are you getting now with Applovin and FB?

I have a similar issue, mysteriously my AppLovin's CPM dropped from 3 dollars to 0.3 overnight, even though it kept the same levels of impressions and clicks.

<img width="1324" alt="Screen Shot 2022-04-27 at 11 41 34 PM" src="https://user-images.githubusercontent.com/5746225/165665971-9c2a59a5-22a9-454e-a325-04b287d3f35b.png">

c/c @santoshbagadi @thomasmso Unfortunately, email support doesn't exist.

**Comment by jmimohsin** [comment]
@lucasrafagnin As I said above that I set bid rate and now seeing eCPM from $0.3 to $1 but fill rate is effected by this and getting approx same earning.

**Comment by jmimohsin** [comment]
Can I get answer from official developers for this situations. I need all Ads from Facebook if they fail to fill then I need from other network because Fb has high eCPM. @santoshbagadi @thomasmso

**Comment by ihassanali259** [comment]
I have active ad campaigns in Tier one countries where Facebook is giving $5+ CPM and Applovin is giving 0.3$ to 0.6$. We are bearing 80% loss on our campaigns. Most of the ads are filled by Applovin exchange. This is not right. Mopub had an option to exclude their waterfall ad source and I think Applovin should also provide an option to exclude waterfall and let the user decide which network he wants to add in bidding.

**Comment by thomasmso** [comment]
Twitter Audience Platform is back live for native ads!
