### ISSUE TITLE
Google Adapter: skipped the video ads but get rewarded in test mode.

### ISSUE THREAD

**Issue by LazyBonesLZ** [AppLovin/AppLovin-MAX-SDK-Android#311]
Using max as mediator and integrated google adapter completed.  On my test device, I skipped the video while admob rewarded ad was showing, it promoted me skipped ad would not get the reward, but Max "onUserReward" callback  was called and the "MaxReward" was not null so that user was rewarded. Next is my code:
```
@Override
            public void onUserRewarded(MaxAd ad, MaxReward reward) {
                //if rewarde is null，user skipped the video。
                bSkippedRewardedVideo = reward == null ;
                Log.d(TAG, "onUserRewarded, skipped =" + bSkippedRewardedVideo);

            }
```

I think there is something wrong in official "GoogleMediationAdaper" class:
```
 @Override
        public void onAdDismissedFullScreenContent()
        {
            listener.onRewardedAdVideoCompleted();

            if ( hasGrantedReward || shouldAlwaysRewardUser() )
            {
                MaxReward reward = getReward();
                log( "Rewarded user with reward: " + reward );
                listener.onUserRewarded( reward );
            }

            log( "Rewarded ad hidden: " + placementId );
            listener.onRewardedAdHidden();
        }
```
`shouldAlwaysRewardUser()` always return `true` in test mode.

**Comment by thomasmso** [comment]
This is the intended behaviour - when in test mode, our spec has always been to reward user so you can test that callback.
