### ISSUE TITLE
banner ad probability not show image，testing environment，help!

### ISSUE THREAD

**Issue by skyzd** [AppLovin/AppLovin-MAX-SDK-Android#313]
MaxAdView banner ad，Probability of abnormal display and normal display。
When the advertisement stays, it switches to abnormal for a while and normal for a while。

As shown below：
<img width="341" alt="image" src="https://user-images.githubusercontent.com/3231503/163707281-647e8b5a-1f8e-4622-b674-c9220f0c9d15.png">

<img width="311" alt="image" src="https://user-images.githubusercontent.com/3231503/163707289-d3a8b123-278e-4e5b-8057-aeaedb1e721e.png">

log：
[logs.log](https://github.com/AppLovin/AppLovin-MAX-SDK-Android/files/8501247/logs.log)

**Comment by thomasmso** [comment]
We will fix this eventually - but this issue is only cosmetic and your integration is fine.
