### ISSUE TITLE
App crash

### ISSUE THREAD

**Issue by RunningTheSnail** [AppLovin/AppLovin-MAX-SDK-Android#314]
signal 5 (SIGTRAP), code 1 (TRAP_BRKPT)
base.apk!libmonochrome.so (offset 0x44f000)

backtrace:
  #00  pc 000000000393c4ac  /data/app/~~j785_v7s-NbOQg34nIXY8A==/com.google.android.webview-sp7Cvj8QBzJ8ugTwRC6_Ug==/base.apk!libmonochrome.so (offset 0x44f000)
  #00  pc 00000000032d4fa4  /data/app/~~j785_v7s-NbOQg34nIXY8A==/com.google.android.webview-sp7Cvj8QBzJ8ugTwRC6_Ug==/base.apk!libmonochrome.so (offset 0x44f000)
  #00  pc 00000000032d4bc0  /data/app/~~j785_v7s-NbOQg34nIXY8A==/com.google.android.webview-sp7Cvj8QBzJ8ugTwRC6_Ug==/base.apk!libmonochrome.so (offset 0x44f000)
  #00  pc 0000000003ee6784  /data/app/~~j785_v7s-NbOQg34nIXY8A==/com.google.android.webview-sp7Cvj8QBzJ8ugTwRC6_Ug==/base.apk!libmonochrome.so (offset 0x44f000)
  #00  pc 0000000003ee6300  /data/app/~~j785_v7s-NbOQg34nIXY8A==/com.google.android.webview-sp7Cvj8QBzJ8ugTwRC6_Ug==/base.apk!libmonochrome.so (offset 0x44f000)
  #00  pc 0000000003ee6268  /data/app/~~j785_v7s-NbOQg34nIXY8A==/com.google.android.webview-sp7Cvj8QBzJ8ugTwRC6_Ug==/base.apk!libmonochrome.so (offset 0x44f000)
  #00  pc 0000000003ee5f38  /data/app/~~j785_v7s-NbOQg34nIXY8A==/com.google.android.webview-sp7Cvj8QBzJ8ugTwRC6_Ug==/base.apk!libmonochrome.so (offset 0x44f000)
  #00  pc 0000000003ee5cec  /data/app/~~j785_v7s-NbOQg34nIXY8A==/com.google.android.webview-sp7Cvj8QBzJ8ugTwRC6_Ug==/base.apk!libmonochrome.so (offset 0x44f000)
  #00  pc 0000000003ee1858  /data/app/~~j785_v7s-NbOQg34nIXY8A==/com.google.android.webview-sp7Cvj8QBzJ8ugTwRC6_Ug==/base.apk!libmonochrome.so (offset 0x44f000)
  #00  pc 0000000002bb6fc8  /data/app/~~j785_v7s-NbOQg34nIXY8A==/com.google.android.webview-sp7Cvj8QBzJ8ugTwRC6_Ug==/base.apk!libmonochrome.so (offset 0x44f000)
  #00  pc 0000000003ee2048  /data/app/~~j785_v7s-NbOQg34nIXY8A==/com.google.android.webview-sp7Cvj8QBzJ8ugTwRC6_Ug==/base.apk!libmonochrome.so (offset 0x44f000)
  #00  pc 0000000002bb6fc8  /data/app/~~j785_v7s-NbOQg34nIXY8A==/com.google.android.webview-sp7Cvj8QBzJ8ugTwRC6_Ug==/base.apk!libmonochrome.so (offset 0x44f000)
  #00  pc 0000000003ee1e58  /data/app/~~j785_v7s-NbOQg34nIXY8A==/com.google.android.webview-sp7Cvj8QBzJ8ugTwRC6_Ug==/base.apk!libmonochrome.so (offset 0x44f000)
  #00  pc 0000000003315a74  /data/app/~~j785_v7s-NbOQg34nIXY8A==/com.google.android.webview-sp7Cvj8QBzJ8ugTwRC6_Ug==/base.apk!libmonochrome.so (offset 0x44f000)
  #00  pc 0000000003315214  /data/app/~~j785_v7s-NbOQg34nIXY8A==/com.google.android.webview-sp7Cvj8QBzJ8ugTwRC6_Ug==/base.apk!libmonochrome.so (offset 0x44f000)
  #00  pc 0000000003315680  /data/app/~~j785_v7s-NbOQg34nIXY8A==/com.google.android.webview-sp7Cvj8QBzJ8ugTwRC6_Ug==/base.apk!libmonochrome.so (offset 0x44f000)
  #00  pc 0000000003313e08  /data/app/~~j785_v7s-NbOQg34nIXY8A==/com.google.android.webview-sp7Cvj8QBzJ8ugTwRC6_Ug==/base.apk!libmonochrome.so (offset 0x44f000)
  #00  pc 0000000003313adc  /data/app/~~j785_v7s-NbOQg34nIXY8A==/com.google.android.webview-sp7Cvj8QBzJ8ugTwRC6_Ug==/base.apk!libmonochrome.so (offset 0x44f000)
  #00  pc 0000000003315214  /data/app/~~j785_v7s-NbOQg34nIXY8A==/com.google.android.webview-sp7Cvj8QBzJ8ugTwRC6_Ug==/base.apk!libmonochrome.so (offset 0x44f000)
  #00  pc 000000000295289c  /data/app/~~j785_v7s-NbOQg34nIXY8A==/com.google.android.webview-sp7Cvj8QBzJ8ugTwRC6_Ug==/base.apk!libmonochrome.so (offset 0x44f000)
  #00  pc 00000000033142ec  /data/app/~~j785_v7s-NbOQg34nIXY8A==/com.google.android.webview-sp7Cvj8QBzJ8ugTwRC6_Ug==/base.apk!libmonochrome.so (offset 0x44f000)
  #00  pc 000000000331406c  /data/app/~~j785_v7s-NbOQg34nIXY8A==/com.google.android.webview-sp7Cvj8QBzJ8ugTwRC6_Ug==/base.apk!libmonochrome.so (offset 0x44f000)
  #00  pc 0000000003306614  /data/app/~~j785_v7s-NbOQg34nIXY8A==/com.google.android.webview-sp7Cvj8QBzJ8ugTwRC6_Ug==/base.apk!libmonochrome.so (offset 0x44f000)
  #00  pc 0000000003307028  /data/app/~~j785_v7s-NbOQg34nIXY8A==/com.google.android.webview-sp7Cvj8QBzJ8ugTwRC6_Ug==/base.apk!libmonochrome.so (offset 0x44f000)
  #00  pc 0000000003d26834  /data/app/~~j785_v7s-NbOQg34nIXY8A==/com.google.android.webview-sp7Cvj8QBzJ8ugTwRC6_Ug==/base.apk!libmonochrome.so (offset 0x44f000)
  #00  pc 0000000003d267e8  /data/app/~~j785_v7s-NbOQg34nIXY8A==/com.google.android.webview-sp7Cvj8QBzJ8ugTwRC6_Ug==/base.apk!libmonochrome.so (offset 0x44f000)
  #00  pc 0000000003d26770  /data/app/~~j785_v7s-NbOQg34nIXY8A==/com.google.android.webview-sp7Cvj8QBzJ8ugTwRC6_Ug==/base.apk!libmonochrome.so (offset 0x44f000)
  #00  pc 0000000000019d04  /system/lib64/libutils.so (android::Looper::pollInner(int)+912)
  #00  pc 000000000001990c  /system/lib64/libutils.so (android::Looper::pollOnce(int, int*, int*, void**)+112)
  #00  pc 0000000000111cf0  /system/lib64/libandroid_runtime.so (android::android_os_MessageQueue_nativePollOnce(_JNIEnv*, _jobject*, long, int)+44)
  #00  pc 0000000000214bfc  /system/framework/arm64/boot-framework.oat (art_jni_trampoline+140)
  #00  pc 0000000000648430  /system/framework/arm64/boot-framework.oat (android.os.MessageQueue.next+192)
  #00  pc 0000000000644ee8  /system/framework/arm64/boot-framework.oat (android.os.Looper.loop+744)
  #00  pc 0000000000404c18  /system/framework/arm64/boot-framework.oat (android.app.ActivityThread.main+1672)
  #00  pc 00000000001337e8  /apex/com.android.art/lib64/libart.so (art_quick_invoke_static_stub+568)
  #00  pc 00000000001a8a88  /apex/com.android.art/lib64/libart.so (art::ArtMethod::Invoke(art::Thread*, unsigned int*, unsigned int, art::JValue*, char const*)+228)
  #00  pc 000000000054aefc  /apex/com.android.art/lib64/libart.so (art::InvokeMethod(art::ScopedObjectAccessAlreadyRunnable const&, _jobject*, _jobject*, _jobject*, unsigned long)+1364)
  #00  pc 00000000004cbef0  /apex/com.android.art/lib64/libart.so (art::Method_invoke(_JNIEnv*, _jobject*, _jobject*, _jobjectArray*)+52)
  #00  pc 00000000000896f4  /apex/com.android.art/javalib/arm64/boot.oat (art_jni_trampoline+180)
  #00  pc 0000000000897288  /system/framework/arm64/boot-framework.oat (com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run+136)
  #00  pc 000000000089f9b8  /system/framework/arm64/boot-framework.oat (com.android.internal.os.ZygoteInit.main+2280)
  #00  pc 00000000001337e8  /apex/com.android.art/lib64/libart.so (art_quick_invoke_static_stub+568)
  #00  pc 00000000001a8a88  /apex/com.android.art/lib64/libart.so (art::ArtMethod::Invoke(art::Thread*, unsigned int*, unsigned int, art::JValue*, char const*)+228)
  #00  pc 0000000000549930  /apex/com.android.art/lib64/libart.so (art::JValue art::InvokeWithVarArgs<art::ArtMethod*>(art::ScopedObjectAccessAlreadyRunnable const&, _jobject*, art::ArtMethod*, std::__va_list)+448)
  #00  pc 0000000000549dec  /apex/com.android.art/lib64/libart.so (art::JValue art::InvokeWithVarArgs<_jmethodID*>(art::ScopedObjectAccessAlreadyRunnable const&, _jobject*, _jmethodID*, std::__va_list)+92)
  #00  pc 00000000004327d0  /apex/com.android.art/lib64/libart.so (art::JNI<true>::CallStaticVoidMethodV(_JNIEnv*, _jclass*, _jmethodID*, std::__va_list)+636)
  #00  pc 0000000000099428  /system/lib64/libandroid_runtime.so (_JNIEnv::CallStaticVoidMethod(_jclass*, _jmethodID*, ...)+124)
  #00  pc 00000000000a0880  /system/lib64/libandroid_runtime.so (android::AndroidRuntime::start(char const*, android::Vector<android::String8> const&, bool)+836)
  #00  pc 0000000000003574  /system/bin/app_process64 (main+1324)
  #00  pc 000000000004973c  /apex/com.android.runtime/lib64/bionic/libc.so (__libc_init+108)

**Comment by thomasmso** [comment]
Can you update to the latest version of our SDK 11.3.3 and share a screenshot of the [Mediation Debugger](https://dash.applovin.com/documentation/mediation/android/testing-networks/mediation-debugger#sharing-the-mediation-debugger) here?

**Comment by akardas16** [comment]
> signal 5 (SIGTRAP), code 1 (TRAP_BRKPT) base.apk!libmonochrome.so (offset 0x44f000)
> 
> backtrace: #00 pc 000000000393c4ac /data/app/~~j785_v7s-NbOQg34nIXY8A==/com.google.android.webview-sp7Cvj8QBzJ8ugTwRC6_Ug==/base.apk!libmonochrome.so (offset 0x44f000) #00 pc 00000000032d4fa4 /data/app/~~j785_v7s-NbOQg34nIXY8A==/com.google.android.webview-sp7Cvj8QBzJ8ugTwRC6_Ug==/base.apk!libmonochrome.so (offset 0x44f000) #00 pc 00000000032d4bc0 /data/app/~~j785_v7s-NbOQg34nIXY8A==/com.google.android.webview-sp7Cvj8QBzJ8ugTwRC6_Ug==/base.apk!libmonochrome.so (offset 0x44f000) #00 pc 0000000003ee6784 /data/app/~~j785_v7s-NbOQg34nIXY8A==/com.google.android.webview-sp7Cvj8QBzJ8ugTwRC6_Ug==/base.apk!libmonochrome.so (offset 0x44f000) #00 pc 0000000003ee6300 /data/app/~~j785_v7s-NbOQg34nIXY8A==/com.google.android.webview-sp7Cvj8QBzJ8ugTwRC6_Ug==/base.apk!libmonochrome.so (offset 0x44f000) #00 pc 0000000003ee6268 /data/app/~~j785_v7s-NbOQg34nIXY8A==/com.google.android.webview-sp7Cvj8QBzJ8ugTwRC6_Ug==/base.apk!libmonochrome.so (offset 0x44f000) #00 pc 0000000003ee5f38 /data/app/~~j785_v7s-NbOQg34nIXY8A==/com.google.android.webview-sp7Cvj8QBzJ8ugTwRC6_Ug==/base.apk!libmonochrome.so (offset 0x44f000) #00 pc 0000000003ee5cec /data/app/~~j785_v7s-NbOQg34nIXY8A==/com.google.android.webview-sp7Cvj8QBzJ8ugTwRC6_Ug==/base.apk!libmonochrome.so (offset 0x44f000) #00 pc 0000000003ee1858 /data/app/~~j785_v7s-NbOQg34nIXY8A==/com.google.android.webview-sp7Cvj8QBzJ8ugTwRC6_Ug==/base.apk!libmonochrome.so (offset 0x44f000) #00 pc 0000000002bb6fc8 /data/app/~~j785_v7s-NbOQg34nIXY8A==/com.google.android.webview-sp7Cvj8QBzJ8ugTwRC6_Ug==/base.apk!libmonochrome.so (offset 0x44f000) #00 pc 0000000003ee2048 /data/app/~~j785_v7s-NbOQg34nIXY8A==/com.google.android.webview-sp7Cvj8QBzJ8ugTwRC6_Ug==/base.apk!libmonochrome.so (offset 0x44f000) #00 pc 0000000002bb6fc8 /data/app/~~j785_v7s-NbOQg34nIXY8A==/com.google.android.webview-sp7Cvj8QBzJ8ugTwRC6_Ug==/base.apk!libmonochrome.so (offset 0x44f000) #00 pc 0000000003ee1e58 /data/app/~~j785_v7s-NbOQg34nIXY8A==/com.google.android.webview-sp7Cvj8QBzJ8ugTwRC6_Ug==/base.apk!libmonochrome.so (offset 0x44f000) #00 pc 0000000003315a74 /data/app/~~j785_v7s-NbOQg34nIXY8A==/com.google.android.webview-sp7Cvj8QBzJ8ugTwRC6_Ug==/base.apk!libmonochrome.so (offset 0x44f000) #00 pc 0000000003315214 /data/app/~~j785_v7s-NbOQg34nIXY8A==/com.google.android.webview-sp7Cvj8QBzJ8ugTwRC6_Ug==/base.apk!libmonochrome.so (offset 0x44f000) #00 pc 0000000003315680 /data/app/~~j785_v7s-NbOQg34nIXY8A==/com.google.android.webview-sp7Cvj8QBzJ8ugTwRC6_Ug==/base.apk!libmonochrome.so (offset 0x44f000) #00 pc 0000000003313e08 /data/app/~~j785_v7s-NbOQg34nIXY8A==/com.google.android.webview-sp7Cvj8QBzJ8ugTwRC6_Ug==/base.apk!libmonochrome.so (offset 0x44f000) #00 pc 0000000003313adc /data/app/~~j785_v7s-NbOQg34nIXY8A==/com.google.android.webview-sp7Cvj8QBzJ8ugTwRC6_Ug==/base.apk!libmonochrome.so (offset 0x44f000) #00 pc 0000000003315214 /data/app/~~j785_v7s-NbOQg34nIXY8A==/com.google.android.webview-sp7Cvj8QBzJ8ugTwRC6_Ug==/base.apk!libmonochrome.so (offset 0x44f000) #00 pc 000000000295289c /data/app/~~j785_v7s-NbOQg34nIXY8A==/com.google.android.webview-sp7Cvj8QBzJ8ugTwRC6_Ug==/base.apk!libmonochrome.so (offset 0x44f000) #00 pc 00000000033142ec /data/app/~~j785_v7s-NbOQg34nIXY8A==/com.google.android.webview-sp7Cvj8QBzJ8ugTwRC6_Ug==/base.apk!libmonochrome.so (offset 0x44f000) #00 pc 000000000331406c /data/app/~~j785_v7s-NbOQg34nIXY8A==/com.google.android.webview-sp7Cvj8QBzJ8ugTwRC6_Ug==/base.apk!libmonochrome.so (offset 0x44f000) #00 pc 0000000003306614 /data/app/~~j785_v7s-NbOQg34nIXY8A==/com.google.android.webview-sp7Cvj8QBzJ8ugTwRC6_Ug==/base.apk!libmonochrome.so (offset 0x44f000) #00 pc 0000000003307028 /data/app/~~j785_v7s-NbOQg34nIXY8A==/com.google.android.webview-sp7Cvj8QBzJ8ugTwRC6_Ug==/base.apk!libmonochrome.so (offset 0x44f000) #00 pc 0000000003d26834 /data/app/~~j785_v7s-NbOQg34nIXY8A==/com.google.android.webview-sp7Cvj8QBzJ8ugTwRC6_Ug==/base.apk!libmonochrome.so (offset 0x44f000) #00 pc 0000000003d267e8 /data/app/~~j785_v7s-NbOQg34nIXY8A==/com.google.android.webview-sp7Cvj8QBzJ8ugTwRC6_Ug==/base.apk!libmonochrome.so (offset 0x44f000) #00 pc 0000000003d26770 /data/app/~~j785_v7s-NbOQg34nIXY8A==/com.google.android.webview-sp7Cvj8QBzJ8ugTwRC6_Ug==/base.apk!libmonochrome.so (offset 0x44f000) #00 pc 0000000000019d04 /system/lib64/libutils.so (android::Looper::pollInner(int)+912) #00 pc 000000000001990c /system/lib64/libutils.so (android::Looper::pollOnce(int, int*, int*, void**)+112) #00 pc 0000000000111cf0 /system/lib64/libandroid_runtime.so (android::android_os_MessageQueue_nativePollOnce(_JNIEnv*, _jobject*, long, int)+44) #00 pc 0000000000214bfc /system/framework/arm64/boot-framework.oat (art_jni_trampoline+140) #00 pc 0000000000648430 /system/framework/arm64/boot-framework.oat (android.os.MessageQueue.next+192) #00 pc 0000000000644ee8 /system/framework/arm64/boot-framework.oat (android.os.Looper.loop+744) #00 pc 0000000000404c18 /system/framework/arm64/boot-framework.oat (android.app.ActivityThread.main+1672) #00 pc 00000000001337e8 /apex/com.android.art/lib64/libart.so (art_quick_invoke_static_stub+568) #00 pc 00000000001a8a88 /apex/com.android.art/lib64/libart.so (art::ArtMethod::Invoke(art::Thread*, unsigned int*, unsigned int, art::JValue*, char const*)+228) #00 pc 000000000054aefc /apex/com.android.art/lib64/libart.so (art::InvokeMethod(art::ScopedObjectAccessAlreadyRunnable const&, _jobject*, _jobject*, _jobject*, unsigned long)+1364) #00 pc 00000000004cbef0 /apex/com.android.art/lib64/libart.so (art::Method_invoke(_JNIEnv*, _jobject*, _jobject*, _jobjectArray*)+52) #00 pc 00000000000896f4 /apex/com.android.art/javalib/arm64/boot.oat (art_jni_trampoline+180) #00 pc 0000000000897288 /system/framework/arm64/boot-framework.oat (com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run+136) #00 pc 000000000089f9b8 /system/framework/arm64/boot-framework.oat (com.android.internal.os.ZygoteInit.main+2280) #00 pc 00000000001337e8 /apex/com.android.art/lib64/libart.so (art_quick_invoke_static_stub+568) #00 pc 00000000001a8a88 /apex/com.android.art/lib64/libart.so (art::ArtMethod::Invoke(art::Thread*, unsigned int*, unsigned int, art::JValue*, char const*)+228) #00 pc 0000000000549930 /apex/com.android.art/lib64/libart.so (art::JValue art::InvokeWithVarArgsart::ArtMethod*(art::ScopedObjectAccessAlreadyRunnable const&, _jobject*, art::ArtMethod*, std::__va_list)+448) #00 pc 0000000000549dec /apex/com.android.art/lib64/libart.so (art::JValue art::InvokeWithVarArgs<_jmethodID*>(art::ScopedObjectAccessAlreadyRunnable const&, _jobject*, _jmethodID*, std::__va_list)+92) #00 pc 00000000004327d0 /apex/com.android.art/lib64/libart.so (art::JNI::CallStaticVoidMethodV(_JNIEnv*, _jclass*, _jmethodID*, std::__va_list)+636) #00 pc 0000000000099428 /system/lib64/libandroid_runtime.so (_JNIEnv::CallStaticVoidMethod(_jclass*, _jmethodID*, ...)+124) #00 pc 00000000000a0880 /system/lib64/libandroid_runtime.so (android::AndroidRuntime::start(char const*, android::Vectorandroid::String8 const&, bool)+836) #00 pc 0000000000003574 /system/bin/app_process64 (main+1324) #00 pc 000000000004973c /apex/com.android.runtime/lib64/bionic/libc.so (__libc_init+108)

are you using jetpack compose
