### ISSUE TITLE
Applovin Interstitial ads too annoying 

### ISSUE THREAD

**Issue by Saren-Arterius** [AppLovin/AppLovin-MAX-SDK-Android#318]
Users have to wait 5 seconds before the close button shows. After the close button is closed, there is 2nd ad screen which takes another 5 seconds for the close button to show. Android's back button is disabled so users have to click the ultra-tiny close button which often triggers misclicks. This is too annoying even to me as a developer. Please review the ad's design or provide a less obstructive ad format.

**Comment by thomasmso** [comment]
@Saren-Arterius / @hoanghiephui - We've discussed internally, and can handle this for you. Please email me at thomas.so@applovin.com with your AppLovin email and App/Play store portfolio.

**Comment by thomasmso** [comment]
UX updated.

**Comment by vishalknishad** [comment]
There should be way to opt out of Applovin ads.
