### ISSUE TITLE
Crash Reports After Adding Applovin SDK 

### ISSUE THREAD

**Issue by tr-appz** [AppLovin/AppLovin-MAX-SDK-Android#319]
`Activity.safedk_CustomTabsIntent_launchUrl_46a735ad316dd66561bc1347435a4f91`

Detailed 

`android.app.Instrumentation.checkStartActivityResult (Instrumentation.java:2067)
android.app.Instrumentation.execStartActivity (Instrumentation.java:1727)
android.app.Activity.startActivityForResult (Activity.java:5383)
androidx.activity.ComponentActivity.safedk_Activity_startActivityForResult_9f44e908bf9d747fc527dbfa22dc7b4d (ComponentActivity.java:8)
androidx.activity.ComponentActivity.startActivityForResult (ComponentActivity.java:597)
android.app.Activity.startActivityForResult (Activity.java:5341)
androidx.activity.ComponentActivity.safedk_Activity_startActivityForResult_206f42f0b65887e835d87ee52d14d221 (ComponentActivity.java:8)
androidx.activity.ComponentActivity.startActivityForResult (ComponentActivity.java:583)
android.app.Activity.startActivity (Activity.java:5727)
androidx.core.content.ContextCompat$Api16Impl.safedk_Context_startActivity_0c4df6808b5c0cfc92f23c850e40a674 (ContextCompat.java:8)
androidx.core.content.ContextCompat$Api16Impl.startActivity (ContextCompat.java:830)
androidx.core.content.ContextCompat.safedk_ContextCompat$Api16Impl_startActivity_dc782a3587eeed046f62de6d976356f8 (ContextCompat.java:8)
androidx.core.content.ContextCompat.startActivity (ContextCompat.java:279)
androidx.browser.customtabs.CustomTabsIntent.safedk_ContextCompat_startActivity_f482d8446b01c5580049a261a99b538c (CustomTabsIntent.java:8)
androidx.browser.customtabs.CustomTabsIntent.launchUrl (CustomTabsIntent.java:376)
my.package.TeamActivity.safedk_CustomTabsIntent_launchUrl_46a735ad316dd66561bc1347435a4f91 (TeamActivity.java:8)
my.package.TeamActivity.openCustomTab (TeamActivity.java:630)
my.package.NewsActivity$1.shouldOverrideUrlLoading (NewsActivity.java:381)
android.webkit.WebViewClient.shouldOverrideUrlLoading (WebViewClient.java:83)
org.chromium.android_webview.AwContentsClientBridge.shouldOverrideUrlLoading (AwContentsClientBridge.java:14)
android.os.MessageQueue.nativePollOnce (MessageQueue.java)
android.os.MessageQueue.next (MessageQueue.java:335)
android.os.Looper.loop (Looper.java:183)
android.app.ActivityThread.main (ActivityThread.java:7950)
java.lang.reflect.Method.invoke (Method.java)
com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run (RuntimeInit.java:603)
com.android.internal.os.ZygoteInit.main (ZygoteInit.java:947)`

I hope that SafeDK is somthng added by applovin. & these are the crashes that may be happening when a user click on AD and It Wanna to Open URL in Custom tab.

**Comment by thomasmso** [comment]
@tr-appz - Do you mind formatting the stack trace for us?
