### ISSUE TITLE
Clarification: Can I show the MREC ads in the apps recyclerview

### ISSUE THREAD

**Issue by nihp** [AppLovin/AppLovin-MAX-SDK-Android#320]
Clarification: Can I show the MREC ads in the apps recyclerview.

I have seen the MREC implementation, but there is no option to show it in the recycler view. Is it possible?

**Comment by thomasmso** [comment]
Yes, it is possible. It behaves as a normal ViewGroup should.

**Comment by nihp** [comment]
It needs to be in any positions inbetween my listview. Say 3rd position, 6th position. So manually add the layout and need to be notified to the recyclerview adapter.

**Comment by thomasmso** [comment]
Correct - we also will release a new Android SDK with an Ad Placer API similar to what MoPub had. Please watch this repository for SDK releases. Timeline is end of May.

**Comment by nihp** [comment]
@thomasmso  Thanks. 

Are you mentioning it will be possible using the  Ad Placer API , but the support is not released. 

In the same way, we can add it in the adapter as well in the recyclerview.
