### ISSUE TITLE
Interstitial custom adapter loading ads in Advance (caching fullscreen ads)

### ISSUE THREAD

**Issue by pm-vishal-chougule** [AppLovin/AppLovin-MAX-SDK-Android#321]
I observed that, once you load the Interstitial ad through MaxInterstitial API, AppLovinMax gives the callback to the adapter to load the Interstitial through mediation flow.

When we show and close the ad, after approx 10secs the mediation provides another load ad call for Meditation partner to load interstitial ad and it caches that ad.(If you call the show, it does not show.) 
But when you call load ad on Max Interstitial API, it immediately responds back with an already loaded ad and does not make a new ad request. 
Is there any documentation around the same feature or any client side API to switch that behavior?

Thanks,
Vishal

**Comment by thomasmso** [comment]
Shoot me an email (thomas.so@applovin.com) and I can point you to the right resources.
