### ISSUE TITLE
Webview crash is being reported after Applovin integration in Oppo devices

### ISSUE THREAD

**Issue by ihassanali259** [AppLovin/AppLovin-MAX-SDK-Android#324]
** Fatal Exception: java.lang.RuntimeException
Using WebView from more than one process at once with the same data directory is not supported. https://crbug.com/558377`**

`org.chromium.android_webview.AwBrowserProcess.b (AwBrowserProcess.java:10)
F5.g (F5.java:27)
E5.run (E5.java:2)
pt.f (pt.java:11)
ot.run (ot.java:2)
android.os.Handler.handleCallback (Handler.java:883)
android.os.Handler.dispatchMessage (Handler.java:100)
android.os.Looper.loop (Looper.java:238)
android.app.ActivityThread.main (ActivityThread.java:7845)
java.lang.reflect.Method.invoke (Method.java)
com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run (RuntimeInit.java:492)
com.android.internal.os.ZygoteInit.main (ZygoteInit.java:993) `

**Comment by thomasmso** [comment]
Are you able to reproduce this? If so, what is the model of your device?

**Comment by ihassanali259** [comment]
No, I am not able to reproduce it in debug. It's only happening in release and also my app doesn't use any webview.

**Comment by goldfish07** [comment]
may be missing proguard rules

-keepclassmembers class * {
    @android.webkit.JavascriptInterface <methods>;
}

**Comment by congdanh1608** [comment]
Are there any new updates?
I implemented the Max Applovin on multiple apps, but there are a few apps that have crash issues, while others do not.

**Comment by congdanh1608** [comment]
up!!!

**Comment by midou221** [comment]
same here...

**Comment by tenesuzun** [comment]
Hi, I am facing the same problem but with Huawei devices. It could be OS related as well but the crashes appeared on firebase after implementing apploving libraries in my project. So is there any update about the issue?
