### ISSUE TITLE
CPM dropped 92% overnight

### ISSUE THREAD

**Issue by lucasrafagnin** [AppLovin/AppLovin-MAX-SDK-Android#329]
Our app was getting an average CPM of $3.5 until 25/4 0:00AM.
Now the price dropped to .25 cents. Even though it kept the same levels of impressions and clicks.

We haven't made any changes to the app or AppLovin setup.
I have no replies to emails I sent to support in the last few days.

![Screen Shot 2022-04-28 at 6 47 33 PM](https://user-images.githubusercontent.com/5746225/165852208-d22e9cbd-e98b-4321-9e9f-6492828a7bc5.png).

Another question, is it possible to disable AppLovin ads and keep 100% with the mediation platforms (facebook for example)? Because this bug is ridiculous and unsustainable.

It is a AppLovin bug? 

@thomasmso 
@santoshbagadi

**Comment by thomasmso** [comment]
What's your AppLovin email? Then we can dig in.

**Comment by lucasrafagnin** [comment]
skuldapps@gmail.com @thomasmso

**Comment by RunningTheSnail** [comment]
Can we manually turn off applovin interstitial ads? @thomasmso

**Comment by thomasmso** [comment]
@lucasrafagnin - Investigating

**Comment by thomasmso** [comment]
@lucasrafagnin - It looks like Twitter Audience Platform is the only DSP buying your inventory, and they're currently fixing an issue. 

https://dash.applovin.com/o/mediation/alx_reporting#rsid=acc25c22ccc1cd6a1eb60fdffc3a2004b5fabd74

**Comment by lucasrafagnin** [comment]
@thomasmso 

If Twitter were the only buyer, shouldn't the number of impressions have dropped proportionately along with cpm?

That is not what happened.

<img width="1240" alt="Screen Shot 2022-04-29 at 8 37 42 AM" src="https://user-images.githubusercontent.com/5746225/165937512-caab410d-2c18-433a-aacd-e9efea9f5424.png">

**Comment by lucasrafagnin** [comment]
Yesterday (28/4) I tried to increase the cpm floor to see if it would increase the revenue again, but it wasn't enough, the cpm even slightly increased to 0.8$ but the impressions plummeted and then the revenue got even lower.

**Comment by lucasrafagnin** [comment]
Now about the Twitter issue, has something that I can do to recovery they inventory? Thanks @thomasmso

**Comment by thomasmso** [comment]
impressions are not proportional with CPMs - it just maeans that DSPs who bid _way_ lower are taking the inventory in Twitter's absence. There's nothing pubs can do right now until they recover, and their traffic is only available on MAX.

**Comment by lucasrafagnin** [comment]
Right, so was this something that impacted all MAX users or just me? Is there any reason why they've lowered their purchase?
because you mentioned above that they were fixing a problem.

Thanks @thomasmso

**Comment by thomasmso** [comment]
Technical issue on **their** side. Affect many native ad publishers but not all. Yours is affected worse since no other DSPs were buying your inventory.

**Comment by lucasrafagnin** [comment]
Ok, thanks by the reply. 

Do you have a link where I can track the progress of this issue?

**Comment by thomasmso** [comment]
We don't have a link for that. But I can notify you when the fix is live. You will also see it in your stats.

**Comment by jmimohsin** [comment]
@thomasmso have approx same issue https://github.com/AppLovin/AppLovin-MAX-SDK-Android/issues/310

**Comment by lucasrafagnin** [comment]
10 days later and the problem persists. Any news on the subject @thomasmso?

It would be interesting to have the possibility to disable the AppLovin network and let 100% with the mediator networks (Facebook in my case).

**Comment by thomasmso** [comment]
Unfortunately, nothing from Twitter. Disabling ALX would result in even lower performance. We only get the impressions where we are the highest bidder. Meta usually bids very little, but when they do they bid at high CPMs.

**Comment by ihassanali259** [comment]
Day by day the performance is getting worse. Applovin exchange is getting ECPM around 0.43  in Tier one countries which is ridiculously low. No event worst network gives you this low CPM value in Tier one countries.

**Comment by thomasmso** [comment]
Twitter Audience Platform is live again for native ads

**Comment by lucasrafagnin** [comment]
Hi @thomasmso,
Yes in the last few days the impressions number has been increased a lot, but the CPM is not in the same level as in the April (around 3.5$) when I created this issue. 

Yesterday the cpm was 0.22$.

**Comment by jmimohsin** [comment]
Closing issues but no improvement. AppLovin bids(eCPM less than $0.3) are more then Facebook(Always greater than $2).

eCPM is very low and bidding process is not working well. What are you doing guys? Just closing issue didn't mean you have fixed it.
