### ISSUE TITLE
Max dashboard not working

### ISSUE THREAD

**Issue by lucasrafagnin** [AppLovin/AppLovin-MAX-SDK-Android#330]
Hi,

All Max dashboard reports (Performance, User Activity, Cohorts, Att Consent and etc.) are broke.

I receive the following message (Unable to run the report. Unknown Error)

![Screen Shot 2022-04-28 at 6 54 10 PM](https://user-images.githubusercontent.com/5746225/165854083-74d65500-f803-4116-889c-8472c7b225ad.png)

**Comment by thomasmso** [comment]
Hi, what is your AppLovin email address?

**Comment by clevsh** [comment]
Same here.
I am using Chrome web browser.
The only workaround I've found is to open the dashboard page in "Incognito mode".

**Comment by lucasrafagnin** [comment]
@clevsh good point, I tried the incognito mode right now and it worked. Thanks.

**Comment by clevsh** [comment]
@lucasrafagnin But I think this is just a temporary workaround.

**Comment by lucasrafagnin** [comment]
Yes, certainly

**Comment by thomasmso** [comment]
I couldn't reproduce. Do you have an ad-block plugin on by any chance?

**Comment by thomasmso** [comment]
Any extra info from Chrome inspector?

**Comment by lucasrafagnin** [comment]
Hi @thomasmso, the chrome console:

<img width="1027" alt="Screen Shot 2022-04-29 at 8 56 50 AM" src="https://user-images.githubusercontent.com/5746225/165939915-3c705793-78e6-4a0b-aa8c-2d2b5c5b6736.png">

If you need more info, please let me know

**Comment by thomasmso** [comment]
@lucasrafagnin - You likely have an ad blocker somewhere in your stack. No one else has reported this issue so far.
