### ISSUE TITLE
Is there any problem with Applovin MAX last 10 days, no impressions?

### ISSUE THREAD

**Issue by mastervnc** [AppLovin/AppLovin-MAX-SDK-Android#331]
Currently, Applovin does not have any ads, while other networks (I integrate with Pangle and Admob) are still working fine.
![MAX](https://user-images.githubusercontent.com/67771965/166407352-62f43eb9-10d2-4d4c-a803-0d39ad24e1df.jpg)

**Comment by thomasmso** [comment]
Same issue as this: https://github.com/AppLovin/AppLovin-MAX-SDK-Android/issues/329
