### ISSUE TITLE
CPM keeps dropping everyday

### ISSUE THREAD

**Issue by ihassanali259** [AppLovin/AppLovin-MAX-SDK-Android#333]
A week ago I was getting  $2+ CMP for my app but after the start of this month, CPM is dropping every day. My App has active app campaigns which are costing me 100 USD on a daily basis, but the CPM is very low that I don't even get 20% back on my spending.

**Comment by jmimohsin** [comment]
Checkout this issue https://github.com/AppLovin/AppLovin-MAX-SDK-Android/issues/310
