### ISSUE TITLE
Clarification regarding the Mediation adapters

### ISSUE THREAD

**Issue by nihp** [AppLovin/AppLovin-MAX-SDK-Android#335]
I have added the mediation adapter dependencies for the applovin integrations. While enabling the debugger in the app it shows the Intialized Status as Not initialized. 

I have four adapters
1. Adcolony ==> Shows ==> Not initialized
2. Admob ==> Shows ==> Initialized
3. Meta (Facebook) ==> Shows ==> Not initialized
4. Applovin ==> Shows ==> Initialized

Shall i need to do any other thing for this facebook and Adcolony?

**Comment by thomasmso** [comment]
It's probably a race condition where the network was still initializing, at the time you displayed the Mediation Debugger. Maybe give it more time? If issue persists, could you share your Mediation Debugger screenshot? Top right corner of MD has a button for conveniently doing so.
