### ISSUE TITLE
Applovin exchange ecpm dropped significantly

### ISSUE THREAD

**Issue by maxakash** [AppLovin/AppLovin-MAX-SDK-Android#343]
Applovin exchange ecpm has dropped from around $10 to less than a dollar in last 2-3 days for native ads.
@thomasmso Please look into this.

**Comment by thomasmso** [comment]
@maxakash - Our GitHub issues are for technical issues only. The only way to raise your yield is to add more networks into your integration. Once you have more network-wide competition in your monetization, it will drive up cometition overall in ALX as well.
