### ISSUE TITLE
how do i  load the interstitial ad in application class 

### ISSUE THREAD

**Issue by curiousfellas** [AppLovin/AppLovin-MAX-SDK-Android#37]
I am using this sdk
implementation 'com.applovin:applovin-sdk:10.1.1'

i want to show the interstitial ad when using navigates from activity A to activity B. But the problem is that the user navigates from activity A to B pretty quickly and ad is not shown to them. Is it possible to load the ad in application class and display it during the activity transition.

**Comment by thomasmso** [comment]
You should be able to load the ad in your Activity A, then show the ad in Activity B. You just need a singleton or something to hold the reference to your instance of `MaxInterstitialAd`. An `Activity` reference is required due to mediated networks requiring an Activity context so you can't load in your `Application` class. Just tested it locally and that works.

**Comment by curiousfellas** [comment]
I am a beginner can you provide some sample code on how to achieve what you just explained
Also i am not using AppLovin max.
If I load the ad in activity A. Can I show it in activity C?
if the user navigation is like this 
A->B->C.

**Comment by thomasmso** [comment]
You mean you are using AppLovin as the only ad network in your app? If that's the case, when you create the `AppLovinInterstitialAd` using one of the various methods, you can store it in a `static` field somewhere, load the ad, then in Activity B access the interstitial (statically) and call `showAd()`.

```
class Application
{
    static AppLovinInterstitialAd sInterstitialAd;
}

class ActivityA extends Activity
{
    @Override
    public void onCreate(Bundle savedInstanceState) {

        Application.sInterstitialAd = AppLovinInterstitialAd.create( AppLovinSdk.getInstance( this ), this );
        Application.sInterstitialAd.loadAd();
...
}

class ActivityA extends Activity
{
    @Override
    public void onCreate(Bundle savedInstanceState) {
        if ( Application.sInterstitialAd.isReadyForDisplay() ) {
            Application.sInterstitialAd.showAd();
        }
    }
}
```
