### ISSUE TITLE
Change Banner position Programmatically

### ISSUE THREAD

**Issue by IhaYarre** [AppLovin/AppLovin-MAX-SDK-Android#40]
How i can Change Banner position Programmatically

**Comment by Lorenzo45** [comment]
You can see an example of this here: https://github.com/AppLovin/AppLovin-MAX-SDK-Android/blob/master/AppLovin%20MAX%20Demo%20App%20-%20Java/app/src/main/java/com/applovin/enterprise/apps/demoapp/ads/applovin/banner/BannerProgrammaticActivity.java
