### ISSUE TITLE
"App info must include app ID"

### ISSUE THREAD

**Issue by midou221** [AppLovin/AppLovin-MAX-SDK-Android#43]
test ads work without problems but when i disable it, this incomprehensible error appears although im sure the package name is compatible and ad unit id..

```
    NO FILL received:
    ..ID: "da339-----------"
    ..FORMAT: "INTER"
    ..SDK KEY: "UITzy4mCr-------------"
    ..PACKAGE NAME: "org.app.example"
    ..Reason: [{"code":1002,"msg":"App info must include app ID"},{"code":1008,"msg":"Ad unit info must include the adunit ID - please double-check that your package name \/ bundle id matches the one defined in the MAX Ad Unit ID being used"}]
```
I contacted support and they told me the problem was fixed, but actually nothing fixed..

Notice:
I use admob mediation to show applovin ads and i haven't had any problems..

**Comment by alvarshahanji** [comment]
Thanks for reaching out. What is the email address associated with your AppLovin account?

**Comment by midou221** [comment]
@alvarshahanji 
midouking951@gmail.com

**Comment by alvarshahanji** [comment]
Thank you. Could you try reproducing the issue in this [demo app](https://github.com/AppLovin/AppLovin-MAX-SDK-Android)?

You are using AdMob mediation and used the zone-id da339... to set up in the dashboard, correct?

**Comment by midou221** [comment]
I solved the problem from here [InterstitialBasicIntegrationActivity](https://github.com/AppLovin/AppLovin-MAX-SDK-Android/blob/e51e72e23afff843a22c5e8f915f14bb6b0a4917/AppLovin%20MAX%20Demo%20App%20-%20Java/app/src/main/java/com/applovin/enterprise/apps/demoapp/ads/applovin/interstitials/InterstitialBasicIntegrationActivity.java#L20)

Thank you :)
