### ISSUE TITLE
Memory leak when display banner

### ISSUE THREAD

**Issue by phoche** [AppLovin/AppLovin-MAX-SDK-Android#51]
I detect a memory leak with leakCanary, here is log:
┬───
│ GC Root: Local variable in native code
│
├─ java.lang.Thread instance
│    Leaking: UNKNOWN
│    Thread name: 'AppLovinSdk:shared_thread_pool:QHGC'
│    ↓ Thread.target
│             ~~~~~~
├─ java.util.concurrent.ThreadPoolExecutor$Worker instance
│    Leaking: UNKNOWN
│    ↓ ThreadPoolExecutor$Worker.this$0
│                                ~~~~~~
├─ java.util.concurrent.ScheduledThreadPoolExecutor instance
│    Leaking: UNKNOWN
│    ↓ ScheduledThreadPoolExecutor.workQueue
│                                  ~~~~~~~~~
├─ java.util.concurrent.ScheduledThreadPoolExecutor$DelayedWorkQueue instance
│    Leaking: UNKNOWN
│    ↓ ScheduledThreadPoolExecutor$DelayedWorkQueue.queue
│                                                   ~~~~~
├─ java.util.concurrent.RunnableScheduledFuture[] array
│    Leaking: UNKNOWN
│    ↓ RunnableScheduledFuture[].[0]
│                                ~~~
├─ java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask instance
│    Leaking: UNKNOWN
│    ↓ ScheduledThreadPoolExecutor$ScheduledFutureTask.callable
│                                                      ~~~~~~~~
├─ java.util.concurrent.Executors$RunnableAdapter instance
│    Leaking: UNKNOWN
│    ↓ Executors$RunnableAdapter.task
│                                ~~~~
├─ com.applovin.impl.mediation.g$c instance
│    Leaking: UNKNOWN
│    ↓ g$c.a
│          ~
├─ com.applovin.impl.mediation.g instance
│    Leaking: UNKNOWN
│    ↓ g.m
│        ~
├─ com.applovin.impl.mediation.g$a instance
│    Leaking: UNKNOWN
│    ↓ g$a.b
│          ~
├─ com.applovin.impl.mediation.MediationServiceImpl$a instance
│    Leaking: UNKNOWN
│    ↓ MediationServiceImpl$a.c
│                             ~
├─ com.applovin.impl.mediation.ads.MaxAdViewImpl$a instance
│    Leaking: UNKNOWN
│    ↓ MaxAdViewImpl$a.a
│                      ~
├─ com.applovin.impl.mediation.ads.MaxAdViewImpl instance
│    Leaking: UNKNOWN
│    ↓ MaxAdViewImpl.a
│                    ~
╰→ com.onesports.score.core.match.football.FootBallMatchDetailActivity instance
​     Leaking: YES (ObjectWatcher was watching this because com.onesports.score.core.match.football.FootBallMatchDetailActivity received Activity#onDestroy() callback and Activity#mDestroyed is true)
​     key = 5c9366a8-f94f-4a61-ba11-bf344abb7b54
​     watchDurationMillis = 12816
​     retainedDurationMillis = 7810

**Comment by thomasmso** [comment]
Hi @phoche - Can you double-check if you are on our latest SDK (v10.3.4)?

**Comment by phoche** [comment]
@thomasmso my dependence is 'com.applovin:applovin-sdk:+'. I call `MaxAdView.destroy()`, and remove MaxAdView from it's parent when Activity.onDestroy(), the leak still happened

**Comment by thomasmso** [comment]
@phoche - Do you mind sending us a debug APK at thomas.so@applovin.com & andrew.tian@applovin.com?

**Comment by thomasmso** [comment]
bump @phoche

**Comment by phoche** [comment]
Sorry, my team has been decided choose not to use MAX sdk
