### ISSUE TITLE
Stop print SDK info to logcat

### ISSUE THREAD

**Issue by OlegTarashkevich** [AppLovin/AppLovin-MAX-SDK-Android#531]
### Feature Description

I can't prevent the log data from being printed, which shows the AppLovin SDK information:

This information is spam and annoying. Please help to disable it.

[AppLovinSdk]
========================================
=====AppLovin SDK=====
===SDK Versions===
Version: 11.11.2
Plugin Version:
Ad Review Version:
OM SDK Version: 1.4.1-Applovin
===Device Info===

...

TG: 71
AEI: 50
MEI: 9
Test Mode On: false
Verbose Logging On: false
===Privacy States===
Please review AppLovin MAX documentation to be compliant with regional privacy policies.

Age Restricted User - No value set
Has User Consent - true
"Do Not Sell" - No value set
===MAX Terms Flow===
Enabled: false
Privacy Policy URI: null
Terms of Service URI: null

I checked and found that flag isVerboseLoggingEnabled is false.
AppLovinSdk.getInstance(context).getSettings().isVerboseLoggingEnabled()

**Comment by thomasmso** [comment]
Hi @OlegTarashkevich - we currently do not have the optionality of displaying SDK debug information. If you send this inquiry to https://support.applovin.com/hc/en-us/requests/new, we might be able to properly assist you there.
