### ISSUE TITLE
How to know ad is closed in interstitial ?

### ISSUE THREAD

**Issue by aZyreTech** [AppLovin/AppLovin-MAX-SDK-Android#532]
### MAX SDK Version

11.10.1

### Device/Platform Info

all

### Current Behavior

How do i know that interstitial ad is closed or not ? there is no onAdClosed method in listener

### Expected Behavior

I want to call another activity when interstitial ad get closed. How to achieve that ?

### How to Reproduce

There is no onAdClosed method . where did i found it ?

**Comment by applovinAsh** [comment]
Hi @aZyreTech, 

We have an `onAdHidden` callback that gets called when the ad is closed. For more information, view our documentation here: https://dash.applovin.com/documentation/mediation/android/ad-formats/interstitials

**Comment by aZyreTech** [comment]
ok thanks
