### ISSUE TITLE
How to close this page？(No need to show）

### ISSUE THREAD

**Issue by kotle** [AppLovin/AppLovin-MAX-SDK-Android#54]
![image](https://user-images.githubusercontent.com/25656015/140683564-20d6e2ac-0829-4279-b70a-85c314decb83.png)

**Comment by thomasmso** [comment]
Hi @kotle - What's the exact issue here? That's an image of AdColony's test ad.

**Comment by kotle** [comment]
> Hi @kotle - What's the exact issue here? That's an image of AdColony's test ad.

Thank you for your reply. I don’t want this page to appear when I display a video ad. Every time I open the app, this page will always appear the first time I display a video ad.

**Comment by thomasmso** [comment]
Are you on a simulator?

**Comment by kotle** [comment]
> Are you on a simulator?
No, I am on a real machine

**Comment by kotle** [comment]
> Are you on a simulator?

I did not open the test mode, why is this displayed? Can the console be set?

**Comment by thomasmso** [comment]
Could you enable our SDK's [verbose logs](https://monetization-support.applovin.com/hc/en-us/articles/236114328-How-do-I-enable-verbose-logging-in-AppLovin-s-SDK-) and send it over?

**Comment by thomasmso** [comment]
Closing - the screenshot is of AdColony's test ad.
