### ISSUE TITLE
Can't integrate with the latest version

### ISSUE THREAD

**Issue by arkilis** [AppLovin/AppLovin-MAX-SDK-Android#541]
### MAX SDK Version

11.11.3

### Device/Platform Info

Android 14

### Current Behavior

Trying to follow the doc: https://dash.applovin.com/documentation/mediation/android/getting-started/integration

but received the following error:

```
Execution failed for task ':app:safedkInstrumentationDebug'.
> Your SafeDK API key is invalid
```

### How to Reproduce

follow the doc: https://dash.applovin.com/documentation/mediation/android/getting-started/integration to integrate

**Comment by Lorenzo45** [comment]
Hi @arkilis can you share your app-level and root-level `build.gradle` files?
