### ISSUE TITLE
Clarification: While adding the Mediation adapter, shall I need to initialize that SDK's initialization as mandatory

### ISSUE THREAD

**Issue by jesphinpt** [AppLovin/AppLovin-MAX-SDK-Android#543]
### MAX SDK Version

11.11.3

### Device/Platform Info

ios and Android

### Current Behavior

Currently, I did not initialize the SDK of the mediation adapters in the code. So it was shown the Not initialized status. Does it cause any issues with the revenue or any other thing.

I have added Applovin SDk and its mediation adapters. But not added the SDKs and the initialization methods to the app's code. For eg) Added Google AdManager Mintegral SDK's ApplovinMediationAdapters. Is that enough? Or shall I need to add the individual SDK and its initialization.

### How to Reproduce

I have added Applovin SDk and its mediation adapters. But not added the SDKs and the initialize the SDKs in the app's code. For eg) Added Google AdManager Mintegral SDK's and ApplovinMediationAdapters. Is that enough?

**Comment by applovinAsh** [comment]
Hi, if you do not initialize the adapters, you cannot use those networks when loading ads. Please follow our documentation to add and initialize networks in your application properly. 
Android: https://dash.applovin.com/documentation/mediation/android/mediation-adapters
Unity: https://dash.applovin.com/documentation/mediation/unity/mediation-adapters

**Comment by jesphinpt** [comment]
@applovinAsh Then why it showing the status as completed in the debugger
<img width="270" alt="Screenshot 2023-09-11 at 11 39 13 AM" src="https://github.com/AppLovin/AppLovin-MAX-SDK-Android/assets/67142639/6f0d989b-cba9-40ae-8d99-0185ef1027ee">
.

**Comment by jesphinpt** [comment]
I have the adapter SDK in my code. I added inmobi applovin mediation. But not initialized of inmobi.  Does this make any issues.

**Comment by applovinAsh** [comment]
Can you open a ticket on zendesk with verbose logs enabled from the start of a session so we can get some more information? 
To enable verbose logs, see here: https://support.applovin.com/hc/en-us/articles/4413218413325-How-to-Enable-Verbose-Logging-in-the-AppLovin-SDK 
To start a zendesk ticket, see here: https://www.applovin.com/support

**Comment by jesphinpt** [comment]
AppLovinSdk: [MediationDebuggerListAdapter] 
    ========== MEDIATION DEBUGGER ==========
    ========== APP INFO ==========
    Dev Build - true
    Test Mode - disabled
    Target SDK - 33
    ========== MAX ==========
    SDK Version - 11.11.3
    Plugin Version - None
    Ad Review Version - Disabled
    ========== PRIVACY ==========
    CMP Name - null
    IABTCF_TCString - null
    IABTCF_gdprApplies - null
    Age Restricted User - No value set
    Has User Consent - No value set
    "Do Not Sell" - No value set
    Consent Flow Enabled - false
    Privacy Policy - undefined
    Terms of Service - undefined
    ========== NETWORKS ==========
    ---------- APPLOVIN_NETWORK ----------
    Status  - COMPLETE
    SDK     - 11.11.3
    Adapter - 11.11.3
    ---------- FACEBOOK_NETWORK ----------
    Status  - COMPLETE
    SDK     - 6.16.0
    Adapter - 6.16.0.0
    ---------- GOOGLE_AD_MANAGER_NETWORK ----------
    Status  - COMPLETE
    SDK     - 22.3.0
    Adapter - 22.3.0.0
    ---------- ADMOB_NETWORK ----------
    Status  - COMPLETE
    SDK     - 22.3.0
    Adapter - 22.3.0.0
D/AppLovinSdk: [MediationDebuggerListAdapter] 
    
    ---------- INMOBI_NETWORK ----------
    Status  - COMPLETE
    SDK     - 10.5.7
    Adapter - 10.5.7.0
    ---------- VUNGLE_BIDDING ----------
    Status  - COMPLETE
    SDK     - 6.12.1
    Adapter - 6.12.1.1
    ---------- MINTEGRAL_BIDDING ----------
    Status  - COMPLETE
    SDK     - MAL_16.5.11
    Adapter - 16.5.11.0
    ---------- OGURY_PRESAGE_NETWORK ----------
    Status  - COMPLETE
    SDK     - 5.6.0
    Adapter - 5.6.0.0
    ---------- TIKTOK_BIDDING ----------
    Status  - COMPLETE
    SDK     - 5.4.1.1
    Adapter - 5.4.1.1.0
    ========== AD UNITS ==========
    ---------- Android_INT ----------
    Identifier - jhijhbub
    Format     - INTER
    ----------  Android App Open ----------
    Identifier - yhbjhbjhb
    Format     - APPOPEN
    ----------  Android MREC ----------
    Identifier - ggguygj
    Format     - MREC
    ========== END ==========
D/AppLovinSdk: [TaskFetchDeveloperUri] Looking up developer URI for package name: 
I/AppLovinSdk: [ConnectionManager] Sending GET request to id=#33357131 "play.google.com/store/apps/details"...

**Comment by applovinAsh** [comment]
Thank you for the information. When you initialize MAX, it should also initialize all networks you have integrated in your application. If you are seeing "Not Initialized" in the Mediation Debugger, this could mean there is a configuration issue with that network. There could be something wrong with the network connection in the dashboard: https://dash.applovin.com/documentation/mediation/ui-max/networks/connect-networks

It would be best if you could provide the full verbose logs in a [zendesk ticket](https://www.applovin.com/support) so we can get more information.
