### ISSUE TITLE
Sudden AndroidManifest.XML merge error related to GoogleAdManager

### ISSUE THREAD

**Issue by OceanBreezeGames** [AppLovin/AppLovin-MAX-SDK-Android#547]
I'm trying to build an APK for my project in Android Studio but I am now suddenly getting errors with my merged AndroidManifest file. 

I believe it's related to the google adapters because if I remove the the following adapters error does not occur:
```
regularImplementation 'com.applovin.mediation:google-ad-manager-adapter:+'
regularImplementation 'com.applovin.mediation:google-adapter:+'
```

This is the error in the AndroidManifest.xml file:
**`Android resource linking failed - AAPT: error: unexpected element <property> found in <manifest><application>.
`**

This is what is located at that line in the manifest:
```
<property
            android:name="android.adservices.AD_SERVICES_CONFIG"
            android:resource="@xml/gma_ad_services_config" />
```

The Merged Manifest tab in Android studio shows the source to be from this:
```play-services-ads-lite-22.4.0\AndroidManifest.XML```
Edit: Looks like 22.4.0 was just released September 13, 2023. So I suspect this is the issue.

So I'm not really sure if this is an AppLovin issue that needs to be addressed, Google or something I've missed but I built a new release for this project a little over a week ago and just came back to rebuild something and now it's not working.

**Comment by OceanBreezeGames** [comment]
Just a little update. I manually set the version for the google adapters to this:
```
regularImplementation 'com.applovin.mediation:google-ad-manager-adapter:22.2.0.1'
regularImplementation 'com.applovin.mediation:google-adapter:22.2.0.1'
```
And now the project compiles and runs. 
So it is something with the latest release of those.

**Comment by thomasmso** [comment]
Thanks for reporting this @OceanBreezeGames - the teams are investigating and provide any updates here. We'll likely roll back the SDK our adapter certifies against, unless Google releases a new SDK.

**Comment by thomasmso** [comment]
Could you update to Android Gradle Plugin 4.2.1 or newer? That should resolve it.

**Comment by AntonPetrov83** [comment]
> The Google Mobile Ads Android SDK 22.4.0 added a [<property>](https://developer.android.com/guide/topics/manifest/property-element) element in its Android manifest. Building against this version or higher requires using Gradle 6.7.1 or higher and [Android Gradle plugin](https://developer.android.com/build/releases/gradle-plugin) 4.2.0 or higher. This guide instructs you on how to make sure your Unity editor is compatible.

https://developers.google.com/admob/unity/gradle
