### ISSUE TITLE
frequency capping not working

### ISSUE THREAD

**Issue by spiraldevapps** [AppLovin/AppLovin-MAX-SDK-Android#549]
### MAX SDK Version

11.11.3

### Device/Platform Info

android 12

### Current Behavior

frequency cap set at ad unit level not working

### Expected Behavior

Expected behaviour was that frequency cap was followed

### How to Reproduce

1. just set frequency cap at the backend like 1/minute
2. verify if the same is being followed on app level

**Comment by applovinAsh** [comment]
Hi @spiraldevapps, How soon after setting the frequency cap in the Ad Unit did you test? It takes about an hour for changes to go into effect. 

If the frequency capping is not working how you expect it to, we recommend programming your application to handle the behavior you want for ads.

**Comment by spiraldevapps** [comment]
Hi @applovinAsh it had been working fine since a few months - I believe, and when we checked the app recently we found about this issue.

Also asking us to set our own checks sort of limits our confidence in Applovin as a mediation platform.

**Comment by applovinAsh** [comment]
Can you provide the ad unit that is experiencing this problem? 

I just tested on my test app and had no problems with frequency capping.

**Comment by spiraldevapps** [comment]
Sure - ad unit id = de32fc6587c2c569

**Comment by applovinAsh** [comment]
@spiraldevapps, thank you. I am testing your ad unit. I see that the frequency capping is set to 1 ad every 30 seconds and 3 per day. The cap works for me as it no longer allows ads after I hit the per-day cap (3). I will update you when I can test the frequency cap again.

**Comment by applovinAsh** [comment]
@spiraldevapps, I ran another test with the frequency cap on the ad unit and did not have any issues; it showed three ads and then didn't show any again.

Can you further explain the issue that you are experiencing with the frequency capping? I tested using your application and got the expected result.
