### ISSUE TITLE
Attempt to invoke virtual method 'void com.applovin.impl.sdk.a.a(com.applovin.impl.sdk.utils.a)' on a null object reference

### ISSUE THREAD

**Issue by qinxiaohui-qq** [AppLovin/AppLovin-MAX-SDK-Android#556]
### MAX SDK Version

11.11.3

### Device/Platform Info

98% background state

### Current Behavior

Fatal Exception: java.lang.NullPointerException
Attempt to invoke virtual method 'void com.applovin.impl.sdk.a.a(com.applovin.impl.sdk.utils.a)' on a null object reference
com.applovin.impl.sdk.array.ArrayService.<init> (SourceFile:103)
com.applovin.impl.sdk.o.af (SourceFile:2173)
com.applovin.impl.sdk.o.aF (SourceFile:525)
com.applovin.impl.sdk.o.b (SourceFile:94)
com.applovin.impl.sdk.o$7.run (SourceFile:433)
java.lang.Thread.run (Thread.java:761)
![1696667637003](https://github.com/AppLovin/AppLovin-MAX-SDK-Android/assets/82812127/40a491e4-d064-44dc-b9ba-f1f215b50fe1)

### How to Reproduce

unknown

**Comment by thomasmso** [comment]
Thanks for reporting this issue. We've rolled back the changes server-side that caused an increase in this crash. You should see this crash trend down. Let us know if that is not the case. Thanks!
