### ISSUE TITLE
App crashes with com.iab.omid.library.applovin.utils.c.a java.lang.OutOfMemoryError

### ISSUE THREAD

**Issue by jesphinpt** [AppLovin/AppLovin-MAX-SDK-Android#557]
### MAX SDK Version

11.11.3

### Device/Platform Info

Android

### Current Behavior

App is crashing with the below error.

```
Fatal Exception: java.lang.OutOfMemoryError
Failed to allocate a 56 byte allocation with 2536624 free bytes and 2477KB until OOM, target footprint 536870912, growth limit 536870912; giving up on allocation because <1% of heap free after GC.
org.json.JSONObject.<init> (JSONObject.java:126)
com.iab.omid.library.applovin.utils.c.a (Unknown Source:2)
com.iab.omid.library.applovin.processor.c.a (Unknown Source:1)
```

### Expected Behavior

The app does not need to crash on any devices.

### How to Reproduce

After updating the applovin version to the  implementation 'com.applovin:applovin-sdk:11.11.3@aar' I am getting this crash for 24 users.

<img width="525" alt="Screenshot 2023-10-09 at 11 17 37 AM" src="https://github.com/AppLovin/AppLovin-MAX-SDK-Android/assets/67142639/854c6f68-1260-46c9-a50d-346ec6288d48">

**Comment by NanaAmoah** [comment]
Hi @jesphinpt, could you check for any memory leaks in your app or try to reduce memory usage?
