### ISSUE TITLE
With the latest upgrade I cant connect to applovin anymore.

### ISSUE THREAD

**Issue by leon6003** [AppLovin/AppLovin-MAX-SDK-Android#56]
With the latest upgrade I cant connect to applovin anymore.

It asks me to add <uses-permission android:name="com.google.android.gms.permission.AD_ID" />
to my Androidmanifest.xml and I did. Still same problem.

My app/build.gradle consists of

implementation("com.applovin:applovin-sdk:+")

I tried to use implementation("com.applovin:applovin-sdk:10.3.4") to downgrade but running the code still shows 10.3.5 !?

Is there a way to force a downgrade?

**Comment by thomasmso** [comment]
What do you mean you "_can't connect to applovin_" anymore? There's usually no good reason to downgrade our SDK.

**Comment by leon6003** [comment]
Hi,
I meant that it was not possible to initiate. It was however only with virtual phones on Android studio.
With real phones it almost worked. I did not crash during init but once running  it had problems showing ads.

I used Applovins test setup on the webpage and with the setting facebook test it worked fine but when i changed to Applovin it only worked ~1 out 20 tries. 

I am using the latest Flutter plugin as further information and i am in contact with Baris Gezer (AppLovin Monetization Support) but its not solved yet.

Reason why I want to downgrade is that it worked fine with 10.3.4 and we are in the process of releasing so if you have any clue why it wont use 10.3.4 when i write implementation("com.applovin:applovin-sdk:10.3.4") in gradle.build i will be very happy!

Best regards
Lennart

**Comment by thomasmso** [comment]
It seems like you're having multiple issues - and we are very motivated to resolve this. 10.3.5 should have no difference with 10.3.4 functionally.

Could you reproduce the issue with our SDK's [verbose logs](https://monetization-support.applovin.com/hc/en-us/articles/236114328-How-do-I-enable-verbose-logging-in-AppLovin-s-SDK-) enabled? And then try displaying ads in the [Mediation Debugger](https://dash.applovin.com/documentation/mediation/android/testing-networks/mediation-debugger).

**Comment by leon6003** [comment]
Hi,
I have already done a verbose log with the app using a real phone instead of VM. It gave some surprising results (see complete mail to get full picture).
I am using the flutter plugin for Applovin Max so Mediation debugger didnt work (At least I could not start it).
I add the log files I created here plus the mail chain with support.




[mail to support.pdf](https://github.com/AppLovin/AppLovin-MAX-SDK-Android/files/7593207/mail.to.support.pdf)
[Crash Verbose VM.txt](https://github.com/AppLovin/AppLovin-MAX-SDK-Android/files/7593208/Crash.Verbose.VM.txt)
[Crash VM.txt](https://github.com/AppLovin/AppLovin-MAX-SDK-Android/files/7593209/Crash.VM.txt)
[Verbose Applovin ads two attempts with real phone.txt](https://github.com/AppLovin/AppLovin-MAX-SDK-Android/files/7593210/Verbose.Applovin.ads.two.attempts.with.real.phone.txt)

**Comment by thomasmso** [comment]
Here are my findings:

1) The Flutter plugin is not integrating our SDK correctly by not initializing with an `Activity` context. That will cause some mediated networks to not initialize properly as THEY need an `Activity` context as well.

2) It looks like the permission `<uses-permission android:name="com.google.android.gms.permission.AD_ID"/>` is missing for emulator builds even though it is originally declared in our SDK's Android Manifest file. Because the permission is missing, our SDK tries to automatically show the Mediation Debugger but another issue with the Flutter plugin is causing that action to crash:

```
    Process: com.remint2.app, PID: 10476
    java.lang.NullPointerException: Attempt to invoke virtual method 'android.content.res.Resources$Theme android.content.Context.getTheme()' on a null object reference
        at android.app.AlertDialog.resolveDialogTheme(AlertDialog.java:227)
        at android.app.AlertDialog$Builder.<init>(AlertDialog.java:469)
        at com.applovin.impl.mediation.debugger.a$2.run(Unknown Source:16)
        at android.os.Handler.handleCallback(Handler.java:938)
        at android.os.Handler.dispatchMessage(Handler.java:99)
        at android.os.Looper.loop(Looper.java:223)
        at android.app.ActivityThread.main(ActivityThread.java:7656)
        at java.lang.reflect.Method.invoke(Native Method)
        at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:592)
        at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:947)
```

I can't tell why you're not able to get ads, b/c the logs are showing that ads are loading correctly - this leads me to believe that the Flutter plugin has integrated our SDK incorrectly here as well. May I ask where you got the plugin from? We're pretty stacked at the moment, but I will personally write the Flutter plugin for you by end of the year - give this [repo](https://github.com/AppLovin/AppLovin-MAX-Flutter) a follow for updates.

**Comment by leon6003** [comment]
Thx a lot for your effort! 
I got the plugin from https://pub.dev/packages/flutter_applovin_max/ latest version

Reply to 1. OK .... however it was working with previous version even though the error was there.
But of course you are right 

2. My logs showed two tries one fail and one working. I am just guessing that the failed one is the same as when I dont get any at all. See log attached if you missed it before.


_"I will personally write the Flutter plugin for you by end of the year "_  
Awesome !! Looking forward to it!

Still no one told me why I cant downgrade ....is it not possible ?


[Cut verbose.txt](https://github.com/AppLovin/AppLovin-MAX-SDK-Android/files/7593700/Cut.verbose.txt)

**Comment by thomasmso** [comment]
It should be possible to downgrade. I think you have to update the [`build.gradle` file](https://github.com/ioridev/flutter_applovin_max/blob/main/android/build.gradle#L37) in the plugin to specify the specific version, like:

```
implementation 'com.applovin:applovin-sdk:10.3.4'
```

**Comment by leon6003** [comment]
This is what I did!
Flutter clean, plus the above and then it still shows 10.3.5 in the log!

Anyway ...looking forward to your flutter plugin! Thx for your support!

**Comment by thomasmso** [comment]
Ah ok, sorry I couldn't help you further, that's why it's best for companies to provide (and maintain/support) official plugins. But yea, I will notify you when it's released!

**Comment by leon6003** [comment]
Hi again!
Sorry to disturb you again ! 
I would just like to know the time frame for the flutter plugin !?
Best regards
Lennart

**Comment by thomasmso** [comment]
Hi @leon6003 - we've unfortunately had higher priority items related to our MoPub acquisition and will put the official Flutter plugin off for later development (est. Feb - Mar). Sorry for the inconvenience this might have caused.

**Comment by thomasmso** [comment]
Also, @leon6003 - please subscribe to our Flutter repo for updates, as this repo is mainly for our Android-SDK specific issues.

**Comment by thomasmso** [comment]
I am pleased to announce that we have released a Flutter plugin with support for interstitials, rewarded videos, banners (programmatic & widget), and MRECs (programmatic & widget).

Here are some valuable resources:

Docs
https://dash.applovin.com/documentation/mediation/flutter/getting-started/integration

GitHub
https://github.com/AppLovin/AppLovin-MAX-Flutter
