### ISSUE TITLE
Clarification: How to show the appopen ads while cold start. I have added the appopen in my main activity. but it failed to show the appopen on cold start.

### ISSUE THREAD

**Issue by nihp** [AppLovin/AppLovin-MAX-SDK-Android#561]
### MAX SDK Version

11..3.3

### Device/Platform Info

Android

### Current Behavior

I am trying to show the appopen on the cold start. But it failed to show the app open ads. How can I show the ads. Currently it showing for me while going from background to foreground alone. Means soft start.

### Expected Behavior

Need to show the appopens when the user launch the app inititally

### How to Reproduce

Add the appopen and its intializationa and load the ads from MainActivity.

**Comment by thomasmso** [comment]
Hey @nihp - We'll need you to enable and send us our SDK's [verbose logs](https://dash.applovin.com/documentation/mediation/android/getting-started/advanced-settings#enable-verbose-logging) to diagnose why it failed to display.
