### ISSUE TITLE
Unable to see the appopens on samsung galaxy models

### ISSUE THREAD

**Issue by jesphinpt** [AppLovin/AppLovin-MAX-SDK-Android#563]
### MAX SDK Version

11.11.3

### Device/Platform Info

Android

### Current Behavior

I can't able to see the App Open Ads in the Samsung Galaxy models. How can I fix or shall I need to add any configuration additionally for this?

But I can able to see the Native and MREC ads for the app from Applovin.

### Expected Behavior

Need to see the AppOpen ads from Applovin network in Samsung Galaxy models.

### How to Reproduce

Add appopen implementation and Applovin SDKs and test it with the Samsung Galaxy models. It won't show the ads in the device.

**Comment by thomasmso** [comment]
App Open Ads are only available for the following networks described [here](https://dash.applovin.com/documentation/mediation/android/mediation-adapters#adapter-network-information), and not AppLovin bidding. It is available for AppLovin Exchange, but there is no guarantee for getting fill, thus, you should always test with [test ads](https://dash.applovin.com/documentation/mediation/android/testing-networks/test-mode).
