### ISSUE TITLE
Gradle builds extremely slow

### ISSUE THREAD

**Issue by og-abdul-mateen** [AppLovin/AppLovin-MAX-SDK-Android#571]
### MAX SDK Version

11.11.3

### Device/Platform Info

Android 11/12

### Current Behavior

Gradle builds are extremely slow for me. Running the app takes more than a minute every time I hit that run button. I am using an M1 Pro Macbook. The app was working fine before adding AppLovin SDK. Looks like the issue has something to do with `safedk` library, but I need help to fix the issue.

Here is Android Studio generated build report.

```
At 23:47, Oct 28, 2023, Android Studio detected the following issue(s) with Gradle plugin applovin-quality-service

Always-Run Tasks
This task might be setting its up-to-date check to always return false.

Plugin: applovin-quality-service
Task: safedkAdjustInputsDebug
Task type: com.safedk.gradleplugin.tasks.AdjustInstrumentationInputsTask
Issues for the same task were detected in 1 module(s), total execution time was <0.1s (0.4%), by module:
  Execution mode: FULL, time: <0.1s (0.4%), determines build duration: true, on critical path: true, issues: Always-Run Tasks

====Build information:====
Execution date: 28/10/2023, 11:47 pm
Total build duration: 98.3s
Configuration time: 86.8s (88.3%)
Critical path tasks time: 11.4s (11.6%)
Critical path tasks size: 10
AGP versions: 8.1.0
====Platform information:====
AI-223.8836.35.2231.10406996, JRE 17.0.6+0-17.0.6b829.9-10027231x64 JetBrains s.r.o., OS Mac OS X(aarch64) v13.5.2, screens 2704.0x1756.0; Retina

AS: Giraffe | 2022.3.1
Kotlin plugin: 223-1.8.0-release-345-AS8836.35.2231.10406996
Android Gradle Plugin: 8.1.0
Gradle: 8.1
Gradle JDK: JetBrains Runtime version 17.0.6
NDK: from local.properties: (not specified), latest from SDK: 24.0.8215888
CMake: from local.properties: (not specified), latest from SDK: 3.10.2, from PATH: (not found)
```

### Expected Behavior

The build should not take this long.

### How to Reproduce

Integrate AppLovin SDK as mentioned in the [official docs](https://dash.applovin.com/documentation/mediation/android/getting-started/integration). Now, run the app and notice the before/after performance of each app run.

**Comment by og-abdul-mateen** [comment]
**POTENTIAL SOLUTION:**

If I remove [Ad Review Service](https://dash.applovin.com/documentation/mediation/android/getting-started/integration#enable-ad-review), then the app builds super fast. Is there a way to enable App Review just for release AAR builds?

**Comment by kientux** [comment]
> **POTENTIAL SOLUTION:**
> 
> If I remove [Ad Review Service](https://dash.applovin.com/documentation/mediation/android/getting-started/integration#enable-ad-review), then the app builds super fast. Is there a way to enable App Review just for release AAR builds?

You can add an env var to enable/disable App Review in gradle:

```gradle
def debugBuild = System.env.DEBUG_BUILD

def appLovinAdReviewKey = envProps.getProperty('APPLOVIN_AD_REVIEW_KEY')
if (debugBuild != 'true' && appLovinAdReviewKey?.trim()) {
    apply plugin: 'applovin-quality-service'
    applovin {
        apiKey appLovinAdReviewKey
    }
}
```

**Comment by og-abdul-mateen** [comment]
> > **POTENTIAL SOLUTION:**
> > If I remove [Ad Review Service](https://dash.applovin.com/documentation/mediation/android/getting-started/integration#enable-ad-review), then the app builds super fast. Is there a way to enable App Review just for release AAR builds?
> 
> You can add an env var to enable/disable App Review in gradle:
> 
> ```groovy-gradle
> def debugBuild = System.env.DEBUG_BUILD
> 
> def appLovinAdReviewKey = envProps.getProperty('APPLOVIN_AD_REVIEW_KEY')
> if (debugBuild != 'true' && appLovinAdReviewKey?.trim()) {
>     apply plugin: 'applovin-quality-service'
>     applovin {
>         apiKey appLovinAdReviewKey
>     }
> }
> ```

Thanks, this looks like a good solution.

**Comment by og-abdul-mateen** [comment]
> > **POTENTIAL SOLUTION:**
> > If I remove [Ad Review Service](https://dash.applovin.com/documentation/mediation/android/getting-started/integration#enable-ad-review), then the app builds super fast. Is there a way to enable App Review just for release AAR builds?
> 
> You can add an env var to enable/disable App Review in gradle:
> 
> ```groovy-gradle
> def debugBuild = System.env.DEBUG_BUILD
> 
> def appLovinAdReviewKey = envProps.getProperty('APPLOVIN_AD_REVIEW_KEY')
> if (debugBuild != 'true' && appLovinAdReviewKey?.trim()) {
>     apply plugin: 'applovin-quality-service'
>     applovin {
>         apiKey appLovinAdReviewKey
>     }
> }
> ```

Thanks, this looks like a good solution.
