### ISSUE TITLE
Clarification: Where can i get the PLACEMENT_HERE for appopen ads

### ISSUE THREAD

**Issue by nihp** [AppLovin/AppLovin-MAX-SDK-Android#573]
### MAX SDK Version

11.11.3

### Device/Platform Info

Android

### Current Behavior

I need to know, where can I get the YOUR_TEST_PLACEMENT_HERE for my app.

`appOpenAd.showAd( "YOUR_TEST_PLACEMENT_HERE" );`

### How to Reproduce

'appOpenAd.showAd( "YOUR_TEST_PLACEMENT_HERE" );;

**Comment by applovinAsh** [comment]
Hi @nihp, if you do not want to use a placement ID, you can use `appOpenAd.showAd()` instead.

**Comment by nihp** [comment]
@applovinAsh But i need to know what is placement ID?

**Comment by applovinAsh** [comment]
@nihp A placement ID is a unique ID used to help manage and track the performance of ad types within your application. It is something that you would create for your specific ad unit IDs.

**Comment by nihp** [comment]
So it is from Google Admob or Meta or Mintegral and so on correct?

**Comment by nihp** [comment]
@applovinAsh I have a clarification, can I able to set maxduration for the ads in applovin for AppOpens or video ads.

**Comment by applovinAsh** [comment]
@nihp Correct. The ad network assigns the placement IDs. 

You cannot customize the maximum duration for advertisements on this platform. We follow the established industry standards concerning the lengths of ads and the options for skipping them.
