### ISSUE TITLE
Auto-click ads redirecting to a fake Amazon site

### ISSUE THREAD

**Issue by kpespisa** [AppLovin/AppLovin-MAX-SDK-Android#575]
### MAX SDK Version

11.11.3

### Device/Platform Info

Android

### Current Behavior

Over the past two weeks there has been a significant increase of auto-click ads, in particular one that launches a web browser displaying a fake Amazon webpage claiming the user has won something. These ads appear regularly and are being served either from AppLovin or AppLovin Exchange. 

### Expected Behavior

Auto-click or auto-redirect ads should never be allowed.

### How to Reproduce

Integrate the latest (11.11.3) AppLovin MAX Android SDK, and serve ads from AppLovin and AppLovin Exchange.

### Additional Info

![Screenshot_20231107_195554_Chrome](https://github.com/AppLovin/AppLovin-MAX-SDK-Android/assets/857622/bbd268f3-a440-4907-aecd-1539d513dbe7)
![Screenshot_20231107-175929](https://github.com/AppLovin/AppLovin-MAX-SDK-Android/assets/857622/960a6713-1de4-46c1-bfd6-e6b89099e0d5)

**Comment by iv-mexx** [comment]
Same issue here on Android and iOS as well!

For us this exploded in the last 24 hours with countless support emails and bad reviews in the app stores, especially since apparently this ads open the scam site so frequently that the our app is virtually unusable for affected users

**Comment by Maradox** [comment]
Same issue here. We use AppLovin mediation and disabled network by network but it didn't help. We turned the ad-units off for now.

**Comment by thomasmso** [comment]
Hey all - we identified the ads that are causing these auto-redirects and paused them from our exchange. Please let me know if the issue persists.

**Comment by Maradox** [comment]
We would like to check but cannot re-enable the ads, since the Mediation/Ad Units page refreshes itself over and over (all other pages work though).

**Comment by kpespisa** [comment]
Thank you! I haven't received any complaints since seeing @thomasmso 's update. 

For the future, is a GitHub issue the best way to bring attention to auto-redirect ads?

**Comment by thomasmso** [comment]
@iv-mexx - Yeah, we are removing the advertising source (Opera) from the exchange at this time. They kind of blew up the whole ecosystem with these ads..
