### ISSUE TITLE
Clarification: How can i restrict/ which status will be shown for the cap limit in UI for applovin ads and also how can I know already the ad is loading in the app

### ISSUE THREAD

**Issue by nihp** [AppLovin/AppLovin-MAX-SDK-Android#579]
### MAX SDK Version

11.11.3

### Device/Platform Info

Android

### Current Behavior

I need to add the conditions for the ads loading in the app which has already crossed its cap limit and also the if the ad is loading already.

What are the other things needs to make the ads too accurate.

### How to Reproduce

I just showed the ad when it is ready.

**Comment by applovinAsh** [comment]
@nihp Have you enabled the frequency cap option in the ad unit, or are you adding logic into your application to handle a frequency cap? 

If you are adding logic to your application, the best thing to do is to add a check that uses a counter and possibly a timer (if you have a time-based cap) in the Ad Loaded or Ad Shown callback. If the number of ads shown hits the max or is within a specific time frame, do not request an ad. 

We recommend only requesting ads when needed and not making ad requests once the frequency cap hits.
