### ISSUE TITLE
AppOpen does not shows on cold start in Samsung Galaxy Models

### ISSUE THREAD

**Issue by jesphinpt** [AppLovin/AppLovin-MAX-SDK-Android#596]
AppOpen **does not show on cold start** in the following Samsung Galaxy Models. 

Android version: 9.0, 13.0

**SDK Version:** 12.0.0
**Platform:** Android

AppOpen ads **work as expected on app cold start** in the following models but it takes up to 30 seconds to show the AppOpen ads.

1. Redmi - v8.1.0
2. Google Pixel - v13.0.0

**Comment by tiandrew** [comment]
Hey @jesphinpt, could you provide some verbose log files of the sessions from above so I can better see what might be going on? Here's documentation on how to enable verbose logging in our SDK: https://dash.applovin.com/documentation/mediation/android/getting-started/advanced-settings#enable-verbose-logging

If the files are too large feel free to email me andrew.tian@applovin.com
