### ISSUE TITLE
Account disabled - Support is dead

### ISSUE THREAD

**Issue by whuahao** [AppLovin/AppLovin-MAX-SDK-Android#600]
### MAX SDK Version

Your account is disabled until AppLovin's re-activation requirements are met. Please check your email for details or reach out to account-approval@applovin.com for assistance.

### Device/Platform Info

Your account is disabled until AppLovin's re-activation requirements are met. Please check your email for details or reach out to account-approval@applovin.com for assistance.

### Current Behavior

Your account is disabled until AppLovin's re-activation requirements are met. Please check your email for details or reach out to [account-approval@applovin.com](mailto:account-approval@applovin.com) for assistance.

### Expected Behavior

Your account is disabled until AppLovin's re-activation requirements are met. Please check your email for details or reach out to [account-approval@applovin.com](mailto:account-approval@applovin.com) for assistance.

### How to Reproduce

Your account is disabled until AppLovin's re-activation requirements are met. Please check your email for details or reach out to [account-approval@applovin.com](mailto:account-approval@applovin.com) for assistance.

### Additional Info

Your account is disabled until AppLovin's re-activation requirements are met. Please check your email for details or reach out to [account-approval@applovin.com](mailto:account-approval@applovin.com) for assistance.

**Comment by phucynwa** [comment]
I got that too. Although I always try to follow their Policy as much as possible. Omg.

**Comment by thomasmso** [comment]
Hey both - please send email to account-approval@applovin.com per process. Thanks!

**Comment by thomasmso** [comment]
@whuahao - What is your play store / app store URL?

**Comment by whuahao** [comment]
> 

It’s not the Play Store, it’s the Apple Store  

I have sent it many times with no results
