### ISSUE TITLE
Account disabled - Support is dead

### ISSUE THREAD

**Issue by whuahao** [AppLovin/AppLovin-MAX-SDK-Android#601]
Your account is disabled until AppLovin's re-activation requirements are met. Please check your email for details or reach out to [account-approval@applovin.com](mailto:account-approval@applovin.com) for assistance.

We are only in the testing phase and are preparing to go online when we receive the message that the account cannot be logged in. There is no explanation for the reason. What is going on?

**Comment by AndersonSL** [comment]
There's no point, they won't respond even though they sent several emails, they will leave your account suspended and they won't tell you the reason and they won't even pay you like they did to me and to this day they haven't given me a response

**Comment by thomasmso** [comment]
@whuahao / @AndersonSL - Due to our policy, we're unable to provide specific feedback. We encourage you to review our Program Policies and Technical Guidelines. I will close this issue out as GitHub is used for technical discussions. Thank you for your understanding.

**Comment by AndersonSL** [comment]
I know this isn't the right place to talk about this, but it's not right what you're doing, basically, it's a robbery because I've been trying to talk to support for days and you just ignore the emails and tickets, you read the ticket and it closes as resolved, either you at least give me an answer as to what happened with my account and my payment or I will have to open a lawsuit to resolve it since your support makes others look like idiots

**Comment by thomasmso** [comment]
@AndersonSL - Send an email to account-approval@applovin.com and reference this GH issue. I'll work with you there. Let me know here after email has been sent.

**Comment by AndersonSL** [comment]
@thomasmso 
I just sent the email again, with the title: Suspended account GH Issue: #601

**Comment by AndersonSL** [comment]
@thomasmso check my last reply on the email I notified the correct account login email

**Comment by zdrake314** [comment]
We are looking at your account re-activation request in the account-approval@applovin.com queue.

**Comment by AndersonSL** [comment]
@zdrake314 reply to the last email I sent

**Comment by AndersonSL** [comment]
@thomasmso Could you solve my problem via email?
