### ISSUE TITLE
Google UMP popup gets shown on every start

### ISSUE THREAD

**Issue by Zone8023** [AppLovin/AppLovin-MAX-SDK-Android#603]
### MAX SDK Version

12.1.0

### Device/Platform Info

s10

### Current Behavior

Google UMP popup gets shown on every start.Is it because of setDebugUserGeography (GDPR)?I manually connected to Google UMP but did not have this problem.Is it because the sdk automatically calls consensusInformation.reset()?

### How to Reproduce

 AppLovinSdkSettings settings = new AppLovinSdkSettings(mActivity);
        settings.getTermsAndPrivacyPolicyFlowSettings().setEnabled( true );
        settings.getTermsAndPrivacyPolicyFlowSettings().setPrivacyPolicyUri(Uri.parse( "https://your_company_name.com/privacy_policy" ) );

        // Terms of Service URL is optional
        settings.getTermsAndPrivacyPolicyFlowSettings().setTermsOfServiceUri(Uri.parse( "https://your_company_name.com/terms_of_service" ) );
        //settings.getTermsAndPrivacyPolicyFlowSettings().setDebugUserGeography(AppLovinSdkConfiguration.ConsentFlowUserGeography.GDPR );
        onLog(TAG,"initAdsConfig");
        AppLovinSdk sdk = AppLovinSdk.getInstance(settings,mActivity);
        sdk.setMediationProvider(AppLovinMediationProvider.MAX);
        sdk.initializeSdk( (AppLovinSdkConfiguration config) -> {

            // Initialize other 3rd-party SDKs - do not initialize mediated advertising SDKs, MAX will automatically do that for you. Not following this step will result in noticeable integration issues

            // Initialize the Adjust SDK inside the AppLovin SDK's initialization callback

            // Start loading ads
            initInterAd();
            initVideoAd();
        } );

**Comment by santoshbagadi** [comment]
@Zone8023 yes, right now this is the expected behavior when Debug Geography is set. We'll update it to only show to new users (match the normal behavior) in the next SDK release.

**Comment by santoshbagadi** [comment]
This has been fixed as of version 12.2.0 of our SDK.
