### ISSUE TITLE
Manual Native ad in andriod does not show Ad Media in production and in test mode both ad icon and ad image is not showing

### ISSUE THREAD

**Issue by AzizFasihHazel** [AppLovin/AppLovin-MAX-SDK-Android#613]
### MAX SDK Version

12.1.0

### Device/Platform Info

Android 13 , google pixel 4

### Current Behavior

Manual Native ad not showing icon and media view in test mode and in production icon is showing but the media is not showing. It shows the media once but not at all the places. I have native ads on various screens in my app with same native ad layout but it only shows media once and only at one place.

### Expected Behavior

Should have show test icon and test media like banner and inter in manual native and have to show media every time in live app

### How to Reproduce

Simply implement manual native ad and show all other data comes instead of icon and media in test mode. getting icon and media view null in test mode as you can see in screenshot.
![Screenshot 2024-01-12 170840](https://github.com/AppLovin/AppLovin-MAX-SDK-Android/assets/121864440/709bdede-0957-4a38-b56c-779cf9ebd667).

In production icon is showing but the media is not showing I implement it 5 days before and only 1 time it shows media at only one place not on the others screens.

### Additional Info

![Screenshot 2024-01-12 170758](https://github.com/AppLovin/AppLovin-MAX-SDK-Android/assets/121864440/33be4099-c480-4f78-b7eb-08cf5c33493e)
![Screenshot 2024-01-12 170820](https://github.com/AppLovin/AppLovin-MAX-SDK-Android/assets/121864440/e442bd55-372f-4e1e-8e0b-dea9fee8f614)
![Screenshot 2024-01-12 170840](https://github.com/AppLovin/AppLovin-MAX-SDK-Android/assets/121864440/1dc46471-2775-41f6-92c3-ca011b114511)
test mode nativeAd

**Comment by AzizFasihHazel** [comment]
Issue resolved.
The issue was it does not support width in percentage if you set it to 0dp using constraint layout. The width should be greater than 0.

**Comment by AzizFasihHazel** [comment]
Was using different package name in debug mode therefor I was not able to get iconView and mediaView.

**Comment by Fansvaer** [comment]
> Was using different package name in debug mode therefor I was not able to get iconView and mediaView.

My debug app doesn't display media either, I finally know why, haha!! Thanks
