### ISSUE TITLE
Kotlin Plugin id 'applovin-quality-service' causes gradle to crash

### ISSUE THREAD

**Issue by abanoubdev** [AppLovin/AppLovin-MAX-SDK-Android#616]
### MAX SDK Version

12.1.0

### Device/Platform Info

Android

### Current Behavior

I am trying to integrate applovin max sdk using the following link 
https://dash.applovin.com/documentation/mediation/android/getting-started/integration
and because i am using version cataloging ,i am integrating this with only kotlin plugins because i already migrated from groovy to kotlin
But whenever i add id 'applovin-quality-service' to app level,
 i am getting the following error : 
 
 **Unable to load class 'com.android.build.gradle.api.ApplicationVariant'
com.android.build.gradle.api.ApplicationVariant

Gradle's dependency cache may be corrupt (this sometimes occurs after a network connection timeout.)

Re-download dependencies and sync project (requires network)
The state of a Gradle build process (daemon) may be corrupt. Stopping all Gradle daemons may solve this problem.

Stop Gradle build processes (requires restart)
Your project may be using a third-party plugin which is not compatible with the other plugins in the project or the version of Gradle requested by the project.

In the case of corrupt Gradle processes, you can also try closing the IDE and then killing all Java processes.**

So please advise what should be done here

### Expected Behavior

App should build normally regardless of using groovy or kotlin

### How to Reproduce

Integrate using the following link but using kotlin plugins
https://dash.applovin.com/documentation/mediation/android/getting-started/integration

**Comment by omatty198** [comment]
https://docs.flutter.dev/release/breaking-changes/flutter-gradle-plugin-apply

When I responded to this request, I also did not have an id.
