### ISSUE TITLE
Can i initialize the sdk multi-times？

### ISSUE THREAD

**Issue by BIGCATDOG** [AppLovin/AppLovin-MAX-SDK-Android#621]
### MAX SDK Version

11.11.3

### Device/Platform Info

Android12

### Current Behavior

Just want to know if i initialize the sdk multi-times, it will take some unexpected behavior?
Such as : Increase ANR or memory usage?

### How to Reproduce

No

**Comment by thomasmso** [comment]
@BIGCATDOG - There is no reason to initialize our SDK multiple times. You only need to do it once. 

https://dash.applovin.com/documentation/mediation/android/getting-started/integration
