### ISSUE TITLE
Crashlytics crash "No zone identifier found in ad response:"

### ISSUE THREAD

**Issue by HitRoxxx** [AppLovin/AppLovin-MAX-SDK-Android#622]
### MAX SDK Version

12.1.0

### Device/Platform Info

No

### Current Behavior

Crash in many devices 
com.applovin.impl.adview.activity.a.a
java.lang.IllegalStateException - No zone identifier found in ad response:

### How to Reproduce

No Idea

### Additional Info

Fatal Exception: java.lang.IllegalStateException
No zone identifier found in ad response: {"ad_size":"INTER","ad_type":"APPOPEN","clcode":"4!v3!609152.1706981746!noi5VdSgB2wggxCTXVtqzkDRWnNpEs7HsCo3bw5eGlISeF-hENgO7ApOHQknVedzn8xBQm2S6f2B_G8pCGdAl8h0nuvdjsCnXuDnFHV6ns_flB-B3YRrSw3qIT57yHEwFE-Gnl1IP7Suv4Q2Y22N5Gc3iXmUtcmSkptAmGDmCK0EOG9z9IKDt9j39XNhAG5Hawuthp8zM9QoWYDgQoNNXFf-77JWWMSWhVOhmjLkHzqeMYC578d2Wf02qrdToi1zQH5modTsXItGHCK6Kqr4kXRJcYEPt7O_wnqyp6_hyus4_1SBGKrblqGM8y-Mz5F-_NmBudDwshbU-np1VBE3vAG3jU95brsE0pCKzyu4eqY9ydAVCxIZ98use13n4uv1UN0gfSL1zs-oKjjM-XW2HC2D2MCEbiq3AnLONtE3ztZzIz3L17fRMmCEGjnROr4t3yY9AAaD-7smXL22lIwBbbCJMuMzomKwrr71KmE8Mq9FzdRmmLXmriOAMKcSiM0FPtdbp9LpP63f_RAnSC2UbzILG6XfV6A47OximVExipTbYvQ_QoWKYa_sQofT8ddLyxdaYTxQASB9qH3qwZ3iOHfx-yh1YSvx48H08HrSKHRlAq_vDMn5bochqEUq1kOfEG42bbsnr6VfGdCGSUMuCIXaFYQtbKVxv7d7nrAP8NsG57a6TqREob9S23Et9DjNwjgfuaeE2McS33tdrgeKyjCEmgS57lTDs0zb8l90Xjh84jcHzQq4Hh6z--nJvVs5LghDHs-gDdUvynV81ZbgMl7adfwUS6TF_cQKqctWQnmk0xslhtO4WN131sT2bo2v3hnLoY9iH-ijQKtmzLXMnxu4-vnOiUNwDLSFIMkkBQFLlwOm_2l743pQYexGupN576mFLhuqUtvjEZYWHwY6hQgwo64C6K-Y5v1LcPj-VDjyzAFW9qiMTdcO0N9gtuWHi8DeiMkiC4cWCfzydjOcnj6soAnEV3rVi7Ub6vScomc5IMQYaVPN9Czs3UaTtMcy","status":200,"event_id":"43dec5a8f0418fdef6ce893703ed3129df761f63","dsp_name":"outbrain.com","dsp_id":593498,"adomain":"tokyo-skytree.jp","ads":[{"close_button_top_margin":20,"close_button_horizontal_margin":42,"fs_2":true,"lhs_skip_button":false,"suep":true,"close_style":1,"close_delay":0,"close_delay_graphic":3,"click_tracking_url":"https:\/\/prod-a.applovin.com\/redirect?nofollow=true&clcode=4!v3!609152.1706981746!noi5VdSgB2wggxCTXVtqzkDRWnNpEs7HsCo3bw5eGlISeF-hENgO7ApOHQknVedzn8xBQm2S6f2B_G8pCGdAl8h0nuvdjsCnXuDnFHV6ns_flB-B3YRrSw3qIT57yHEwFE-Gnl1IP7Suv4Q2Y22N5Gc3iXmUtcmSkptAmGDmCK0EOG9z9IKDt9j39XNhAG5Hawuthp8zM9QoWYDgQoNNXFf-77JWWMSWhVOhmjLkHzqeMYC578d2Wf02qrdToi1zQH5modTsXItGHCK6Kqr4kXRJcYEPt7O_wnqyp6_hyus4_1SBGKrblqGM8y-Mz5F-_NmBudDwshbU-np1VBE3vAG3jU95brsE0pCKzyu4eqY9ydAVCxIZ98use13n4uv1UN0gfSL1zs-oKjjM-XW2HC2D2MCEbiq3AnLONtE3ztZzIz3L17fRMmCEGjnROr4t3yY9AAaD-7smXL22lIwBbbCJMuMzomKwrr71KmE8<truncated: 7489 chars>

**Comment by thomasmso** [comment]
@HitRoxxx - How often is this crash occurring?

**Comment by HitRoxxx** [comment]
In the last 90 days, there have been a total of 283 crashes, averaging 3 crashes per day. I intend to simply notify you of this issue which occurs rarely.
