### ISSUE TITLE
Mediation Debugger Crash with Selective Initialized Ad Units and Test Mode Enabled

### ISSUE THREAD

**Issue by TyelorD** [AppLovin/AppLovin-MAX-SDK-Android#626]
### MAX SDK Version

12.2.0

### Device/Platform Info

Android

### Current Behavior

Before updating from v12.1.0 this worked fine, but after updating I now get a crash when attempting to load ads inside the Mediation Debugger while it's set to Test Mode, after specifying selectively initialized ad units. Just before the crash AppLovinSdk throws the following error:
```Ad Unit ID test_mode_interstitial has not been initialized. When you use selective init, any ad units that you do not explicitly specify are excluded from serving ads for the current session.```

But this error doesn't make sense, because I am explicitly specifying which ad units I want to use. This exact logic worked fine with v12.1.0 as well, so I assume this must be a new bug introduced, or perhaps there is some undocumented way I'm now supposed to set Test Mode Ad Units explicitly.

### Expected Behavior

I expected to be able to use Selective Initialized Ad Units with the Mediation Debugger in Test Mode.

### How to Reproduce

1. Before initializing AppLovinSdk, create a List<String> with the ad units we want to initialize.
2. On our AppLovinSdkSettings call setInitializationAdUnitIds passing in the list from above.
3. Set our mediation provider to "max".
4. Initialize AppLovinSdk.
5. Build and run the app, opening the Mediation Debugger
6. Enable Test Mode in the Mediation Debugger, and restart the app as required.
7. Open the Mediation Debugger back up, scroll down to "Completed SDK Integrations".
8. Tap AppLovin, then scroll down to "Test Ads" and tap Test Mode.
9. Attempt to load an Interstitial Ad
10. Observe Crash

**Comment by Lorenzo45** [comment]
Hey @TyelorD - thanks for raising this. We'll make sure to fix this in our next SDK release.

**Comment by Lorenzo45** [comment]
Hi @TyelorD - we just released SDK 12.3.0 which fixes this issue. Thanks for reporting!
