### ISSUE TITLE
How can I preload an Interstitial ads on an Activity then show the ads on another Activity?

### ISSUE THREAD

**Issue by Nghicv** [AppLovin/AppLovin-MAX-SDK-Android#629]
### Feature Description

How can I preload an Interstitial ads on an Activity then show the ads on another Activity?

**Comment by thomasmso** [comment]
@Nghicv - You can follow our docs [here](https://dash.applovin.com/documentation/mediation/android/ad-formats/interstitials) and use the same `MaxInterstitialAd` instance across your `Activity` instances.

**Comment by Nghicv** [comment]
> @Nghicv - You can follow our docs [here](https://dash.applovin.com/documentation/mediation/android/ad-formats/interstitials) and use the same `MaxInterstitialAd` instance across your `Activity` instances.

HI @thomasmso , Thanks for your support
As I checked, MaxInterstitialAd holds an Activity instance at the inittial time. if we use the same MaxInterstitialAd instance across Activity instances, it can lead to leak the inittial Activity.

**Comment by thomasmso** [comment]
@Nghicv - It actually will not make a difference which `Activity` instance you pass into the API. Our SDK is able to detect the topmost `Activity`.

**Comment by Nghicv** [comment]
> @Nghicv - It actually will not make a difference which `Activity` instance you pass into the API. Our SDK is able to detect the topmost `Activity`.

Thanks @thomasmso , I think we should use the application context instead of Activity
