### ISSUE TITLE
Ads Time

### ISSUE THREAD

**Issue by denverku** [AppLovin/AppLovin-MAX-SDK-Android#63]
Optimize ads time it too long

**Comment by thomasmso** [comment]
@denverku - Are you concerned about the time it takes to load an ad? This is generally the behaviour the more ad demand sources / mediated networks you add to your Ad Unit. We have an API such that you can inspect the latency of every ad network in the waterfall in our SDK's callbacks, by following the docs attached:

[Intercepting Ad Responses _ Credentials _ Configurations Doc.pdf](https://github.com/AppLovin/AppLovin-MAX-SDK-Android/files/7834388/Intercepting.Ad.Responses._.Credentials._.Configurations.Doc.pdf)

**Comment by denverku** [comment]
Rewarded ads time is too long not load ad
