### ISSUE TITLE
Native ads in Jetpack Compose Vertical Pager

### ISSUE THREAD

**Issue by kasem-sm** [AppLovin/AppLovin-MAX-SDK-Android#631]
### Feature Description

These days Native Ads inside Reel like layout or Vertical Pager is very popular. Can the AppLovin team provide an official sample?

I have tried to create it, please let me know if its right!

<img width="775" alt="Screenshot 2024-03-07 at 12 02 05 AM" src="https://github.com/AppLovin/AppLovin-MAX-SDK-Android/assets/83884225/2bb3367b-170b-4661-ba29-82d77c4209c7">

**Comment by EngrAhsan** [comment]
Native ad cause too much trouble with jetpack compose , so its batter to stick with xml layout for native ads
