### ISSUE TITLE
Use play-services-ads-lite instead of play-services-ads

### ISSUE THREAD

**Issue by gzjaychen** [AppLovin/AppLovin-MAX-SDK-Android#632]
### Feature Description

mediation google-adapter
Is it ok to use play-services-ads-lite instead of play-services-ads.
lite version can greatly reduce the package size.
And the latest version is 23.0.0

**Comment by gzjaychen** [comment]
@thomasmso Can you see if this problem can be handled?

**Comment by gzjaychen** [comment]
> Unfortunately no, we have to follow the instructions outlined here: https://developers.google.com/admob/android/quick-start

https://developers.google.com/admob/android/lite-sdk
Could you please think about it again?
Using the lite version also complies with the specifications.

Mediation google-adapter can use ads-lite version by default. If developers need to publish outside GP store, they only need to add the following code.
implementation 'com.google.android.gms:play-services-ads:23.0.0'

ads relies on ads-lite, so no additional work is required. See Compile Dependencies at https://mvnrepository.com/artifact/com.google.android.gms/play-services-ads/23.0.0

I hope you'll reconsider this suggestion, I'd be very grateful as it would be beneficial to developers at large.
Thanks.

**Comment by thomasmso** [comment]
@gzjaychen - If you have an account manager at AppLovin, please raise the concern with him or her. Otherwise, this is not a technological change we will consider.

**Comment by gzjaychen** [comment]
> @gzjaychen - If you have an account manager at AppLovin, please raise the concern with him or her. Otherwise, this is not a technological change we will consider.

How can I contact the account manager?
Thanks
