### ISSUE TITLE
Google UMP: Ads still show up after user chooses do not consent

### ISSUE THREAD

**Issue by Nghicv** [AppLovin/AppLovin-MAX-SDK-Android#633]
### MAX SDK Version

12.2.0

### Device/Platform Info

Android 11

### Current Behavior

Ads still show up after User selects "do not consent" option

### Expected Behavior

Ads shouldn't be shown if User selects "do not consent" option

### How to Reproduce

We can reproduce the bug easily

**Comment by rampr** [comment]
As I understand Limited Ads(https://support.google.com/admanager/answer/9882911?hl=en) can still be shown even if consent is not given. Maybe that is the scenario?
