### ISSUE TITLE
Whether the custom adapter supports In-app header bidding

### ISSUE THREAD

**Issue by longyunAd** [AppLovin/AppLovin-MAX-SDK-Android#635]
### MAX SDK Version

12.3.0

### Device/Platform Info

android

### Current Behavior

Our company has developed an advertising sdk, and we want to support In-app header bidding through the custom adapter. What should I do

### How to Reproduce

Function of the MaxSignalProvider.collectSignal method, when to cal

**Comment by Lorenzo45** [comment]
Hi @longyunAd,

We don't support header bidding for custom networks, only waterfall placements.
