### ISSUE TITLE
Why does the MaxInterstitialAd object require an activity parameter?

### ISSUE THREAD

**Issue by omeratesss** [AppLovin/AppLovin-MAX-SDK-Android#639]
### Feature Description

I want to load Interstitial ads without opening an Activity. Therefore, the activity parameter is not needed. When I will show an Interstitial ad, the activity parameter is needed.
  Note: It requires an activity parameter for the MaxInterstitialAd object. But it is cast to context within Applovin SDK. You can see it below. Why does this situation exist? Why can't I give a context parameter to the MaxInterstitialAd object?
---------
![Ekran Resmi 2024-03-21 10 57 59](https://github.com/AppLovin/AppLovin-MAX-SDK-Android/assets/141737366/c28c8081-af20-4ae9-ae6a-e3f7b25d315f)
---------
![Ekran Resmi 2024-03-21 10 55 38](https://github.com/AppLovin/AppLovin-MAX-SDK-Android/assets/141737366/315e8758-f627-4039-b2e4-72480017bf45)

**Comment by omeratesss** [comment]
![Ekran Resmi 2024-03-21 10 55 38](https://github.com/AppLovin/AppLovin-MAX-SDK-Android/assets/141737366/0d1882a1-2e7f-498a-820b-da94618ab42e)

**Comment by thomasmso** [comment]
Hey @omeratesss - we actually had a few other inquiries with regards to these APIs. Last time we looked at it a few years ago, having an active `Activity` and passing that through to some mediated SDKs were a requirement. Things might have changed in 2024. We'll investigate next week and update this thread.

**Comment by omeratesss** [comment]
Hi @thomasmso , is there any progress? I am waiting for you.

**Comment by omeratesss** [comment]
@thomasmso, your proposed middleground solution aligns perfectly with our requirements. Our aim is to initialize the SDK and load ads using a non-activity context. When it comes to displaying the ad, we intend to utilize activity contexts.

**Comment by thomasmso** [comment]
@omeratesss - we're working on this - pushing new adapters to ensure if an Activity context is not needed, we won't look for one when loading. Then to update SDK to allow passing of the Activity context.

To prevent completely breaking current implementations, we'll likely just deprecate existing APIs first while adding the new ones.

**Comment by thomasmso** [comment]
@omeratesss - We just released Android SDK v12.5.0. Our `MaxInterstitialAd` class can be created without requiring an Activity context. Just make sure sure to pass in an Activity context when calling `MaxInterstitialAd#show(...)`.
