### ISSUE TITLE
Native Ads Integration

### ISSUE THREAD

**Issue by kovachx** [AppLovin/AppLovin-MAX-SDK-Android#64]
This is the error I get when I try to use TEST ads in my app to test the new Native Ads (Beta):

E/AppLovinSdk: [AppLovinSdk] 
    **************************************************
    NO FILL received:
    ..ID: "****************" ( I am hiding the info of my ID)
    ..FORMAT: "NATIVE"
    ..SDK KEY: "****************" ( I am hiding the info of my SDK KEY)
    ..PACKAGE NAME: "****************" ( I am hiding the info of my PACKAGE name)
    ..Reason: [{"code":1008,"msg":"Ad unit info must include the adunit ID - please double-check that your package name \/ bundle id matches the one defined in the MAX Ad Unit ID being used"}]
    **************************************************

I have setup everything as per instructions, but I cannot get test ads to work. It keeps showing this error code.

**Comment by hoanghiephui** [comment]
Me too.

**Comment by williamycyh** [comment]
Me too

**Comment by jmimohsin** [comment]
Native Ads are not working right now. Wait for the next update!

**Comment by AndroidBuilder-ab** [comment]
Same issue on my side, native ads not work

**Comment by gautier-gdx** [comment]
Same here, any update on this? thanks!

**Comment by Mouadabdelghafouraitali** [comment]
Me too, same issue with interstitial

**Comment by williamycyh** [comment]
Same issue on my side, native ads not work

**Comment by thomasmso** [comment]
Hey all - 

Please use [test mode](https://dash.applovin.com/documentation/mediation/android/testing-networks/test-mode) to test your native ads integration. As of now, AppLovin is the only one with stable test ads, and we're currently working on adding support for test ads from other networks including Facebook.

**Comment by ihassanali259** [comment]
Can I enable bidding for both Interstitial and Native ads at the same time?

**Comment by jmimohsin** [comment]
@ihassanali259 yes you can.

**Comment by ankit-appbiz360** [comment]
Getting same error.
[{"code":1008,"msg":"Ad unit info must include the adunit ID - please double-check that your package name \/ bundle id matches the one defined in the MAX Ad Unit ID being used"}]

**Comment by ankit-appbiz360** [comment]
> Hey all -
> 
> Please use [test mode](https://dash.applovin.com/documentation/mediation/android/testing-networks/test-mode) to test your native ads integration. As of now, AppLovin is the only one with stable test ads, and we're currently working on adding support for test ads from other networks including Facebook.

Geeting ads only in test mode.  Geeting error on live mode : [{"code":1008,"msg":"Ad unit info must include the adunit ID - please double-check that your package name \/ bundle id matches the one defined in the MAX Ad Unit ID being used"}]

**Comment by chauduyphanvu** [comment]
@ankit-appbiz360 - did you make sure your package name / bundle ID from the app matches the one you define on the MAX dashboard?

**Comment by ankit-appbiz360** [comment]
Problem resolved. Thanks for your reply.
