### ISSUE TITLE
safedk ANR

### ISSUE THREAD

**Issue by gzjaychen** [AppLovin/AppLovin-MAX-SDK-Android#640]
### MAX SDK Version

12.3.1

### Device/Platform Info

Android

### Current Behavior

ANR occur

### How to Reproduce

I received several anr reports form GP Console. Is a serious problem in my app.

### Additional Info

[stacktrace.log](https://github.com/AppLovin/AppLovin-MAX-SDK-Android/files/14735177/stacktrace.log)
[stacktrace2.log](https://github.com/AppLovin/AppLovin-MAX-SDK-Android/files/14735179/stacktrace2.log)
-------
Thread 1 "main" tid=1 Blocked
01  at com.safedk.android.analytics.brandsafety.InterstitialFinder.b (SourceFile:1075)
The main thread is blocked here, waiting, and trying to acquire the lock 0x0a431326 held by thread 2
(com.safedk.android.analytics.brandsafety.InterstitialFinder)

Thread 2 "AppLovinSdk:communicator" tid=2 Native
...
31 at com.safedk.android.analytics.brandsafety.b.a (SourceFile:158)
Lock 0x0a431326 (com.safedk.android.analytics.brandsafety.InterstitialFinder) has this thread to get here. This causes ANR because the main thread is blocked and cannot attempt to acquire the same lock.

**Comment by lishun001** [comment]
I also encountered the same problem, is there any solution?

**Comment by lishun001** [comment]
![anr_ap](https://github.com/AppLovin/AppLovin-MAX-SDK-Android/assets/131642671/d077dab2-e44f-41be-87d0-0de2e97cbea0)

**Comment by gzjaychen** [comment]
The latest version 12.4.2 still has this problem.

**Comment by Lorenzo45** [comment]
@gzjaychen we just released Ad Review 5.2.0 which should have a fix for this ANR. Can you try this version and let us know if it resolves the issue for you? Thanks

**Comment by lishun001** [comment]
> @gzjaychen we just released Ad Review 5.2.0 which should have a fix for this ANR. Can you try this version and let us know if it resolves the issue for you? Thanks

What is Ad Review? How do I upgrade?

**Comment by gzjaychen** [comment]
> lishun001

Your project's buildscript dependencies
classpath ("com.applovin.quality:AppLovinQualityServiceGradlePlugin:5.2.0")

**Comment by Lorenzo45** [comment]
Note that the Ad Review SDK is optional and if you do not wish to use it you may remove the SDK to avoid these ANRs.
