### ISSUE TITLE
Remove MaxDebugger**Activity and their res to reduce package size.

### ISSUE THREAD

**Issue by gzjaychen** [AppLovin/AppLovin-MAX-SDK-Android#643]
### MAX SDK Version

12.3.1

### Device/Platform Info

Android

### Current Behavior

MaxDebugger**Activity is integrated with the release, increasing the package size.

### Expected Behavior

MaxDebugger**Activity and their res can be removed from the release integration to reduce package size.
--
Make debug a separate module, use reflect or SPI to load it.

### How to Reproduce

--

**Comment by thomasmso** [comment]
Thanks for the feedback @gzjaychen - we're not looking to make any modifications with regards to this atm, and rather actively deleting other parts of the SDK that is no longer in use.
