### ISSUE TITLE
High ANR Rate

### ISSUE THREAD

**Issue by FredVssg** [AppLovin/AppLovin-MAX-SDK-Android#65]
We are receiving a huge anr rate using the lastest version of Ads Adapters.

>   #00  pc 00000000000ddb48  /apex/com.android.runtime/lib64/bionic/libc.so (__ioctl+8)
>   #00  pc 0000000000097108  /apex/com.android.runtime/lib64/bionic/libc.so (ioctl+156)
>   #00  pc 0000000000053420  /system/lib64/libbinder.so (android::IPCThreadState::talkWithDriver(bool)+248)
>   #00  pc 0000000000054878  /system/lib64/libbinder.so (android::IPCThreadState::waitForResponse(android::Parcel*, int*)+60)
>   #00  pc 00000000000545f0  /system/lib64/libbinder.so (android::IPCThreadState::transact(int, unsigned int, android::Parcel const&, android::Parcel*, unsigned int)+184)
>   #00  pc 000000000004c044  /system/lib64/libbinder.so (android::BpBinder::transact(unsigned int, android::Parcel const&, android::Parcel*, unsigned int)+152)
>   #00  pc 000000000012fc40  /system/lib64/libandroid_runtime.so (android_os_BinderProxy_transact(_JNIEnv*, _jobject*, int, _jobject*, _jobject*, int)+152)
>   at android.os.BinderProxy.transactNative (Native method)
>   at android.os.BinderProxy.transact (BinderProxy.java:605)
>   at android.content.ContentProviderProxy.query (ContentProviderNative.java:470)
>   at android.content.ContentResolver.query (ContentResolver.java:1193)
>   at android.content.ContentResolver.query (ContentResolver.java:1125)
>   at android.content.ContentResolver.query (ContentResolver.java:1081)
>   at com.google.android.gms.dynamite.DynamiteModule.zzc (unavailable:122)
>   at com.google.android.gms.dynamite.DynamiteModule.zza (unavailable:96)
>   at com.google.android.gms.dynamite.DynamiteModule.getRemoteVersion (unavailable:149)
>   at com.google.android.gms.internal.ads.zzwd.zzd
>   at com.google.android.gms.internal.ads.zzvp.zzc
>   at com.applovin.mediation.adapters.GoogleMediationAdapter.loadRewardedAd (GoogleMediationAdapter.java:177)
>   at com.applovin.impl.mediation.g$8.run (unavailable)
>   at com.applovin.impl.mediation.g$12.run (unavailable)
>   at com.applovin.impl.mediation.g$6.run (unavailable)
>   at android.os.Handler.handleCallback (Handler.java:938)
>   at android.os.Handler.dispatchMessage (Handler.java:99)
>   at android.os.Looper.loop (Looper.java:246)
>   at android.app.ActivityThread.main (ActivityThread.java:8633)
>   at java.lang.reflect.Method.invoke (Native method)
>   at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run (RuntimeInit.java:602)
>   at com.android.internal.os.ZygoteInit.main (ZygoteInit.java:1130)

It looks so similar to the closed issue number #52 . But instead a crash its an ANR.

**Comment by waqas-334** [comment]
Hi, did you manage to find any solution for it?

**Comment by FredVssg** [comment]
Hello, we turned off UnityAds and it "solved" (reduced considerably) until we investigate and send logs to UnityAds, Admob and AppLovin Max.
Looks like, UnityAds with Admob turned on together is increasing ANRs.

**Comment by waqas-334** [comment]
Thanks, @FredVssg, I am using Unity and AdColony ads. Will try pausing Unity Ads and see if it helps. Thank you :)

**Comment by Lorenzo45** [comment]
Hey @FredVssg and @waqas-334 

I wanted to give you an update on these ANRs you have reported. We have received the confirmation that on January 25th, Unity and Admob discovered the issue with their integration resulting in spikes in CPU usage and increased ANRs in a select number of Android apps.

They identified the root cause and temporarily modified their integration to mitigate these issues (via backend change, no SDK update required). We have seen a correlating improvement since the change across various publishers. We recommend re-enabling Unity and monitoring ANR rates for the next few days to verify the issue is fully resolved.
