### ISSUE TITLE
SDK tries to display ad in own orientation ignoring the requested one

### ISSUE THREAD

**Issue by makssokolovWork** [AppLovin/AppLovin-MAX-SDK-Android#654]
### MAX SDK Version

12.4.2 

### Device/Platform Info

Different devices: 1) Android 10, honor 30; 2) Android 12,  Pixel 3a XL;  (and more)

### Current Behavior

When requested activity orientation is landscape then intersitial anyway loads portrait ad, that leads to plural unexpected screen rotations.

### Expected Behavior

When requested activity orientation is landscape then intersitial loads landscape ad too or loads nothing calling onLoadFailed.

### How to Reproduce

Met on 12.1.0 and 12.4.2 sdk versions.

When we begin display our content, we're requesting (by `activity.requestedOrientation`)some activity orientation because the content need it.
Also, at the near time, when we start content displaying, we call `interstitialAd.showAd()`.
ApplovinSdk initialized with the same main activity and the `MaxInterstitialAd()` constructor gets this one.

When MaxInterstitialAd() is being called, orientation according content requires (landscape), but anyway ad is portrait.

**Comment by thomasmso** [comment]
@makssokolovWork - Do you know which mediated network these ads are coming from? Are you requesting the ads when the app is in portrait mode? Could you enable and send over our SDK's [verbose logs](https://developers.applovin.com/en/android/overview/advanced-settings/#enable-verbose-logging)?

**Comment by makssokolovWork** [comment]
@thomasmso 
1. Answer is coming soon. 
2. No, firstly I request activity orientation and later I call loadAd and showAd.
3. Answer is coming soon.
