### ISSUE TITLE
Ogury sdk update is showing the wrong version in Mediation Debugger

### ISSUE THREAD

**Issue by rjsuzuki** [AppLovin/AppLovin-MAX-SDK-Android#661]
### MAX SDK Version

12.4.2

### Device/Platform Info

No

### Current Behavior

Ogury sdk is suggesting to update to `2.7.7.1`
See screenshot.

<img src="https://github.com/AppLovin/AppLovin-MAX-SDK-Android/assets/9149908/67800d17-8fa8-4748-acc1-16a115aab151" width=400 />

### Expected Behavior

Ogury sdk should be suggesting to update to `5.6.2.2`

### How to Reproduce

open mediation debugger with Ogury SDK mediation lib dependency installed

**Comment by thomasmso** [comment]
Thanks for reporting this @rjsuzuki, we're investigating..

**Comment by thomasmso** [comment]
This has been fixed.
