### ISSUE TITLE
There is a bug in the latest my target version.

### ISSUE THREAD

**Issue by omeratesss** [AppLovin/AppLovin-MAX-SDK-Android#669]
### MAX SDK Version

12.5.0

### Device/Platform Info

Xiaomi 13 lite - android 14

### Current Behavior

I updated Max SDK to the latest version and updated My Target to the latest version (5.20.1.0). The application crashes when it is first opened.

### Expected Behavior

I should not crash in the latest Max SDK and the latest My Target version.

### How to Reproduce

If MAX SDK has version 12.3.1 and My Target has version 5.20.0.0, there is no crash.
If you want to get Crash, MAX SDK should be 12.5.0 and My Target should be 5.20.1.0.

Note: This error is only received in release mode. Dexguard is used in my project.

- Workaround: I downgraded My Target version to 5.20.0.0. The problem is gone.

### Additional Info

This is my crash log:
![Ekran Resmi 2024-05-22 02 31 57](https://github.com/AppLovin/AppLovin-MAX-SDK-Android/assets/141737366/c514af4d-4e69-41ff-8024-392cbf51aad2)

This is my Sdk initialize code block:
` val initConfig = AppLovinSdkInitializationConfiguration
            .builder(applovinAppId, getApplicationContext())
            .setMediationProvider("max")
            .build()

        AppLovinSdk.getInstance(getApplicationContext()).initialize(initConfig) {
            Log.i(TAG, "Applovin onInitCompleted")
        }`

**Comment by thomasmso** [comment]
@jplianghu - could you investigate?

**Comment by jplianghu** [comment]
@omeratesss It seems that the myTarget SDK is attempting to access a resource that is missing in MIUI (Xiaomi's UI system). This likely explains why we can not reproduce it. To resolve this issue, myTarget should review their updates in version 5.20.1 and ensure that all required resources are available in MIUI as well. Could you please reach out to myTarget regarding this matter?
