### ISSUE TITLE
something wrong

### ISSUE THREAD

**Issue by Luopan1** [AppLovin/AppLovin-MAX-SDK-Android#67]
**************************************************
    NO FILL received:
    ..ID: "6ddfc7f065a9935**"
    ..FORMAT: "INTER"
    ..SDK KEY: "4IQKAU1Dll07VcdzTg2nqbFwR-A7MHxCGkeU03uQL3gqLRef1GyRONaG33sgwd5iRw8o6vuB*****"
    ..PACKAGE NAME: "com.*******.****.****"
    ..Reason: [{"code":2051,"msg":"Please set test mode for guaranteed fill"},{"code":1000,"msg":"Ad network does not match filter ad networks list"}]
    **************************************************

max bidding Facebook ad

**Comment by thomasmso** [comment]
Hi, please enable [test mode](https://dash.applovin.com/documentation/mediation/android/testing-networks/test-mode) to guarantee fill. Facebook very rarely fills live ads. Thanks!
