### ISSUE TITLE
Amazon APS Adapter not initializing

### ISSUE THREAD

**Issue by Farasy** [AppLovin/AppLovin-MAX-SDK-Android#672]
### MAX SDK Version

12.5.0

### Device/Platform Info

Android 12,13,14, Various devices

### Current Behavior

I'm integrating Amazon APS and use the Mediation Debugger to test the implementation. Followed steps on [Applovin Official Documentation](https://developers.applovin.com/en/android/preparing-mediated-networks?networks=002) and the docs from [APS](https://ams.amazon.com/webpublisher/uam/docs/aps-mobile/android).
Docs say the APS SDK must be initialized besides MAX. I tested init before MAX and after. However, the Mediation Debugger states the APS SDK is not initialized and while debugging I can see that AmazonAdMarketplaceMediationAdapter.initialize(...) is not called. 

### How to Reproduce

```
AdRegistration.getInstance("XXX", activityContext);
AdRegistration.setAdNetworkInfo(new DTBAdNetworkInfo(DTBAdNetwork.MAX));
AdRegistration.setMRAIDSupportedVersions(new String[] {"1.0", "2.0", "3.0"});
AdRegistration.setMRAIDPolicy(MRAIDPolicy.CUSTOM);

AdRegistration.enableTesting(true);
AdRegistration.enableLogging(true);
```

### Additional Info

implementation 'com.applovin:applovin-sdk:12.5.0'
implementation 'com.applovin.mediation:amazon-tam-adapter:9.9.5.0'

**Comment by thomasmso** [comment]
@Farasy - `AmazonAdMarketplaceMediationAdapter.initialize(...)` not being call is not indicative of an issue, as the initialization of their SDK is your responsibility, which you have done correctly. Please re-open the thread if you are facing any other issues.
