### ISSUE TITLE
Native ad class inaccesible.

### ISSUE THREAD

**Issue by ltsadevs** [AppLovin/AppLovin-MAX-SDK-Android#68]
I am testing native ads but app crashes when I try to load native ads. MAX SDK version: 10.3.5

java.lang.IllegalAccessError: Method 'void com.applovin.mediation.nativeAds.MaxNativeAd.<init>(com.applovin.mediation.nativeAds.MaxNativeAd$Builder)' is inaccessible to class 'com.applovin.mediation.adapters.FacebookMediationAdapter$MaxFacebookNativeAd' (declaration of 'com.applovin.mediation.adapters.FacebookMediationAdapter$MaxFacebookNativeAd' appears in /data/app/{package_name}-EdAnUM8_cJq1oBCZLpb1DA==/base.apk)

**Comment by thomasmso** [comment]
Hey - whatever we have right now is for preview purposes only. We're going to release a new SDK first week of Jan with full support for native ads and a new API not using templates (rather binding against your custom views). I will notify this thread.

**Comment by nihp** [comment]
@thomasmso  Any updates for the above. 
@Itsadevs Shall I need to get the key from the app lovin dashbord to set it in my app?

**Comment by ltsadevs** [comment]
I am using manual integration of Native ads, manual is working currently.

**Comment by ltsadevs** [comment]
@nihp Yes! you need to add the sdk key in manifest file.

```
<meta-data android:name="applovin.sdk.key"
           android:value="your_sdk_key"/>
```

**Comment by thomasmso** [comment]
Glad to hear things are working @ltsadevs.

**Comment by nihp** [comment]
@deeteeh Are you mentioning the manual integration guidelines in [this](https://dash.applovin.com/documentation/mediation/ios/mediation-adapters) is works fine for you to show the native ads?

Manual Integration — Read the [manual integration instructions](https://dash.applovin.com/documentation/mediation/manual-integration-ios) if you want to integrate the adapter artifacts, mediated SDKs, and their dependencies manually.
