### ISSUE TITLE
When using Bytedance open ads, WebView crashes.

### ISSUE THREAD

**Issue by henyiwu** [AppLovin/AppLovin-MAX-SDK-Android#681]
### MAX SDK Version

12.5.0

### Device/Platform Info

android 5.1.1

### Current Behavior

1
#00 pc 01e043ae /data/app/com.google.android.webview-2/lib/arm/libwebviewchromium.so [armeabi-v7a::828800bb9ac343a1d20038afcc3299ae]
2
#01 pc 021793e7 /data/app/com.google.android.webview-2/lib/arm/libwebviewchromium.so [armeabi-v7a::828800bb9ac343a1d20038afcc3299ae]
3
#02 pc 019d4125 /data/app/com.google.android.webview-2/lib/arm/libwebviewchromium.so [armeabi-v7a::828800bb9ac343a1d20038afcc3299ae]
4
#03 pc 019d3afd /data/app/com.google.android.webview-2/lib/arm/libwebviewchromium.so [armeabi-v7a::828800bb9ac343a1d20038afcc3299ae]
5
#04 pc 019d3ae3 /data/app/com.google.android.webview-2/lib/arm/libwebviewchromium.so (Java_J_N_MLlibBXh+10) [armeabi-v7a::828800bb9ac343a1d20038afcc3299ae]
6
#05 pc 003ccbd5 /data/dalvik-cache/arm/data@app@com.google.android.webview-2@base.apk@classes.dex (oatexec+302037) [armeabi::55e3989715bc987fb9713247f190e929]
7
java:
8
org.chromium.base.JavaExceptionReporter.uncaughtException(chromium-SystemWebViewGoogle.aab-stable-463807400:4)
9
com.mbridge.msdk.foundation.same.report.b.d.a(SourceFile:51)
10
com.mbridge.msdk.foundation.same.report.b.d.uncaughtException(SourceFile:8)
11
com.pgl.ssdk.m.uncaughtException(SourceFile)
12
com.bytedance.sdk.openadsdk.utils.x.uncaughtException(SourceFile:9)
13
java.lang.ThreadGroup.uncaughtException(ThreadGroup.java:693)
14
java.lang.ThreadGroup.uncaughtException(ThreadGroup.java:690)

### How to Reproduce

this happens online and we cannot reproduce it

**Comment by applovinAsh** [comment]
@henyiwu, can you report the ANR to ByteDance? It looks to be getting caused by their SDK.

**Comment by henyiwu** [comment]
sure, Thank you.
