### ISSUE TITLE
Account is disabled

### ISSUE THREAD

**Issue by PatrickUnity** [AppLovin/AppLovin-MAX-SDK-Android#682]
### MAX SDK Version

all

### Device/Platform Info

all

### Current Behavior

My account has been disabled for no reason and I have done nothing. My game has been released on googleplay and the amazon app store, but every time I email applovin I'm told that the game doesn't meet the minimum requirements and there's no indication of what exactly is wrong. I have emailed at least 5 times and still no resolution!
My email address: patrickleegogogo@gmail.com

### How to Reproduce

Log in to your account and you will be prompted that your account has been disabled

**Comment by applovinAsh** [comment]
Hi @PatrickUnity, we are unable to process Account Approval requests on GitHub. Please submit your request here: https://support.applovin.com/hc/en-us/requests/new
