### ISSUE TITLE
AppLovinFullscreenActivity memory leak on Android version 14

### ISSUE THREAD

**Issue by LevGloba** [AppLovin/AppLovin-MAX-SDK-Android#683]
### MAX SDK Version

12.5.0

### Device/Platform Info

Android14.0, Google Pixel 8 Pro

### Current Behavior

The AppLovinFullscreenActivity is not destroyed and creates a memory leak in Android version 14. After viewing a rewarded or embedded ad, and calling the destroy method on the MaxInterstitialAd or MaxRewardedAd.
![leanks](https://github.com/AppLovin/AppLovin-MAX-SDK-Android/assets/90703192/2063aff4-5063-4dd7-b90d-0e90d40f1ccb)

### How to Reproduce

On Android version 14. call loading, and then display advertising from the fragment, after showing the advertisement and when it is hidden, close the fragment. Then open the fragment, repeat the steps described above and close.

**Comment by applovinAsh** [comment]
@LevGloba, Are you able to recreate the issue in our demo application?

**Comment by LevGloba** [comment]
I reproduced the error with a memory leak on an emulator device: Google Pixel 6 (Android version 13.0); Google Piskel 8 pro (Android version 14.0), in the AppLovin MAX application Demo in Kotlin language

![leanks_appLovin_max_api 33](https://github.com/AppLovin/AppLovin-MAX-SDK-Android/assets/90703192/1c6ab3d7-6768-4e38-9df2-08f1d0239396)

![leanks_appLovin_max](https://github.com/AppLovin/AppLovin-MAX-SDK-Android/assets/90703192/49cc6a73-a05e-4d5d-a3d2-d5e0c4b4f6a6)

**Comment by LevGloba** [comment]
I also noticed in the profile that AppLovinFullscreenActivity stopped being destroyed after clicking on the cross.

![stopped_destpry](https://github.com/AppLovin/AppLovin-MAX-SDK-Android/assets/90703192/c4e4b87e-12a4-444c-b7bb-c078f77c41c8)

**Comment by applovinAsh** [comment]
@LevGloba - I am looking into this and will update you when more information is available. We appreciate your patience.

**Comment by applovinAsh** [comment]
@LevGloba - We have identified the issue and fixed the leak in our demo app. You can find the changes here: https://github.com/AppLovin/AppLovin-MAX-SDK-Android/commit/c59e86417193989f006255e53eed6f6d6dfb0649
