### ISSUE TITLE
Build failed on AGP 4.2.2 when target/compileSdkVersion 34

### ISSUE THREAD

**Issue by sosloop** [AppLovin/AppLovin-MAX-SDK-Android#686]
### MAX SDK Version

12.1.0

### Device/Platform Info

android 14

### Current Behavior

implementation ('com.applovin:applovin-sdk:12.1.0') 
implementation 'com.applovin.mediation:fyber-adapter:8.2.5.0'

gradle 6.7.1 , 4.2.2 , android sdk 34

### How to Reproduce

* What went wrong:
Execution failed for task ':launcher:processReleaseResources'.
> A failure occurred while executing com.android.build.gradle.internal.res.LinkApplicationAndroidResourcesTask$TaskAction
   > AAPT2 aapt2-4.2.2-7147631-windows Daemon #0: Unexpected error during link, attempting to stop daemon.
     This should not happen under normal circumstances, please file an issue if it does.

**Comment by applovinAsh** [comment]
@sosloop - This seems to be caused by an incompatibility between AGP 4.2.2 and Android SDK 34. You will need to update your project's AGP, as explained here: https://stackoverflow.com/questions/77032836/error-after-changing-apps-compilesdkversion-and-targetsdkversion/77622916#77622916.

**Comment by sosloop** [comment]
> @sosloop - This seems to be caused by an incompatibility between AGP 4.2.2 and Android SDK 34. You will need to update your project's AGP, as explained here: https://stackoverflow.com/questions/77032836/error-after-changing-apps-compilesdkversion-and-targetsdkversion/77622916#77622916.

unity2021 not support gradle7.1.2

**Comment by applovinAsh** [comment]
According to Unity's documentation, 7.1.2 is only compatible with Unity Versions 2022.3 and up: https://docs.unity3d.com/Manual/android-gradle-overview.html
