### ISSUE TITLE
unable to render applovin ad com.applovin.impl.adview.b.a runtimeexception SDK 12.5.0

### ISSUE THREAD

**Issue by NewMacPro** [AppLovin/AppLovin-MAX-SDK-Android#688]
### MAX SDK Version

12.5.0

### Device/Platform Info

Android 12,11....

### Current Behavior

unable to render applovin ad com.applovin.impl.adview.b.a runtimeexception

### Expected Behavior

NO crash

### How to Reproduce

I get the crash from google play console

### Additional Info

![743209ca7ec13a38fecd50450b87666e](https://github.com/user-attachments/assets/e41a452a-8303-4dde-a290-fd3711e92362)

**Comment by NewMacPro** [comment]
![b344b19eeb67bddf873bb0ac7034cbaa](https://github.com/user-attachments/assets/2e1950d0-8236-491f-8748-3528881ce32f)
another one

**Comment by richashukla23** [comment]
@NewMacPro Could you please share an Android profiler session with us for further analysis?

**Comment by NewMacPro** [comment]
@richashukla23

**Comment by NewMacPro** [comment]
This is the crash record of Google Play Console. I don't have any other.

**Comment by richashukla23** [comment]
Thanks @NewMacPro. What is your Ad Review version? Can you please make sure to be on Ad Review version 5.4.2 and see if that fixes the issue?

**Comment by NewMacPro** [comment]
@richashukla23 


    implementation 'com.applovin:applovin-sdk:12.5.0'
    implementation 'com.applovin.mediation:vungle-adapter:7.3.2.0'
    implementation 'com.applovin.mediation:mintegral-adapter:16.7.31.0'
    implementation 'com.applovin.mediation:bytedance-adapter:5.9.0.6.0'
//  implementation 'com.applovin.mediation:google-adapter:23.1.0.0'
    implementation 'com.applovin.mediation:unityads-adapter:4.11.3.0'
    implementation 'com.applovin.mediation:facebook-adapter:6.17.0.0'

**Comment by NewMacPro** [comment]
@richashukla23 

    implementation 'com.applovin:applovin-sdk:12.5.0'
    implementation 'com.applovin.mediation:vungle-adapter:7.3.2.0'
    implementation 'com.applovin.mediation:mintegral-adapter:16.7.31.0'
    implementation 'com.applovin.mediation:bytedance-adapter:5.9.0.6.0'
    implementation 'com.applovin.mediation:google-adapter:23.1.0.0'
    implementation 'com.applovin.mediation:unityads-adapter:4.11.3.0'
    implementation 'com.applovin.mediation:facebook-adapter:6.17.0.0'

**Comment by NewMacPro** [comment]
@richashukla23 
Ad Review， Is it an sdk, vungle, admob, or something else?

**Comment by richashukla23** [comment]
Ad Review is a tool provided via AppLovin SDK. You can find more information [here](https://developers.applovin.com/en/ad-review/overview/). 

You can find the Ad Review version via [Mediation Debugger](https://developers.applovin.com/en/android/testing-networks/mediation-debugger/) or device logs by filtering for "Ad review version".

Since you are on an older version of AppLovin SDK - we recommend updating to the latest AppLovin SDK which should update your Ad Review version as well.

**Comment by Lorenzo45** [comment]
@NewMacPro - OutOfMemoryErrors indicate that the device is running low on memory. This could mean that the app has a memory leak or high memory usage. When the device is running low on memory, many things can result in an OutOfMemoryError, this is not specific to our SDK.

I'd recommend using the Android Studio memory profiler to check the memory usage of your app and see if there are any memory leaks or consistent memory usage increase. If your app requires high memory usage, you may consider making your app eligible on high memory devices only to reduce crashes.

If you see any indications of memory leaks or abnormally high memory usage coming from our SDK, please feel free to open a new ticket with details and we can investigate. Thanks
