### ISSUE TITLE
The request number is too much when Ads response failure

### ISSUE THREAD

**Issue by congdanh1608** [AppLovin/AppLovin-MAX-SDK-Android#689]
### MAX SDK Version

12.5.0

### Device/Platform Info

Android

### Current Behavior

Hi,
I have an issue: High ad request frequency can negatively affect revenue rates.

https://developers.applovin.com/en/android/ad-formats/interstitial-ads/
I see in the Max documentation that the onAdLoadFailed function includes a function to resend the request after N seconds. However, if there are limits set on the Dashboard, such as daily caps or cooldown periods, the app isn't aware of these limits. As a result, when the user reaches these limits, the app will receive a response onAdLoadFailed from the Max server, then the app will continue to send new requests indefinitely.

Has anyone encountered the same issue?  
Does Max have any solutions or suggestions to help reduce requests after an ad load failure?

Thank you!

a 

### How to Reproduce

On the Max dashboard, the limit daily cap is 3 per day. Cooldown is 5 mins.

### Additional Info

![image](https://github.com/user-attachments/assets/2d3714af-4430-4446-b4cb-0c41d27fe522)

**Comment by applovinAsh** [comment]
@congdanh1608—The retry attempt code is just a suggestion on how to request ads when an ad fails to load. If you are using frequency capping, you will need to make adjustments to handle the request properly and obey your frequency capping time set.

**Comment by congdanh1608** [comment]
Hi @applovinAsh 
Thanks for your reply.

I have another question. While the interstitial/banner/open ads are sending a request to the Max server if I call maxAd?.loadAd() again, I get a log message similar to 'The ad is already requesting.' Does this count as a request on the Max dashboard, or does the Max SDK already prevent duplicate requests locally on the device?

Thank you.

**Comment by applovinAsh** [comment]
@congdanh1608—it should not be counted on the dashboard, and you should also not call load ad while an ad request is in process.

**Comment by applovinAsh** [comment]
@congdanh1608 - We do not count that as a request on the dashboard. We also do not recommend making ad requests while an ad is loading.

**Comment by congdanh1608** [comment]
Hi @applovinAsh 
Thanks for your reply. 
I was asking about the case where there are additional requests (user does other action to trigger ads) while waiting for a response from the Max server. But I will handle it. 
Thanks.
