### ISSUE TITLE
please add native ad demo, i am a mopub user.

### ISSUE THREAD

**Issue by williamycyh** [AppLovin/AppLovin-MAX-SDK-Android#69]

**Comment by thomasmso** [comment]
Hey @williamycyh - We are actively working on adding native ads demos into the demo apps. (cc @Billy-Hu)

**Comment by thomasmso** [comment]
@williamycyh - We just merged native ads demo into master: https://github.com/AppLovin/AppLovin-MAX-SDK-Android/pull/97
