### ISSUE TITLE
Crashes are spiking com.vungle.warren.utility.FileUtility.writeSerializable

### ISSUE THREAD

**Issue by jesphinpt** [AppLovin/AppLovin-MAX-SDK-Android#690]
### MAX SDK Version

11.11.3

### Device/Platform Info

Android

### Current Behavior

Crashing the app

Crashes are spiking for an issue in version 4.2.0 in the last hour.
Investigate issue
com.vungle.warren.utility.FileUtility.writeSerializable
java.lang.NoSuchMethodError - No direct method clear(BLjava/io/OutputStream;)V in class Ljava/io/ObjectStreamClass$$ExternalSyntheticLamb...

```
100%
Sanmu - FIH Foxconn
100%
Vortex Z23
```

### Expected Behavior

It needs to work without crashes.

### How to Reproduce

Add Vungle and the applovin sdks

**Comment by applovinAsh** [comment]
@jesphinpt—Can you send the stack trace of the crash so we can get more information? From what you are providing, it looks to be an issue with Liftoff.
