### ISSUE TITLE
setLocationCollectionEnabled() has been removed in 12.6.0 without any information in the documentation!

### ISSUE THREAD

**Issue by theboubougne** [AppLovin/AppLovin-MAX-SDK-Android#692]
### MAX SDK Version

12.6.0

### Device/Platform Info

Android

### Current Behavior

I cannot call this method anymore

### Expected Behavior

I want to be able to set this true or false

### How to Reproduce

Just update the SDK to 12.6.0 and this method isn't there anymore

**Comment by richashukla23** [comment]
This method has been deprecated and is no longer available in our SDK.

**Comment by richashukla23** [comment]
This method has been deprecated and is no longer available in our SDK.

**Comment by theboubougne** [comment]
I got that but where is the documentation about the new way to achieve the
same feature???
You don't remove functions without updating the documentation!

**Comment by thomasmso** [comment]
@theboubougne - our SDK does not have any location collection logic.

**Comment by theboubougne** [comment]
That doesn't make any sense. You had until your previous version and all
3rd party networks used through your mediation have locations input to
provide better /customized ads
