### ISSUE TITLE
AppLovinSdkSettings.setCreativeDebuggerEnabled:java.lang.NullPointerException: Attempt to read from a field on a null object reference

### ISSUE THREAD

**Issue by harinlin** [AppLovin/AppLovin-MAX-SDK-Android#695]
### MAX SDK Version

12.5.0

### Device/Platform Info

Android 10

### Current Behavior

  Fatal Exception: java.lang.NullPointerException: Attempt to read from a field on a null object reference

### Expected Behavior

Non   Fatal Exception: java.lang.NullPointerException: Attempt to read from a field on a null object reference

### How to Reproduce

Crash reported by firebase

### Additional Info

     Fatal Exception: java.lang.NullPointerException: Attempt to read from a field on a null object reference
   at com.applovin.sdk.AppLovinSdkSettings.setCreativeDebuggerEnabled(SourceFile:3)
   at com.applovin.impl.pj.c(SourceFile:497)
   at com.applovin.impl.sdk.t.a(SourceFile:15)
   at com.applovin.impl.sdk.t.a(SourceFile:14)
   at com.applovin.impl.sdk.array.ArrayService.createAppHubServiceIntent(SourceFile:14)
   at com.applovin.impl.sdk.array.ArrayService.<init>(SourceFile:22)
   at com.applovin.impl.sdk.k.l(SourceFile:1)
   at com.applovin.impl.sdk.k.Q0(SourceFile:10)
   at com.applovin.impl.sdk.k.R0(ProGuard:1)
   at java.lang.Thread.run(Thread.java:764)

**Comment by richashukla23** [comment]
@harinlin Can you please share the following details:
- How frequently are the crashes happening and what is the overall percentage impact on users?
- Do you have a breakdown of the devices experiencing the crash?
- Can you confirm the SDK versions encountering the crashes?

**Comment by harinlin** [comment]
> @harinlin Can you please share the following details:
> 
> * How frequently are the crashes happening and what is the overall percentage impact on users?
> * Do you have a breakdown of the devices experiencing the crash?
> * Can you confirm the SDK versions encountering the crashes?

1. This crash is a small crash rate and  impact very few users
2. Happened sdk version 12.5.0 / review version 5.4.2

**Comment by Lorenzo45** [comment]
Hi @harinlin - thanks for reaching out. We have not seen this crash before and the stack trace you sent does not align with any code paths in our SDK. If this crash escalates or you have any more information you can provide, feel free to reopen the ticket and share more details.
