### ISSUE TITLE
MaxAdReward Configuration Click url

### ISSUE THREAD

**Issue by qwer3210185** [AppLovin/AppLovin-MAX-SDK-Android#696]
### Feature Description

MaxAdReward Configuration Click the url. Is it supported to add custom parameters?

**Comment by applovinAsh** [comment]
@qwer3210185 - Can you clarify what MaxAdReward Configuration Click you are referring to?

**Comment by qwer3210185** [comment]
![截屏2024-08-03 09 55 00](https://github.com/user-attachments/assets/5eb4e602-da41-47f0-acd6-86085df16fbd)
If you click the url, can you add custom parameters?

**Comment by qwer3210185** [comment]
> @qwer3210185 - Can you clarify what MaxAdReward Configuration Click you are referring to?

If you click the url, can you add custom parameters?
![Uploading 截屏2024-08-03 09.55.00.png…]()

**Comment by applovinAsh** [comment]
We have a set list of supported macros explained in our documentation that you can find here: https://developers.applovin.com/en/advanced-features/direct-sold#adding-creative-tags

**Comment by qwer3210185** [comment]
我希望在Tracking URLs上，添加自定义的宏参数，而不是官方文档中定义的固定宏参数值。

> We have a set list of supported macros explained in our documentation that you can find here: https://developers.applovin.com/en/advanced-features/direct-sold#adding-creative-tags

I want to add custom macro parameters to Tracking URLs, rather than the fixed macro parameter values defined in the official documentation.

**Comment by qwer3210185** [comment]
> We have a set list of supported macros explained in our documentation that you can find here: https://developers.applovin.com/en/advanced-features/direct-sold#adding-creative-tags

I want to add custom macro parameters to Tracking URLs, rather than the fixed macro parameter values defined in the official documentation.

**Comment by qwer3210185** [comment]
> We have a set list of supported macros explained in our documentation that you can find here: https://developers.applovin.com/en/advanced-features/direct-sold#adding-creative-tags

Can I set it up like this? If there is, please guide me.

**Comment by applovinAsh** [comment]
We do not support custom macros.

**Comment by qwer3210185** [comment]
> We do not support custom macros.

Excuse me, how to control the UI display of the countdown advertisement?

**Comment by applovinAsh** [comment]
We do not support changing the display of the countdown timer, and we are sorry for any inconvenience this may cause.
