### ISSUE TITLE
UnityAds 4.12.2 will keep all your classes and increase your apk size

### ISSUE THREAD

**Issue by gzjaychen** [AppLovin/AppLovin-MAX-SDK-Android#701]
### MAX SDK Version

any

### Device/Platform Info

android

### Current Behavior

UnityAds 4.12.2 proguard

-keep public class * {
    *;
}

wait for unity update.

### How to Reproduce

use UnityAds 4.12.2.0 will increase your apk size.

**Comment by alvarshahanji** [comment]
Could you report this to Unity team? Thank you.
