### ISSUE TITLE
Opt : GoogleAds init  background thread ?

### ISSUE THREAD

**Issue by harinlin** [AppLovin/AppLovin-MAX-SDK-Android#702]
### Feature Description

According to google blog: https://ads-developers.googleblog.com/2024/07/reduce-anrs-when-implementing-mobile-ads.html
Is google ads  init in  background thread?
If not in background thread, please follow google suggestion.
Thanks,

**Comment by harinlin** [comment]
@applovin-mobile-engineering

**Comment by applovinAsh** [comment]
@harinlin - We call Google's init on the background thread.
