### ISSUE TITLE
AppLoving version 12.6.1 is not compliant with android google play policies

### ISSUE THREAD

**Issue by Satendra9984** [AppLovin/AppLovin-MAX-SDK-Android#707]
### Feature Description

So I had recently published my flutter app [https://play.google.com/store/apps/details?id=com.vicharshala.link_vault](url) with AppLovin integeration with 
`implementation("com.google.ads.mediation:applovin:12.6.1.0")
`
And got the update rejection from play team
Issue found: Invalid Data safety form
We reviewed your app’s Data safety form in Play Console and found discrepancies between it and how the app collects and shares user data. All apps are required to complete an accurate Data safety form that discloses their data collection and sharing practices - this is required even if your app does not collect any user data.

We detected user data transmitted off device that you have not disclosed in your app’s Data safety form as user data collected.

You must ensure that your app’s Data safety section accurately reflects your app’s data collection, sharing, and handling practices. This includes data collected and handled through any third-party libraries or SDKs used in your app. When available, we’ve included details on SDKs that contain code similar to the code in your APK that may be sending user data off device. You can check if your app uses any of these SDKs, but note that this list of SDKs may not be exhaustive. You must review and account for all data collected and shared by your app.

Issue details

We found an issue in the following area(s):

Version code 13: Policy Declaration - Data Safety Section: Device Or Other IDs Data Type - Device Or Other IDs (some common examples may include Advertising ID, Android ID, IMEI, BSSID, MAC address), Possible SDKs: com.applovin:applovin-sdk
To bring your app into compliance, follow these steps:

com.applovin:applovin-sdk com.applovin:applovin-sdk: Consider upgrading to a policy-compliant version of the SDK if available from your SDK provider, or removing the SDK.
About the [Data safety section in Google Play User Data policy](https://notifications.google.com/g/p/ANiao5rvnwSSzuerWa44wAbQUUAidKR4gnedRFc-aXiU0p2xEaI85yE3XdzjsQkLtS4SG7SWo-SQQ-pfaIoIKpOSL5Kmhg_UxFTsCpoM4ywVwvaVrWKXOEx3zxdd5XPGUDC6FXI4zBnoDd_to4rsEGzQN8eMH7iOtf5xq9WRtP846FUi0YL3YhtkuF4EYpA0G1ZGfFw-GxEZMjaZ5cj5SHJeGufkQjNn8mPVl_tztM7lhULWPUzvzp-QDO8keZfbTFtpjYrGO9VG3V45jiJnwfPlkJDH74BBgDXuyA)
Your app must be in compliance with this policy. If your app continues to be non-compliant, your app updates will be rejected and your app may face additional enforcement actions in the future.

Please make changes to align your app’s Data safety form with the app’s behavior. This can be done by either:

Updating your form in Play Console to declare collection of Data Types noted below; or
Removing unwanted functionality and attributable code that collects this user data from your app or libraries used in your app, and when applicable to deactivate all non-compliant APKs.
To deactivate non-compliant APKS, you can create a new release and upload a compliant APK to each track containing the non-compliant APKs.
Be sure to increment the APK version code. If using staged rollout, be sure to set the release to 100% rollout.
For helpful resources, you can:

Learn more about how to [provide app privacy and security information for Google Play's Data safety section](https://notifications.google.com/g/p/ANiao5pS6kRLZgFh0pSxlQsDx9L1Y5A-PSk5yHRchhbXWoh5WuSy-11x_TEhuZCq8CS1I9IgQ8914zUoHA0h6G_MCcKbzWUGx2tia8YlWPiv_IUgKKSrzbs4AwFwFL2fxUiACeQMoXBAQia4Yre59wAXu6PCWHY2cX8pwzf3jg9HgjHnmiJi8kKKqC_Kbus9AUL-kzYXNjkMh4lCtQFpsaM0KRcRWQP1LCm3z0FyrccfNzwlvwVS6thTCxr-n5a0qh0s1I9sdxt17tRlAb4).

**Comment by applovinAsh** [comment]
Hi @Satendra9984, you may need to update your app's data safety policies to include Device or other IDs, like so: 
![image](https://github.com/user-attachments/assets/f491a954-8e05-4194-94ca-a9edb89a6703)

Here is an example: This is an example: https://play.google.com/store/apps/datasafety?id=com.peoplefun.wordcross&hl=en_US
