### ISSUE TITLE
Mintegral OnAdRevenuePaidEvent have clear creativeId field 

### ISSUE THREAD

**Issue by RomanNiki** [AppLovin/AppLovin-MAX-SDK-Android#718]
### MAX SDK Version

6.5.2

### Device/Platform Info

Android

### Current Behavior

Callback MaxSdkCallbacks.(any).OnAdRevenuePaidEvent from Mintegral have clear field creativeId 

### Expected Behavior

callback from Mintegral have creativeId

### How to Reproduce

get MaxSdkCallbacks.(any).OnAdRevenuePaidEvent from Mintegral.

### Reproducible in the demo app?

Not Tested

### Additional Info

<img width="348" alt="image" src="https://github.com/user-attachments/assets/b2991131-9836-4e96-8554-eb0d8b469752">

**Comment by alvarshahanji** [comment]
@RomanNiki I do see Mintegral creativeIdentifier being passed correctly. But if you are seeing it missing for certain ads, please reach out to the Mintegral team. Thank you!
