### ISSUE TITLE
Permission undetected "com.google.android.gms.permission.AD_ID"

### ISSUE THREAD

**Issue by affane1** [AppLovin/AppLovin-MAX-SDK-Android#72]
Dear support team,

Since I made the last Applovin SDK update (10.3.5), i'm facing this issue of undetected permission "com.google.android.gms.permission.AD_ID" even though i'm mentioning it in my AndroidManifest.xml

Is it a known issue ? I couldn't find a solution anywhere on internet.
Please find below the screenshots related to this issue. I'm ready to provide any other information/stacks if needed.
Thanks in advance, best regards !

![image](https://user-images.githubusercontent.com/74044522/147465216-1bd191d2-2af7-4271-a442-ca5de143610d.png)
![image](https://user-images.githubusercontent.com/74044522/147465252-4ad7ad9f-d458-44b0-be71-e41fc2a96019.png)
![image](https://user-images.githubusercontent.com/74044522/147465331-61b5fbb6-cb40-4ec3-80af-86d1e7940804.png)

**Comment by thomasmso** [comment]
I assume this is only happening in the emulator? It can be ignored and next SDK release will not have the warning.

**Comment by affane1** [comment]
Indeed, this 'invalid integration' warning only shows on the Mediation debugger. The ads are running correctly.
Thanks for the hint, i'll just ignore it then.
Best regards!

**Comment by thomasmso** [comment]
Sounds good - let us know if you encounter any other issues!
