### ISSUE TITLE
Fatal Exception: kotlin.UninitializedPropertyAccessException

### ISSUE THREAD

**Issue by chaoshengyuan** [AppLovin/AppLovin-MAX-SDK-Android#727]
### MAX SDK Version

12.3.1

### Device/Platform Info

More than 10 different models

### Crashes/ANRs per Day

Last 180 days

### Percentage of Users Affected

More than 100 crashes

### First Occurrence of Crash/ANR

Always have

### Exception and Stack Trace

Fatal Exception: kotlin.UninitializedPropertyAccessException
lateinit property unsafeApplication has not been initialized
com.chartboost.sdk.impl.g4.d (SourceFile:8)
com.chartboost.sdk.impl.g4.a (SourceFile:1)
com.chartboost.sdk.impl.g4$a.a (SourceFile:2)
com.chartboost.sdk.impl.g4$a.invoke
kotlin.SynchronizedLazyImpl.getValue (LazyJVM.kt:74)
com.chartboost.sdk.impl.g4.a (SourceFile:2)
com.chartboost.sdk.impl.g4$b.a (SourceFile:2)
com.chartboost.sdk.impl.g4$b.invoke
kotlin.SynchronizedLazyImpl.getValue (LazyJVM.kt:74)
com.chartboost.sdk.impl.g4.e (SourceFile:1)
com.chartboost.sdk.impl.g4$i$b.a (SourceFile:1)
com.chartboost.sdk.impl.g4$i$b.invoke
kotlin.SynchronizedLazyImpl.getValue (LazyJVM.kt:74)
com.chartboost.sdk.impl.lb$c$c.a (SourceFile:1)
com.chartboost.sdk.impl.lb$c$c.invoke
kotlin.SynchronizedLazyImpl.getValue (LazyJVM.kt:74)
com.chartboost.sdk.impl.b5.track (SourceFile:1)
com.chartboost.sdk.impl.b5.track (SourceFile:16)
com.chartboost.sdk.internal.clickthrough.EmbeddedBrowserActivity.track (SourceFile:1)
com.chartboost.sdk.internal.clickthrough.EmbeddedBrowserActivity$b.c (SourceFile:12)
com.chartboost.sdk.internal.clickthrough.EmbeddedBrowserActivity$b.onReceivedError (SourceFile:3)
WV.RN.e (chromium-TrichromeWebViewGoogle6432.aab-stable-666808133:70)
WV.Y6.handleMessage (chromium-TrichromeWebViewGoogle6432.aab-stable-666808133:406)
android.os.Handler.dispatchMessage (Handler.java:106)

com.android.internal.os.ZygoteInit.main (ZygoteInit.java:1019)

### How to Reproduce

Unable to reproduce, this is the crash reported by our firebase
![WechatIMG10](https://github.com/user-attachments/assets/020d6222-05cb-4d9f-a6e2-c1c783e77fc9)

### Reproducible in the demo app?

No

**Comment by NanaAmoah** [comment]
Hi @chaoshengyuan, it looks like this crash is coming from Chartboost's SDK. Could you report it to them?
