### ISSUE TITLE
Add support for loading ads without an Activity context for All Adapters

### ISSUE THREAD

**Issue by ibrahimeywin** [AppLovin/AppLovin-MAX-SDK-Android#729]
### Feature Description

Hello,

Recently, the ability to load ads without an activity context was integrated for the AdMob and GAM adapters. 

Could you please clarify if there are plans to extend this functionality to other adapters, and if so, is there an estimated release date? Our ANR rate has increased significantly in the latest release, and we suspect it may be related to this issue.

We need to realase urgent new version to decrase ANR's.
Thank you in advance for any information you can provide.

**Comment by thomasmso** [comment]
@ibrahimeywin - it really depends on the mediated SDK's requirements. Is there a specific adapter that you are inquiring for?

**Comment by ibrahimeywin** [comment]
Thank you so much for your quick response!

These are the most critical adapters for us.

Admob
Gam
Meta
Liftoff
DTExchange(Fyber-Inneractive)
Amazon
Pangle
Verve/Pubnative
Bidmachine
Inmobi
Mintegral
Applovin

**Comment by thomasmso** [comment]
Generally speaking, using an `Activity` instance shouldn't cause ANRs, but we're in the process of combing through the adapters to see where else we can stop passing in `Activity` references to mediated SDKs (which might hold a reference to it longer than necessary).

**Comment by ibrahimeywin** [comment]
With version 12.5.0, we send applicationcontext since it is not mandatory to use activity in load requests. 

<img width="1213" alt="ss" src="https://github.com/user-attachments/assets/6437b21e-45a5-4e31-a669-f68916f34322">


However, I think this causes problems in some adapters.
I see that there was a fix for GAM and Google a while ago, will there be an improvement for other adapters in the near future?


<img width="909" alt="ss2" src="https://github.com/user-attachments/assets/c5023e57-d0c3-4857-b2b3-136997caec5e">

**Comment by ibrahimeywin** [comment]
Hi @Kennyhbui ,

Will there be a development for other adapters in the near future?
It is very important that other adapters can load without activity context.

<img width="726" alt="ss" src="https://github.com/user-attachments/assets/b09a7c8d-f21d-475c-a3c9-257666f7e941">

**Comment by Kennyhbui** [comment]
Hi @ibrahimeywin,

I'm currently finalizing fixes to ensure there are no issues in the adapters when loading ads with an activity context. These changes will be available soon.

**Comment by ibrahimeywin** [comment]
Hi @Kennyhbui 

Thank you very much for the information. Then we will postpone our update until you complete the fixes. Originally, our plan was to release the update today.

**Comment by ibrahimeywin** [comment]
Hi @Kennyhbui , is there any date for the update?

**Comment by Kennyhbui** [comment]
Hi @ibrahimeywin, the updates should be ready early next week. I'll let you know once they're available.

**Comment by Kennyhbui** [comment]
Hi @ibrahimeywin, the adapter updates are live.

**Comment by ibrahimeywin** [comment]
Thank you very much! 
Are the same changes planned for the following adapters?
Verve
Bidmachine
Mintegral

**Comment by Kennyhbui** [comment]
@ibrahimeywin - These adapters should already have the ability to load ads without an `Activity` context. Are you experiencing issues with these adapters?

**Comment by ibrahimeywin** [comment]
@Kennyhbui Now I have checked these adapters again.

- ❌ **Mintegral**; It is given as a reference in the activity load phase. If Activity is invalid, it may cause problems. It doesn't seem to be compatible with Applicationcontext. ❌
<img width="977" alt="mintegral" src="https://github.com/user-attachments/assets/4c331d56-002d-435f-957c-6e60356ba780">

- ✅**Bidmachine**; It seems compatible because it uses getApplicationContext in the load phase.✅
<img width="1028" alt="Bidmachine" src="https://github.com/user-attachments/assets/54769279-a7a1-49ac-afdb-ffafd4e89fdd">

- ✅**Verve**; It seems compatible because it uses getApplicationContext in the load phase. ✅
<img width="1087" alt="Verve" src="https://github.com/user-attachments/assets/45d64dc9-c3be-4ce7-a4ba-8cfe5c0c540c">

**Comment by Kennyhbui** [comment]
@ibrahimeywin - Thank you for pointing that out. I'll update the Mintegral adapter shortly.

**Comment by ibrahimeywin** [comment]
@Kennyhbui  Thank you for your collaboration and support.
