### ISSUE TITLE
Support is Slow!

### ISSUE THREAD

**Issue by kovachx** [AppLovin/AppLovin-MAX-SDK-Android#73]
Hi,

I have been asking for Admob Bidding to be enabled under my ad units because I don't see it. I only see the old waterfall Admob placement option under ad units. Is it possible to enable it? I have been waiting for my ticket to be answered for weeks.

**Comment by thomasmso** [comment]
Hi @kovachx - AdMob bidding is limited to a small subset of pubs approved by Google. You must contact Google to contact us in order to proceed.

**Comment by kovachx** [comment]
I have admob bidding for a long time now I can add applovin from my Admob
account but I want to do it the other way around.
