### ISSUE TITLE
AppLovinMaxSdk never complete initialization

### ISSUE THREAD

**Issue by k-morozumi** [AppLovin/AppLovin-MAX-SDK-Android#730]
### MAX SDK Version

13.0.0, 12.6.0

### Device/Platform Info

Android 13/SH-54B, Android 14/Google Pixel 6a, Android 8.0/emulator

### Current Behavior

AppLovinSdk.getInstance(context).initialize() never call complete listener.
All ads are not displayed or exception occurs.

```
AppLovinSdk.getInstance(context).initialize(
    initConfig,
    {
        // never reach here.
        Log.d("AppLovinSdk initialized.")
    }
)
```

And mediation debugger show us `initializing ...` endlessly.
<img width="280" src="https://github.com/user-attachments/assets/4a5eaac6-57af-4096-b6d9-32466ee67f86" />

### Expected Behavior

initializing normally.

### How to Reproduce

This problem only occurs with certain combinations of devices and operating systems.
It did not occur on Android 12L/Google Pixel 6a combination.

### Reproducible in the demo app?

Yes

**Comment by k-morozumi** [comment]
Here is logs.
[2024OCT18_001.log](https://github.com/user-attachments/files/17426179/2024OCT18_001.log)

**Comment by applovinAsh** [comment]
The logs suggest that you may be using our demo application to test. However, I am unable to recreate the issue. Can you provide the project in a zip folder?

**Comment by k-morozumi** [comment]
> Can you provide the project in a zip folder?

The demo project we recognized this problem is here.
I think it it should be the same as the latest master branch (for Android).

[AppLovin-MAX-SDK-Android-master.zip](https://github.com/user-attachments/files/17452785/AppLovin-MAX-SDK-Android-master.zip)

**Comment by applovinAsh** [comment]
Thank you for providing the zip file. It's just our demo project without any additional changes, right? I was unable to recreate the issue that you are describing. I had a similar error to the one in the logs, and to fix I had to add `implementation 'androidx.browser:browser:1.4.0'` to the build.gradle file. You may also need to add `implementation 'com.google.android.gms:play-services-tasks:17.1.0'`. 

If you have done that and are still experiencing the issue, please send an updated verbose log from the start of a session.

**Comment by k-morozumi** [comment]
Thank you for reply.

I added implementation 'androidx.browser:browser:1.4.0' at app:dependencies, but not resolved.
('com.google.android.gms:play-services-tasks:17.1.0' already is in demo project.)

And I attached the log with details and ANR traces.
I hpe these logs will help to find a solution.

[2024OCT24_003.log](https://github.com/user-attachments/files/17499915/2024OCT24_003.log)
[2024OCT24_traces.txt](https://github.com/user-attachments/files/17499916/2024OCT24_traces.txt)

**Comment by applovinAsh** [comment]
Thank you for providing additional information. Can you provide device specifics where you are seeing this issue like device name, android version, android SDK version and where you are testing from?

**Comment by k-morozumi** [comment]
Thank you for your reply.

Device
emulator(AVD)
<details>
<summary>AVD editor screenshots</summary>
<img width="320" alt="so-02h_2024-10-28_13 05 36" src="https://github.com/user-attachments/assets/5c442d15-db5d-436a-a4c3-9dab4bbab109">
<img width="320" alt="so-02h_2024-10-28_13 05 50" src="https://github.com/user-attachments/assets/28f898a1-0614-4afa-9f2a-386938a3c7a6">
<img width="320" alt="so-02h_2024-10-28_13 06 03" src="https://github.com/user-attachments/assets/5d8f6767-b9e5-43e5-9eb1-6f756f1603fd">
</details>

Android Version
8.0

Android SDK Version
34

And as I wrote in this issue's body, it is also happening at Android13/SH-54B and Android 14/Google Pixel 6a.

**Comment by applovinAsh** [comment]
We are unable to recreate the issue and have had no other reports. I have collaborated with engineering, and we have released a fix for your current error in SDK version 12.1.0. Can you try invalidating caches and restarting Android Studio? You can do this by going to File > Invalidate Caches... > Invalidate and Restart

**Comment by k-morozumi** [comment]
Thank you for version 12.1.0.
I will try with this version.

**Comment by k-morozumi** [comment]
Only for the emulator, but the initialization was succeed after wiping data (using version 12.1.0.).
It could be due to the user's data on the device, not problems for SDK, so we close this issue for a moment. 

Thank you for your help.
