### ISSUE TITLE
AwDataDirLock crash logs started to appear in Firebase after integrating AppLovin SDK in my projecty

### ISSUE THREAD

**Issue by tenesuzun** [AppLovin/AppLovin-MAX-SDK-Android#731]
### MAX SDK Version

13.0.0

### Device/Platform Info

Android 9,11,12,13 - Huawei devices

### Crashes/ANRs per Day

10

### Percentage of Users Affected

10

### First Occurrence of Crash/ANR

after new integration new process started to appear on debug windows <packageName:AppMetrica> and that process started to appear in the crash logs as well.
![Sabah Firebase Crash SS](https://github.com/user-attachments/assets/88fd470b-9b8a-4d59-8897-8538760b0d86)

### Exception and Stack Trace

[tr.sabah_issue_d61f5a84f3addfb6c46bdcd244582738_crash_session_6711E0A600D7000123638940F83AFB2A_DNE_0_v2_stacktrace.txt](https://github.com/user-attachments/files/17434243/tr.sabah_issue_d61f5a84f3addfb6c46bdcd244582738_crash_session_6711E0A600D7000123638940F83AFB2A_DNE_0_v2_stacktrace.txt)
[tr.sabah_issue_d61f5a84f3addfb6c46bdcd244582738_crash_session_670F944002F000013B4772B948A3B5B4_DNE_0_v2_stacktrace.txt](https://github.com/user-attachments/files/17434244/tr.sabah_issue_d61f5a84f3addfb6c46bdcd244582738_crash_session_670F944002F000013B4772B948A3B5B4_DNE_0_v2_stacktrace.txt)
![Sabah Firebase Crash SS](https://github.com/user-attachments/assets/b685a7a3-a753-44fe-a000-a8303f97c800)

### How to Reproduce

Unfortunetly we don't know how to produce this. 

### Reproducible in the demo app?

Not Tested

### Additional Info

We have started to recieve these logs after integrating the AppLovin SDK to use in our ads. We tried our manifest files to check if there is a new process created but could not see. Tried some other possible solutions suggested on stack over flow but could not solve it and the crash logs continued to appear. We thought it could be SDK related files
[tr.sabah_issue_d61f5a84f3addfb6c46bdcd244582738_crash_session_6711E0A600D7000123638940F83AFB2A_DNE_0_v2_stacktrace.txt](https://github.com/user-attachments/files/17434350/tr.sabah_issue_d61f5a84f3addfb6c46bdcd244582738_crash_session_6711E0A600D7000123638940F83AFB2A_DNE_0_v2_stacktrace.txt)
[tr.sabah_issue_d61f5a84f3addfb6c46bdcd244582738_crash_session_670F944002F000013B4772B948A3B5B4_DNE_0_v2_stacktrace.txt](https://github.com/user-attachments/files/17434351/tr.sabah_issue_d61f5a84f3addfb6c46bdcd244582738_crash_session_670F944002F000013B4772B948A3B5B4_DNE_0_v2_stacktrace.txt)

**Comment by NanaAmoah** [comment]
Hi @tenesuzun, `AppMetrica` is a Yandex product so it looks like the crash is caused by their SDK. There's not much we can do on our end. Could you reach out to them about this?
