### ISSUE TITLE
com.fyber.inneractive.sdk.response.f

### ISSUE THREAD

**Issue by maitycyrus** [AppLovin/AppLovin-MAX-SDK-Android#740]
### MAX SDK Version

13.0.0

### Device/Platform Info

Android 13

### Crashes/ANRs per Day

100

### Percentage of Users Affected

5

### First Occurrence of Crash/ANR

With new Version 13.0.0.

### Exception and Stack Trace

Fatal Exception: java.lang.ClassCastException
com.fyber.inneractive.sdk.response.f cannot be cast to com.fyber.inneractive.sdk.response.g
com.fyber.inneractive.sdk.flow.u.g (SourceFile:5)
com.fyber.inneractive.sdk.flow.k.h (SourceFile:18)
com.fyber.inneractive.sdk.flow.k.b (SourceFile:19)
com.fyber.inneractive.sdk.flow.j.run (SourceFile:7)
android.os.Handler.handleCallback (Handler.java:971)
android.os.Handler.dispatchMessage (Handler.java:107)
android.os.Looper.loopOnce (Looper.java:206)
android.os.Looper.loop (Looper.java:296)
android.app.ActivityThread.main (ActivityThread.java:9194)
java.lang.reflect.Method.invoke (Method.java)
com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run (RuntimeInit.java:591)
com.android.internal.os.ZygoteInit.main (ZygoteInit.java:1018)

### How to Reproduce

Yes

### Reproducible in the demo app?

Yes

### Additional Info

Doctor summary (to see all details, run flutter doctor -v):
[✓] Flutter (Channel stable, 3.24.4, on macOS 15.0.1 24A348 darwin-arm64, locale en-AT)
[✓] Android toolchain - develop for Android devices (Android SDK version 34.0.0)
[✓] Xcode - develop for iOS and macOS (Xcode 16.0)
[✓] Chrome - develop for the web
[✓] Android Studio (version 2024.2)
[✓] Android Studio (version 2022.1)
[✓] IntelliJ IDEA Community Edition (version 2023.1)
[✓] IntelliJ IDEA Ultimate Edition (version 2023.1)
[✓] VS Code (version 1.95.0)
[✓] Connected device (4 available)            
[✓] Network resources

**Comment by NanaAmoah** [comment]
Hi @maitycyrus, it looks like this crash is coming from Fyber (now DT Exchange)'s SDK. Could you report this to them?
