### ISSUE TITLE
Facebook SDK Integration Memory Leak

### ISSUE THREAD

**Issue by ipena-spigot** [AppLovin/AppLovin-MAX-SDK-Android#745]
### MAX SDK Version

13.0.1

### Device/Platform Info

Pixel 4 XL - Android 13

### Current Behavior

Android Studio Profiler tool detects memory leaks after rendering the following Ad format when using `Facebook SDK 6.18.0.1`:
* Native

This is preventing Activities from getting garbage collected and ultimately causing ANRs and crashes

### Expected Behavior

Resources / references should be released such that no memory leaks occur

### How to Reproduce

Mrec
- MAX Mediation Debugger
- Completed SDK integrations
- `Facebook (6.18.0.1)`
- Test Mode
- Native (in MREC vs Native section)
- Native (In the section with the 5 Ad formats)
- Load
- Close Activity
- Check for memory leak with Android Studio profiler***

Steps for: Check for memory leak with Android Studio***
- In Android Studio
- Profiler
- Analyze Memory Usage
- Start profiler task
- Click on Detected 2 Leaks
- `MaxDebuggerMultiAdActivity`
- In the `Instance` tab: `MaxDebuggerMultiAdActivity`
- `References` tab
- `Show nearest GC root only`
- Expand non `referent in WeakReference` references

### Reproducible in the demo app?

Yes

### Additional Info

Native `Facebook SDK 6.18.0.1` Memory Leak:
![Screenshot 2024-11-05 at 2 16 25 PM](https://github.com/user-attachments/assets/94c57dd5-924b-410c-b4e1-1d6e08839bef)

**Comment by mattn02** [comment]
Hi @ipena-spigot - I was able to reproduce this memory leak and it is caused by Facebook's SDK with their `MediaView`. Could you please report it to the Meta Audience Network team? Thanks!
