### ISSUE TITLE
HyprMX fail to download

### ISSUE THREAD

**Issue by felipeViana** [AppLovin/AppLovin-MAX-SDK-Android#75]
Since today, our builds are failing because can't download HyprMX artifact

```
> Could not download HyprMX-SDK.aar (com.hyprmx.android:HyprMX-SDK:6.0.1)
   > Could not get resource 'https://hyprmx.jfrog.io/artifactory/hyprmx/com/hyprmx/android/HyprMX-SDK/6.0.1/HyprMX-SDK-6.0.1.aar'.
      > Could not GET 'https://hyprmx.jfrog.io/artifactory/hyprmx/com/hyprmx/android/HyprMX-SDK/6.0.1/HyprMX-SDK-6.0.1.aar'.
         > Read timed out
```

**Versions used:**
- applovin-sdk:10.3.5
- hyprmx-adapter:6.0.1.0

we're using the repository as mentioned in applovin docs
```
maven {
    // Repository for HyprMx.
    url "https://hyprmx.jfrog.io/artifactory/hyprmx"
}
```

Is there any fix for now?

**Comment by alvarshahanji** [comment]
@felipeViana could be network delay issue. I just tried and worked on my end. Could you please try again?

**Comment by felipeViana** [comment]
Hi, the problem seems to be solved now, for me it's working.
It was probably just an instability on their system or something like that.

Thanks for the help!

**Comment by vovasazonov** [comment]
Hi! We have same problem. 
`[ INFO     ] > Could not resolve all task dependencies for configuration ':launcher:releaseRuntimeClasspath'.
15:31:23 [ INFO     ]    > Could not resolve com.hyprmx.android:HyprMX-SDK:6.0.1.
15:31:23 [ INFO     ]      Required by:
15:31:23 [ INFO     ]          project :launcher > project :unityLibrary > com.applovin.mediation:hyprmx-adapter:6.0.1.6
15:31:23 [ INFO     ]       > Could not resolve com.hyprmx.android:HyprMX-SDK:6.0.1.
15:31:23 [ INFO     ]          > Could not get resource 'https://artifactory.verizonmedia.com/artifactory/maven/com/hyprmx/android/HyprMX-SDK/6.0.1/HyprMX-SDK-6.0.1.pom'.
15:31:23 [ INFO     ]             > Could not HEAD 'https://artifactory.verizonmedia.com/artifactory/maven/com/hyprmx/android/HyprMX-SDK/6.0.1/HyprMX-SDK-6.0.1.pom'.
15:31:23 [ INFO     ]                > Read timed out`
