### ISSUE TITLE
onAdHidden have long time callback

### ISSUE THREAD

**Issue by tracer8** [AppLovin/AppLovin-MAX-SDK-Android#756]
### MAX SDK Version

Last

### Device/Platform Info

A71

### Current Behavior

When displaying interstitial or reward ads, I noticed that the onAdHidden callback is significantly delayed when using MAX Mediation compared to using Admob directly. While testing with Admob test ads, I found that MAX Mediation takes at least 2-3 seconds longer to return the callback than standalone Admob implementation. Could you please investigate and resolve this performance issue? Thank you!
I am confident that this issue also occurs in the MAX Demo app.

Admob Test Inter ID: ca-app-pub-3940256099942544/1033173712
Admob Test AppID: ca-app-pub-3940256099942544~3347511713

### Expected Behavior

Callback from onAdHidden return faster almost immediately

### How to Reproduce

- Show inter
- Close inter
- Watch the callback return

### Reproducible in the demo app?

Yes

**Comment by alvarshahanji** [comment]
We forward the callback when AdMob fires it. You can see the AdMob callbacks and MAX callbacks in the verbose logs as well.

Could you share [verbose logs](https://developers.applovin.com/en/max/faq/how-to-enable-verbose-logging-in-the-applovin-sdk) where you test AdMob test ads?

**Comment by tracer8** [comment]
Yes, here is the verbose log from start showing to close inter ad from Applovin MAX:
[CallBackInterClose.log](https://github.com/user-attachments/files/18108007/CallBackInterClose.log)

**Comment by alvarshahanji** [comment]
Thanks for the logs!

```
2024-12-12 15:23:13.089 18342-18342/com.example.platformsdks I/AppLovinSdk: [GoogleMediationAdapter] Interstitial ad hidden: ca-app-pub-3940256099942544/1033173712
2024-12-12 15:23:13.608 18342-18342/com.example.platformsdks D/AppLovinSdk: [MaxInterstitialAd] MaxAdListener.onAdHidden(ad=MediatedAd{thirdPartyAdPlacementId=ca-app-pub-3940256099942544/1033173712, adUnitId=acc968b6b1bb7ae0, format=INTER, networkName='Google AdMob'}), listener=com.airbnb.lottie.ads.adapters.max.MaxNetwork$2@193256

```

As you can see, in the above two logs there is no time gap. The first log is printed when the AdMob SDK fires the [onAdDismissedFullScreenContent()](https://github.com/AppLovin/AppLovin-MAX-SDK-Android/blob/master/Google/src/main/java/com/applovin/mediation/adapters/GoogleMediationAdapter.java#L1026) callback. You can also check by adding logs in the onAdHidden  callbacks you receive from AppLovin MAX. Let us know if you have any questions.

**Comment by tracer8** [comment]
`2024-12-12 15:23:13.089 -> 2024-12-12 15:23:13.608`
You can observe a delay of approximately 1 second in the callback response, which is not the immediate response I expected. This noticeable delay occurs consistently, unlike the instant response we typically get with direct Admob implementation.
