### ISSUE TITLE
[SDK v11.0.0] Native ad never load, always return 204 error code

### ISSUE THREAD

**Issue by Mouadabdelghafouraitali** [AppLovin/AppLovin-MAX-SDK-Android#77]
I always get 204 error code

    **************************************************
    NO FILL received:
    ..ID: "my_id"
    ..FORMAT: "NATIVE"
    ..SDK KEY: "my_sdk_key"
    ..PACKAGE NAME: "maa.abc"
    ..Reason: [{"code":1020,"msg":"Parse Response Error"},{"code":1000,"msg":"Ad network does not match filter ad networks list"}]
    **************************************************

**Test mode is enabled**

**Comment by ltsadevs** [comment]
```
E/AppLovinSdk: [AppLovinSdk] 
    **************************************************
    NO FILL received:
    ..ID: "***********"
    ..FORMAT: "NATIVE"
    ..SDK KEY: "**********"
    ..PACKAGE NAME: "com.*****.#####"
    ..Reason: [{"code":1020,"msg":"Parse Response Error"},{"code":1000,"msg":"Ad network does not match filter ad networks list"}]
    **************************************************
```

I am having same issue, native ads do not load even in test mode it shows no fill.

**Comment by williamycyh** [comment]
I am having same issue, native ads do not load even in test mode it shows no fill.

**Comment by ltsadevs** [comment]
@Mouadabdelghafouraitali Use a test device and set an ad network which supports native ad formats.

**Comment by Mouadabdelghafouraitali** [comment]
@ltsadevs I've done all that (just read what I've written)

**Comment by thomasmso** [comment]
Hey all - 

Please use [test mode](https://dash.applovin.com/documentation/mediation/android/testing-networks/test-mode) to test your native ads integration. As of now, AppLovin is the only one with stable test ads, and we're currently working on adding support for test ads from other networks including Facebook.
