### ISSUE TITLE
MoPubRecyclerAdapter class

### ISSUE THREAD

**Issue by deeteeh** [AppLovin/AppLovin-MAX-SDK-Android#78]
We use MoPubRecyclerAdapter class to dynamically set the positions of ads from Mopub dashboard in a recycle view. It is very useful for some developer.

As of MAX sdk 11, the class is not included in the sdk. Kindly add it to the sdk.

**Comment by tracer8** [comment]
It is early of MAX SDK upgrade from Mopub. 
I think it will take time to reliable and add more features.

**Comment by nihp** [comment]
@ltsadevs I am using Mopub, do you know any migration guides from Mopub to applovin?

**Comment by ltsadevs** [comment]
@nihp Use 'Ad nUnit Manager' to import your all ad units from MoPub dashboard.

**Comment by nihp** [comment]
@itsadevs Thanks.

Are you mentioning the Ad Unit Manager from the applovin? or anything else?
I have a question as well, any option to show the video and native ads, I have used these sdks from the **mopub mopub-sdk-native-static:5.4.1, mopub-sdk-native-video:5.4.1, mopub-sdk-interstitial:5.4.1**

**Comment by thomasmso** [comment]
Hey yall - 

MAX native ads is still in its infancy, but we are listening to you and will build what is needed to ensure smoother integrations.

MoPub has the AdPlacer API and RecyclerView API, which one are you asking for specifically?

**Comment by ltsadevs** [comment]
Hi @thomasmso, both AdPlcaer and RecyclerView API are required for implementing ads on recyclerview and controlling the positions from server side.
MoPub implementation- [Integrate Native Ads Using Ad Placer and MoPubRecyclerAdapter](https://developers.mopub.com/publishers/android/native-recyclerview/#integrate-native-ads-using-ad-placer-and-mopubrecycleradapter)

**Comment by Luklek** [comment]
This. If it's not implemented, I will not choose to MAX surely.

**Comment by thomasmso** [comment]
We will implement it. We have a lot of other changes that are in our pipeline in order to support the migration from MoPub, we're looking at ideally an SDK release EoM.

**Comment by vishnusp** [comment]
> This. If it's not implemented, I will not choose to move to MAX.

That would be the right decision according to me. At the moment MAX sdk is highly unstable and mostly fills no ads. All my facebook placements became idle after MAX migration. Fb team says, they are receiving waterfall request which is no more supported by fb.
And MAX support is very poor that they either won't respond or tell nothing they can do.

**Comment by Luklek** [comment]
> > This. If it's not implemented, I will not choose to move to MAX.
> 
> That would be the right decision according to me. At the moment MAX sdk is highly unstable and mostly fills no ads. All my facebook placements became idle after MAX migration. Fb team says, they are receiving waterfall request which is no more supported by fb. And MAX support is very poor that they either won't respond or tell nothing they can do.

It's really strange that they didn't simply rebrand the vastly superior MoPub SDK to MAX/AppLovin/Whatever instead of having so much work to do both on their side and the user side too.

**Comment by tfkci** [comment]
Any enhancement about this issue? We need to migrate our users from MoPub to Apploving and just waiting for this issue. Since there will be a migration time for users to update their apps MoPub servers are going to down at the end of the month, we need to migrate these days.

**Comment by Luklek** [comment]
Yes, this is stopping me from starting out the migration

**Comment by chauduyphanvu** [comment]
@tfkci, @Luklek - understood the urgency on your end, we are currently working on this feature and will ship it out ASAP. Thanks for your patience!

**Comment by nihp** [comment]
I am also going to migrate to MAX. @all who are in the process of migrating the Mopub to MAX, could you please let me know, is there is any vast changes are there for **mopub mopub-sdk-native-static:5.4.1, mopub-sdk-native-video:5.4.1, mopub-sdk-interstitial:5.4.1**

Clarification: I only have the the sdk id, don't have the app lovin account. Is it fine to migrate using the repo update. And where can I get the migration guide for the above three packages. It will be helpful for me.

Thanks

**Comment by nihp** [comment]
Can anyone let me know the equivalent package to for mopub **mopub-sdk-native-static:5.4.1, mopub-sdk-native-video:5.4.1, mopub-sdk-interstitial:5.4.1** in applovin?

Thanks

**Comment by ltsadevs** [comment]
Their support is pathetic, I emailed them regarding native ads, still no reply from them. Also, their mediation is biased. With low ecpm($0.05) applovin's impression is getting rendered even though other networks provide much higher ecpm. You can not even see stats of how many ad requests you are getting. They destroyed superior MoPub. I am moving out from MAX. If you are serious about your revenue, please find any other mediation provider.

**Comment by vishnusp** [comment]
I also have same experience. MAX seems to be biased for me also as most of the impressions are only for AppLovin which has the lowest eCpm. And many times they don't have any ad fills also. So I integrated FB ads directly and I always have ad fills. But  MAX mediation with FB and few networks has no fills. With all these, I have decided to move out of AppLovin. Really sad to see such a good platform MoPub being destroyed like this!

**Comment by Luklek** [comment]
Another thing I don't understand is why AppLovin still has such a bad eCPM/fillrate now that they acquired the MoPub marketplace. Is the process not yet completed? I expected my apps which already had AppLovin SDK inside would see a big boost in AppLovin revenue comparable to MoPub marketplace

**Comment by taugin** [comment]
> I also have same experience. MAX seems to be biased for me also as most of the impressions are only for AppLovin which has the lowest eCpm. And many times they don't have any ad fills also. So I integrated FB ads directly and I always have ad fills. But MAX mediation with FB and few more networks has no fills. With all these, I have decided to move out of AppLovin. Really sad to see such a good platform MoPub being destroyed like this!

Any other better mediation recommendations?

**Comment by Luklek** [comment]
Sad to hear that along the integration problems AppLovin can't even run a waterfall/bidding properly :(

**Comment by nihp** [comment]
Any updates on this?

**Comment by silane-tech** [comment]
@thomasmso @chauduyphanvu Still no update on this? Half of March gone still no improvements on native and banner ad's eCPM.

**Comment by chauduyphanvu** [comment]
Hi all, the feature is ready and undergoing testing. We plan to ship it for iOS first in ~2 weeks, and then for Android in about a month.

Thanks for your patience as we finalize the feature.

**Comment by Luklek** [comment]
> Hi all, the feature is ready and undergoing testing. We plan to ship it for iOS first in ~2 weeks, and then for Android in about a month.
> 
> Thanks for your patience as we finalize the feature.

LOL 
Again nothing against you personally or the dev team.
But MoPub is closing down on 31 March and AppLovin will not have the SDK ready for another month? if there was any other decent alternative, I would stay clear from such a bad company (again, with an awesome dev team but incompetent management/owner)

**Comment by tfkci** [comment]
Are you kidding us :) You are shutting MoPub down and this feature is still not ready. Do you know how much it will cost for us? How a company can make this loss deliberately for itself and its publishers. Shame.

**Comment by deeteeh** [comment]
As expected. Pathetic.

**Comment by nihp** [comment]
Any update on this?

**Comment by nihp** [comment]
Any update on this?

**Comment by tracer8** [comment]
Stop spam, you can see no dev reply, so answer is no.
Wait for them or just switch to another network like me. Now i'm using
HyperBid, it is better than MAX.

**Comment by Luklek** [comment]
> Stop spam, you can see no dev reply, so answer is no. Wait for them or just switch to another network like me. Now i'm using HyperBid, it is better than MAX.

I had a look but it doesn't seem to have Native ads in recylerview too

**Comment by nihp** [comment]
@Luklek I assume there is no support from MAX for this as well. https://developers.mopub.com/publishers/android/native-manual/.

**Comment by tracer8** [comment]
They have, check their android demo.
And what are you doing? Are you developer? Can you make it yourself?
Lol.
It is just a simple native ads inside recylerview.

**Comment by Luklek** [comment]
@nihp they said it may be available in the middle of April. But their requirement of using 1 placement id in only 1 application not allows me to use MAX mediation anyway

**Comment by Luklek** [comment]
> They have, check their android demo. And what are you doing? Are you developer? Can you make it yourself? Lol. It is just a simple native ads inside recylerview.

I am not a real developer honestly so I need a simple way to integrate native ads in recyclerview (as MoPub had)

**Comment by ritamsarmah** [comment]
We have officially released Ad Placer in our latest Android SDK (11.4.0), allowing you to easily insert native ads into your existing content streams using `RecyclerView`. Check out our documentation for more information and integration instructions: https://dash.applovin.com/documentation/mediation/android/getting-started/native-ad-placer
