### ISSUE TITLE
Can't  resolve adapter

### ISSUE THREAD

**Issue by slabgames** [AppLovin/AppLovin-MAX-SDK-Android#79]
Does anyone have this issue as well?

```> Could not resolve all files for configuration ':debugRuntimeClasspath'.
   > Could not resolve com.applovin.mediation:ironsource-adapter:+.
     Required by:
         project :
      > Failed to list versions for com.applovin.mediation:ironsource-adapter.
         > Unable to load Maven meta-data from https://dl.bintray.com/mobilap/maven/com/applovin/mediation/ironsource-adapter/maven-metadata.xml.
            > Could not get resource 'https://dl.bintray.com/mobilap/maven/com/applovin/mediation/ironsource-adapter/maven-metadata.xml'.
               > Could not GET 'https://dl.bintray.com/mobilap/maven/com/applovin/mediation/ironsource-adapter/maven-metadata.xml'. Received status code 502 from server: Bad Gateway
```

**Comment by chauduyphanvu** [comment]
@slabgames, thanks for the report. We are currently looking into this and will report back.

Vu Chau
AppLovin Team

**Comment by chauduyphanvu** [comment]
@slabgames, we confirmed there are no issues with `com.applovin.mediation:ironsource-adapter` at this time. Could you try again and let us know if the error persists?

You may also share your Gradle setup with us so we can help troubleshoot it. Thanks!

**Comment by vishnusp** [comment]
Facing similar issue with smatoo adapter also

```
> Could not resolve all artifacts for configuration.
   > Could not find com.smaato.android.sdk:smaato-sdk:21.6.7.
     Required by:
         project : > com.applovin.mediation:smaato-adapter:21.6.7.1
   > Could not find com.smaato.android.sdk:smaato-sdk-in-app-bidding:21.6.7.
     Required by:
         project : > com.applovin.mediation:smaato-adapter:21.6.7.1
   > Could not find com.smaato.android.sdk:smaato-sdk-native:21.6.7.
     Required by:
         project : > com.applovin.mediation:smaato-adapter:21.6.7.1
```
I just don't understand how such basic issues are happening!

**Comment by chauduyphanvu** [comment]
@vishnusp, Smaato works fine for me:

![image](https://user-images.githubusercontent.com/25616035/149549837-5ea96cec-9022-4cf8-a968-c115d2d2fd2d.png)

Which Gradle version are you using? Could you show how you set up your Gradle? Thanks

**Comment by vishnusp** [comment]
@chauduyphanvu I'm using gradlw wrapper 6.7.1.
Gradle sync is success where as build fails with the above error.

**Comment by chauduyphanvu** [comment]
@vishnusp - could you show us your Gradle setup / content? If you can reproduce this in an empty project, please send that over as well. 

Thanks!
