### ISSUE TITLE
myTarget adapter - missing sdk initialization

### ISSUE THREAD

**Issue by apshard** [AppLovin/AppLovin-MAX-SDK-Android#80]
Please add explicit SDK initialization in myTarget adapter.

Right now there is a comment in the "initialize" method
`//myTarget SDK does not have any API for initialization.`

But in fact, SDK does have API for initialization (MyTargetManager.initSdk) and it should be called to cover the case when auto init is disabled in the manifest (by com.my.target.autoInitMode=0). So please add the following line to the "initialize" method in myTarget adapter
`MyTargetManager.initSdk(activity)`

**Comment by thomasmso** [comment]
Thanks for raising this issue @apshard - we will implement it and update the thread when the adapter is live (sometime this week).

**Comment by NanaAmoah** [comment]
Hi @apshard, MAX myTarget adapter 5.14.4.3 is live with the initialization API implemented.
