### ISSUE TITLE
VAST ads

### ISSUE THREAD

**Issue by deeteeh** [AppLovin/AppLovin-MAX-SDK-Android#84]
Hi @thomasmso, is there any way that we can implement In-Stream Ads like sending request to a MAX ad server which returns VAST ad response?

**Comment by thomasmso** [comment]
"in-stream ads" as in native ads? We don't explicitly expose the type of ad response of the ad (vast vs mraid vs custom), and I'm not sure how returning VAST ads would help implement in-stream ads either, could you describe more in detail?

**Comment by ltsadevs** [comment]
Thanks Thomas for the reply.Actually we are using Exoplayer IMA extension for displaying in-stream video ads. Google provides adtag which is used for sending ad requests from IMA extension and the response is in VAST xml format. Also InMobi has in-stream video ads format, an endpoint vast url server with some macros which returns vast ad response. On Jan 12, 2022 1:38 PM, Thomas So ***@***.***> wrote:
"in-stream ads" as in native ads? We don't explicitly expose the type of ad response of the ad (vast vs mraid vs custom), and I'm not sure how returning VAST ads would help implement in-stream ads either, could you describe more in detail?

**Comment by thomasmso** [comment]
I see - could you email partner_support@applovin.com with your portfolio and MoPub account? They will handle product inquiries there.

**Comment by ltsadevs** [comment]
Emailed but no reply.

**Comment by thomasmso** [comment]
What's the title of the email?
