### ISSUE TITLE
Can we prefetch native ads?

### ISSUE THREAD

**Issue by ihassanali259** [AppLovin/AppLovin-MAX-SDK-Android#93]

**Comment by chauduyphanvu** [comment]
@ihassanali259, we encourage cleaning up any unused native ads ([docs](https://dash.applovin.com/documentation/mediation/android/getting-started/native-templates)) to prevent memory leaks, so you will need to weigh your preferences. 

```java
@Override
public void onNativeAdLoaded(final MaxNativeAdView nativeAdView, final MaxAd ad)
{
    // Clean up any pre-existing native ad to prevent memory leaks.
    if ( nativeAd != null )
    {
        nativeAdLoader.destroy( nativeAd );
    }

    // Save ad for cleanup.
    nativeAd = ad;

    // Add ad view to view.
    nativeAdContainer.removeAllViews();
    nativeAdContainer.addView( nativeAdView );
}
```

We will be adding support for caching native ads in a scrolling feed (e.g. `RecyclerView`) so if that's your use case, check back for an update!

Vu Chau
AppLovin Team

**Comment by npace** [comment]
Hey, I'm also interested in preloading native ads, specifically from another activity or independently of Activity contexts.
For example, would it be possible to load some native ad in Activity A, keep a global reference to it and then render it in Activity B?

**Comment by chauduyphanvu** [comment]
Cross-Activity native ad handling is not officially supported at this time as we require you to pass in an Activity context:

```java
MaxNativeAdLoader nativeAdLoader = new MaxNativeAdLoader( "YOUR_AD_UNIT_ID", this );
```
