### ISSUE TITLE
You need the ability to select a delivery creative and the option not to deliver Applovin

### ISSUE THREAD

**Issue by 1008k** [AppLovin/AppLovin-MAX-SDK-Android#94]
I'm trying to create a full-screen ad space that doesn't serve video ads using networks that allow you to choose the creative to serve, such as AdColony, Pangle, AdMob, and UnityAds.
However, when trying to do that with MAX, Applovin and Applovin Exchange Demand are in the way.
We would like to request a setting that would allow us to disable Applovin and Applovin Exchange, as well as a setting that would allow us to not serve videos and playables.
(The MoPub had both features)

**Comment by thomasmso** [comment]
You cannot disable AppLovin Bidding and AppLovin Exchange. However, if you want to test live ads you can targets specific networks via our Mediation Debugger. See [here](https://dash.applovin.com/documentation/mediation/android/testing-networks/mediation-debugger) for more info.

**Comment by 1008k** [comment]
@thomasmso Hi. Thank you for your previous answer.
I've got a few additional questions.
In order to somehow achieve the requirements of this issue, I set the Bid Floor of the MAX ad unit to a very high value such as 100$ (so that Applovin and others don't buy it) and set up AdMob and other ad networks in the waterfall.

I created a report by adUnit/Network to check the numbers and it seems that no ad requests are being made to AdMob etc.
If the eCPM of a network is below the value set in Bid Floor, will it not be bought regardless of whether it is a Bidding enabled network or not?
(In MoPub, I was able to set a floor only for Advanced Bidding.)

If that's the way it works, I'll have to consider switching to a different solution...
We would appreciate it if you would consider again the option to stop Applovin & ApplovinExchange, and the option to control the creative.

Best Regards.

**Comment by thomasmso** [comment]
@1008k - What is your AppLovin account email?

**Comment by 1008k** [comment]
@thomasmso Hi. My email for my AppLovin account is "chiba@leafnet.jp".
(I don't really like to write Email in these places, so I may delete it later)

**Comment by thomasmso** [comment]
Got it, thanks (feel free to delete). Will send internal email.
