### ISSUE TITLE
How to add a new Adapter

### ISSUE THREAD

**Issue by JoseTappx** [AppLovin/AppLovin-MAX-SDK-Android#96]
Hi @thomasmso ,
  is there any guide with the steps to add a new adapter network? I'm interested to integrate Tappx, but couldn't find any guide or contact to guide me. Or I only have to implement the adapter following any of the adapter actually integrated as a guide and create a pull request?

Thanks!

**Comment by thomasmso** [comment]
Hey @JoseTappx - We can work on the custom adapters. Could you ping me at thomas.so@applovin.com? We can discuss details there. Thanks!
