### ISSUE TITLE
Facebook - Native Banner format support

### ISSUE THREAD

**Issue by lucasrafagnin** [AppLovin/AppLovin-MAX-SDK-Android#99]
Hi,

I have a technical question about integrating with Facebook Audience Network inventory through the MAX Mediation Platform.

Today we do this integration through Mopub Mediation. We have an app with the Facebook ad "Native Banner" format (https://developers.facebook.com/docs/audience-network/setting-up/ad-setup/android/native-banner) and Mopub supports this same format in his SDK (https://developers.mopub.com/publishers/mediation/networks/facebook/#request-native-banner-ads).

The question is about how to do this with MAX. The only guides I found in MAX documentation were for Native Ads (Manual and Templates), but not Native Banner.

![Captura de Tela 2022-01-19 às 17 55 03](https://user-images.githubusercontent.com/5746225/150212236-b7b54bb6-0027-4d28-963a-0455be42a291.png)

Are the Native Banner (Facebook) and Native Ads (MAX) formats the same thing or equivalent? If not, how do we make this migration from Mopub to MAX without the support of this advertising format?

Thanks.

**Comment by chauduyphanvu** [comment]
@lucasrafagnin, thanks for getting in touch. We'll be adding support for Facebook's native banner soon. 

In the meantime, when you request for a Facebook native ad from MAX, you will get Facebook's regular native ad (non-native-banner). 

Vu Chau
AppLovin Team

**Comment by lucasrafagnin** [comment]
Hi @chauduyphanvu,

So I need to set up the MAX SDK in my project and then follow this [doc](https://dash.applovin.com/documentation/mediation/android/getting-started/native-manual)? 

Also, do you plan to add the Native Banner before the March deadline?

**Comment by chauduyphanvu** [comment]
@lucasrafagnin, you can use "template" or "manual" depending on your use case. But yes, the doc you link is the starting place. 

Once we've supported Facebook's native banner, you will just need to get the new Facebook adapter version (and potentially reconfigure some dashboard/app settings to let us know that you want Facebook's native banner instead of native).

Our current ETA is some time around the end of Q1.

**Comment by usman1122** [comment]
@chauduyphanvu On facebook audience network they say MAX supports native banner?

**Comment by chauduyphanvu** [comment]
@usman1122 - could you share the links? Thanks.

**Comment by apshard** [comment]
[](https://developers.facebook.com/docs/audience-network/bidding/partner-mediation/max)
It also says MAX supports Medium Rectangle but in fact, only Facebook Native Bidding is available for MREC units.

**Comment by chauduyphanvu** [comment]
@usman1122, @apshard - the "native banner" listed on https://developers.facebook.com/docs/audience-network/bidding/partner-mediation/max is when you request a regular native ad from Facebook and we/MAX render that as a regular banner/MREC. 

It does not refer to Facebook's own "native banner" (https://developers.facebook.com/docs/audience-network/setting-up/ad-setup/android/native-banner), which would be rendered as a native ad by MAX. We will be adding support for that use case soon.

**Comment by lucasrafagnin** [comment]
So can I continue using the same ad unit in Facebook (native banner as below)
<img width="539" alt="Captura de Tela 2022-01-22 às 15 12 31" src="https://user-images.githubusercontent.com/5746225/150650521-e785e7b8-52b1-4f07-8b9b-b779f7c78a06.png">
but calling now the MAX Ad [Native](https://dash.applovin.com/documentation/mediation/android/getting-started/native-manual) integration instead of Mopub, and this will continue working properly?

**Comment by lucasrafagnin** [comment]
thanks a lot for the support @chauduyphanvu, Mopub's deadline is very close and today our revenue depends on the Facebook native banner ads.

**Comment by chauduyphanvu** [comment]
@lucasrafagnin - the way things look right now, we'll add radio buttons on the MAX dashboard to let you specify the FB native flavor (native or native banner) you would like to mediate for the current MAX ad unit ID. 

So, you have two options:
* You could set up 2 native ad units on the MAX side and 2 placements (native and native banner) on the Facebook side, or
* You could set up 1 native ad unit on the MAX side and use the radio buttons to toggle between Facebook's native or native banner

Of course things are subject to change and I'll let you know if that's the case.

**Comment by chauduyphanvu** [comment]
@lucasrafagnin - Meta "native banner" is now supported. Please update to the latest adapters and select native banner on the MAX dashboard to use this feature!
